import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHmac} from 'node:crypto';import {openDb} from '../src/db.js';import {initAccount,funds,createDeposit,creditDeposit,placeTestOrder,dashboard,range,history,listKeys,createKey,revokeKey,authenticateKey,accountOrders} from '../src/services/account.js';import {buildServer} from '../src/server.js';import {loadConfig} from '../src/config.js';
const actor='wallet:0x'+'1'.repeat(40),other='wallet:0x'+'2'.repeat(40),receiver='0x'+'3'.repeat(40);const hash='0x'+'a'.repeat(64);
function fixture(){const db=openDb(':memory:');initAccount(db);return db}
function seed(db:ReturnType<typeof openDb>,units=20_000_000n){const d=createDeposit(db,actor,randomUUID(),receiver,'1');creditDeposit(db,actor,d.id,{amount:units,confirmations:2n,blockHash:'0xblock',txHash:hash,blockTime:d.created_at});return d;}
test('account balance begins at zero, visitor cannot access private account',()=>{const db=fixture();assert.equal(funds(db,actor).availableUnits,'0');assert.throws(()=>funds(db,'session:visitor'));db.close()});
test('deposit intent alone creates no funds',()=>{const db=fixture();createDeposit(db,actor,randomUUID(),receiver,'20');assert.equal(funds(db,actor).availableUnits,'0');db.close()});
test('exact verified deposit is immutable, idempotent, actor isolated',()=>{const db=fixture(),d=seed(db);assert.equal(funds(db,actor).availableUnits,'20000000');assert.equal(funds(db,other).availableUnits,'0');assert.throws(()=>creditDeposit(db,other,d.id,{amount:1n,confirmations:2n,blockHash:'b',txHash:hash,blockTime:Date.now()}));assert.throws(()=>db.prepare('UPDATE account_deposits SET amount_units=? WHERE id=?').run('99',d.id));db.close()});
test('reject non-final, old, underpaid and future deposit evidence',()=>{const db=fixture(),d=createDeposit(db,actor,randomUUID(),receiver,'1');const p={amount:1_000_000n,confirmations:2n,blockHash:'b',txHash:hash,blockTime:d.created_at};for(const change of [{confirmations:1n},{amount:999999n},{blockTime:d.created_at-5000},{blockTime:Date.now()+60000}])assert.throws(()=>creditDeposit(db,actor,d.id,{...p,...change}));assert.equal(funds(db,actor).availableUnits,'0');db.close()});
test('transaction cannot credit two deposits',()=>{const db=fixture();seed(db);const d=createDeposit(db,actor,randomUUID(),receiver,'1');assert.throws(()=>creditDeposit(db,actor,d.id,{amount:20_000_000n,confirmations:2n,blockHash:'b',txHash:hash,blockTime:d.created_at}),/PAYMENT_ALREADY_USED/);assert.equal(funds(db,actor).availableUnits,'20000000');db.close()});
test('repeated verification never credits again',()=>{const db=fixture(),d=seed(db);creditDeposit(db,actor,d.id,{amount:20_000_000n,confirmations:2n,blockHash:'b',txHash:hash,blockTime:d.created_at});assert.equal(funds(db,actor).availableUnits,'20000000');db.close()});
test('deposit intent idempotency and conflicting amount',()=>{const db=fixture(),id=randomUUID(),d=createDeposit(db,actor,id,receiver,'1');assert.equal(createDeposit(db,actor,id,receiver,'1').id,d.id);assert.throws(()=>createDeposit(db,actor,id,receiver,'2'),/CONFLICT/);db.close()});
test('orders debit exact units, reserve/capture balance and segregated history',()=>{const db=fixture();seed(db);const id=randomUUID(),o=placeTestOrder(db,actor,id,'test-creator',2,'example');assert.equal(o.amount_units,'3064000');assert.equal(o.status,'SIMULATED_FULFILLED');assert.equal(funds(db,actor).availableUnits,'16936000');assert.equal(funds(db,actor).reservedUnits,'0');assert.equal(placeTestOrder(db,actor,id,'test-creator',2,'example').id,o.id);assert.equal(history(db,actor,'transactions').length,2);assert.equal(accountOrders(db,other).length,0);assert.throws(()=>db.prepare('UPDATE account_activity SET comment=?').run('change'));db.close()});
test('insufficient balance, quantity and per-order cap block spending',()=>{const db=fixture();assert.throws(()=>placeTestOrder(db,actor,randomUUID(),'test-creator',1,''),/INSUFFICIENT/);seed(db);assert.throws(()=>placeTestOrder(db,actor,randomUUID(),'test-gaming',2,''),/LIMIT/);assert.throws(()=>placeTestOrder(db,actor,randomUUID(),'test-creator',1.5,''));assert.equal(funds(db,actor).availableUnits,'20000000');db.close()});
test('dashboard tracks channel spend, API initiator, and time filters',()=>{const db=fixture();seed(db);placeTestOrder(db,actor,randomUUID(),'test-creator',1,'','API key:test');placeTestOrder(db,actor,randomUUID(),'test-gaming',1,'');const d=dashboard(db,actor);assert.equal(d.totalOrders,2);assert.equal(d.totalSpentUnits,'6805400');assert.equal(d.shopSpentUnits,'5273400');assert.equal(d.directTopUpSpentUnits,'1532000');assert.equal(d.topServices[0].units,'5273400');assert.equal(dashboard(db,actor,{initiator:'Portal'}).totalOrders,1);assert.equal(dashboard(db,actor,{from:Date.now()+1000}).totalOrders,0);db.close()});
test('date ranges use inclusive UTC days and reject invalid calendar dates',()=>{assert.deepEqual(range('all'),{});assert.equal(range('7d',undefined,undefined,864000000).from,259200000);assert.equal(range('custom','2026-01-01','2026-01-02').to,Date.parse('2026-01-03')-1);for(const args of [['custom','2026-02-30','2026-03-01'],['custom','2026-03-01','2026-02-01'],['custom',undefined,undefined]])assert.throws(()=>range(args[0]!,args[1],args[2]));});
test('API keys are hash-only, scoped, isolated and immediately revocable',()=>{const db=fixture(),k=createKey(db,actor,'backend',['account:read'],1);assert.equal(authenticateKey(db,k.secret,'account:read').actor,actor);assert.throws(()=>authenticateKey(db,k.secret,'orders:create'),/SCOPE/);const listed=JSON.stringify(listKeys(db,actor));assert(!listed.includes(k.secret));assert(!listed.includes('key_hash'));assert.equal(listKeys(db,other).length,0);assert.throws(()=>revokeKey(db,other,k.id));revokeKey(db,actor,k.id);assert.throws(()=>authenticateKey(db,k.secret,'account:read'));db.close()});
test('keys expire and reject invalid or privileged scopes',()=>{const db=fixture(),k=createKey(db,actor,'test',['orders:read'],1);db.prepare('UPDATE account_keys SET expires_at=? WHERE id=?').run(Date.now()-1,k.id);assert.throws(()=>authenticateKey(db,k.secret,'orders:read'));assert.throws(()=>createKey(db,actor,'test',['funds:withdraw'],30));assert.throws(()=>createKey(db,actor,'test',['orders:read'],0));db.close()});
test('portal account routes require authenticated wallet and signed BFF evidence',async()=>{const c=loadConfig({NODE_ENV:'test',DATABASE_PATH:':memory:',BACKEND_PROXY_SECRET:'x'.repeat(32)}),app=await buildServer(c);for(const url of ['/api/account/dashboard','/api/account/funds','/api/account/keys','/api/account/summary'])assert.equal((await app.inject({url})).statusCode,401);const path='/api/account/dashboard?period=all',ts=String(Date.now()),sig=createHmac('sha256',c.BACKEND_PROXY_SECRET).update(`${ts}\nGET\n${path}\n${actor}\n`).digest('hex');const r=await app.inject({url:path,headers:{'x-mercenta-actor':actor,'x-mercenta-timestamp':ts,'x-mercenta-signature':sig}});assert.equal(r.statusCode,200);assert.equal(r.json().totalOrders,0);assert.equal((await app.inject({url:'/api/v1/account',headers:{authorization:'Bearer fake'}})).statusCode,401);await app.close()});

test('burn and self-transfer receiver cannot credit an account',()=>{const db=fixture();for(const receiver of ['0x'+'0'.repeat(40),actor.slice(7)])assert.throws(()=>createDeposit(db,actor,randomUUID(),receiver,'1'),/RECEIVER_INVALID/);db.close()});
