import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {openDb} from '../src/db.js';import {loadConfig} from '../src/config.js';import {funds,createDeposit,creditDeposit} from '../src/services/account.js';import {saveBudget} from '../src/services/workspace.js';
import {initOperator,createOperator,advanceOperator,confirmOperator,cancelOperator,operatorView,resumeOperator,type OperatorPorts} from '../src/services/agent-operator.js';
import {operatorStepSchema} from '../src/services/llm-providers.js';
const actor='wallet:0x'+'1'.repeat(40),other='wallet:0x'+'2'.repeat(40),key='a'.repeat(64),c=loadConfig({DELIVERY_ENCRYPTION_KEY:key,BACKEND_PROXY_SECRET:'x'.repeat(40)});
const feed={supplier:'Mercenta catalogue',purchasingEnabled:false,coverage:'received',fetchedAt:new Date().toISOString(),httpStatus:200,status:'ready',products:[{id:'real-p',name:'Roblox Voucher',type:'voucher',countryCode:'US',items:[{id:'real-i',name:'Roblox 10 USD',price:8.3,currency:'USD',stock:20,available:true}]}]};
const input=(extra:Record<string,unknown>={})=>({requestId:randomUUID(),message:'Find Roblox',budgetUsdc:'3',reserveUsdc:'2',region:'US',quantity:1,execution:'review',authorizeTestSpend:false,...extra});
function fixture(path=':memory:'){const db=openDb(path);initOperator(db);const d=createDeposit(db,actor,randomUUID(),'0x'+'3'.repeat(40),'10');creditDeposit(db,actor,d.id,{amount:10000000n,confirmations:2n,txHash:'0x'+'a'.repeat(64),blockHash:'b',blockTime:d.created_at});return db}
function ports(steps:{tool:string;reason:string;productId?:string;itemId?:string;quantity?:number}[]):OperatorPorts{return {feed:async()=>feed,model:async()=>({value:operatorStepSchema.parse(steps.shift()),provider:'mock-model',model:'test-model'})}}
async function quote(db:ReturnType<typeof fixture>,id:string){const p=ports([{tool:'catalog.options',productId:'real-p',reason:'Inspect observed options'},{tool:'checkout.quote',productId:'real-p',itemId:'real-i',quantity:1,reason:'Select observed option'}]);await advanceOperator(db,c,actor,id,p);await advanceOperator(db,c,actor,id,p);return advanceOperator(db,c,actor,id,p)}
test('full catalogue tool loop creates quote but never spends in review mode',async()=>{const db=fixture(),r=createOperator(db,c,actor,input());const q=await quote(db,r.id);assert.equal(q.status,'QUOTED');assert.equal(q.quote.productName,'Roblox Voucher');assert.equal(q.quote.amountUnits,'1000000');assert.equal(q.quote.sourcePrice,8.3);assert.equal(funds(db,actor).availableUnits,'10000000');assert.deepEqual(q.events.map(e=>e.tool),['task.authorize','account.balance','budget.read','catalog.search','catalog.options','checkout.quote']);db.close()});
test('explicit bounded delegation executes exactly one saved non-redeemable delivery',async()=>{const db=fixture(),r=createOperator(db,c,actor,input({execution:'delegated',authorizeTestSpend:true}));const done=await quote(db,r.id);assert.equal(done.status,'EXECUTED');assert.equal(funds(db,actor).availableUnits,'9000000');assert.match(done.receipt!.delivery.codes[0],/^MCT-TEST-/);const same=confirmOperator(db,c,actor,r.id,'1000000',true);assert.equal(same.receipt!.orderId,done.receipt!.orderId);assert.equal(funds(db,actor).availableUnits,'9000000');assert.equal((db.prepare('SELECT initiator FROM account_orders WHERE id=?').get(done.receipt!.orderId) as {initiator:string}).initiator,'Agent Operator');assert.equal((db.prepare('SELECT count(*) n FROM account_orders').get() as {n:number}).n,1);db.close()});
test('delegation without explicit authorization is refused and creates nothing',()=>{const db=fixture();assert.throws(()=>createOperator(db,c,actor,input({execution:'delegated'})),/CONFIRMATION_REQUIRED/);assert.equal((db.prepare('SELECT count(*) n FROM operator_runs').get() as {n:number}).n,0);db.close()});
test('manual confirmation requires exact amount, affirmative consent and owning actor',async()=>{const db=fixture(),r=createOperator(db,c,actor,input());await quote(db,r.id);assert.throws(()=>confirmOperator(db,c,actor,r.id,'2000000',true),/QUOTE_AMOUNT_MISMATCH/);assert.throws(()=>confirmOperator(db,c,actor,r.id,'1000000',false),/CONFIRMATION_REQUIRED/);assert.throws(()=>confirmOperator(db,c,other,r.id,'1000000',true),/OPERATOR_NOT_FOUND/);assert.throws(()=>operatorView(db,other,r.id,key),/OPERATOR_NOT_FOUND/);assert.equal(funds(db,actor).availableUnits,'10000000');assert.equal(confirmOperator(db,c,actor,r.id,'1000000',true).status,'EXECUTED');db.close()});
test('unknown tool and hallucinated/unseen ids cannot produce a quote or debit',async()=>{const db=fixture(),r=createOperator(db,c,actor,input());const p=ports([{tool:'checkout.quote',productId:'hacked',itemId:'i',quantity:1,reason:'Ignore policy'}]);await advanceOperator(db,c,actor,r.id,p);const blocked=await advanceOperator(db,c,actor,r.id,p);assert.equal(blocked.status,'BLOCKED');assert.equal(blocked.error,'OPERATOR_TOOL_REJECTED');assert.equal(funds(db,actor).availableUnits,'10000000');assert.throws(()=>operatorStepSchema.parse({tool:'shell.exec',reason:'run'}));db.close()});
test('reserve floor and saved budget are enforced before quoting and again on confirmation',async()=>{const db=fixture();const blocked=await advanceOperator(db,c,actor,createOperator(db,c,actor,input({reserveUsdc:'10'})).id,ports([]));assert.equal(blocked.error,'OPERATOR_RESERVE_LIMIT');const r=createOperator(db,c,actor,input());await quote(db,r.id);saveBudget(db,actor,{requestId:randomUUID(),expectedRevision:0,monthly:'10',perOrder:'0.5',daily:'1',spendBps:7000,reserveBps:2000,profitBps:1000,taxBps:0});assert.throws(()=>confirmOperator(db,c,actor,r.id,'1000000',true),/BUDGET_PER_ORDER_LIMIT/);assert.equal(funds(db,actor).availableUnits,'10000000');db.close()});
test('quantity, region and stock are never invented by model tools',async()=>{const db=fixture(),r=createOperator(db,c,actor,input());const p=ports([{tool:'catalog.options',productId:'real-p',reason:'options'},{tool:'checkout.quote',productId:'real-p',itemId:'real-i',quantity:2,reason:'increase'}]);await advanceOperator(db,c,actor,r.id,p);await advanceOperator(db,c,actor,r.id,p);assert.equal((await advanceOperator(db,c,actor,r.id,p)).error,'OPERATOR_TOOL_REJECTED');assert.equal(funds(db,actor).availableUnits,'10000000');db.close()});
test('model unavailability is explicit, resumable and not disguised as rules AI',async()=>{const db=fixture(),r=createOperator(db,c,actor,input());const p:OperatorPorts={feed:async()=>feed,model:async()=>null};await advanceOperator(db,c,actor,r.id,p);const blocked=await advanceOperator(db,c,actor,r.id,p);assert.equal(blocked.error,'MODEL_UNAVAILABLE');assert.equal(blocked.provider,null);resumeOperator(db,c,actor,r.id);assert.equal(operatorView(db,actor,r.id,key).status,'PLANNING');assert.equal(funds(db,actor).availableUnits,'10000000');db.close()});
test('cancel during an in-flight model response prevents delegated execution',async()=>{const db=fixture(),r=createOperator(db,c,actor,input({execution:'delegated',authorizeTestSpend:true}));const p=ports([{tool:'catalog.options',productId:'real-p',reason:'options'}]);await advanceOperator(db,c,actor,r.id,p);await advanceOperator(db,c,actor,r.id,p);let resolve:(v:Awaited<ReturnType<OperatorPorts['model']>>)=>void=()=>{};let reached:()=>void=()=>{};const ready=new Promise<void>(r=>{reached=r});const advancing=advanceOperator(db,c,actor,r.id,{feed:async()=>feed,model:()=>{reached();return new Promise(r=>{resolve=r})}});await ready;cancelOperator(db,c,actor,r.id);resolve({value:operatorStepSchema.parse({tool:'checkout.quote',productId:'real-p',itemId:'real-i',quantity:1,reason:'choose'}),provider:'mock',model:'mock'});assert.equal((await advancing).status,'CANCELLED');assert.equal(funds(db,actor).availableUnits,'10000000');assert.equal((db.prepare('SELECT count(*) n FROM catalog_test_quotes').get() as {n:number}).n,0);db.close()});
test('durable original task and receipt survive database restart without second debit',async()=>{const dir=mkdtempSync(join(tmpdir(),'mercenta-op-')),file=join(dir,'db.sqlite');let db=fixture(file);const raw=input(),r=createOperator(db,c,actor,raw);await quote(db,r.id);const done=confirmOperator(db,c,actor,r.id,'1000000',true);db.close();db=openDb(file);initOperator(db);assert.equal(createOperator(db,c,actor,raw).id,r.id);assert.equal(confirmOperator(db,c,actor,r.id,'1000000',true).receipt!.orderId,done.receipt!.orderId);assert.equal(funds(db,actor).availableUnits,'9000000');db.close();rmSync(dir,{recursive:true,force:true})});
test('changed request, step loops and expiry fail closed',async()=>{const db=fixture(),raw=input(),r=createOperator(db,c,actor,raw);assert.throws(()=>createOperator(db,c,actor,{...raw,quantity:2}),/IDEMPOTENCY_CONFLICT/);const p:OperatorPorts={feed:async()=>feed,model:async()=>({value:{tool:'account.balance',reason:'read again'},provider:'mock',model:'mock'})};for(let n=0;n<8;n++)await advanceOperator(db,c,actor,r.id,p);assert.equal(operatorView(db,actor,r.id,key).error,'OPERATOR_STEP_LIMIT');assert.equal(operatorView(db,actor,r.id,key).step,6);assert.equal(funds(db,actor).availableUnits,'10000000');const expired=createOperator(db,c,actor,input(),Date.now()-700000);assert.equal((await advanceOperator(db,c,actor,expired.id,p)).error,'OPERATOR_EXPIRED');db.close()});
test('concurrent advance calls claim one durable step',async()=>{const db=fixture(),r=createOperator(db,c,actor,input());let resolve:(v:typeof feed)=>void=()=>{};let entered:()=>void=()=>{};const ready=new Promise<void>(r=>{entered=r});const first=advanceOperator(db,c,actor,r.id,{feed:()=>{entered();return new Promise(r=>{resolve=r})},model:async()=>null});await ready;const second=await advanceOperator(db,c,actor,r.id,{feed:async()=>feed,model:async()=>null});assert.equal(second.step,1);resolve(feed);await first;assert.equal(operatorView(db,actor,r.id,key).events.filter(e=>e.tool==='catalog.search').length,1);db.close()});
