import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHmac} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {openDb} from '../src/db.js';import {createDeposit,creditDeposit,funds,accountOrders} from '../src/services/account.js';import {initCatalogTestCheckout,createTestQuote,confirmTestQuote,testDelivery,getTestQuote} from '../src/services/catalog-test-checkout.js';import {saveBudget} from '../src/services/workspace.js';import {buildServer} from '../src/server.js';import {loadConfig} from '../src/config.js';import type {SupplierPreview} from '../src/services/supplier-preview.js';
const actor='wallet:0x'+'1'.repeat(40),other='wallet:0x'+'2'.repeat(40),key='ab'.repeat(32);
const feed={supplier:'Mercenta catalogue',purchasingEnabled:false,coverage:'unverified',status:'ready',httpStatus:200,fetchedAt:new Date().toISOString(),products:[{id:'catalog-1',name:'Example product',countryCode:'US',items:[{id:'option-1',name:'Expensive example',price:53.7483,currency:'USD',available:true,stock:20}]}]} as SupplierPreview;
function setup(path=':memory:'){const db=openDb(path);initCatalogTestCheckout(db);return db}
function seed(db:ReturnType<typeof openDb>){const d=createDeposit(db,actor,randomUUID(),'0x'+'3'.repeat(40),'20');creditDeposit(db,actor,d.id,{amount:20_000_000n,confirmations:2n,blockHash:'b',txHash:'0x'+'a'.repeat(64),blockTime:d.created_at})}
const quote=(db:ReturnType<typeof openDb>,quantity=1,now=Date.now())=>createTestQuote(db,actor,randomUUID(),'catalog-1','option-1',quantity,feed,now);
test('quote is read-only, fixed test price distinct from USD, owner scoped',()=>{const db=setup(),q=quote(db,2);assert.equal(q.amountUnits,'2000000');assert.equal(q.sourcePrice,53.7483);assert.equal(q.nonRedeemable,true);assert.equal(funds(db,actor).availableUnits,'0');assert.throws(()=>getTestQuote(db,other,q.id),/NOT_FOUND/);assert.throws(()=>db.prepare('UPDATE catalog_test_quotes SET amount_units=?').run('1'),/IMMUTABLE/);db.close()});
test('only existing available options and bounded whole quantity get quotes',()=>{const db=setup();for(const qty of [0,11,1.1])assert.throws(()=>quote(db,qty));assert.throws(()=>createTestQuote(db,actor,randomUUID(),'missing','option-1',1,feed));assert.throws(()=>createTestQuote(db,actor,randomUUID(),'catalog-1','missing',1,feed));assert.throws(()=>createTestQuote(db,actor,randomUUID(),'catalog-1','option-1',1,{...feed,status:'unavailable'}));const noStock={...feed,products:[{...feed.products[0]!,items:[{...feed.products[0]!.items[0]!,stock:0}]}]};assert.throws(()=>createTestQuote(db,actor,randomUUID(),'catalog-1','option-1',1,noStock),/UNAVAILABLE/);db.close()});
test('quote idempotency binds exact selection',()=>{const db=setup(),id=randomUUID(),q=createTestQuote(db,actor,id,'catalog-1','option-1',1,feed);assert.equal(createTestQuote(db,actor,id,'catalog-1','option-1',1,feed).id,q.id);assert.throws(()=>createTestQuote(db,actor,id,'catalog-1','option-1',2,feed),/CONFLICT/);db.close()});
test('confirm exact atomic debit plus encrypted test delivery; replay never double-charges',()=>{const db=setup();seed(db);const q=quote(db,2),id=randomUUID(),r=confirmTestQuote(db,actor,q.id,id,q.amountUnits,key);assert.equal(funds(db,actor).availableUnits,'18000000');assert.equal(funds(db,actor).reservedUnits,'0');assert.equal(r.delivery.codes.length,2);assert(r.delivery.codes.every((c:string)=>c.startsWith('MCT-TEST-')));assert.equal(r.delivery.supplierCalls,0);const encrypted=JSON.stringify(db.prepare('SELECT * FROM catalog_test_deliveries').all());assert(!encrypted.includes('MCT-TEST-'));assert.deepEqual(confirmTestQuote(db,actor,q.id,id,q.amountUnits,key,Date.now()+999999).delivery,r.delivery);assert.equal(accountOrders(db,actor).length,1);assert.equal(funds(db,actor).availableUnits,'18000000');assert.throws(()=>confirmTestQuote(db,actor,q.id,randomUUID(),q.amountUnits,key),/ALREADY_CONFIRMED/);db.close()});
test('quote expiry, amount tampering, owner mismatch and insufficient funds fail closed',()=>{const db=setup(),q=quote(db);assert.throws(()=>confirmTestQuote(db,actor,q.id,randomUUID(),'1',key),/AMOUNT_MISMATCH/);assert.throws(()=>confirmTestQuote(db,other,q.id,randomUUID(),q.amountUnits,key),/NOT_FOUND/);assert.throws(()=>confirmTestQuote(db,actor,q.id,randomUUID(),q.amountUnits,key),/INSUFFICIENT/);const expired=quote(db,1,Date.now()-300001);seed(db);assert.throws(()=>confirmTestQuote(db,actor,expired.id,randomUUID(),expired.amountUnits,key),/EXPIRED/);assert.equal(funds(db,actor).availableUnits,'20000000');assert.equal(accountOrders(db,actor).length,0);db.close()});
test('confirmation request conflict cannot consume a second quote',()=>{const db=setup();seed(db);const q=quote(db),q2=quote(db),id=randomUUID();confirmTestQuote(db,actor,q.id,id,q.amountUnits,key);assert.throws(()=>confirmTestQuote(db,actor,q2.id,id,q2.amountUnits,key),/CONFLICT/);assert.equal(funds(db,actor).availableUnits,'19000000');db.close()});
test('saved Shop budget also applies to catalogue rehearsal',()=>{const db=setup();seed(db);saveBudget(db,actor,{requestId:randomUUID(),expectedRevision:0,monthly:'20',daily:'10',perOrder:'1',spendBps:7000,reserveBps:2000,profitBps:1000,taxBps:0});const q=quote(db,2);assert.throws(()=>confirmTestQuote(db,actor,q.id,randomUUID(),q.amountUnits,key),/BUDGET_PER_ORDER/);assert.equal(funds(db,actor).availableUnits,'20000000');db.close()});
test('delivery insertion failure rolls back debit, order and quote consumption',()=>{const db=setup();seed(db);const q=quote(db);db.exec("CREATE TRIGGER force_failure BEFORE INSERT ON catalog_test_deliveries BEGIN SELECT RAISE(ABORT,'TEST_FAILURE'); END;");assert.throws(()=>confirmTestQuote(db,actor,q.id,randomUUID(),q.amountUnits,key),/TEST_FAILURE/);assert.equal(funds(db,actor).availableUnits,'20000000');assert.equal(funds(db,actor).reservedUnits,'0');assert.equal(accountOrders(db,actor).length,0);assert.equal((db.prepare('SELECT count(*) n FROM catalog_test_deliveries').get() as {n:number}).n,0);db.close()});
test('saved delivery survives restart and is inaccessible to another owner',()=>{const dir=mkdtempSync(join(tmpdir(),'mct-')),path=join(dir,'test.sqlite');let db=setup(path);seed(db);const q=quote(db),r=confirmTestQuote(db,actor,q.id,randomUUID(),q.amountUnits,key);db.close();db=setup(path);assert.deepEqual(testDelivery(db,actor,r.order.id,key),r.delivery);assert.throws(()=>testDelivery(db,other,r.order.id,key),/NOT_FOUND/);assert.throws(()=>db.prepare('DELETE FROM catalog_test_deliveries').run(),/IMMUTABLE/);db.close();rmSync(dir,{recursive:true,force:true})});
test('routes require signed owner, strict payload and explicit nonredeemable consent',async()=>{const c=loadConfig({NODE_ENV:'test',DATABASE_PATH:':memory:',BACKEND_PROXY_SECRET:'x'.repeat(32)}),app=await buildServer(c);const path='/api/account/catalog-checkout/confirm';assert.equal((await app.inject({method:'POST',url:path,payload:{}})).statusCode,401);const payload={quoteId:randomUUID(),requestId:randomUUID(),acceptedAmountUnits:'1000000',mode:'TESTNET_SIMULATED',confirmNonRedeemable:true,price:'0'};const ts=String(Date.now()),sig=createHmac('sha256',c.BACKEND_PROXY_SECRET).update(`${ts}\nPOST\n${path}\n${actor}\n${JSON.stringify(payload)}`).digest('hex');const res=await app.inject({method:'POST',url:path,payload,headers:{'x-mercenta-actor':actor,'x-mercenta-timestamp':ts,'x-mercenta-signature':sig}});assert.equal(res.statusCode,400);assert.equal(res.json().code,'INVALID_REQUEST');const id=randomUUID();assert.equal((await app.inject({url:'/api/account/orders/'+id+'/delivery'})).statusCode,401);await app.close()});
