import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHmac} from 'node:crypto';import {openDb} from '../src/db.js';import {loadConfig} from '../src/config.js';import {buildServer} from '../src/server.js';import {CircleAgent,unseal,type CirclePorts} from '../src/services/circle-agent.js';import {agentConfigSchema,checkedRequirements,checkDailyLimit,matchTransfer,CHAIN,NETWORK,publicCircleStatus,type AgentConfig} from '../src/services/circle-policy.js';import {publicIPv4} from '../src/services/circle-http.js';
const owner='0x'+'1'.repeat(40),wallet='0x'+'2'.repeat(40),recipient='0x'+'3'.repeat(40),actor='wallet:'+owner,nonce='0x'+'4'.repeat(64),hash='0x'+'5'.repeat(64);
const a:AgentConfig={provider:'circle-mpc',apiKey:'TEST_API_KEY:'+'x'.repeat(32),entitySecret:'e'.repeat(64),walletId:randomUUID(),walletAddress:wallet,ownerWallet:owner,enabled:true,services:[{id:'market-data',url:'https://quotes.example.com/data',payTo:recipient,maxAmountUnits:'10000'}]};
const req={scheme:'exact',network:NETWORK,asset:CHAIN.usdc,amount:'1000',payTo:recipient,maxTimeoutSeconds:604900,extra:{name:'GatewayWalletBatched',version:'1',verifyingContract:CHAIN.gatewayWallet}};
const header=(changes:unknown={})=>Buffer.from(JSON.stringify({x402Version:2,accepts:[{...req,...changes as object}],resource:{url:a.services[0].url}})).toString('base64');
const c={...loadConfig(),DATABASE_PATH:':memory:',CIRCLE_AGENT_CONFIG_FILE:undefined};
function fixture(options:{timeout?:boolean;phase?:string}={}){const db=openDb(':memory:');let signs=0,paid=0;const transferId=randomUUID();const ports:CirclePorts={walletCheck:async()=>{},sign:async()=>{signs++;return {x402Version:2,payload:{signature:'0x'+'a'.repeat(130),authorization:{from:wallet,to:recipient,value:'1000',validAfter:'0',validBefore:'9999999999',nonce}}}},http:async(url,headers)=>{if(url.includes('/x402/transfers'))return {status:200,headers:{},body:JSON.stringify({transfers:[{id:transferId,status:options.phase??'completed',token:'USDC',sendingNetwork:NETWORK,recipientNetwork:NETWORK,fromAddress:wallet,toAddress:recipient,amount:'1000',nonce,txHash:hash}]})};if(headers?.['PAYMENT-SIGNATURE']){paid++;if(options.timeout)throw new Error('timeout');return {status:200,headers:{},body:'{"price":"1.25"}'}}return {status:402,headers:{'payment-required':header()},body:''}},receipt:async()=>({blockHash:'0x'+'6'.repeat(64),confirmed:true})};return {db,ports,service:new CircleAgent(db,c,ports,a),count:()=>({signs,paid})}}
test('Circle rejects live keys, private endpoints, excessive caps, and unknown quote routes',()=>{assert.throws(()=>agentConfigSchema.parse({...a,apiKey:'LIVE_API_KEY:'+'x'.repeat(32)}));assert.throws(()=>agentConfigSchema.parse({...a,services:[{...a.services[0],url:'https://127.0.0.1/'}]}));assert.throws(()=>agentConfigSchema.parse({...a,services:[{...a.services[0],maxAmountUnits:'10001'}]}));assert.throws(()=>checkedRequirements(header({network:'eip155:1'}),a.services[0]));assert.throws(()=>checkedRequirements(header({payTo:owner}),a.services[0]));assert.throws(()=>checkedRequirements(header({asset:owner}),a.services[0]));assert.throws(()=>checkedRequirements(header({amount:'10001'}),a.services[0]));assert.throws(()=>checkedRequirements(header({extra:{...req.extra,verifyingContract:owner}}),a.services[0]));assert.throws(()=>checkDailyLimit('99999','2'));});
test('Circle HTTP transport rejects private, loopback and documentation networks',()=>{for(const ip of ['127.0.0.1','10.2.3.4','172.31.5.1','192.168.1.1','169.254.169.254','100.64.0.1','198.18.1.1','203.0.113.1','224.0.0.1'])assert.equal(publicIPv4(ip),false);assert.equal(publicIPv4('8.8.8.8'),true)});
test('Circle status never exposes credentials or another actor wallet',()=>{const x=JSON.stringify(publicCircleStatus(a,actor));assert.ok(!x.includes(a.apiKey));assert.ok(!x.includes(a.entitySecret));assert.equal(publicCircleStatus(a,'wallet:'+recipient).walletAddress,null);assert.equal(publicCircleStatus(null,actor).enabled,false)});
test('Circle quote moves no money, is idempotent, and rejects foreign actors',async()=>{const f=fixture();try{const requestId=randomUUID(),q=await f.service.prepare(actor,requestId,'market-data');assert.equal((await f.service.prepare(actor,requestId,'market-data')).id,q.id);assert.deepEqual(f.count(),{signs:0,paid:0});assert.equal(q.settled,false);assert.throws(()=>f.service.get('wallet:'+recipient,q.id));await assert.rejects(f.service.prepare('wallet:'+recipient,randomUUID(),'market-data'));await assert.rejects(f.service.prepare(actor,randomUUID(),'not-allowed'));await assert.rejects(f.service.confirm(actor,q.id,false));}finally{f.db.close()}});
test('Circle explicit confirmation signs/submits once, encrypts authorization and never credits prepaid balance',async()=>{const f=fixture();try{const q=await f.service.prepare(actor,randomUUID(),'market-data');assert.equal((await f.service.confirm(actor,q.id,true)).status,'QUEUED');await f.service.confirm(actor,q.id,true);assert.deepEqual(f.count(),{signs:1,paid:1});const stored=f.db.prepare('SELECT * FROM circle_agent_payments WHERE id=?').get(q.id) as any;assert.ok(!stored.encrypted_payload.includes('PAYMENT-SIGNATURE'));assert.ok(!stored.encrypted_payload.includes('authorization'));assert.ok(unseal(c.DELIVERY_ENCRYPTION_KEY,stored.encrypted_payload).length>0);assert.equal(JSON.parse(f.service.resource(actor,q.id).content).price,'1.25');assert.equal(f.db.prepare('SELECT count(*) n FROM ledger_entries').get().n,0);const done=await f.service.reconcile(actor,q.id);assert.equal(done.status,'COMPLETED');await f.service.reconcile(actor,q.id);assert.equal(f.db.prepare('SELECT count(*) n FROM ledger_entries').get().n,2);assert.equal(f.db.prepare('SELECT sealed FROM ledger_batches WHERE id=?').get('circle:'+q.id).sealed,1);assert.deepEqual(f.count(),{signs:1,paid:1});}finally{f.db.close()}});
test('Circle timeout remains unknown, refuses automatic respend and can reconcile original nonce',async()=>{const f=fixture({timeout:true});try{const q=await f.service.prepare(actor,randomUUID(),'market-data');assert.equal((await f.service.confirm(actor,q.id,true)).status,'UNKNOWN');await f.service.confirm(actor,q.id,true);assert.deepEqual(f.count(),{signs:1,paid:1});assert.equal((await f.service.reconcile(actor,q.id)).status,'COMPLETED')}finally{f.db.close()}});
test('Circle queued/confirmed transfers are not final journals; wrong attribution is rejected',async()=>{const f=fixture({phase:'confirmed'});try{const q=await f.service.prepare(actor,randomUUID(),'market-data');await f.service.confirm(actor,q.id,true);assert.equal((await f.service.reconcile(actor,q.id)).settled,false);assert.equal(f.db.prepare('SELECT count(*) n FROM ledger_entries').get().n,0);assert.throws(()=>matchTransfer({id:randomUUID(),status:'completed',token:'USDC',sendingNetwork:NETWORK,recipientNetwork:NETWORK,fromAddress:owner,toAddress:recipient,amount:'1000',nonce,txHash:hash},{nonce,from:wallet,to:recipient,amount:'1000'}));}finally{f.db.close()}});
test('Circle HTTP routes require auth, reject unknown fields, default disabled',async()=>{const config={...c,BACKEND_PROXY_SECRET:'s'.repeat(32)};const app=await buildServer(config,[]);function h(method:string,url:string,body:unknown=null){const ts=Date.now().toString();return {'x-mercenta-actor':actor,'x-mercenta-timestamp':ts,'x-mercenta-signature':createHmac('sha256',config.BACKEND_PROXY_SECRET).update(`${ts}\n${method}\n${url}\n${actor}\n${body?JSON.stringify(body):''}`).digest('hex')}}try{const url='/api/account/circle/status';assert.equal((await app.inject({url})).statusCode,401);assert.equal((await app.inject({url,headers:h('GET',url)})).json().enabled,false);const post='/api/account/circle/payments',body={requestId:randomUUID(),serviceId:'market-data',url:'https://evil.example.com'};assert.equal((await app.inject({method:'POST',url:post,headers:h('POST',post,body),payload:body})).json().code,'INVALID_REQUEST');}finally{await app.close()}});

test('Circle history is bounded, actor isolated and contains no encrypted authorization',async()=>{const f=fixture();try{const q=await f.service.prepare(actor,randomUUID(),'market-data');assert.equal(f.service.list(actor).items[0].id,q.id);assert.deepEqual(f.service.list('wallet:'+recipient).items,[]);const data=JSON.stringify(f.service.list(actor));for(const key of ['encrypted_payload','encrypted_response','entitySecret','apiKey','signature'])assert.ok(!data.includes(key));assert.equal(publicCircleStatus(null,actor).custody,null);}finally{f.db.close()}});
test('Circle service revocation during asynchronous signing prevents any paid request',async()=>{const f=fixture();const config={...a,services:a.services.map(x=>({...x}))};const original=f.ports.sign;f.ports.sign=async(...args)=>{const signature=await original(...args);config.services=[];return signature};const service=new CircleAgent(f.db,c,f.ports,config);try{const q=await service.prepare(actor,randomUUID(),'market-data');const result=await service.confirm(actor,q.id,true);assert.equal(result.status,'UNKNOWN');assert.deepEqual(f.count(),{signs:1,paid:0});const stored=f.db.prepare('SELECT encrypted_payload FROM circle_agent_payments WHERE id=?').get(q.id) as {encrypted_payload:string|null};assert.equal(stored.encrypted_payload,null);}finally{f.db.close()}});

test('Circle balances reject a foreign actor before any RPC or API call',async()=>{const f=fixture();try{await assert.rejects(f.service.balances('wallet:'+recipient),/CIRCLE_AGENT_NOT_AVAILABLE/);assert.deepEqual(f.count(),{signs:0,paid:0});}finally{f.db.close()}});
