import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID,createHmac} from 'node:crypto';import {buildServer} from '../src/server.js';import {refreshProcurementHealth} from '../src/services/procurement-health.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {openDb} from '../src/db.js';import {loadConfig} from '../src/config.js';
import {PublicCommerceApi,type SpendCapEvidence} from '../src/services/fulfillment/public-commerce-api.js';
import {DocumentedVoucherSupply} from '../src/services/fulfillment/documented-voucher.js';
import {Orders} from '../src/services/orders.js';import {SupplyNode,requestRef} from '../src/services/fulfillment/index.js';
import {recordProcurementHealth,procurementHealth} from '../src/services/procurement-health.js';
import {balance,transfer} from '../src/services/ledger/index.js';import {reconcileOnce} from '../src/services/fulfillment/reconciler.js';
const sid='11111111-1111-4111-8111-111111111111',item='22222222-2222-4222-8222-222222222222',oid='fixture-order-001',sku=sid+':'+item,code='SYNTHETIC_TEST_ONLY_12345';
function setup(dbPath=':memory:'){
 const db=openDb(dbPath),c={...loadConfig({NODE_ENV:'test'}),ENABLE_FULFILLMENT:'true' as const,FULFILLMENT_CONTRACT_VERIFIED:'true' as const};
 const calls:{method:string;path:string}[]=[],f={price:0.0194,available:30,status:'SUCCESS',mask:false,wrongRef:false,wrongItem:false,wrongCost:false,wrongReveal:false,timeout:false,missing:false,partial:false,ledgerAmount:-0.0194,ledgerWrongOrder:false,ledgerTotal:1,stock:500,type:'voucher',postRef:'',beforeTimeout:false,postHttp:202};
 const api=new PublicCommerceApi('fixture-key-not-real', (async(u,init)=>{
  const url=new URL(String(u)),method=init?.method??'GET';calls.push({method,path:url.pathname+url.search});let data:unknown,status='SUCCESS',appCode=0,http=200;
  if(url.pathname.endsWith('/accounts'))data={items:[{currency:'USD',balance:f.available,available:f.available}]};
  else if(url.pathname.endsWith('/accounts/transactions'))data={totalCount:f.ledgerTotal,items:[{currency:'USD',orderId:f.ledgerWrongOrder?'foreign-order':oid,amount:f.ledgerAmount}]};
  else if(url.pathname.endsWith('/items/'+item)){if(f.beforeTimeout)throw Error('fixture read timeout');data={id:item,price:f.price,currency:'USD',inStock:f.stock,isLongOrder:false};}
  else if(url.pathname.endsWith('/services/'+sid))data={id:sid,type:f.type,countryCode:'EG',fields:null};
  else if(method==='POST'){
   assert.equal(url.pathname,'/api/v1/orders');const b=JSON.parse(String(init?.body));assert.equal(b.ordersType,'shop');assert.equal(b.orders[0].denominationId,item);assert.equal(b.orders[0].quantity,1);assert.equal(b.orders[0].isLongOrder,false);assert(b.referenceId.length<=40);assert(!('request_ref' in b));f.postRef=b.referenceId;
   if(f.timeout)throw Error('fixture lost response');data={orderId:oid,price:0.0194,currency:'USD'};status='IN_PROGRESS';appCode=1;http=f.postHttp;
  }else if(url.pathname.endsWith('/orders')){
   const reveal=url.searchParams.get('unhide')==='true';assert.equal(url.searchParams.get('referenceId'),f.postRef);if(reveal)assert.equal(url.searchParams.get('orderId'),oid);
   data={page:{items:f.missing?[]:[{orderId:reveal&&f.wrongReveal?'foreign-order':oid,reference:f.wrongRef?'foreign-reference':f.postRef,itemId:f.wrongItem?'foreign-item':item,quantity:1,currency:'USD',amount:f.wrongCost?0.02:0.0194,status:f.partial?'PARTIALLY_COMPLETED':f.status,vouchers:[{pin:reveal&&!f.mask?code:'****2345'}]}]}};
  }else throw Error('Unexpected fixture endpoint');
  return Response.json({status,statusCode:appCode,data},{status:http});
 }) as typeof fetch);
 const cap=():SpendCapEvidence=>({verified:true,currency:'USD',remainingUsd:'0.0194',keyFingerprint:api.keyFingerprint,observedAt:Date.now()});
 recordProcurementHealth(db,{currency:'USD',available:'30',observedAt:Date.now()});
 const node=new DocumentedVoucherSupply(db,c,api,{enabled:true,capEvidence:cap});
 const products=[{id:'p',name:'Fixture resource',category:'gaming' as const,price:'1',cost:'0.0194',currency:'USDC' as const,enabled:true,quotedAt:Date.now(),supplierSku:sku}];
 const orders=new Orders(db,c,products,node);transfer(db,'funding','fixture-funding','equity:usdc','arc:usdc:available',20000000000n);
 const posts=()=>calls.filter(c=>c.method==='POST').length;
 return {db,c,api,node,orders,products,f,cap,calls,posts};
}
const proof=(tx='fixture-payment')=>({amount:1000000n,confirmations:2n,txHash:tx,blockHash:'fixture-block'});
const actor='wallet:0x'+'1'.repeat(40);
test('documented checkout: payment, one POST, original-order reconcile, settlement, encrypted owner-only delivery',async()=>{
 const s=setup();try{const o=s.orders.create(actor,'p',1);await s.orders.acceptPayment(o.id,actor,proof());assert.equal(s.orders.get(o.id)?.status,'SUPPLIER_UNKNOWN');assert.equal(s.posts(),1);const ref=s.orders.get(o.id)!.request_ref!;assert.equal(ref.length,40);s.orders.applySupply(o.id,await s.node.lookup(ref));assert.equal(s.orders.get(o.id)?.status,'FULFILLED');assert.equal(balance(s.db,'arc:usdc:reserved'),0n);assert.equal(balance(s.db,'revenue:usdc'),-1000000n);assert.equal(balance(s.db,'settlement:usdc:paid'),19400n);assert(!s.orders.get(o.id)!.encrypted_code!.includes(code));assert.throws(()=>s.orders.reveal(o.id,'other-owner'),/DELIVERY_UNAVAILABLE/);assert.equal(s.orders.reveal(o.id,actor).code,code);assert.throws(()=>s.orders.reveal(o.id,actor),/DELIVERY_UNAVAILABLE/);assert.equal(s.posts(),1);assert.equal((s.db.prepare('SELECT count(*) n FROM procurement_reservations').get() as {n:number}).n,0);}finally{s.db.close()}
});
test('two simultaneous fulfill calls issue one purchase only',async()=>{const s=setup();try{const o=s.orders.create(actor,'p',1);await s.orders.acceptPayment(o.id,actor,proof());await Promise.all([s.orders.fulfill(o.id),s.orders.fulfill(o.id)]);assert.equal(s.posts(),1)}finally{s.db.close()}});
test('a lost POST response retains reserve; new adapter and restart reconcile without POST',async()=>{const s=setup();try{s.f.timeout=true;const o=s.orders.create(actor,'p',1);await s.orders.acceptPayment(o.id,actor,proof());const ref=s.orders.get(o.id)!.request_ref!;assert.equal(s.posts(),1);assert.equal(balance(s.db,'arc:usdc:reserved'),19400n);s.orders.recover();const restarted=new DocumentedVoucherSupply(s.db,s.c,s.api,{enabled:true});assert.equal(restarted.ready,false);const resumed=new Orders(s.db,s.c,s.products,restarted);resumed.applySupply(o.id,await restarted.lookup(ref));assert.equal(resumed.get(o.id)?.status,'FULFILLED');assert.equal(s.posts(),1)}finally{s.db.close()}});
for(const key of ['wrongRef','wrongItem','wrongCost','wrongReveal','mask','missing','partial','ledgerWrongOrder'] as const)test('untrusted '+key+' cannot fulfill or release reserve',async()=>{const s=setup();try{await s.node.purchase('bounded_reference_'+key,sku,1,'19400');s.f[key]=true;const r=await s.node.lookup('bounded_reference_'+key);assert.equal(r.status,'UNKNOWN');assert.equal(s.posts(),1);assert.equal((s.db.prepare('SELECT count(*) n FROM procurement_reservations').get() as {n:number}).n,1)}finally{s.db.close()}});
for(const [label,change] of Object.entries({changedPrice:{price:0.02},zeroStock:{stock:0},lowCash:{available:10.01},nonVoucher:{type:'direct_topup'},readTimeout:{beforeTimeout:true}}))test(label+' before submission proves NOT_EXECUTED without POST',async()=>{const s=setup();try{Object.assign(s.f,change);assert.equal((await s.node.purchase('preflight_'+label,sku,1,'19400')).status,'NOT_EXECUTED');assert.equal(s.posts(),0)}finally{s.db.close()}});
test('cancelled after POST is not assumed refundable; reserve remains until review',async()=>{const s=setup();try{await s.node.purchase('cancelled_reference',sku,1,'19400');s.f.status='CANCELLED';assert.equal((await s.node.lookup('cancelled_reference')).status,'UNKNOWN');assert.equal((s.db.prepare('SELECT count(*) n FROM procurement_reservations').get() as {n:number}).n,1)}finally{s.db.close()}});
test('ledger mismatch and incomplete transaction page cannot complete accounting',async()=>{for(const change of [{ledgerAmount:-0.02},{ledgerTotal:2}]){const s=setup();try{Object.assign(s.f,change);await s.node.purchase('accounting_reference',sku,1,'19400');assert.equal((await s.node.lookup('accounting_reference')).status,'UNKNOWN');assert.equal(s.posts(),1)}finally{s.db.close()}}});
test('pre-submit refusal after payment marks REFUND_REQUIRED, not paid-out refund',async()=>{const s=setup();try{const o=s.orders.create(actor,'p',1);s.f.price=0.02;await s.orders.acceptPayment(o.id,actor,proof());assert.equal(s.orders.get(o.id)?.status,'REFUND_REQUIRED');assert.equal(s.posts(),0);assert.equal(balance(s.db,'arc:usdc:reserved'),0n);assert.equal(balance(s.db,'revenue:usdc'),0n);assert.equal((s.db.prepare('SELECT count(*) n FROM payments').get() as {n:number}).n,1)}finally{s.db.close()}});
test('unsupported quantity and invalid quantity refused before customer invoice',()=>{const s=setup();try{for(const q of [0,-1,1.5,11,2])assert.throws(()=>s.orders.create(actor,'p',q));assert.equal((s.db.prepare('SELECT count(*) n FROM orders').get() as {n:number}).n,0);assert.equal(s.posts(),0)}finally{s.db.close()}});
test('no verified exact server cap means no customer invoice and no purchase',async()=>{const s=setup();try{const disabled=new DocumentedVoucherSupply(s.db,s.c,s.api,{enabled:true,capEvidence:()=>({...s.cap(),verified:false})});assert.equal(disabled.ready,false);const orders=new Orders(s.db,s.c,s.products,disabled);assert.throws(()=>orders.create(actor,'p',1),/PAUSED/);assert.equal(s.posts(),0);assert.throws(()=>s.node.validateQuote(sku,1,'20000'),/EXACT_ORDER_SERVER_CAP/)}finally{s.db.close()}});
test('same reference with changed immutable body is rejected without second POST',async()=>{const s=setup();try{await s.node.purchase('same_reference',sku,1,'19400');await assert.rejects(()=>s.node.purchase('same_reference',sku,1,'20000'),/IDEMPOTENCY_CONFLICT/);assert.equal(s.posts(),1)}finally{s.db.close()}});
test('completed delivery replay does not contact provider or repost customer journal',async()=>{const s=setup();try{const o=s.orders.create(actor,'p',1);await s.orders.acceptPayment(o.id,actor,proof());const ref=s.orders.get(o.id)!.request_ref!;s.orders.applySupply(o.id,await s.node.lookup(ref));const calls=s.calls.length;s.orders.applySupply(o.id,await s.node.lookup(ref));assert.equal(s.calls.length,calls);assert.equal(balance(s.db,'revenue:usdc'),-1000000n);assert.equal(s.posts(),1)}finally{s.db.close()}});
test('reconciler isolates failed lookup, releases lease and processes next order',async()=>{const s=setup();try{const a=s.orders.create(actor,'p',1),b=s.orders.create(actor,'p',1);await s.orders.acceptPayment(a.id,actor,proof('tx-a'));await s.orders.acceptPayment(b.id,actor,proof('tx-b'));let lookups=0;const port={configured:true,ready:false,purchase:async()=>({status:'UNKNOWN'} as const),lookup:async()=>{lookups++;if(lookups===1)throw Error('fixture lookup failure');return {status:'UNKNOWN'} as const}};await reconcileOnce(s.db,s.orders,port,Date.now()+20000);assert.equal(lookups,2);assert.equal((s.db.prepare('SELECT count(*) n FROM reconciliations WHERE lease_until=0 AND attempts=1').get() as {n:number}).n,2);assert.equal(s.posts(),2)}finally{s.db.close()}});
test('generic flags cannot enable the obsolete guessed HTTP procurement protocol',async()=>{const s=setup();try{const legacy=new SupplyNode({...s.c,SUPPLIER_API_URL:'https://approute.io/api/v1',SUPPLIER_API_KEY:'fixture'},async()=>true,()=>true);assert.equal(legacy.ready,false);await assert.rejects(()=>legacy.purchase('reference','sku',1,'19400'),/NOT_CONFIGURED/);assert.equal(s.posts(),0)}finally{s.db.close()}});
test('reference is stable, keyed, bounded to documented forty characters',()=>{const a=requestRef('fixture-secret','order-a');assert.equal(a.length,40);assert.equal(a,requestRef('fixture-secret','order-a'));assert.notEqual(a,requestRef('another-secret','order-a'));assert.notEqual(a,requestRef('fixture-secret','order-b'))});
test('order rejects mismatched charged amount without fulfillment journal or reveal',async()=>{const s=setup();try{const o=s.orders.create(actor,'p',1);await s.orders.acceptPayment(o.id,actor,proof());s.orders.applySupply(o.id,{status:'COMPLETED',code,chargedUsdUnits:'20000'});assert.equal(s.orders.get(o.id)?.status,'SUPPLIER_UNKNOWN');assert.equal(balance(s.db,'revenue:usdc'),0n)}finally{s.db.close()}});

test('fresh supplier preflight precedes invoice, performs no paid request and idempotent quote replays do not refetch',async()=>{const s=setup();try{const id=randomUUID(),o=await s.orders.createVerified(actor,id,'p',1);assert.equal(o.status,'AWAITING_PAYMENT');assert(s.calls.some(c=>c.path.endsWith('/items/'+item)));assert.equal(s.posts(),0);const calls=s.calls.length;assert.equal((await s.orders.createVerified(actor,id,'p',1)).id,o.id);assert.equal(s.calls.length,calls);await assert.rejects(()=>s.orders.createVerified(actor,id,'p',2),/IDEMPOTENCY_CONFLICT/)}finally{s.db.close()}});
for(const change of [{price:0.02},{stock:0},{available:10.01},{type:'direct_topup'}])test('unavailable fresh quote is rejected before invoice creation: '+JSON.stringify(change),async()=>{const s=setup();try{Object.assign(s.f,change);await assert.rejects(()=>s.orders.createVerified(actor,randomUUID(),'p',1));assert.equal((s.db.prepare('SELECT count(*) n FROM orders').get() as {n:number}).n,0);assert.equal(s.posts(),0)}finally{s.db.close()}});
test('unpaid order and insufficient finality cannot start procurement',async()=>{const s=setup();try{const o=s.orders.create(actor,'p',1);await s.orders.fulfill(o.id);await assert.rejects(()=>s.orders.acceptPayment(o.id,actor,{...proof(),confirmations:1n}),/NOT_FINAL/);assert.equal(s.posts(),0);assert.equal(s.orders.get(o.id)?.status,'AWAITING_PAYMENT')}finally{s.db.close()}});
test('persistent file database survives close/reopen after unknown POST, with no replacement purchase',async()=>{const dir=mkdtempSync(join(tmpdir(),'mercenta-checkout-fixture-')),file=join(dir,'fixture.sqlite'),s=setup(file);let reopened:ReturnType<typeof openDb>|undefined;try{s.f.timeout=true;const o=s.orders.create(actor,'p',1);await s.orders.acceptPayment(o.id,actor,proof());const ref=s.orders.get(o.id)!.request_ref!;s.db.close();reopened=openDb(file);const port=new DocumentedVoucherSupply(reopened,s.c,s.api,{enabled:true}),orders=new Orders(reopened,s.c,s.products,port);orders.recover();orders.applySupply(o.id,await port.lookup(ref));assert.equal(orders.get(o.id)?.status,'FULFILLED');assert.equal(s.posts(),1);assert.equal(orders.reveal(o.id,actor).code,code)}finally{if(s.db.open)s.db.close();reopened?.close();rmSync(dir,{recursive:true,force:true})}});
test('aggregate durable per-key rollout budget cannot exceed one dollar across many references',async()=>{const s=setup();try{for(let i=0;i<52;i++)await s.node.purchase('aggregate_reference_'+i,sku,1,'19400');assert.equal(s.posts(),51);assert.equal((s.db.prepare('SELECT count(*) n FROM voucher_attempts WHERE attempts=1').get() as {n:number}).n,51)}finally{s.db.close()}});
test('documented accounts reader excludes overdraft and preserves ten-dollar circuit breaker',async()=>{const d=openDb(':memory:'),c=loadConfig({NODE_ENV:'test',SUPPLIER_API_URL:'https://approute.io/api/v1',SUPPLIER_API_KEY:'fixture',SUPPLIER_BALANCE_PATH:'/api/v1/accounts'});try{const fetcher=(async(u,i)=>{assert.equal(String(u),'https://approute.io/api/v1/accounts');assert.equal(i?.method,'GET');return Response.json({status:'SUCCESS',statusCode:0,data:{items:[{currency:'USD',balance:9,available:200,overdraftLimit:191}]}})}) as typeof fetch;assert.equal((await refreshProcurementHealth(d,c,fetcher)).open,false);assert.equal(procurementHealth(d).availableUnits,'9000000')}finally{d.close()}});
test('protected HTTP invoice endpoint runs fresh preflight, has owner isolation and does not expose procurement identifiers',async()=>{const s=setup();const app=await buildServer({...s.c,DATABASE_PATH:':memory:'},s.products,(db)=>{recordProcurementHealth(db,{currency:'USD',available:'30',observedAt:Date.now()});return new DocumentedVoucherSupply(db,s.c,s.api,{enabled:true,capEvidence:s.cap})});try{function headers(method:string,url:string,body?:object,a=actor){const ts=String(Date.now());return {'x-mercenta-actor':a,'x-mercenta-timestamp':ts,'x-mercenta-signature':createHmac('sha256',s.c.BACKEND_PROXY_SECRET).update(`${ts}\n${method}\n${url}\n${a}\n${body?JSON.stringify(body):''}`).digest('hex')}}const b={requestId:randomUUID(),productId:'p',quantity:1},created=await app.inject({method:'POST',url:'/api/orders',headers:headers('POST','/api/orders',b),payload:b});assert.equal(created.statusCode,200);const view=created.json();assert.equal(view.status,'AWAITING_PAYMENT');assert(!JSON.stringify(view).includes(item));assert(!JSON.stringify(view).includes('costUnits'));assert.equal(s.posts(),0);const route='/api/orders/'+view.id,foreign=await app.inject({method:'GET',url:route,headers:headers('GET',route,undefined,'wallet:0x'+'2'.repeat(40))});assert.equal(foreign.statusCode,404);const unauth=await app.inject({method:'POST',url:'/api/orders',payload:b});assert.equal(unauth.statusCode,401)}finally{await app.close();s.db.close()}});

test('production flags cannot turn testnet payment into a real voucher',async()=>{const s=setup();try{const prod=new DocumentedVoucherSupply(s.db,{...s.c,NODE_ENV:'production'},s.api,{enabled:true,capEvidence:s.cap});assert.equal(prod.configured,false);assert.equal(prod.ready,false);await assert.rejects(()=>prod.purchase('production_reference',sku,1,'19400'),/NOT_CONFIGURED/);assert.equal(s.posts(),0)}finally{s.db.close()}});
