import test from 'node:test';import assert from 'node:assert/strict';
import {generateReceiptProof,type WitnessPorts,type ReceiptProofInput} from '../src/services/receipt-proof-generator.js';
import {openDb} from '../src/db.js';import {transfer,balance} from '../src/services/ledger/index.js';import {simulateShadow,type ShadowPolicy} from '../src/services/shadow-mode-simulator.js';
import {recordProcurementHealth,reserveProcurement,procurementHealth} from '../src/services/procurement-health.js';
const sender='0x'+'1'.repeat(40),recipient='0x'+'2'.repeat(40),hash='0x'+'a'.repeat(64),block='0x'+'b'.repeat(64),token='0x3600000000000000000000000000000000000000',topic='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',pad=(s:string)=>'0x'+s.slice(2).padStart(64,'0');
const input:ReceiptProofInput={hash,expectedSender:sender,expectedRecipient:recipient,expectedAmountMicro:1000000n};
function witness(name:string,change:Partial<WitnessPorts>={}):WitnessPorts{return {name,endpoint:`https://${name}.example/rpc`,getChainId:async()=>5042002,getTransaction:async()=>({hash,from:sender,to:recipient,value:0n,chainId:5042002}),getReceipt:async()=>({status:1,blockNumber:10n,blockHash:block,from:sender,to:recipient,logs:[{address:token,topics:[topic,pad(sender),pad(recipient)],data:'0x'+(1000000n).toString(16).padStart(64,'0')}]}),getBlock:async()=>({hash:block,number:10n}),getHead:async()=>11n,...change}}
const verify=(a=witness('a'),b=witness('b'),i=input)=>generateReceiptProof(i,{primaryWitness:a,secondaryWitness:b});
test('no zero-value address-only fallback can mint ERC20 proof',async()=>{const bad={getReceipt:async()=>({status:1,blockNumber:10n,blockHash:block,from:sender,to:recipient,logs:[]})};assert.notEqual((await verify(witness('a',bad),witness('b',bad))).status,'VERIFIED')});
test('native receipt must match the exact 18-to-6 decimal conversion',async()=>{const i={...input,assetKind:'native' as const};assert.equal((await verify(witness('a'),witness('b'),i)).reason,'AMOUNT_MISMATCH');const native={getTransaction:async()=>({hash,from:sender,to:recipient,value:1000000000000000000n,chainId:5042002})};assert.equal((await verify(witness('a',native),witness('b',native),i)).status,'VERIFIED')});
test('receipt must be canonical at its block height on both witnesses',async()=>{assert.equal((await verify(witness('a'),witness('b',{getBlock:async()=>({hash:'0x'+'c'.repeat(64),number:10n})}))).reason,'NON_CANONICAL_RECEIPT')});
test('secondary transaction data is checked, not just its receipt block hash',async()=>{assert.equal((await verify(witness('a'),witness('b',{getTransaction:async()=>({hash,from:sender,to:recipient,value:1n,chainId:5042002})}))).reason,'WITNESS_TRANSACTION_MISMATCH')});
test('different witness names cannot disguise the same endpoint',async()=>{assert.equal((await verify(witness('a',{endpoint:'https://same.example/a'}),witness('b',{endpoint:'https://same.example/b'}))).reason,'IDENTICAL_RPC_ENDPOINTS_REJECTED')});
test('minimum confirmations and invalid addresses fail closed',async()=>{assert.equal((await verify(undefined,undefined,{...input,minConfirmations:0})).reason,'INVALID_PROOF_INPUT');assert.equal((await verify(undefined,undefined,{...input,expectedSender:'business-123'})).status,'REJECTED')});
test('proof digest binds the amount and canonical block',async()=>{const good=await verify();const wrong=await verify(undefined,undefined,{...input,expectedAmountMicro:2n});assert.notEqual(good.evidenceDigest,wrong.evidenceDigest);assert.equal(wrong.status,'REJECTED')});
test('ledger exact intent keys distinguish prefixes and reject replay atomically',()=>{const db=openDb(':memory:');try{transfer(db,'fund','capital','equity','cash',100n);transfer(db,'one','source','cash','vendor',1n,'USDC',{intentId:'task-long',sourceDocumentRef:'doc'});transfer(db,'two','source','cash','vendor',1n,'USDC',{intentId:'task',sourceDocumentRef:'doc'});assert.throws(()=>transfer(db,'three','source','cash','vendor',1n,'USDC',{intentId:'task',sourceDocumentRef:'doc'}),/REPLAY/);assert.equal(balance(db,'cash'),98n);assert.equal((db.prepare('SELECT count(*) n FROM ledger_intent_keys').get() as {n:number}).n,2)}finally{db.close()}});
test('live shadow mode requires atomic reserving adapter and explicit addresses',async()=>{const policy:ShadowPolicy={dryRun:false,perRunCapMicro:100n,oneOrderCeilingMicro:100n,reserveFloorMicro:0n,currentVaultBalanceMicro:100n};await assert.rejects(()=>simulateShadow([],{clock:()=>0,idempotencyStore:{has:()=>false,set:()=>{}}},policy),/ATOMIC_ADAPTER_REQUIRED/)});
test('procurement reserves protect the 10 USD floor and stale balance disables new lots',()=>{const db=openDb(':memory:');try{const now=100000;recordProcurementHealth(db,{currency:'USD',available:'11.000000',observedAt:now},now);reserveProcurement(db,'order-first','1000000',now);assert.throws(()=>reserveProcurement(db,'order-second','1',now),/RESERVE_LIMIT/);assert.equal(procurementHealth(db,now+30001).open,false)}finally{db.close()}});
