import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {loadConfig} from '../src/config.js';import {completeIntent,containsProviderCredential,modelAvailability,resetProviderCircuits} from '../src/services/llm-providers.js';
function fixture(){resetProviderCircuits();const dir=mkdtempSync(join(tmpdir(),'mercenta-providers-')),path=join(dir,'providers.json');const providers=[{id:'groq',kind:'openai',url:'https://api.groq.com/openai/v1/chat/completions',model:'openai/gpt-oss-120b',keys:['synthetic-key-primary-001','synthetic-key-spare-002']},{id:'gemini',kind:'gemini',url:'https://generativelanguage.googleapis.com/v1beta',model:'gemini-2.5-flash',keys:['synthetic-gemini-key-001']}];writeFileSync(path,JSON.stringify(providers),{mode:0o600});return {c:{...loadConfig(),LLM_PROVIDERS_FILE:path,LLM_API_KEY:undefined},providers,path,clean:()=>rmSync(dir,{recursive:true,force:true})}}
const messages=[{role:'system' as const,content:'Return safe intent'},{role:'user' as const,content:'Show balance'}];
test('OpenAI intent parsed; credentials never returned',async()=>{const f=fixture();try{const fetcher=(async(u,o)=>{assert.equal(String(u),f.providers[0]!.url);const b=JSON.parse(String(o?.body));assert.equal(b.reasoning_effort,'low');return Response.json({choices:[{message:{content:'{"action":"balance"}'}}]})}) as typeof fetch;const r=await completeIntent(f.c,messages,fetcher);assert.equal(r?.provider,'groq');assert.equal(r?.intent.action,'balance');assert(!JSON.stringify(r).includes('synthetic'));assert.equal(modelAvailability(f.c).configured,true)}finally{f.clean()}});
test('429 respects provider cooldown; never rotates spare keys to evade quotas; Gemini protocol works',async()=>{const f=fixture();try{const calls:string[]=[],fetcher=(async(u,o)=>{calls.push(String(u));if(String(u).includes('groq'))return new Response('',{status:429,headers:{'Retry-After':'120'}});assert.equal((o?.headers as Record<string,string>)['x-goog-api-key'],'synthetic-gemini-key-001');assert(!String(u).includes('synthetic'));const b=JSON.parse(String(o?.body));assert(b.systemInstruction);return Response.json({candidates:[{content:{parts:[{text:'{"action":"catalog"}'}]}}]})}) as typeof fetch;assert.equal((await completeIntent(f.c,messages,fetcher))?.provider,'gemini');assert.equal(calls.filter(u=>u.includes('groq')).length,1);assert.equal((await completeIntent(f.c,messages,fetcher))?.provider,'gemini');assert.equal(calls.filter(u=>u.includes('groq')).length,1);assert.equal(modelAvailability(f.c).providers[0]?.status,'cooldown')}finally{f.clean()}});
test('malformed or arbitrary calls rejected before tool execution, falls back to next provider',async()=>{const f=fixture();try{const fetcher=(async(u)=>String(u).includes('groq')?Response.json({choices:[{message:{content:'{"action":"send","privateKey":"x"}'}}]}):Response.json({candidates:[{content:{parts:[{text:'{"action":"earn"}'}]}}]})) as typeof fetch;assert.equal((await completeIntent(f.c,messages,fetcher))?.intent.action,'earn')}finally{f.clean()}});
test('registry cannot redirect credentials to arbitrary host; missing file is rules fallback',async()=>{const f=fixture();try{f.providers[0]!.url='https://evil.example.com';writeFileSync(f.path,JSON.stringify(f.providers),{mode:0o600});assert.equal(modelAvailability(f.c).configured,false);assert.equal(await completeIntent(f.c,messages,(async()=>{throw Error('must not fetch')}) as typeof fetch),null);assert.equal(modelAvailability({...f.c,LLM_PROVIDERS_FILE:join(tmpdir(),'not-a-provider-registry')}).configured,false)}finally{f.clean()}});
test('oversized responses rejected and all failures return null',async()=>{const f=fixture();try{const fetcher=(async()=>new Response('x'.repeat(65537))) as typeof fetch;assert.equal(await completeIntent(f.c,messages,fetcher),null)}finally{f.clean()}});

test('known provider credentials cannot enter chat or model history',()=>{const f=fixture();try{assert.equal(containsProviderCredential(f.c,'Do not share synthetic-key-primary-001'),true);assert.equal(containsProviderCredential(f.c,'Show my account balance'),false)}finally{f.clean()}});
