import test from 'node:test';import assert from 'node:assert/strict';import {ARC_PRODUCTION,evaluateProductionLaunch,assertProductionNamespace,mainnetMaintenanceMessage} from '../src/services/production-mainnet.js';import {verifyMainnetUsdcReceipt} from '../src/services/mainnet-usdc-receipt.js';import type {WitnessPorts} from '../src/services/receipt-proof-generator.js';import {CHAIN_CONFIGS} from '@circle-fin/x402-batching/client';
const now=1000000,sender='0x'+'1'.repeat(40),recipient='0x'+'2'.repeat(40),txHash='0x'+'a'.repeat(64),blockHash='0x'+'b'.repeat(64),token=ARC_PRODUCTION.usdc;
const checks={separateRuntime:true,separateDatabase:true,separateSecrets:true,mainnetSignerVerified:true,supplyContractVerified:true,providerSpendCapVerified:true,refundPathVerified:true,restoreDrillVerified:true,alertsVerified:true,securityReviewVerified:true,ownerApprovalVerified:true};
const launch=()=>({network:'arc-mainnet',chainId:5042,phase:'canary',ownerWallet:sender,merchantWallet:recipient,databaseNamespace:'mercenta-mainnet',primaryChainId:5042,secondaryChainId:5042,rpcObservedAt:now,supplierAvailableUsdMicro:'12000000',supplierReservedUsdMicro:'0',supplierObservedAt:now,canaryCostUsdMicro:'500000',canarySaleUsdcMicro:'750000',providerRemainingUsdMicro:'1000000',approvalExpiresAt:now+300000,checks:{...checks}});
function witness(host:string,mutate:Record<string,unknown>={}):WitnessPorts{const topic=(a:string)=>'0x'+a.slice(2).padStart(64,'0');const r={status:1,blockNumber:100n,blockHash,from:sender,to:token,logs:[{address:token,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',topic(sender),topic(recipient)],data:'0x'+(1000n).toString(16).padStart(64,'0')}],...mutate};return {name:host,endpoint:'https://'+host,getChainId:async()=>5042,getHead:async()=>103n,getTransaction:async()=>({hash:txHash,from:sender,to:token,value:0n,chainId:5042}),getReceipt:async()=>r,getBlock:async()=>({hash:blockHash,number:100n})};}
const input={hash:txHash,sender,recipient,amountMicro:1000n,assetKind:'erc20' as const},ports=()=>({primaryWitness:witness('primary.example'),secondaryWitness:witness('secondary.example')});
test('SDK production Arc pins match official profile; Testnet contract differs',()=>{assert.equal(CHAIN_CONFIGS.arc.usdc.toLowerCase(),token);assert.equal(CHAIN_CONFIGS.arc.gatewayWallet.toLowerCase(),ARC_PRODUCTION.gatewayWallet);assert.notEqual(CHAIN_CONFIGS.arcTestnet.gatewayWallet.toLowerCase(),ARC_PRODUCTION.gatewayWallet);});
test('complete evidence is only eligible for owner review; never activates routes',()=>{const r=evaluateProductionLaunch(launch(),now);assert.equal(r.eligibleForOwnerCanary,true);assert.equal(r.purchasesEnabled,false);});
for(const name of Object.keys(checks))test('missing production evidence blocks '+name,()=>{const l=launch();(l.checks as Record<string,boolean>)[name]=false;assert.equal(evaluateProductionLaunch(l,now).eligibleForOwnerCanary,false);});
for(const [key,value] of [['phase','closed'],['primaryChainId',5042002],['secondaryChainId',5042002],['rpcObservedAt',now-15001],['supplierObservedAt',now+1],['supplierAvailableUsdMicro',null],['supplierAvailableUsdMicro','10499999'],['supplierReservedUsdMicro','2000000'],['canaryCostUsdMicro','1000001'],['canarySaleUsdcMicro','1000001'],['providerRemainingUsdMicro',null],['providerRemainingUsdMicro','1'],['approvalExpiresAt',now],['approvalExpiresAt',now+600001]] as const)test('launch guard blocks '+key+' '+value,()=>{assert.equal(evaluateProductionLaunch({...launch(),[key]:value},now).eligibleForOwnerCanary,false);});
test('isolation rejects Testnet database even with production flags',()=>{assert.throws(()=>assertProductionNamespace('/var/lib/mercenta/testnet.sqlite','/var/lib/mercenta/testnet.sqlite'));assert.throws(()=>assertProductionNamespace('/var/lib/shared.sqlite','/var/lib/testnet.sqlite'));assert.doesNotThrow(()=>assertProductionNamespace('/var/lib/mercenta-mainnet/ledger.sqlite','/var/lib/mercenta/testnet.sqlite'));});
test('maintenance pauses new purchases but does not erase order or refund obligations',()=>{const r=mainnetMaintenanceMessage();assert.equal(r.purchasesEnabled,false);assert.equal(r.existingOrdersMustRemainReadable,true);assert.equal(r.refundsMustRemainAvailable,true);});
test('exact ERC20 Mainnet canary receipt passes two canonical witnesses',async()=>{assert.equal((await verifyMainnetUsdcReceipt(input,ports())).status,'VERIFIED');});
test('Testnet witness rejected',async()=>{const w=ports();w.secondaryWitness.getChainId=async()=>5042002;assert.equal((await verifyMainnetUsdcReceipt(input,w)).status,'UNVERIFIED');});
test('same RPC hostname rejected',async()=>{const w=ports();w.secondaryWitness.endpoint=w.primaryWitness.endpoint;assert.equal((await verifyMainnetUsdcReceipt(input,w)).status,'UNVERIFIED');});
test('wrong receiver rejected',async()=>{assert.equal((await verifyMainnetUsdcReceipt({...input,recipient:'0x'+'3'.repeat(40)},ports())).status,'UNVERIFIED');});
test('wrong receipt amount rejected',async()=>{assert.equal((await verifyMainnetUsdcReceipt({...input,amountMicro:1001n},ports())).status,'UNVERIFIED');});
test('future/reorg block evidence rejected',async()=>{const w=ports();w.secondaryWitness.getBlock=async()=>({hash:'0x'+'c'.repeat(64),number:100n});assert.equal((await verifyMainnetUsdcReceipt(input,w)).status,'UNVERIFIED');});
test('fewer than three Mainnet confirmations rejected',async()=>{const w=ports();w.secondaryWitness.getHead=async()=>101n;assert.equal((await verifyMainnetUsdcReceipt(input,w)).status,'UNVERIFIED');});
test('native USDC exact 6-to-18-decimal conversion succeeds; dust rejected',async()=>{const w=ports();for(const p of Object.values(w)){p.getTransaction=async()=>({hash:txHash,from:sender,to:recipient,value:1000n*1000000000000n,chainId:5042});p.getReceipt=async()=>({status:1,blockNumber:100n,blockHash,from:sender,to:recipient,logs:[]});}assert.equal((await verifyMainnetUsdcReceipt({...input,assetKind:'native'},w)).status,'VERIFIED');w.secondaryWitness.getTransaction=async()=>({hash:txHash,from:sender,to:recipient,value:1000n*1000000000000n+1n,chainId:5042});assert.equal((await verifyMainnetUsdcReceipt({...input,assetKind:'native'},w)).status,'UNVERIFIED');});
test('unknown RPC outcome is never confirmed or retried as a payment',async()=>{const w=ports();w.primaryWitness.getReceipt=async()=>{throw Error('network')};assert.equal((await verifyMainnetUsdcReceipt(input,w)).status,'UNVERIFIED');});

import {loadConfig} from '../src/config.js';
for(const env of [{FINANCIAL_NETWORK:'mainnet'},{ARC_CHAIN_ID:'5042'},{WEB_ORIGIN:'https://mainnet.mercenta.xyz'},{ARC_RPC_URL:'https://rpc.mainnet.arc.io'},{ARC_SECONDARY_RPC_URL:'https://rpc.quicknode.mainnet.arc.io'}])test('Testnet runtime rejects accidental production configuration '+JSON.stringify(env),()=>{assert.throws(()=>loadConfig({...env,NODE_ENV:'test'}));});
test('namespace rejects dot-segment aliases and misleading substring',()=>{assert.throws(()=>assertProductionNamespace('/var/lib/mercenta-mainnet/../testnet.sqlite','/var/lib/testnet.sqlite'));assert.throws(()=>assertProductionNamespace('/var/lib/not-mercenta-mainnet/ledger.sqlite','/var/lib/testnet.sqlite'));});
test('missing token logs cannot verify a successful USDC transfer',async()=>{const w=ports();w.secondaryWitness.getReceipt=async()=>({status:1,blockNumber:100n,blockHash,from:sender,to:token});assert.equal((await verifyMainnetUsdcReceipt(input,w)).status,'UNVERIFIED');});
