import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {MainnetStagingStore} from '../src/services/mainnet-staging-store.js';
import {createMainnetStagingServer} from '../src/mainnet-staging-server.js';
import type {WitnessPorts} from '../src/services/receipt-proof-generator.js';
import {ARC_PRODUCTION} from '../src/services/production-mainnet.js';
const now=2000000000000,owner='0x'+'1'.repeat(40),merchant='0x'+'2'.repeat(40),hash='0x'+'a'.repeat(64),block='0x'+'b'.repeat(64);
const quote=()=>({reference:randomUUID(),owner,merchant,sku:'mercenta-synthetic-voucher',region:'US',quantity:1 as const,saleMicro:'750000',costMicro:'500000',expiresAt:now+300000,chainId:5042 as const});
function setup(){const dir=mkdtempSync(join(tmpdir(),'mercenta-stage-'));mkdirSync(join(dir,'mercenta-mainnet'));const path=join(dir,'mercenta-mainnet','stage.sqlite'),testnet=join(dir,'testnet.sqlite');const store=new MainnetStagingStore(path,testnet);return {store,path,testnet,dir,cleanup:()=>{store.close();rmSync(dir,{recursive:true,force:true});}};}
function ports(tx=hash,amount=750000n,chain=5042){
 const make=(name:string):WitnessPorts=>({name,endpoint:'https://'+name+'.example',getChainId:async()=>chain,getHead:async()=>103n,getBlock:async()=>({hash:block,number:100n}),getTransaction:async()=>({hash:tx,from:owner,to:ARC_PRODUCTION.usdc,value:0n,chainId:chain}),getReceipt:async()=>({status:1,blockNumber:100n,blockHash:block,from:owner,to:ARC_PRODUCTION.usdc,logs:[{address:ARC_PRODUCTION.usdc,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef','0x'+owner.slice(2).padStart(64,'0'),'0x'+merchant.slice(2).padStart(64,'0')],data:'0x'+amount.toString(16).padStart(64,'0')}]})});return {primaryWitness:make('one'),secondaryWitness:make('two')};
}
async function paid(s:MainnetStagingStore,tx=hash){const id=s.quote(quote(),now);s.authorize(id,owner,now);await s.verifyPayment(id,owner,tx,'erc20',ports(tx),now);return id;}
test('Mainnet stage uses isolated WAL, FULL sync and closed health',()=>{const x=setup();try{assert.equal(x.store.snapshot().journalMode,'wal');assert.equal(x.store.snapshot().purchasesEnabled,false);assert.equal(x.store.db.pragma('synchronous',{simple:true}),2);}finally{x.cleanup();}});
test('reference replay returns same id; changed SKU, owner or amount rejected',()=>{const x=setup();try{const q=quote(),id=x.store.quote(q,now);assert.equal(x.store.quote(q,now),id);for(const change of [{sku:'other'},{owner:'0x'+'3'.repeat(40)},{saleMicro:'800000'}])assert.throws(()=>x.store.quote({...q,...change},now),/REFERENCE_BINDING/);assert.equal(x.store.snapshot().orders,1);}finally{x.cleanup();}});
test('Testnet quote, zero funds, loss price and invalid expiry fail closed',()=>{const x=setup();try{for(const change of [{chainId:5042002},{saleMicro:'0'},{costMicro:'900000'},{expiresAt:now},{expiresAt:now+600001},{saleMicro:'0.75'}])assert.throws(()=>x.store.quote({...quote(),...change},now));assert.equal(x.store.snapshot().orders,0);}finally{x.cleanup();}});
test('cross-owner read and actions cannot see order',()=>{const x=setup();try{const id=x.store.quote(quote(),now);assert.throws(()=>x.store.owned(id,merchant),/NOT_FOUND/);assert.throws(()=>x.store.authorize(id,merchant,now),/NOT_FOUND/);}finally{x.cleanup();}});
test('expired quote cannot authorize',()=>{const x=setup();try{const id=x.store.quote(quote(),now);assert.throws(()=>x.store.authorize(id,owner,now+300000),/EXPIRED/);assert.equal(x.store.owned(id,owner).state,'QUOTED');}finally{x.cleanup();}});
test('two witnesses bind exact payment once; replay does not append event',async()=>{const x=setup();try{const id=await paid(x.store);await x.store.verifyPayment(id,owner,hash,'erc20',ports(),now);assert.equal(x.store.owned(id,owner).state,'PAYMENT_VERIFIED');assert.equal((x.store.db.prepare('SELECT COUNT(*) AS n FROM staging_events').get() as {n:number}).n,3);}finally{x.cleanup();}});
test('a receipt cannot fund two distinct orders',async()=>{const x=setup();try{await paid(x.store);const id=x.store.quote(quote(),now);x.store.authorize(id,owner,now);await assert.rejects(x.store.verifyPayment(id,owner,hash,'erc20',ports(),now),/ALREADY_ATTRIBUTED/);assert.equal(x.store.owned(id,owner).state,'AUTHORIZED');}finally{x.cleanup();}});
test('wrong amount, Testnet, pending receipt never mark payment',async()=>{const x=setup();try{const id=x.store.quote(quote(),now);x.store.authorize(id,owner,now);for(const p of [ports(hash,1n),ports(hash,750000n,5042002)])await assert.rejects(x.store.verifyPayment(id,owner,hash,'erc20',p,now),/NOT_VERIFIED/);const p=ports();p.secondaryWitness.getReceipt=async()=>null;await assert.rejects(x.store.verifyPayment(id,owner,hash,'erc20',p,now));assert.equal(x.store.owned(id,owner).state,'AUTHORIZED');}finally{x.cleanup();}});
test('unpaid order cannot reserve and stale or unknown balance fails closed',async()=>{const x=setup();try{const unpaid=x.store.quote(quote(),now);assert.throws(()=>x.store.reserve(unpaid,owner,{availableUsdMicro:'11000000',observedAt:now},now),/ILLEGAL/);const id=await paid(x.store);for(const b of [{availableUsdMicro:null,observedAt:now},{availableUsdMicro:'11000000',observedAt:now-15001},{availableUsdMicro:'11000000',observedAt:now+1},{availableUsdMicro:'10499999',observedAt:now}])assert.throws(()=>x.store.reserve(id,owner,b,now));assert.equal(x.store.owned(id,owner).reserve_micro,'0');}finally{x.cleanup();}});
test('25 concurrent reservations preserve the ten-dollar floor',async()=>{const x=setup();try{const ids=[];for(let i=0;i<25;i++)ids.push(await paid(x.store,'0x'+(i+1).toString(16).padStart(64,'0')));const other=new MainnetStagingStore(x.path,x.testnet);const results=await Promise.allSettled(ids.map(async (id,i)=>(i%2?other:x.store).reserve(id,owner,{availableUsdMicro:'11000000',observedAt:now},now)));other.close();assert.equal(results.filter(r=>r.status==='fulfilled').length,2);const rows=x.store.db.prepare('SELECT reserve_micro FROM staging_orders').all() as {reserve_micro:string}[];assert.equal(rows.reduce((s,r)=>s+BigInt(r.reserve_micro),0n),1000000n);assert.equal(x.store.snapshot().integrity,'ok');}finally{x.cleanup();}});
test('intent persisted before I/O; unknown outcome retains reserve and forbids repost after restart',async()=>{const x=setup();try{const id=await paid(x.store);x.store.reserve(id,owner,{availableUsdMicro:'11000000',observedAt:now},now);x.store.procurementIntent(id,owner,now);x.store.quarantine(id,owner,now);const reopened=new MainnetStagingStore(x.path,x.testnet);try{assert.equal(reopened.owned(id,owner).state,'SUPPLIER_UNKNOWN');assert.equal(reopened.owned(id,owner).reserve_micro,'500000');assert.throws(()=>reopened.procurementIntent(id,owner,now),/ILLEGAL/);}finally{reopened.close();}}finally{x.cleanup();}});
test('refund is idempotent manual review only, no execution',async()=>{const x=setup();try{const id=await paid(x.store);for(let i=0;i<2;i++)assert.equal(x.store.requestRefundReview(id,owner,now).refundExecuted,false);assert.equal((x.store.db.prepare('SELECT COUNT(*) AS n FROM staging_refund_requests').get() as {n:number}).n,1);}finally{x.cleanup();}});
test('event log rejects UPDATE and DELETE',()=>{const x=setup();try{x.store.quote(quote(),now);assert.throws(()=>x.store.db.exec('DELETE FROM staging_events'),/APPEND_ONLY/);assert.throws(()=>x.store.db.exec("UPDATE staging_events SET to_state='DELIVERED'"),/APPEND_ONLY/);}finally{x.cleanup();}});
test('closed HTTP runtime exposes no order, payment, auth or deposit writes',async()=>{const x=setup();x.store.close();const app=await createMainnetStagingServer(x.path,x.testnet);try{const h=await app.inject({url:'/api/health'});assert.equal(h.statusCode,200);assert.equal(h.json().chainId,5042);for(const url of ['/api/orders','/api/deposit','/api/auth','/api/refunds']){const r=await app.inject({method:'POST',url,payload:{}});assert.equal(r.statusCode,503);assert.equal(r.json().purchasesEnabled,false);}assert.equal((await app.inject({url:'/api/readiness'})).json().capabilities.signer,false);}finally{await app.close();rmSync(x.dir,{recursive:true,force:true});}});

test('staging refuses an existing foreign database instead of adopting its balances',()=>{const x=setup();x.store.db.exec('CREATE TABLE real_customer_balance(amount TEXT)');assert.throws(()=>new MainnetStagingStore(x.path,x.testnet),/NOT_EMPTY_OR_ISOLATED/);x.cleanup();});

function delivery(q:ReturnType<typeof quote>,code='MERCENTA-SYNTHETIC-NOT-REDEEMABLE'){return {reference:q.reference,sku:q.sku,region:q.region,costUsdMicro:q.costMicro,codes:[code]};}
function refundPorts(tx:string){const p=ports(tx);const topic=(a:string)=>'0x'+a.slice(2).padStart(64,'0');for(const w of Object.values(p)){w.getTransaction=async()=>({hash:tx,from:merchant,to:ARC_PRODUCTION.usdc,value:0n,chainId:5042});w.getReceipt=async()=>({status:1,blockNumber:100n,blockHash:block,from:merchant,to:ARC_PRODUCTION.usdc,logs:[{address:ARC_PRODUCTION.usdc,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',topic(merchant),topic(owner)],data:'0x'+(750000n).toString(16).padStart(64,'0')}]});}return p;}
async function submitted(s:MainnetStagingStore){const q=quote(),id=s.quote(q,now);s.authorize(id,owner,now);await s.verifyPayment(id,owner,hash,'erc20',ports(),now);s.reserve(id,owner,{availableUsdMicro:'11000000',observedAt:now},now);s.procurementIntent(id,owner,now);return {id,q};}
test('verified payment books cash and liability atomically in micro-USDC',async()=>{const x=setup();try{await paid(x.store);assert.deepEqual(x.store.journal.totals(),{'USDC:merchant_cash':'750000','USDC:customer_liability':'-750000'});}finally{x.cleanup();}});
test('journal failure rolls back receipt attribution and state, preventing omitted payment books',async()=>{const x=setup();try{const id=x.store.quote(quote(),now);x.store.authorize(id,owner,now);x.store.db.exec("CREATE TRIGGER fail_journal BEFORE INSERT ON staging_journal_lines BEGIN SELECT RAISE(ABORT,'TEST_JOURNAL_FAILURE'); END;");await assert.rejects(x.store.verifyPayment(id,owner,hash,'erc20',ports(),now),/TEST_JOURNAL_FAILURE/);assert.equal(x.store.owned(id,owner).state,'AUTHORIZED');assert.equal((x.store.db.prepare('SELECT COUNT(*) AS n FROM staging_receipts').get() as {n:number}).n,0);assert.deepEqual(x.store.journal.totals(),{});}finally{x.cleanup();}});
test('full delivery is encrypted, ownership-bound, idempotent and currency-separated',async()=>{const x=setup();try{const {id,q}=await submitted(x.store),key=Buffer.alloc(32,7),d=delivery(q);assert.deepEqual(x.store.sealDelivery(id,owner,d,key,now),{delivered:true,secretReturned:false});x.store.sealDelivery(id,owner,d,key,now);assert.deepEqual(x.store.readOwnedDelivery(id,owner,key),d);assert.throws(()=>x.store.readOwnedDelivery(id,merchant,key),/NOT_FOUND/);assert.throws(()=>x.store.readOwnedDelivery(id,owner,Buffer.alloc(32,8)));const stored=x.store.db.prepare('SELECT encrypted_payload FROM staging_delivery').get() as {encrypted_payload:string};assert.ok(!stored.encrypted_payload.includes(d.codes[0]!));assert.equal(x.store.owned(id,owner).reserve_micro,'0');assert.deepEqual(x.store.journal.totals(),{'USDC:merchant_cash':'750000','USDC:customer_liability':'0','USDC:sales_revenue':'-750000','USD:procurement_expense':'500000','USD:supplier_credit':'-500000'});assert.throws(()=>x.store.sealDelivery(id,owner,delivery(q,'OTHER-SYNTHETIC'),key,now),/REPLAY_MISMATCH/);}finally{x.cleanup();}});
test('partial and wrong denomination or region deliveries cannot recognize revenue',async()=>{const x=setup();try{const {id,q}=await submitted(x.store);for(const d of [{...delivery(q),codes:[]},{...delivery(q),region:'BR'},{...delivery(q),sku:'wrong'},{...delivery(q),costUsdMicro:'600000'}])assert.throws(()=>x.store.sealDelivery(id,owner,d,Buffer.alloc(32,1),now));assert.equal(x.store.owned(id,owner).state,'PROCUREMENT_SUBMITTED');assert.equal(x.store.journal.totals()['USDC:sales_revenue'],undefined);}finally{x.cleanup();}});
test('delivery journal failure rolls back encrypted code and both FSM transitions',async()=>{const x=setup();try{const {id,q}=await submitted(x.store);x.store.db.exec("CREATE TRIGGER fail_delivery BEFORE INSERT ON staging_journals WHEN NEW.kind='DELIVERY' BEGIN SELECT RAISE(ABORT,'TEST_DELIVERY_FAILURE'); END;");assert.throws(()=>x.store.sealDelivery(id,owner,delivery(q),Buffer.alloc(32,1),now),/TEST_DELIVERY_FAILURE/);assert.equal(x.store.owned(id,owner).state,'PROCUREMENT_SUBMITTED');assert.equal((x.store.db.prepare('SELECT COUNT(*) AS n FROM staging_delivery').get() as {n:number}).n,0);assert.equal(x.store.owned(id,owner).reserve_micro,'500000');}finally{x.cleanup();}});
test('unknown procurement manual refund is verified once and retains the unresolved supply reservation',async()=>{const x=setup();try{const {id}=await submitted(x.store);x.store.quarantine(id,owner,now);const tx='0x'+'c'.repeat(64);assert.deepEqual(await x.store.recordManualRefund(id,owner,tx,'erc20',refundPorts(tx),now),{recorded:true,refundExecuted:false});await x.store.recordManualRefund(id,owner,tx,'erc20',refundPorts(tx),now);assert.equal(x.store.owned(id,owner).reserve_micro,'500000');assert.equal(x.store.owned(id,owner).state,'SUPPLIER_UNKNOWN');assert.deepEqual(x.store.journal.totals(),{'USDC:merchant_cash':'0','USDC:customer_liability':'0'});await assert.rejects(x.store.recordManualRefund(id,owner,'0x'+'d'.repeat(64),'erc20',refundPorts('0x'+'d'.repeat(64)),now),/ALREADY_RECORDED/);}finally{x.cleanup();}});
test('payment-direction, pending and wrong-owner refunds never change liabilities',async()=>{const x=setup();try{const id=await paid(x.store),tx='0x'+'c'.repeat(64);await assert.rejects(x.store.recordManualRefund(id,owner,tx,'erc20',ports(tx),now),/NOT_VERIFIED/);await assert.rejects(x.store.recordManualRefund(id,merchant,tx,'erc20',refundPorts(tx),now),/NOT_FOUND/);assert.equal(x.store.journal.totals()['USDC:customer_liability'],'-750000');}finally{x.cleanup();}});
test('refund after delivery books returns instead of creating negative customer liability',async()=>{const x=setup();try{const {id,q}=await submitted(x.store);x.store.sealDelivery(id,owner,delivery(q),Buffer.alloc(32,1),now);const tx='0x'+'c'.repeat(64);await x.store.recordManualRefund(id,owner,tx,'erc20',refundPorts(tx),now);const t=x.store.journal.totals();assert.equal(t['USDC:customer_liability'],'0');assert.equal(t['USDC:sales_returns'],'750000');assert.equal(t['USDC:merchant_cash'],'0');}finally{x.cleanup();}});
test('quote and financial journal are append-only, not editable balance counters',async()=>{const x=setup();try{await paid(x.store);assert.throws(()=>x.store.db.exec("UPDATE staging_orders SET body='{}'"),/QUOTE_IMMUTABLE/);for(const table of ['staging_journals','staging_journal_lines'])assert.throws(()=>x.store.db.exec('DELETE FROM '+table),/APPEND_ONLY/);}finally{x.cleanup();}});

test('legacy receipts without a journal require explicit reconciliation, never silent migration',()=>{const x=setup();try{const id=x.store.quote(quote(),now);x.store.db.exec('DROP TABLE staging_journal_lines; DROP TABLE staging_journals;');x.store.db.prepare('INSERT INTO staging_receipts VALUES(?,?,?)').run(hash,id,'{}');assert.throws(()=>new MainnetStagingStore(x.path,x.testnet),/REQUIRES_RECEIPT_RECONCILIATION/);}finally{x.cleanup();}});
