import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomBytes,randomUUID} from 'node:crypto';
import {privateKeyToAccount} from 'viem/accounts';
import {MainnetStagingStore,type StagingQuote} from '../src/services/mainnet-staging-store.js';
import {MainnetWalletAuth,MAINNET_COOKIE_OPTIONS} from '../src/services/mainnet-wallet-auth.js';
import {MainnetCanaryOperator,canaryTypedData} from '../src/services/mainnet-canary-operator.js';
import {createMainnetStagingServer} from '../src/mainnet-staging-server.js';
import {PublicCommerceApi} from '../src/services/fulfillment/public-commerce-api.js';
import {ARC_PRODUCTION,type ProductionLaunch} from '../src/services/production-mainnet.js';import type {WitnessPorts} from '../src/services/receipt-proof-generator.js';
const account=()=>privateKeyToAccount(('0x'+randomBytes(32).toString('hex')) as `0x${string}`);
const origin='https://mainnet.mercenta.xyz',merchant='0x'+'2'.repeat(40),tx='0x'+'a'.repeat(64),block='0x'+'b'.repeat(64);
function fixture(){
 const dir=mkdtempSync(join(tmpdir(),'mercenta-mainnet-integration-'));mkdirSync(join(dir,'mercenta-mainnet'));const path=join(dir,'mercenta-mainnet','orders.sqlite'),store=new MainnetStagingStore(path,join(dir,'testnet.sqlite')),auth=new MainnetWalletAuth(store.db),owner=account(),customer=account(),service=randomUUID(),item=randomUUID(),sku=service+':'+item,clock={now:Date.now()},counters={posts:0,unhide:0,getOrders:0},flags={timeout:false,stock:1,cost:'0.5',country:'US',cap:true,phase:'canary' as 'canary'|'closed',status:'SUCCESS',debit:'-0.5',gas:21000n,wrongReceipt:false};
 let reference='',orderId='mercenta-synthetic-order',saleMicro='545000';
 const envelope=(data:unknown,status='SUCCESS',code=0)=>new Response(JSON.stringify({status,statusCode:code,data}),{status:status==='IN_PROGRESS'?202:200,headers:{'Content-Type':'application/json'}});
 const fetcher:typeof fetch=async(input,init)=>{
  const url=new URL(String(input)),p=url.pathname.replace('/api/v1','');
  if(init?.method==='POST'){assert.equal(p,'/orders');counters.posts++;const b=JSON.parse(String(init.body));assert.equal(b.ordersType,'shop');assert.equal(b.orders[0].quantity,1);assert.equal(b.orders[0].denominationId,item);reference=b.referenceId;if(flags.timeout)throw Error('synthetic-timeout-after-accept');return envelope({orderId,currency:'USD',price:flags.cost},'IN_PROGRESS',1);}
  if(p==='/services/'+service)return envelope({id:service,type:'voucher',countryCode:flags.country,fields:null});
  if(p==='/services/'+service+'/items/'+item)return envelope({id:item,price:flags.cost,currency:'USD',inStock:flags.stock,isLongOrder:false});
  if(p==='/accounts')return envelope({items:[{currency:'USD',balance:'12',available:'12'}]});
  if(p==='/accounts/transactions')return envelope({totalCount:1,items:[{currency:'USD',orderId,amount:flags.debit}]});
  if(p==='/orders'){counters.getOrders++;if(url.searchParams.get('unhide')==='true')counters.unhide++;return envelope({page:{items:[{orderId,reference:flags.wrongReceipt?randomUUID():reference,itemId:item,quantity:1,currency:'USD',amount:'0.5',status:flags.status,vouchers:[{pin:url.searchParams.get('unhide')==='true'?'MERCENTA-SYNTHETIC-NOT-REDEEMABLE':'****1234'}]}]}});}
  throw Error('Unexpected synthetic endpoint');
 };
 const api=new PublicCommerceApi('synthetic-key-'+randomUUID(),fetcher,'https://supply.example/api/v1','https://supply.example');
 const make=(name:string):WitnessPorts=>({name,endpoint:'https://'+name+'.example',getChainId:async()=>5042,getHead:async()=>103n,getBlock:async()=>({hash:block,number:100n}),getTransaction:async()=>({hash:tx,from:customer.address,to:ARC_PRODUCTION.usdc,value:0n,chainId:5042}),getReceipt:async()=>({status:1,blockNumber:100n,blockHash:block,from:customer.address,to:ARC_PRODUCTION.usdc,gasUsed:flags.gas,effectiveGasPrice:20000000000n,logs:[{address:ARC_PRODUCTION.usdc,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef','0x'+customer.address.slice(2).toLowerCase().padStart(64,'0'),'0x'+merchant.slice(2).padStart(64,'0')],data:'0x'+BigInt(saleMicro).toString(16).padStart(64,'0')}]})});
 const witnesses={primaryWitness:make('first'),secondaryWitness:make('second')};
 const evidence=():ProductionLaunch=>({network:'arc-mainnet',chainId:5042,phase:flags.phase,ownerWallet:owner.address,merchantWallet:merchant,databaseNamespace:'mercenta-mainnet',primaryChainId:5042,secondaryChainId:5042,rpcObservedAt:clock.now,supplierAvailableUsdMicro:'12000000',supplierReservedUsdMicro:'0',supplierObservedAt:clock.now,canaryCostUsdMicro:'500000',canarySaleUsdcMicro:saleMicro,providerRemainingUsdMicro:'500000',approvalExpiresAt:clock.now+100000,checks:{separateRuntime:true,separateDatabase:true,separateSecrets:true,mainnetSignerVerified:true,supplyContractVerified:true,providerSpendCapVerified:true,refundPathVerified:true,restoreDrillVerified:true,alertsVerified:true,securityReviewVerified:true,ownerApprovalVerified:true}});
 const ports={api,ownerWallet:owner.address,merchantWallet:merchant,deliveryKey:Buffer.alloc(32,7),launchEvidence:evidence,capEvidence:()=>flags.cap?{verified:true,currency:'USD' as const,remainingUsd:'0.5',keyFingerprint:api.keyFingerprint,observedAt:clock.now}:undefined,witnesses,allowedSku:(s:string)=>s===sku,clock:()=>Math.max(clock.now,Date.now()),pricing:()=>({usdPerUsdcMicro:'1000000',markupBps:900,policyId:'owner-fixed-peg-synthetic-only'})};
 const operator=new MainnetCanaryOperator(store,ports);
 async function quote(){const q=await operator.prepareQuote(customer.address,sku,'US');saleMicro=q.saleMicro;return q;}
 async function signed(id:string,change:Partial<{expiresAt:number;gasCapMicro:string;nonce:`0x${string}`}>= {},signer=owner){const row=store.owned(id,customer.address),q=JSON.parse(row.body) as StagingQuote,g={nonce:('0x'+randomBytes(32).toString('hex')) as `0x${string}`,orderId:id,expiresAt:clock.now+120000,gasCapMicro:'10000',allowVoucherReceipt:true as const,...change};return {...g,signature:await signer.signTypedData(canaryTypedData(q,id,row.fingerprint,g))};}
 async function approved(){const q=await quote();await operator.approve(q.id,customer.address,await signed(q.id));return q;}
 async function paid(){const q=await approved();await operator.verifyPayment(q.id,customer.address,tx,'erc20');return q;}
 return {store,auth,operator,ports,customer,owner,clock,counters,flags,quote,signed,approved,paid,sku,cleanup:()=>{store.close();rmSync(dir,{recursive:true,force:true});}};
}
test('Mainnet sign-in is origin/chain scoped, hashes sessions, and grants no money permission',async()=>{const f=fixture();try{const c=f.auth.issue(f.customer.address,origin,f.clock.now);assert.ok(c.message.includes('Chain ID: 5042'));assert.ok(c.message.includes('does not authorize'));const signature=await f.customer.signMessage({message:c.message}),s=await f.auth.verify({address:f.customer.address,origin,nonce:c.nonce,signature},f.clock.now);assert.equal(s.paymentsAuthorized,false);assert.equal(f.auth.actor(s.token,origin,f.clock.now),f.customer.address.toLowerCase());const row=f.store.db.prepare('SELECT token_hash FROM staging_auth_sessions').get() as {token_hash:string};assert.notEqual(row.token_hash,s.token);assert.equal(MAINNET_COOKIE_OPTIONS.secure,true);await assert.rejects(f.auth.verify({address:f.customer.address,origin,nonce:c.nonce,signature},f.clock.now),/REJECTED/);f.auth.revoke(s.token);assert.throws(()=>f.auth.actor(s.token,origin,f.clock.now),/REJECTED/);}finally{f.cleanup();}});
test('Testnet origin, changed sign-in text and expired nonce are rejected',async()=>{const f=fixture();try{assert.throws(()=>f.auth.issue(f.customer.address,'https://testnet.mercenta.xyz',f.clock.now));const c=f.auth.issue(f.customer.address,origin,f.clock.now),signature=await f.customer.signMessage({message:c.message.replace('5042','5042002')});await assert.rejects(f.auth.verify({address:f.customer.address,origin,nonce:c.nonce,signature},f.clock.now));const valid=await f.customer.signMessage({message:c.message});await assert.rejects(f.auth.verify({address:f.customer.address,origin,nonce:c.nonce,signature:valid},f.clock.now+300000));}finally{f.cleanup();}});
test('parallel nonce consumption creates only one authenticated session',async()=>{const f=fixture();try{const c=f.auth.issue(f.customer.address,origin,f.clock.now),signature=await f.customer.signMessage({message:c.message});const results=await Promise.allSettled(Array.from({length:10},()=>f.auth.verify({address:f.customer.address,origin,nonce:c.nonce,signature},f.clock.now)));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);}finally{f.cleanup();}});
test('fresh quote uses explicit pricing policy, supported region and stock',async()=>{const f=fixture();try{const q=await f.quote();assert.equal(q.saleMicro,'545000');assert.equal(q.purchasesEnabled,false);assert.equal(f.counters.posts,0);await assert.rejects(f.operator.prepareQuote(f.customer.address,f.sku,'BR'));f.flags.stock=0;await assert.rejects(f.quote());}finally{f.cleanup();}});
test('full contract flow signs owner scope, verifies payment, posts once and seals exact delivery',async()=>{const f=fixture();try{const q=await f.paid();assert.equal((await f.operator.procure(q.id,f.customer.address)).status,'PENDING');assert.equal((await f.operator.reconcile(q.id,f.customer.address)).status,'DELIVERED');assert.equal((await f.operator.procure(q.id,f.customer.address)).status,'DELIVERED');assert.equal(f.counters.posts,1);assert.equal(f.counters.unhide,1);assert.equal(f.store.owned(q.id,f.customer.address).reserve_micro,'0');assert.equal(f.store.journal.totals()['USDC:customer_liability'],'0');const g=f.store.db.prepare('SELECT encrypted_proof FROM staging_owner_grants').get() as {encrypted_proof:string};assert.ok(!g.encrypted_proof.includes('signature'));}finally{f.cleanup();}});
test('a customer sign-in or customer signature cannot substitute for owner purchase permission',async()=>{const f=fixture();try{const q=await f.quote();await assert.rejects(f.operator.approve(q.id,f.customer.address,await f.signed(q.id,{},f.customer)),/OWNER_CANARY_SIGNATURE/);await assert.rejects(f.operator.procure(q.id,f.customer.address),/PAYMENT/);assert.equal(f.counters.posts,0);}finally{f.cleanup();}});
test('expired and altered gas grants reject before payment or supply',async()=>{const f=fixture();try{const q=await f.quote();await assert.rejects(f.operator.approve(q.id,f.customer.address,await f.signed(q.id,{expiresAt:f.clock.now})),/GRANT_INVALID/);const g=await f.signed(q.id);await assert.rejects(f.operator.approve(q.id,f.customer.address,{...g,gasCapMicro:'20000'}),/SIGNATURE/);assert.equal(f.counters.posts,0);}finally{f.cleanup();}});
test('over-budget gas records the received payment liability but prevents procurement',async()=>{const f=fixture();try{const q=await f.approved();f.flags.gas=1000000n;await assert.rejects(f.operator.verifyPayment(q.id,f.customer.address,tx,'erc20'),/GAS_CAP/);assert.equal(f.store.owned(q.id,f.customer.address).state,'PAYMENT_VERIFIED');await assert.rejects(f.operator.procure(q.id,f.customer.address),/GAS_REQUIRED/);assert.equal(f.counters.posts,0);assert.equal(f.store.journal.totals()['USDC:customer_liability'],'-545000');}finally{f.cleanup();}});
for(const mode of ['closed','no-cap','price-changed','out-of-stock','wrong-region'] as const)test('supply fails closed for '+mode,async()=>{const f=fixture();try{const q=await f.paid();if(mode==='closed')f.flags.phase='closed';if(mode==='no-cap')f.flags.cap=false;if(mode==='price-changed')f.flags.cost='0.6';if(mode==='out-of-stock')f.flags.stock=0;if(mode==='wrong-region')f.flags.country='BR';await assert.rejects(f.operator.procure(q.id,f.customer.address));assert.equal(f.counters.posts,0);assert.equal(f.store.owned(q.id,f.customer.address).reserve_micro,'0');}finally{f.cleanup();}});
test('timeout after submit is lookup-only across retry, with reserve retained',async()=>{const f=fixture();try{const q=await f.paid();f.flags.timeout=true;assert.equal((await f.operator.procure(q.id,f.customer.address)).status,'SUPPLIER_UNKNOWN');assert.equal(f.store.owned(q.id,f.customer.address).reserve_micro,'500000');f.clock.now+=700000;f.flags.phase='closed';f.flags.cap=false;assert.equal((await f.operator.procure(q.id,f.customer.address)).status,'DELIVERED');assert.equal(f.counters.posts,1);}finally{f.cleanup();}});
for(const mode of ['partial','wrong-debit','wrong-reference'] as const)test('reconciliation refuses '+mode+' before unmasking codes',async()=>{const f=fixture();try{const q=await f.paid();await f.operator.procure(q.id,f.customer.address);if(mode==='partial')f.flags.status='PARTIALLY_COMPLETED';if(mode==='wrong-debit')f.flags.debit='-0.4';if(mode==='wrong-reference')f.flags.wrongReceipt=true;assert.equal((await f.operator.reconcile(q.id,f.customer.address)).status,'SUPPLIER_UNKNOWN');assert.equal(f.counters.unhide,0);assert.equal(f.store.owned(q.id,f.customer.address).reserve_micro,'500000');}finally{f.cleanup();}});
test('one lifetime canary slot and one active owner grant prevent another order',async()=>{const f=fixture();try{const first=await f.paid(),second=await f.quote();await assert.rejects(f.operator.approve(second.id,f.customer.address,await f.signed(second.id)),/ONE_OWNER_CANARY/);await f.operator.procure(first.id,f.customer.address);await assert.rejects(f.operator.approve(second.id,f.customer.address,await f.signed(second.id)),/ONE_OWNER_CANARY/);assert.equal(f.counters.posts,1);assert.throws(()=>f.store.db.exec('DELETE FROM staging_canary_slot'),/IMMUTABLE/);}finally{f.cleanup();}});
test('another wallet cannot inspect, approve or reconcile the owned order',async()=>{const f=fixture();try{const q=await f.quote();await assert.rejects(f.operator.approve(q.id,f.owner.address,await f.signed(q.id)),/NOT_FOUND/);await assert.rejects(f.operator.reconcile(q.id,f.owner.address),/NOT_FOUND/);assert.equal(f.counters.posts,0);}finally{f.cleanup();}});

test('identity HTTP routes set a separate Secure host cookie, reject sibling origins, and never enable money',async()=>{const f=fixture(),app=await createMainnetStagingServer(f.store.db.name,join(tmpdir(),'not-this-mainnet.sqlite'));try{
 const preflight=await app.inject({method:'OPTIONS',url:'/api/auth/verify',headers:{origin}});assert.equal(preflight.statusCode,204);assert.equal(preflight.headers['access-control-allow-origin'],origin);
 const denied=await app.inject({method:'POST',url:'/api/auth/nonce',headers:{origin:'https://testnet.mercenta.xyz'},payload:{address:f.customer.address}});assert.equal(denied.statusCode,403);assert.equal(denied.headers['access-control-allow-origin'],undefined);
 const challenge=await app.inject({method:'POST',url:'/api/auth/nonce',headers:{origin},payload:{address:f.customer.address}});assert.equal(challenge.statusCode,200);const c=challenge.json();const signature=await f.customer.signMessage({message:c.message});
 const verified=await app.inject({method:'POST',url:'/api/auth/verify',headers:{origin},payload:{address:f.customer.address,nonce:c.nonce,signature}});assert.equal(verified.statusCode,200);assert.equal(verified.json().paymentsEnabled,false);assert.equal(verified.json().token,undefined);const cookie=String(verified.headers['set-cookie']);assert.ok(cookie.startsWith('__Host-mercenta-mainnet-session='));assert.ok(cookie.includes('HttpOnly; Secure; SameSite=Strict'));assert.ok(!cookie.includes('Domain='));
 assert.equal((await app.inject({url:'/api/auth/session',headers:{origin,cookie}})).json().authenticated,true);
 for(const url of ['/api/orders','/api/deposit','/api/procure'])assert.equal((await app.inject({method:'POST',url,headers:{origin,cookie},payload:{}})).statusCode,503);
 await app.inject({method:'POST',url:'/api/auth/logout',headers:{origin,cookie},payload:{}});assert.equal((await app.inject({url:'/api/auth/session',headers:{origin,cookie}})).json().authenticated,false);
 }finally{await app.close();f.cleanup();}});
