import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';import Database from 'better-sqlite3';
import {createRetailQuote,validateRetailQuote,retailQuoteDigest,retailPaymentVerificationInput,MAINNET_RETAIL_RECIPIENT,MAINNET_RETAIL_POLICY} from '../src/services/mainnet-retail-policy.js';
import {MainnetRetailStore} from '../src/services/mainnet-retail-store.js';
import {verifyMainnetUsdcReceipt,verifyRetailMainnetUsdcReceipt} from '../src/services/mainnet-usdc-receipt.js';
import {ARC_PRODUCTION} from '../src/services/production-mainnet.js';
import type {DualWitnessPorts,WitnessPorts} from '../src/services/receipt-proof-generator.js';
const now=1700000000123,owner='0x'+'1'.repeat(40),other='0x'+'2'.repeat(40),hash='0x'+'a'.repeat(64),blockHash='0x'+'b'.repeat(64);
const observation=()=>({serviceId:'11111111-1111-4111-8111-111111111111',itemId:'22222222-2222-4222-8222-222222222222',region:'US',type:'voucher',requiredFields:[],unitCostUsdMicro:'10000000',inStock:50,observedAt:now,cashUsdMicro:'500000000',cashObservedAt:now});
const quote=()=>createRetailQuote(owner,1,observation(),0n,now);
function ports(q=quote(),timestamp=BigInt(Math.ceil(now/1000))):DualWitnessPorts{
 const port=(endpoint:string):WitnessPorts=>({name:endpoint,endpoint,getChainId:async()=>5042,getHead:async()=>102n,
 getTransaction:async()=>({hash,from:q.owner,to:q.recipient,value:BigInt(q.saleUsdcMicro)*1000000000000n,chainId:5042}),
 getReceipt:async()=>({status:1,blockHash,blockNumber:100n,from:q.owner,to:q.recipient,logs:[]}),getBlock:async()=>({hash:blockHash,number:100n,timestamp})});
 return {primaryWitness:port('https://primary.example'),secondaryWitness:port('https://secondary.example')};
}
const input=(q=quote(),at=now+2000)=>retailPaymentVerificationInput(q,hash,'native',at);
function withStore<T>(work:(store:MainnetRetailStore,path:string)=>T){const dir=mkdtempSync(join(tmpdir(),'mercenta-retail-')),root=join(dir,'mercenta-mainnet');mkdirSync(root);const path=join(root,'retail.sqlite'),s=new MainnetRetailStore(path,join(dir,'testnet.sqlite'));const finish=()=>{try{s.close()}finally{rmSync(dir,{recursive:true,force:true})}};try{const value=work(s,path);if(value instanceof Promise)return value.finally(finish);finish();return value}catch(e){finish();throw e}}

test('owner public recipient is pinned, policy does not enable transfers',()=>{assert.equal(MAINNET_RETAIL_RECIPIENT,'0x58863e4a739da0e62c2eba258b7783e95d5c48ce');assert.equal(MAINNET_RETAIL_POLICY.paymentsEnabled,false);assert.equal(MAINNET_RETAIL_POLICY.refundMode,'support-owner-manual');});
test('fresh retail quote above one dollar uses nine percent markup',()=>{const q=quote();assert.equal(q.costUsdMicro,'10000000');assert.equal(q.saleUsdcMicro,'10900000');assert.equal(q.quantity,1);assert.equal(q.expiresAt,now+300000);});
test('submicro markup rounds upward per unit, not twice',()=>{const q=createRetailQuote(owner,3,{...observation(),unitCostUsdMicro:'1'},0n,now);assert.equal(q.costUsdMicro,'3');assert.equal(q.saleUsdcMicro,'6');});
for(const change of [{recipient:other},{chainId:5042002},{saleUsdcMicro:'10000000'},{costUsdMicro:'1'},{expiresAt:now+300001},{owner:MAINNET_RETAIL_RECIPIENT},{extra:'untrusted'},{quantity:101}])test('immutable quote rejects '+Object.keys(change).join(','),()=>assert.throws(()=>validateRetailQuote({...quote(),...change})));
for(const change of [{type:'direct_topup'},{type:'esim'},{requiredFields:['account']},{inStock:0},{unitCostUsdMicro:'0'},{unitCostUsdMicro:'0.1'},{observedAt:now-15001},{observedAt:now+1},{cashObservedAt:now-15001},{cashUsdMicro:'10000000'},{cashUsdMicro:'19999999'}])test('quote fails closed for '+JSON.stringify(change),()=>assert.throws(()=>createRetailQuote(owner,1,{...observation(),...change},0n,now)));
test('quantity and aggregate cash reservation are checked',()=>{assert.throws(()=>createRetailQuote(owner,51,observation(),0n,now));assert.throws(()=>createRetailQuote(owner,1,observation(),480000001n,now));assert.doesNotThrow(()=>createRetailQuote(owner,1,observation(),480000000n,now));});
test('digest is stable after owner casing normalization',()=>{const q=quote();assert.equal(retailQuoteDigest(q),retailQuoteDigest({...q,owner:q.owner.toUpperCase().replace('0X','0x')}));});
test('retail exact native payment above one dollar is verified, legacy canary remains capped',async()=>{const q=quote();assert.equal((await verifyRetailMainnetUsdcReceipt(input(q),ports(q))).status,'VERIFIED');assert.equal((await verifyMainnetUsdcReceipt(input(q),ports(q))).status,'UNVERIFIED');});
test('canonical timestamp prevents old matching transaction',async()=>{const r=await verifyRetailMainnetUsdcReceipt(input(),ports(quote(),BigInt(Math.floor(now/1000))));assert.equal(r.status,'UNVERIFIED');assert.equal('reason' in r&&r.reason,'PAYMENT_PREDATES_QUOTE');});
test('future block is not accepted',async()=>{const r=await verifyRetailMainnetUsdcReceipt(input(),ports(quote(),BigInt(Math.floor(now/1000))+20n));assert.equal(r.status,'UNVERIFIED');});
test('missing or disagreeing timestamp blocks retail verification',async()=>{for(const timestamp of [undefined,BigInt(Math.ceil(now/1000))+1n]){const w=ports();w.secondaryWitness.getBlock=async()=>({hash:blockHash,number:100n,timestamp});assert.equal((await verifyRetailMainnetUsdcReceipt(input(),w)).status,'UNVERIFIED');}});
test('wrong canonical block height fails even with matching hash',async()=>{const w=ports();w.primaryWitness.getBlock=async()=>({hash:blockHash,number:99n,timestamp:BigInt(Math.ceil(now/1000))});assert.equal((await verifyRetailMainnetUsdcReceipt(input(),w)).status,'UNVERIFIED');});
test('wrong chain, recipient, amount, reverted receipt and insufficient confirmations fail',async()=>{for(const variant of ['chain','recipient','amount','status','head','rpc','sameHost']){const q=quote(),w=ports(q),b=w.secondaryWitness;
 if(variant==='chain')b.getChainId=async()=>5042002;
 if(variant==='recipient')b.getTransaction=async()=>({hash,from:owner,to:other,value:10900000n*1000000000000n,chainId:5042});
 if(variant==='amount')b.getTransaction=async()=>({hash,from:owner,to:q.recipient,value:10900000n*1000000000000n+1n,chainId:5042});
 if(variant==='status')b.getReceipt=async()=>({status:0,blockHash,blockNumber:100n,from:owner,to:q.recipient});
 if(variant==='head')b.getHead=async()=>101n;
 if(variant==='rpc')b.getReceipt=async()=>{throw Error('timeout')};
 if(variant==='sameHost')b.endpoint=w.primaryWitness.endpoint;
 assert.equal((await verifyRetailMainnetUsdcReceipt(input(q),w)).status,'UNVERIFIED',variant);
 }});
test('retail ERC20 payment needs exact single token transfer in both witnesses',async()=>{const q=quote(),w=ports(q),topic=(s:string)=>'0x'+s.slice(2).padStart(64,'0');const log={address:ARC_PRODUCTION.usdc,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',topic(owner),topic(q.recipient)],data:'0x'+BigInt(q.saleUsdcMicro).toString(16).padStart(64,'0')};for(const p of Object.values(w)){p.getTransaction=async()=>({hash,from:owner,to:ARC_PRODUCTION.usdc,value:0n,chainId:5042});p.getReceipt=async()=>({status:1,blockHash,blockNumber:100n,from:owner,to:ARC_PRODUCTION.usdc,logs:[log]});}const i={...input(q),assetKind:'erc20' as const};assert.equal((await verifyRetailMainnetUsdcReceipt(i,w)).status,'VERIFIED');w.secondaryWitness.getReceipt=async()=>({status:1,blockHash,blockNumber:100n,from:owner,to:ARC_PRODUCTION.usdc,logs:[log,log]});assert.equal((await verifyRetailMainnetUsdcReceipt(i,w)).status,'UNVERIFIED');});
test('quote owner isolation hides other customer order',()=>withStore(s=>{const q=s.quote(owner,1,observation(),now);assert.throws(()=>s.get(q.id,other));assert.equal(s.get(q.id,owner).state,'QUOTED');}));
test('atomic stock holds cannot sell last unit twice; expired unpaid hold releases',()=>withStore(s=>{const o={...observation(),inStock:1};s.quote(owner,1,o,now);assert.throws(()=>s.quote(other,1,o,now));const later=now+300000;assert.doesNotThrow(()=>s.quote(other,1,{...o,observedAt:later,cashObservedAt:later},later));}));
test('aggregate quote cash holds preserve ten dollars',()=>withStore(s=>{const o={...observation(),cashUsdMicro:'30000000'};s.quote(owner,1,o,now);s.quote(other,1,o,now);assert.throws(()=>s.quote(other,1,o,now));assert.equal(s.accounting(now).procurementHeldUsdMicro,'20000000');}));
test('concurrent receipt replay books incoming liability once and never revenue',()=>withStore(async s=>{const q=s.quote(owner,1,observation(),now);const results=await Promise.all(Array.from({length:25},()=>s.recordPayment(q.id,owner,hash,'native',ports(q),now+2000)));assert.equal(results.filter(r=>'replay' in r&&!r.replay).length,1);assert.equal(s.accounting(now).incomingCustomerLiabilityUsdcMicro,'10900000');assert.equal(s.accounting(now).revenueUsdcMicro,'0');assert.equal(s.accounting(now).purchasesEnabled,false);}));
test('same settled hash cannot pay two quotes',()=>withStore(async s=>{const a=s.quote(owner,1,observation(),now),b=s.quote(owner,1,observation(),now);await s.recordPayment(a.id,owner,hash,'native',ports(a),now+2000);await assert.rejects(s.recordPayment(b.id,owner,hash,'native',ports(b),now+2000),/ALREADY_CLAIMED/);}));
test('late observed payment becomes manual liability without buying anything',()=>withStore(async s=>{const q=s.quote(owner,1,observation(),now),later=now+301000;const r=await s.recordPayment(q.id,owner,hash,'native',ports(q,BigInt(Math.floor(later/1000))),later);assert.equal('state' in r&&r.state,'MANUAL_REVIEW');assert.equal(s.accounting(later).incomingCustomerLiabilityUsdcMicro,'10900000');assert.equal(s.accounting(later).signingEnabled,false);}));
test('invalid payment leaves accounting and hold unchanged',()=>withStore(async s=>{const q=s.quote(owner,1,observation(),now),before=s.accounting(now);const r=await s.recordPayment(q.id,owner,hash,'native',ports(q,0n),now+2000);assert.equal(r.recorded,false);assert.deepEqual(s.accounting(now),before);}));
test('WAL payment claim persists across restart',()=>withStore(async(s,path)=>{const q=s.quote(owner,1,observation(),now);await s.recordPayment(q.id,owner,hash,'native',ports(q),now+2000);const second=new MainnetRetailStore(path,join(tmpdir(),'testnet.sqlite'));try{assert.equal(second.get(q.id,owner).transactionHash,hash);assert.equal(second.accounting(now).integrity,'ok');const r=await second.recordPayment(q.id,owner,hash,'native',ports(q),now+2000);assert.equal('replay' in r&&r.replay,true);}finally{second.close();}}));
test('retail refuses a database containing staging or operational tables',()=>{const dir=mkdtempSync(join(tmpdir(),'mercenta-')),root=join(dir,'mercenta-mainnet');mkdirSync(root);const path=join(root,'retail.sqlite'),db=new Database(path);db.exec('CREATE TABLE staging_orders(id TEXT)');db.close();try{assert.throws(()=>new MainnetRetailStore(path,join(dir,'testnet.sqlite')),/SEPARATE/);}finally{rmSync(dir,{recursive:true,force:true});}});

import {SupplyMonitor,createSupplyMonitorServer} from '../src/supply-monitor-server.js';
import {loadConfig} from '../src/config.js';
test('public recipient policy is read-only, never a transfer instruction or activation',async()=>{const db=new Database(':memory:'),app=createSupplyMonitorServer(new SupplyMonitor(db,loadConfig({NODE_ENV:'test'})));try{const r=await app.inject({method:'GET',url:'/payment-policy'});assert.equal(r.statusCode,200);const p=r.json();assert.equal(p.recipient,MAINNET_RETAIL_RECIPIENT);assert.equal(p.chainId,5042);assert.equal(p.paymentsEnabled,false);assert.equal(p.transferInstructionsAvailable,false);assert.equal(r.headers['cache-control'],'no-store');assert.equal((await app.inject({method:'POST',url:'/payment-policy',payload:{recipient:other,paymentsEnabled:true}})).statusCode,405);}finally{await app.close();db.close();}});
