import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {MainnetStagingStore} from '../src/services/mainnet-staging-store.js';
import {createMainnetStagingServer} from '../src/mainnet-staging-server.js';
import type {WitnessPorts} from '../src/services/receipt-proof-generator.js';
import {ARC_PRODUCTION} from '../src/services/production-mainnet.js';
const now=2000000000000,owner='0x'+'1'.repeat(40),merchant='0x'+'2'.repeat(40),hash='0x'+'a'.repeat(64),block='0x'+'b'.repeat(64);
const quote=()=>({reference:randomUUID(),owner,merchant,sku:'mercenta-synthetic-voucher',region:'US',quantity:1 as const,saleMicro:'750000',costMicro:'500000',expiresAt:now+300000,chainId:5042 as const});
function setup(){const dir=mkdtempSync(join(tmpdir(),'mercenta-stage-'));mkdirSync(join(dir,'mercenta-mainnet'));const path=join(dir,'mercenta-mainnet','stage.sqlite'),testnet=join(dir,'testnet.sqlite');const store=new MainnetStagingStore(path,testnet);return {store,path,testnet,dir,cleanup:()=>{store.close();rmSync(dir,{recursive:true,force:true});}};}
function ports(tx=hash,amount=750000n,chain=5042){
 const make=(name:string):WitnessPorts=>({name,endpoint:'https://'+name+'.example',getChainId:async()=>chain,getHead:async()=>103n,getBlock:async()=>({hash:block,number:100n}),getTransaction:async()=>({hash:tx,from:owner,to:ARC_PRODUCTION.usdc,value:0n,chainId:chain}),getReceipt:async()=>({status:1,blockNumber:100n,blockHash:block,from:owner,to:ARC_PRODUCTION.usdc,logs:[{address:ARC_PRODUCTION.usdc,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef','0x'+owner.slice(2).padStart(64,'0'),'0x'+merchant.slice(2).padStart(64,'0')],data:'0x'+amount.toString(16).padStart(64,'0')}]})});return {primaryWitness:make('one'),secondaryWitness:make('two')};
}
async function paid(s:MainnetStagingStore,tx=hash){const id=s.quote(quote(),now);s.authorize(id,owner,now);await s.verifyPayment(id,owner,tx,'erc20',ports(tx),now);return id;}
test('Mainnet stage uses isolated WAL, FULL sync and closed health',()=>{const x=setup();try{assert.equal(x.store.snapshot().journalMode,'wal');assert.equal(x.store.snapshot().purchasesEnabled,false);assert.equal(x.store.db.pragma('synchronous',{simple:true}),2);}finally{x.cleanup();}});
test('reference replay returns same id; changed SKU, owner or amount rejected',()=>{const x=setup();try{const q=quote(),id=x.store.quote(q,now);assert.equal(x.store.quote(q,now),id);for(const change of [{sku:'other'},{owner:'0x'+'3'.repeat(40)},{saleMicro:'800000'}])assert.throws(()=>x.store.quote({...q,...change},now),/REFERENCE_BINDING/);assert.equal(x.store.snapshot().orders,1);}finally{x.cleanup();}});
test('Testnet quote, zero funds, loss price and invalid expiry fail closed',()=>{const x=setup();try{for(const change of [{chainId:5042002},{saleMicro:'0'},{costMicro:'900000'},{expiresAt:now},{expiresAt:now+600001},{saleMicro:'0.75'}])assert.throws(()=>x.store.quote({...quote(),...change},now));assert.equal(x.store.snapshot().orders,0);}finally{x.cleanup();}});
test('cross-owner read and actions cannot see order',()=>{const x=setup();try{const id=x.store.quote(quote(),now);assert.throws(()=>x.store.owned(id,merchant),/NOT_FOUND/);assert.throws(()=>x.store.authorize(id,merchant,now),/NOT_FOUND/);}finally{x.cleanup();}});
test('expired quote cannot authorize',()=>{const x=setup();try{const id=x.store.quote(quote(),now);assert.throws(()=>x.store.authorize(id,owner,now+300000),/EXPIRED/);assert.equal(x.store.owned(id,owner).state,'QUOTED');}finally{x.cleanup();}});
test('two witnesses bind exact payment once; replay does not append event',async()=>{const x=setup();try{const id=await paid(x.store);await x.store.verifyPayment(id,owner,hash,'erc20',ports(),now);assert.equal(x.store.owned(id,owner).state,'PAYMENT_VERIFIED');assert.equal((x.store.db.prepare('SELECT COUNT(*) AS n FROM staging_events').get() as {n:number}).n,3);}finally{x.cleanup();}});
test('a receipt cannot fund two distinct orders',async()=>{const x=setup();try{await paid(x.store);const id=x.store.quote(quote(),now);x.store.authorize(id,owner,now);await assert.rejects(x.store.verifyPayment(id,owner,hash,'erc20',ports(),now),/ALREADY_ATTRIBUTED/);assert.equal(x.store.owned(id,owner).state,'AUTHORIZED');}finally{x.cleanup();}});
test('wrong amount, Testnet, pending receipt never mark payment',async()=>{const x=setup();try{const id=x.store.quote(quote(),now);x.store.authorize(id,owner,now);for(const p of [ports(hash,1n),ports(hash,750000n,5042002)])await assert.rejects(x.store.verifyPayment(id,owner,hash,'erc20',p,now),/NOT_VERIFIED/);const p=ports();p.secondaryWitness.getReceipt=async()=>null;await assert.rejects(x.store.verifyPayment(id,owner,hash,'erc20',p,now));assert.equal(x.store.owned(id,owner).state,'AUTHORIZED');}finally{x.cleanup();}});
test('unpaid order cannot reserve and stale or unknown balance fails closed',async()=>{const x=setup();try{const unpaid=x.store.quote(quote(),now);assert.throws(()=>x.store.reserve(unpaid,owner,{availableUsdMicro:'11000000',observedAt:now},now),/ILLEGAL/);const id=await paid(x.store);for(const b of [{availableUsdMicro:null,observedAt:now},{availableUsdMicro:'11000000',observedAt:now-15001},{availableUsdMicro:'11000000',observedAt:now+1},{availableUsdMicro:'10499999',observedAt:now}])assert.throws(()=>x.store.reserve(id,owner,b,now));assert.equal(x.store.owned(id,owner).reserve_micro,'0');}finally{x.cleanup();}});
test('25 concurrent reservations preserve the ten-dollar floor',async()=>{const x=setup();try{const ids=[];for(let i=0;i<25;i++)ids.push(await paid(x.store,'0x'+(i+1).toString(16).padStart(64,'0')));const other=new MainnetStagingStore(x.path,x.testnet);const results=await Promise.allSettled(ids.map(async (id,i)=>(i%2?other:x.store).reserve(id,owner,{availableUsdMicro:'11000000',observedAt:now},now)));other.close();assert.equal(results.filter(r=>r.status==='fulfilled').length,2);const rows=x.store.db.prepare('SELECT reserve_micro FROM staging_orders').all() as {reserve_micro:string}[];assert.equal(rows.reduce((s,r)=>s+BigInt(r.reserve_micro),0n),1000000n);assert.equal(x.store.snapshot().integrity,'ok');}finally{x.cleanup();}});
test('intent persisted before I/O; unknown outcome retains reserve and forbids repost after restart',async()=>{const x=setup();try{const id=await paid(x.store);x.store.reserve(id,owner,{availableUsdMicro:'11000000',observedAt:now},now);x.store.procurementIntent(id,owner,now);x.store.quarantine(id,owner,now);const reopened=new MainnetStagingStore(x.path,x.testnet);try{assert.equal(reopened.owned(id,owner).state,'SUPPLIER_UNKNOWN');assert.equal(reopened.owned(id,owner).reserve_micro,'500000');assert.throws(()=>reopened.procurementIntent(id,owner,now),/ILLEGAL/);}finally{reopened.close();}}finally{x.cleanup();}});
test('refund is idempotent manual review only, no execution',async()=>{const x=setup();try{const id=await paid(x.store);for(let i=0;i<2;i++)assert.equal(x.store.requestRefundReview(id,owner,now).refundExecuted,false);assert.equal((x.store.db.prepare('SELECT COUNT(*) AS n FROM staging_refund_requests').get() as {n:number}).n,1);}finally{x.cleanup();}});
test('event log rejects UPDATE and DELETE',()=>{const x=setup();try{x.store.quote(quote(),now);assert.throws(()=>x.store.db.exec('DELETE FROM staging_events'),/APPEND_ONLY/);assert.throws(()=>x.store.db.exec("UPDATE staging_events SET to_state='DELIVERED'"),/APPEND_ONLY/);}finally{x.cleanup();}});
test('closed HTTP runtime exposes no order, payment, auth or deposit writes',async()=>{const x=setup();x.store.close();const app=await createMainnetStagingServer(x.path,x.testnet);try{const h=await app.inject({url:'/api/health'});assert.equal(h.statusCode,200);assert.equal(h.json().chainId,5042);for(const url of ['/api/orders','/api/deposit','/api/auth','/api/refunds']){const r=await app.inject({method:'POST',url,payload:{}});assert.equal(r.statusCode,503);assert.equal(r.json().purchasesEnabled,false);}assert.equal((await app.inject({url:'/api/readiness'})).json().capabilities.signer,false);}finally{await app.close();rmSync(x.dir,{recursive:true,force:true});}});

test('staging refuses an existing foreign database instead of adopting its balances',()=>{const x=setup();x.store.db.exec('CREATE TABLE real_customer_balance(amount TEXT)');assert.throws(()=>new MainnetStagingStore(x.path,x.testnet),/NOT_EMPTY_OR_ISOLATED/);x.cleanup();});
