import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {openDb} from '../src/db.js';import {MicroPurchaseProbe,verifyMicroQuote,type ProbeAdapter} from '../src/services/fulfillment/micro-purchase.js';
const now=Date.now(),key='12'.repeat(32),ref='owner_probe_001';const quote=(x:Record<string,unknown>={})=>({itemId:'gift-item-1',quoteId:'fixed-quote-1',quantity:1,currency:'USD',totalUsd:'0.25',feesIncluded:true,priceBinding:'fixed-final-quote',stockVerified:true,balanceUsd:'20',balanceVerified:true,expiresAt:now+60000,...x});const done=(x:Record<string,unknown>={})=>({reference:ref,status:'COMPLETED',providerOrderId:'provider-order-1',itemId:'gift-item-1',quoteId:'fixed-quote-1',quantity:1,currency:'USD',chargedUsd:'0.25',code:'FIXTURE_ONLY_NOT_A_REAL_PRODUCT',...x});
function setup(response:unknown=done()){const db=openDb(':memory:');let posts=0,gets=0;const adapter:ProbeAdapter={contractVerified:true,purchase:async()=>{posts++;return response},lookup:async()=>{gets++;return done()}};const probe=new MicroPurchaseProbe(db,adapter,key);return {db,adapter,probe,counts:()=>({posts,gets})}}
test('owner probe: fixed USD final quote includes all fees and exact one-dollar boundary',()=>{assert.equal(verifyMicroQuote(quote({totalUsd:'1.000000'}),now).quantity,1);assert.throws(()=>verifyMicroQuote(quote({totalUsd:'1.000001'}),now),/OWNER_ONE_DOLLAR_LIMIT/)});
for(const [name,change] of Object.entries({zero:{totalUsd:'0'},negative:{totalUsd:'-1'},float:{totalUsd:0.25},precision:{totalUsd:'0.2500001'},currency:{currency:'EUR'},quantity:{quantity:2},feeUnknown:{feesIncluded:false},priceUnbound:{priceBinding:'catalogue-preview'},stockUnverified:{stockVerified:false},balanceUnverified:{balanceVerified:false},expired:{expiresAt:now-1},unboundedExpiry:{expiresAt:now+300001},reserve:{balanceUsd:'10.249999'}}))test('owner probe rejects '+name+' before any POST',async()=>{const s=setup();await assert.rejects(()=>s.probe.execute(ref,quote(change),now));assert.equal(s.counts().posts,0);assert.equal(s.probe.status(),null);s.db.close()});
test('one POST, encrypted delivery, receipt and idempotent replay; no clear code in status',async()=>{const s=setup();await s.probe.execute(ref,quote(),now);await s.probe.execute(ref,quote(),now+999999);assert.equal(s.counts().posts,1);assert.equal(s.probe.status()?.status,'COMPLETED');assert.equal(s.probe.ownerDelivery(ref),'FIXTURE_ONLY_NOT_A_REAL_PRODUCT');assert.equal(JSON.stringify(s.probe.status()).includes('FIXTURE'),false);const row=s.db.prepare('SELECT delivery_encrypted FROM owner_micro_purchase_probe').get() as {delivery_encrypted:string};assert.equal(row.delivery_encrypted.includes('FIXTURE'),false);s.db.close()});
test('a second reference cannot spend even the remaining authorization budget',async()=>{const s=setup();await s.probe.execute(ref,quote(),now);await assert.rejects(()=>s.probe.execute('owner_probe_002',quote(),now),/SINGLE_ATTEMPT/);assert.equal(s.counts().posts,1);s.db.close()});
test('same reference with changed quote is a conflict, not a new invoice',async()=>{const s=setup();await s.probe.execute(ref,quote(),now);await assert.rejects(()=>s.probe.execute(ref,quote({totalUsd:'0.5'}),now),/IDEMPOTENCY_CONFLICT/);assert.equal(s.counts().posts,1);s.db.close()});
test('unverified actual adapter cannot spend, even with a valid fixture quote',async()=>{const s=setup();s.adapter.contractVerified=false;await assert.rejects(()=>s.probe.execute(ref,quote(),now),/PROVIDER_CONTRACT_UNVERIFIED/);assert.equal(s.counts().posts,0);s.db.close()});
test('transport timeout preserves claim; only GET lookup can recover delivery',async()=>{const s=setup();s.adapter.purchase=async()=>{throw Error('timeout')};await s.probe.execute(ref,quote(),now);assert.equal(s.probe.status()?.status,'UNKNOWN');await s.probe.execute(ref,quote(),now);await s.probe.reconcile(ref);assert.equal(s.counts().gets,1);assert.equal(s.probe.status()?.status,'COMPLETED');s.db.close()});
test('unknown reference cannot reveal or reconcile another order',async()=>{const s=setup();await s.probe.execute(ref,quote(),now);assert.throws(()=>s.probe.ownerDelivery('other_ref_001'));await assert.rejects(()=>s.probe.reconcile('other_ref_001'));assert.equal(s.counts().gets,0);s.db.close()});
test('wrong reference, malformed status and fee ambiguity never claim successful delivery',async()=>{for(const result of [done({reference:'other_ref_001'}),done({chargedUsd:0.25}),{status:'COMPLETED'},done({currency:'EUR'})]){const s=setup(result);await s.probe.execute(ref,quote(),now);assert.equal(s.probe.status()?.status,'UNKNOWN');assert.throws(()=>s.probe.ownerDelivery(ref));s.db.close()}});
test('overcharge is an incident, never a verified receipt or fake refund',async()=>{const s=setup(done({chargedUsd:'1.01'}));await s.probe.execute(ref,quote(),now);assert.equal(s.probe.status()?.status,'INCIDENT');assert.throws(()=>s.probe.ownerDelivery(ref));await s.probe.reconcile(ref);assert.equal(s.counts().gets,0);s.db.close()});
test('concurrent runs share one durable attempt',async()=>{const s=setup();await Promise.all([s.probe.execute(ref,quote(),now),s.probe.execute(ref,quote(),now)]);assert.equal(s.counts().posts,1);s.db.close()});
test('restart retains uncertain claim and does not POST replacement',async()=>{const dir=mkdtempSync(join(tmpdir(),'mercenta-owner-probe-')),file=join(dir,'probe.sqlite');let db=openDb(file),posts=0;const a:ProbeAdapter={contractVerified:true,purchase:async()=>{posts++;throw Error('timeout')},lookup:async()=>done()};let p=new MicroPurchaseProbe(db,a,key);await p.execute(ref,quote(),now);db.close();db=openDb(file);p=new MicroPurchaseProbe(db,a,key);await p.execute(ref,quote(),now);assert.equal(posts,1);await p.reconcile(ref);assert.equal(p.status()?.status,'COMPLETED');db.close();rmSync(dir,{recursive:true,force:true})});
test('invalid encryption key blocks probe before financial action',()=>{const s=setup();assert.throws(()=>new MicroPurchaseProbe(s.db,s.adapter,'bad'),/ENCRYPTION/);s.db.close()});

for(const change of [{itemId:'wrong-item'},{quoteId:'wrong-fixed-quote'}])test('wrong item/quote binding never reveals delivery',async()=>{const s=setup(done(change));await s.probe.execute(ref,quote(),now);assert.equal(s.probe.status()?.status,'INCIDENT');assert.throws(()=>s.probe.ownerDelivery(ref));s.db.close()});
