import test from 'node:test';import assert from 'node:assert/strict';import {buildOperatorTelemetry,type OperatorTelemetryInput} from '../src/services/operator-telemetry.js';
const sample:OperatorTelemetryInput={id:'11111111-1111-4111-8111-111111111111',status:'QUOTED',step:3,maxSteps:6,updatedAt:1000,expiresAt:600000,events:[{seq:1,tool:'account.read',status:'CHECKED',result:{wallet:'private',code:'private'}},{seq:2,tool:'catalog.search',status:'CHECKED',result:{apiKey:'hidden'}}],receipt:null,scope:{chainId:5042002,realPurchasingEnabled:false}};
test('telemetry is deterministic, unsigned and never invents settlement proof',()=>{const a=buildOperatorTelemetry(sample);assert.deepEqual(a,buildOperatorTelemetry(sample));assert.equal(a.settlementProofVerified,false);assert.equal(a.kind,'UNSIGNED_OPERATOR_OBSERVATION');assert.equal(a.observedEventCount,2);assert.match(a.digest,/^[a-f0-9]{64}$/)});
test('private results, provider credentials and voucher payloads are excluded',()=>{const out=JSON.stringify(buildOperatorTelemetry({...sample,receipt:{codes:['secret-voucher']},events:[{seq:1,tool:'receipt.read',status:'CHECKED',result:{password:'private-value'},provider:'private-provider'}]}));for(const text of ['secret-voucher','private-value','private-provider','password','apiKey'])assert(!out.includes(text));assert(out.includes('"receiptAvailable":true'));assert(out.includes('"settlementProofVerified":false'))});
test('wrong network or enabled real purchasing cannot generate rehearsal telemetry',()=>{for(const scope of [{chainId:5042,realPurchasingEnabled:false},{chainId:5042002,realPurchasingEnabled:true}])assert.throws(()=>buildOperatorTelemetry({...sample,scope}),/SCOPE_REJECTED/)});
test('invalid ordering, unsafe seq or budget-step counts fail closed',()=>{for(const seq of [0,-1,NaN,2**54])assert.throws(()=>buildOperatorTelemetry({...sample,events:[{seq,tool:'x',status:'CHECKED'}]}));assert.throws(()=>buildOperatorTelemetry({...sample,events:[{seq:2,tool:'x',status:'CHECKED'},{seq:2,tool:'x',status:'CHECKED'}]}));assert.throws(()=>buildOperatorTelemetry({...sample,step:7}));assert.throws(()=>buildOperatorTelemetry({...sample,updatedAt:NaN}))});
test('unstable or arbitrary tool strings are redacted and observation digest changes with state',()=>{const x=buildOperatorTelemetry({...sample,events:[{seq:1,tool:'secret with whitespace',status:'payload with whitespace'}]});assert.equal(x.events[0]!.tool,'REDACTED');assert.equal(x.events[0]!.status,'REDACTED');assert.notEqual(buildOperatorTelemetry(sample).digest,buildOperatorTelemetry({...sample,status:'BLOCKED'}).digest)});

import {openDb} from '../src/db.js';import {loadConfig} from '../src/config.js';import {initOperator,createOperator,operatorView,cancelOperator} from '../src/services/agent-operator.js';
test('authenticated operator view exposes only persisted unsigned observations and retains owner isolation',()=>{const db=openDb(':memory:');try{initOperator(db);const c=loadConfig({NODE_ENV:'test',DELIVERY_ENCRYPTION_KEY:'a'.repeat(64),BACKEND_PROXY_SECRET:'x'.repeat(40)}),actor='wallet:0x'+'1'.repeat(40);const run=createOperator(db,c,actor,{requestId:sample.id,message:'Find Roblox',budgetUsdc:'3',reserveUsdc:'0',region:'US',quantity:1,execution:'review',authorizeTestSpend:false});const view=operatorView(db,actor,run.id,c.DELIVERY_ENCRYPTION_KEY);assert.equal(view.telemetry.runId,view.id);assert.equal(view.telemetry.status,view.status);assert.equal(view.telemetry.observedEventCount,view.events.length);assert.equal(view.telemetry.settlementProofVerified,false);assert.equal(view.telemetry.digest,operatorView(db,actor,run.id,c.DELIVERY_ENCRYPTION_KEY).telemetry.digest);assert.throws(()=>operatorView(db,'wallet:0x'+'2'.repeat(40),run.id,c.DELIVERY_ENCRYPTION_KEY));const cancelled=cancelOperator(db,c,actor,run.id);assert.equal(cancelled.telemetry.status,'CANCELLED');assert.notEqual(cancelled.telemetry.digest,view.telemetry.digest)}finally{db.close()}});
