import test from 'node:test';import assert from 'node:assert/strict';import {openDb} from '../src/db.js';import {loadConfig} from '../src/config.js';import {recordProcurementHealth,procurementHealth,publicProcurementHealth,requireProcurementFunds,refreshProcurementHealth,MAX_BALANCE_AGE_MS,reserveProcurement} from '../src/services/procurement-health.js';import {financeCapabilities} from '../src/services/app-kit/capabilities.js';import {SupplyNode} from '../src/services/fulfillment/index.js';import {mintOnrampSession} from '../src/services/app-kit/index.js';
const now=Date.now(),c=loadConfig({NODE_ENV:'test'}),credit=(available:string)=>({currency:'USD',available,observedAt:now});
test('exact USD boundary: ten and below pause, above ten opens, no floating point rounding',()=>{const d=openDb(':memory:');assert.equal(recordProcurementHealth(d,credit('9.999999'),now).open,false);assert.equal(recordProcurementHealth(d,credit('12'),now).open,true);assert.equal(recordProcurementHealth(d,credit('10'),now).open,false);assert.equal(procurementHealth(d,now).availableUnits,'10000000');d.close()});
test('balance recovers automatically as soon as above ten',()=>{const d=openDb(':memory:');recordProcurementHealth(d,credit('9'),now);assert.equal(recordProcurementHealth(d,credit('10.5'),now).open,true);assert.equal(recordProcurementHealth(d,credit('11.999999'),now).reason,'READY');assert.equal(recordProcurementHealth(d,credit('12'),now).open,true);d.close()});
test('unknown, stale, future, non-USD, floats, negatives and malformed values fail closed',()=>{for(const raw of [null,credit('-1'),credit('NaN'),credit('1e3'),{...credit('30'),available:30},{...credit('30'),currency:'EUR'},{...credit('30'),observedAt:now-30001},{...credit('30'),observedAt:now+5001}]){const d=openDb(':memory:');assert.equal(recordProcurementHealth(d,raw,now).open,false);d.close()}});
test('balances age out without a client poll; stale funds cannot authorize execution',()=>{const d=openDb(':memory:');recordProcurementHealth(d,credit('30'),now);assert.throws(()=>requireProcurementFunds(d,'1000000',now+MAX_BALANCE_AGE_MS+1),/SERVICE_PURCHASES_PAUSED/);d.close()});
test('per-order cost cannot breach operating reserve; exact remaining ten is allowed',()=>{const d=openDb(':memory:');recordProcurementHealth(d,credit('15'),now);requireProcurementFunds(d,'5000000',now);assert.throws(()=>requireProcurementFunds(d,'5000001',now),/SERVICE_RESERVE_LIMIT/);assert.throws(()=>requireProcurementFunds(d,'1e6',now),/PROCUREMENT_COST_UNVERIFIED/);d.close()});
test('public maintenance status reveals no business balance or credential and keeps testnet separate',()=>{const d=openDb(':memory:');recordProcurementHealth(d,credit('30'),now);const v=publicProcurementHealth(d,c);assert.equal(v.lotsEnabled,false);assert.equal(v.realPurchasesEnabled,false);assert.equal(v.testnetRehearsalEnabled,true);assert(!JSON.stringify(v).includes('30000000'));d.close()});
test('configured fulfillment alone cannot silently enable real supplier orders',async()=>{const node=new SupplyNode({...c,ENABLE_FULFILLMENT:'true',SUPPLIER_ALLOWED_ORIGIN:'https://supplier.example',SUPPLIER_API_URL:'https://supplier.example/api/v1',SUPPLIER_API_KEY:'fixture-key'});assert.equal(node.ready,false);await assert.rejects(node.purchase('ref','sku',1),/SUPPLY_NODE_NOT_CONFIGURED/)});
test('unverified order cost is refused before any supplier call',async()=>{let checked=0;const node=new SupplyNode({...c,ENABLE_FULFILLMENT:'true',FULFILLMENT_CONTRACT_VERIFIED:'true',SUPPLIER_ALLOWED_ORIGIN:'https://supplier.example',SUPPLIER_API_URL:'https://supplier.example/api/v1',SUPPLIER_API_KEY:'fixture'},async()=>{checked++;return true},()=>true);await assert.rejects(node.purchase('ref','sku',1),/PROCUREMENT_COST_UNVERIFIED/);assert.equal(checked,0)});
test('missing verified balance contract performs no guessed API request',async()=>{const d=openDb(':memory:');let calls=0;const h=await refreshProcurementHealth(d,{...c,SUPPLIER_ALLOWED_ORIGIN:'https://supplier.example',SUPPLIER_API_URL:'https://supplier.example/api/v1',SUPPLIER_API_KEY:'fixture'},(async()=>{calls++;throw Error('no')}) as typeof fetch);assert.equal(h.open,false);assert.equal(calls,0);d.close()});
test('balance API is fixed-host, GET-only, no redirects, bounded and schema-validated',async()=>{const d=openDb(':memory:');const cfg={...c,SUPPLIER_ALLOWED_ORIGIN:'https://supplier.example',SUPPLIER_API_URL:'https://supplier.example/api/v1',SUPPLIER_API_KEY:'fixture',SUPPLIER_BALANCE_PATH:'/api/v1/account/balance'};const h=await refreshProcurementHealth(d,cfg,(async(_url,o)=>{assert.equal(o?.redirect,'error');assert.equal(o?.method,undefined);return Response.json({currency:'USD',available:'30',observedAt:Date.now()})}) as typeof fetch);assert.equal(h.open,true);assert.equal((await refreshProcurementHealth(d,cfg,(async()=>new Response('x'.repeat(9000))) as typeof fetch)).open,false);d.close()});
test('balance credential cannot be sent to another host',async()=>{const d=openDb(':memory:');let called=false;const h=await refreshProcurementHealth(d,{...c,SUPPLIER_API_URL:'https://evil.example',SUPPLIER_API_KEY:'fixture',SUPPLIER_BALANCE_PATH:'/api/v1/balance'},(async()=>{called=true;throw Error()}) as typeof fetch);assert.equal(called,false);assert.equal(h.open,false);d.close()});
test('finance capabilities never manufacture APY, borrow market or mainnet support',()=>{const v=financeCapabilities(c);assert.equal(v.mainnetEnabled,false);assert.equal(v.earn.executionEnabled,false);assert.equal(v.borrow.executionEnabled,false);assert.equal(v.onramp.executionEnabled,false);assert.equal(v.onramp.configured,false);assert(!JSON.stringify(v).includes('apyBps'))});
test('configured onramp key without verification cannot create hosted fiat session',async()=>{await assert.rejects(mintOnrampSession({...c,ONRAMP_API_KEY:'fixture'},'wallet:0x'+'1'.repeat(40),'0x'+'1'.repeat(40)),/ONRAMP_VERIFICATION_REQUIRED/)});

test('concurrent-style reservations cannot consume the same operating reserve twice',()=>{const d=openDb(':memory:');recordProcurementHealth(d,credit('15'),now);assert.equal(reserveProcurement(d,'reference_A','4000000',now),true);assert.throws(()=>reserveProcurement(d,'reference_B','4000000',now),/SERVICE_RESERVE_LIMIT/);assert.equal(reserveProcurement(d,'reference_A','4000000',now),false);assert.throws(()=>reserveProcurement(d,'reference_A','3000000',now),/IDEMPOTENCY_CONFLICT/);assert.equal((d.prepare('SELECT count(*) n FROM procurement_reservations').get() as {n:number}).n,1);d.close()});

test('an older concurrent response cannot overwrite a newer low-balance stop',()=>{const d=openDb(':memory:');recordProcurementHealth(d,credit('9'),now);recordProcurementHealth(d,{...credit('100'),observedAt:now-1000},now);assert.equal(procurementHealth(d,now).open,false);assert.equal(procurementHealth(d,now).availableUnits,'9000000');d.close()});
test('holds count against public lot availability, not just the purchase guard',()=>{const d=openDb(':memory:');recordProcurementHealth(d,credit('15'),now);reserveProcurement(d,'reference_hold','5000000',now);assert.equal(procurementHealth(d,now).availableUnits,'10000000');assert.throws(()=>reserveProcurement(d,'reference_next','1',now),/SERVICE_PURCHASES_PAUSED/);assert.equal(procurementHealth(d,now).availableUnits,'10000000');d.close()});

test('new order availability can close while read-only recovery remains configured',()=>{const node=new SupplyNode({...c,ENABLE_FULFILLMENT:'true',FULFILLMENT_CONTRACT_VERIFIED:'true',SUPPLIER_ALLOWED_ORIGIN:'https://supplier.example',SUPPLIER_API_URL:'https://supplier.example/api/v1',SUPPLIER_API_KEY:'fixture'},async()=>true,()=>false);assert.equal(node.configured,true);assert.equal(node.ready,false)});

test('SDK discovery is available without an invented configured API key, but no deposit execution',()=>{const v=financeCapabilities(c);assert.equal(v.earn.configured,true);assert.equal(v.earn.executionEnabled,false)});
