import test from 'node:test';import assert from 'node:assert/strict';import {PublicCommerceApi,type SpendCapEvidence} from '../src/services/fulfillment/public-commerce-api.js';
const sid='10f65d93-ba82-4c27-a851-6db0390544ac',item='e1dd9ec4-6ebc-46ea-aef2-2a02cdda3af3',ref='owner_micro_probe_001',now=Date.now();
const body=(data:unknown,status='SUCCESS',statusCode=0)=>({status,statusCode,traceId:'fixture-trace',data});
function setup(data:unknown={},status='SUCCESS',code=0,http=200){const calls:{url:string;init:RequestInit}[]=[];const api=new PublicCommerceApi('fixture-not-a-real-secret',(async(u,i)=>{calls.push({url:String(u),init:i!});return new Response(JSON.stringify(body(data,status,code)),{status:http,headers:{'Content-Type':'application/json'}})}) as typeof fetch);const cap:SpendCapEvidence={verified:true,currency:'USD',remainingUsd:'1',keyFingerprint:api.keyFingerprint,observedAt:now};return {api,calls,cap}}
test('documented purchase uses camelCase, correct key header and exactly one non-long voucher',async()=>{const s=setup({orderId:'fixture-order',price:0.0194});await s.api.createVoucher(ref,item,'19400',s.cap,now);assert.equal(s.calls.length,1);const r=s.calls[0];assert.equal(r.url,'https://approute.io/api/v1/orders');assert.equal(r.init.redirect,'error');assert.equal((r.init.headers as Record<string,string>)['X-API-Key'],'fixture-not-a-real-secret');assert.equal((r.init.headers as Record<string,string>)['Content-Type'],'application/json');assert.deepEqual(JSON.parse(String(r.init.body)),{ordersType:'shop',referenceId:ref,orders:[{denominationId:item,quantity:1,isLongOrder:false,fields:[]}]});assert.equal('Authorization' in r.init.headers!,false)});
for(const [label,change]of Object.entries({unverified:{verified:false},overOne:{remainingUsd:'1.000001'},exhausted:{remainingUsd:'0'},tooSmall:{remainingUsd:'0.01'},wrongKey:{keyFingerprint:'other-key'},stale:{observedAt:now-15001},future:{observedAt:now+1},float:{remainingUsd:1},nonUsd:{currency:'EUR'}}))test('server cap '+label+' blocks before POST',async()=>{const s=setup();await assert.rejects(()=>s.api.createVoucher(ref,item,'19400',{...s.cap,...change} as SpendCapEvidence,now),/ONE_DOLLAR_CAP_REQUIRED/);assert.equal(s.calls.length,0)});
test('price over owner budget blocks even with verified server cap',async()=>{const s=setup();await assert.rejects(()=>s.api.createVoucher(ref,item,'1000001',s.cap,now),/OWNER_ONE_DOLLAR_LIMIT/);assert.equal(s.calls.length,0)});
test('accepted HTTP 202 is in-progress, not delivery',async()=>{const s=setup({orderId:'fixture-order'},'IN_PROGRESS',1,202);const r=await s.api.createVoucher(ref,item,'19400',s.cap,now);assert.equal(r.status,'IN_PROGRESS');assert.equal(r.statusCode,1)});
test('HTTP 409 spend cap is not retried',async()=>{const s=setup(null,'CANCELLED',13,409);await assert.rejects(()=>s.api.createVoucher(ref,item,'19400',s.cap,now),/HTTP_409/);assert.equal(s.calls.length,1)});
test('HTTP 502 uncertain result is not retried',async()=>{const s=setup(null,'CANCELLED',11,502);await assert.rejects(()=>s.api.createVoucher(ref,item,'19400',s.cap,now),/HTTP_502/);assert.equal(s.calls.length,1)});
test('HTTP 200 does not override application insufficient-funds code',async()=>{const s=setup(null,'CANCELLED',10);await assert.rejects(()=>s.api.createVoucher(ref,item,'19400',s.cap,now),/APPLICATION_10/);assert.equal(s.calls.length,1)});
test('masked status lookup cannot acknowledge codes; explicit receipt binds both original filters',async()=>{const s=setup({page:{items:[]}});await s.api.orderStatus(ref,'fixture-order');let u=new URL(s.calls[0].url);assert.equal(u.searchParams.get('unhide'),'false');assert.equal(s.calls[0].init.method,'GET');await s.api.receiveVouchers(ref,'fixture-order');u=new URL(s.calls[1].url);assert.equal(u.searchParams.get('unhide'),'true');assert.equal(u.searchParams.get('referenceId'),ref);assert.equal(u.searchParams.get('orderId'),'fixture-order');await assert.rejects(()=>s.api.receiveVouchers(ref,''));assert.equal(s.calls.length,2)});
test('procurement USD uses lower of cash and available, never overdraft or other currency',async()=>{const s=setup({items:[{currency:'USD',balance:12,available:112,overdraftLimit:100},{currency:'EUR',balance:999,available:999}]});assert.equal((await s.api.procurementCashUsd()).availableUnits,'12000000');assert.equal(s.calls[0].init.method,'GET')});
test('missing USD account is not converted or invented',async()=>{const s=setup({items:[{currency:'USDT',balance:12,available:12}]});await assert.rejects(()=>s.api.procurementCashUsd(),/USD_BALANCE_UNVERIFIED/)});
test('item refresh is separate from purchase and never presented as fixed final quote',async()=>{const s=setup({id:item,price:0.0194,currency:'USD',inStock:500,isLongOrder:false});const r=await s.api.item(sid,item);assert.equal(r.priceUsdUnits,'19400');assert.equal(r.fixedFinalQuote,false);assert.equal(s.calls[0].init.method,'GET')});
test('body size limit rejects excessive response without retries',async()=>{let n=0;const api=new PublicCommerceApi('fixture',(async()=>{n++;return new Response('x'.repeat(262145),{status:200})}) as typeof fetch);await assert.rejects(()=>api.procurementCashUsd(),/RESPONSE_TOO_LARGE/);assert.equal(n,1)});
