import test from 'node:test';import assert from 'node:assert/strict';import Database from 'better-sqlite3';import {loadConfig} from '../src/config.js';import {SupplyMonitor,createSupplyMonitorServer,supplyMonitorEntrypoint} from '../src/supply-monitor-server.js';
const config=loadConfig({NODE_ENV:'test',SUPPLIER_API_KEY:'fixture',SUPPLIER_API_URL:'https://supply.example/api/v1',SUPPLIER_ALLOWED_ORIGIN:'https://supply.example'});
function fixture(){let cash='11',stock=1,fail=false,calls=0;const db=new Database(':memory:');const m=new SupplyMonitor(db,config,(async(url,opt)=>{calls++;assert.notEqual(opt?.method,'POST');if(fail)throw Error();if(String(url).endsWith('/accounts'))return Response.json({status:'SUCCESS',statusCode:0,data:{items:[{currency:'USD',balance:cash,available:cash}]}});return Response.json({data:{items:[{id:'product',name:'Steam Wallet',countryCode:'US',items:[{id:'item',price:10,currency:'USD',inStock:stock}]}]}})}) as typeof fetch);return {db,m,setCash:(v:string)=>cash=v,setStock:(v:number)=>stock=v,fail:()=>fail=true,calls:()=>calls};}
test('ten pauses and above ten automatically resumes without public balance disclosure',async()=>{const f=fixture();f.setCash('10');await f.m.refreshBalance();assert.equal(f.m.availability().supplyReady,false);f.setCash('10.000001');await f.m.refreshBalance();assert.equal(f.m.availability().supplyReady,true);assert(!JSON.stringify(f.m.availability()).includes('10000001'));assert.equal(f.m.availability().realPurchasesEnabled,false);f.db.close()});
test('stock disappearance and recovery hide and restore exact denomination, with 9 percent once',async()=>{const f=fixture();await f.m.refreshStock();assert.equal(f.m.catalog().products[0]!.items[0]!.price,10.9);f.setStock(0);await f.m.refreshStock();assert.equal(f.m.catalog().products.length,0);f.setStock(4);await f.m.refreshStock();assert.equal(f.m.catalog().products[0]!.items[0]!.price,10.9);f.db.close()});
test('failures and stale observations do not keep old availability green',async()=>{const f=fixture();await f.m.refreshBalance();await f.m.refreshStock();assert.equal(f.m.availability().supplyReady,true);f.fail();await f.m.refreshBalance();await f.m.refreshStock();assert.equal(f.m.availability().maintenance,true);assert.equal(f.m.catalog().products.length,0);f.db.close()});
test('poll bursts coalesce and read-only HTTP never forwards a purchase',async()=>{const f=fixture();await Promise.all(Array.from({length:25},()=>f.m.refreshBalance()));assert.equal(f.calls(),1);const app=createSupplyMonitorServer(f.m);assert.equal((await app.inject({method:'POST',url:'/catalog',payload:{}})).statusCode,405);assert.equal((await app.inject({url:'/orders'})).statusCode,404);assert.equal((await app.inject({url:'/health'})).json().signingEnabled,false);await app.close();f.db.close()});

import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
test('runtime entrypoint uses canonical paths, not a symlink spelling comparison',()=>{const root=mkdtempSync(join(tmpdir(),'mercenta-entry-'));try{const file=join(root,'entry.js');writeFileSync(file,'');assert.equal(supplyMonitorEntrypoint(file,pathToFileURL(file).href),true);assert.equal(supplyMonitorEntrypoint(join(root,'missing'),pathToFileURL(file).href),false);assert.equal(supplyMonitorEntrypoint(undefined),false)}finally{rmSync(root,{recursive:true,force:true})}});
