import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import Database from 'better-sqlite3';
import {SupportRefunds} from '../src/services/support-refunds.js';import {refundInput} from '../src/services/refund-input.js';
const input=()=>({requestId:randomUUID(),email:'owner@example.invalid',orderReference:'TEST-ORDER-001',network:'testnet',reason:'NOT_DELIVERED',details:'Technical engineering test; no customer payment.',transactionHash:'',manualReviewAcknowledged:true,website:''});
function setup(){const db=new Database(':memory:');return {db,q:new SupportRefunds(db,'a'.repeat(64))};}
test('durable encrypted ticket; no refund or ownership claim',()=>{const {db,q}=setup();try{const b=input(),r=q.submit(b,'b'.repeat(64));assert.equal(r.refundExecuted,false);assert.equal(r.ownershipVerified,false);const raw=JSON.stringify(db.prepare('SELECT * FROM support_refunds').get());assert.ok(!raw.includes(b.email));assert.ok(!raw.includes(b.details));assert.equal(q.read(r.ticketId).request.email,b.email);assert.deepEqual(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE '%ledger%'").all(),[]);}finally{db.close();}});
test('retry returns original; changed body conflicts',()=>{const {db,q}=setup();try{const b=input(),r=q.submit(b,'b'.repeat(64));assert.deepEqual(q.submit(b,'c'.repeat(64)),r);assert.throws(()=>q.submit({...b,details:'Changed submitted request details'},'b'.repeat(64)),/IDEMPOTENCY_CONFLICT/);assert.equal(q.list().length,1);}finally{db.close();}});
test('contact throttling persisted',()=>{const {db,q}=setup();try{for(let i=0;i<5;i++)q.submit(input(),'b'.repeat(64),10000);assert.throws(()=>q.submit(input(),'b'.repeat(64),10001),/SUPPORT_RATE_LIMIT/);}finally{db.close();}});
test('source throttling ignores client contact rotation',()=>{const {db,q}=setup();try{for(let i=0;i<6;i++)q.submit({...input(),email:`owner${i}@example.invalid`},'b'.repeat(64),10000);assert.throws(()=>q.submit({...input(),email:'next@example.invalid'},'b'.repeat(64),10001),/SUPPORT_RATE_LIMIT/);}finally{db.close();}});
test('review changes do not move funds; encrypted payload retained',()=>{const {db,q}=setup();try{const r=q.submit(input(),'b'.repeat(64));assert.equal(q.review(r.ticketId,'IN_REVIEW').refundExecuted,false);assert.equal(q.review(r.ticketId,'CLOSED').refundExecuted,false);assert.equal(q.read(r.ticketId).status,'CLOSED');assert.equal((db.prepare('SELECT count(*) n FROM support_refund_reviews').get() as {n:number}).n,2);}finally{db.close();}});
test('strict consent, honeypot, secret and source rejection',()=>{const {db,q}=setup();try{assert.equal(refundInput.safeParse({...input(),manualReviewAcknowledged:false}).success,false);assert.equal(refundInput.safeParse({...input(),website:'bot'}).success,false);assert.throws(()=>q.submit({...input(),details:'private key: definitely-not-a-real-secret'},'b'.repeat(64)),/DO_NOT_SHARE_SECRETS/);assert.throws(()=>q.submit(input(),'client-ip'),/UNAUTHORIZED/);}finally{db.close();}});
