import test from 'node:test';import assert from 'node:assert/strict';import {supplierPreview} from '../src/services/supplier-preview.js';import {loadConfig} from '../src/config.js';
const c={...loadConfig(),SUPPLIER_ALLOWED_ORIGIN:'https://supplier.example',SUPPLIER_API_URL:'https://supplier.example/api/v1',SUPPLIER_API_KEY:'synthetic-supplier-key'};
test('supplier rejection has no invented products, credential or availability',async()=>{const r=await supplierPreview(c,(async()=>new Response('',{status:403})) as typeof fetch);assert.equal(r.status,'access-denied');assert.equal(r.products.length,0);assert.equal(r.purchasingEnabled,false);assert(!JSON.stringify(r).includes(c.SUPPLIER_API_KEY))});
test('supplier credentials cannot be redirected to legacy or arbitrary hosts',async()=>{let n=0;const f=(async()=>{n++;return Response.json({})}) as typeof fetch;assert.equal((await supplierPreview({...c,SUPPLIER_API_URL:'https://ikhdev.example/api/v1'},f)).status,'invalid-config');assert.equal(n,0)});
test('supplier feed whitelists public fields and does not claim completeness',async()=>{const r=await supplierPreview(c,(async(u,o)=>{assert.equal(u,'https://supplier.example/api/v1/services');assert.equal(o?.redirect,'error');return Response.json({data:{items:[{id:'a',name:'Product',supplierSecret:'private',imageUrl:'https://cdn.example.com/a.webp',items:[{id:'d',price:2,currency:'USD',inStock:3}]}]}})}) as typeof fetch);assert.equal(r.status,'ready');assert.equal(r.products.length,1);assert.equal(r.coverage,'unverified');assert(!JSON.stringify(r).includes('supplierSecret'))});
test('malformed and oversized supplier responses fail closed',async()=>{assert.equal((await supplierPreview(c,(async()=>Response.json({data:{items:[{id:'a',name:'Bad',items:[{id:'d',price:-2,currency:'USD'}]}]}})) as typeof fetch)).status,'invalid-response');assert.equal((await supplierPreview(c,(async()=>new Response('bad',{headers:{'Content-Length':'5000000'}})) as typeof fetch)).status,'invalid-response')});

test('authorized catalogue accepts nullable subcategory and retains services without options',async()=>{const r=await supplierPreview(c,(async()=>Response.json({data:{items:[{id:'a',name:'Gift card',subcategoryName:null,items:[{id:'d',price:4.3095,currency:'USD',inStock:159}]},{id:'b',name:'No options yet',subcategoryName:null,items:[]}]}})) as typeof fetch);assert.equal(r.status,'ready');assert.equal(r.products.length,2);assert.equal(r.products[0]?.subcategoryName,undefined);assert.equal(r.products[0]?.items[0]?.price,4.3095);assert.equal(r.purchasingEnabled,false)});
test('supplier images cannot target private 172 addresses',async()=>{const r=await supplierPreview(c,(async()=>Response.json({data:{items:[{id:'a',name:'Product',imageUrl:'https://172.20.0.1/a',items:[]}]}})) as typeof fetch);assert.equal(r.products[0]?.imageUrl,undefined)});

test('public source metadata uses the merchant brand only',async()=>{const r=await supplierPreview(c,(async()=>Response.json({data:{items:[]}})) as typeof fetch);assert.equal(r.supplier,'Mercenta catalogue');assert.equal(r.purchasingEnabled,false)});
