import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHmac} from 'node:crypto';
import {openDb} from '../src/db.js';import {initAccount,createDeposit,creditDeposit,placeTestOrder,funds} from '../src/services/account.js';
import {profile,saveProfile,saveBudget,getBudget,budgetUsage,checkBudget,addNote,journal} from '../src/services/workspace.js';
import {loadConfig} from '../src/config.js';import {buildServer} from '../src/server.js';import {financialCoach} from '../src/services/financial-coach.js';
const a='wallet:0x'+'1'.repeat(40),other='wallet:0x'+'2'.repeat(40),receiver='0x'+'3'.repeat(40),key='a'.repeat(64);
const plan=(over={})=>({requestId:randomUUID(),expectedRevision:0,monthly:'10',perOrder:'2',daily:'3',spendBps:7000,reserveBps:2000,profitBps:1000,taxBps:0,...over});
function fixture(){const db=openDb(':memory:');initAccount(db);return db}
function seed(db:ReturnType<typeof fixture>){const d=createDeposit(db,a,randomUUID(),receiver,'20');creditDeposit(db,a,d.id,{amount:20000000n,confirmations:2n,blockHash:'0xblock',txHash:'0x'+'a'.repeat(64),blockTime:d.created_at})}
test('workspace profile is wallet scoped and reviewed steps never assert financial execution',()=>{const db=fixture();saveProfile(db,a,{language:'ru',role:'reseller',reviewed:['shop','shop'],dismissed:true});assert.deepEqual(profile(db,a).reviewed,['shop']);assert.equal(profile(db,other).dismissed,false);assert.throws(()=>profile(db,'session:guest'));assert.throws(()=>saveProfile(db,a,{language:'en',role:'buyer',reviewed:['invented'],dismissed:false}));db.close()});
test('budget rejects invalid allocations, zero caps, oversized caps and floats in percentages',()=>{const db=fixture();for(const p of [plan({spendBps:6999}),plan({daily:'8'}),plan({perOrder:'4'}),plan({daily:'0'}),plan({spendBps:7000.1})])assert.throws(()=>saveBudget(db,a,p));assert.equal(getBudget(db,a),null);db.close()});
test('budget save is idempotent and optimistic revision prevents lost update',()=>{const db=fixture(),p=plan(),v=saveBudget(db,a,p);assert.deepEqual(saveBudget(db,a,p),v);assert.throws(()=>saveBudget(db,a,{...p,monthly:'12'}),/CONFLICT/);assert.throws(()=>saveBudget(db,a,plan()),/REVISION_CONFLICT/);assert.equal(getBudget(db,other),null);saveBudget(db,a,plan({expectedRevision:1,monthly:'12'}));assert.equal(getBudget(db,a)?.revision,2);db.close()});
test('per-order and daily budgets fail before debit; replay does not charge or recheck a completed order',()=>{const db=fixture();seed(db);saveBudget(db,a,plan());const id=randomUUID(),order=placeTestOrder(db,a,id,'test-creator',1,'');assert.equal(order.amount_units,'1532000');assert.throws(()=>placeTestOrder(db,a,randomUUID(),'test-creator',1,''),/BUDGET_DAILY_LIMIT/);assert.throws(()=>checkBudget(db,a,2000001n),/BUDGET_PER_ORDER_LIMIT/);saveBudget(db,a,plan({expectedRevision:1,perOrder:'0.1',daily:'0.2'}));assert.equal(placeTestOrder(db,a,id,'test-creator',1,'').id,order.id);assert.equal(funds(db,a).availableUnits,'18468000');db.close()});
test('monthly spend cap uses integer micros and only current actor/month',()=>{const db=fixture();saveBudget(db,a,plan({monthly:'4',daily:'2',perOrder:'2'}));const now=Date.UTC(2026,9,15,12);db.prepare("INSERT INTO account_orders VALUES(?,?,?,?,?,?,?,?,?,?,'SIMULATED_FULFILLED',?,?,?)").run(randomUUID(),a,randomUUID(),'fp','test','test','GLOBAL','Shop',1,'1500000','Portal','',now-86400000);assert.throws(()=>checkBudget(db,a,1400000n,now),/BUDGET_MONTHLY_LIMIT/);assert.equal(budgetUsage(db,other).monthSpentUnits,'0');db.close()});
test('bundle transaction rollback removes all debits when later line exceeds daily budget',()=>{const db=fixture();seed(db);saveBudget(db,a,plan());assert.throws(()=>db.transaction(()=>{placeTestOrder(db,a,randomUUID(),'test-creator',1,'');placeTestOrder(db,a,randomUUID(),'test-creator',1,'')})(),/BUDGET_DAILY_LIMIT/);assert.equal(funds(db,a).availableUnits,'20000000');assert.equal(budgetUsage(db,a).monthSpentUnits,'0');db.close()});
const note=(over={})=>({requestId:randomUUID(),kind:'expense',amount:'1.000001',date:new Date().toISOString().slice(0,10),category:'digital-goods',title:'Private observation',note:'Private text never sent to the coach',...over});
test('journal is encrypted, idempotent, actor isolated and never changes the ledger',()=>{const db=fixture();const b=note(),r=addNote(db,a,b,key);assert.equal(addNote(db,a,b,key).id,r.id);assert.throws(()=>addNote(db,a,{...b,note:'changed'},key),/CONFLICT/);const stored=db.prepare('SELECT encrypted_text FROM finance_notes').get() as {encrypted_text:string};assert.ok(!stored.encrypted_text.includes(b.note));assert.equal(journal(db,other,key).total,0);assert.equal(journal(db,a,key).declaredExpenseUnits,'1000001');assert.equal(funds(db,a).availableUnits,'0');assert.equal((db.prepare('SELECT count(*) n FROM ledger_entries').get() as {n:number}).n,0);db.close()});
test('journal rejects impossible/future dates, secrets and inconsistent note amount',()=>{const db=fixture();for(const b of [note({date:'2026-02-30'}),note({date:'2999-01-01'}),note({note:'0x'+'a'.repeat(64)}),note({kind:'note',amount:'1'}),note({amount:'0'})])assert.throws(()=>addNote(db,a,b,key));db.close()});
test('coach falls back honestly without configured model and has no execution authority',async()=>{const r=await financialCoach(loadConfig({NODE_ENV:'test'}),{language:'ru',question:'Как вести бюджет?',declaredIncomeUnits:'0',declaredExpenseUnits:'1',usage:{monthSpentUnits:'0',remainingUnits:null},budget:null});assert.equal(r.mode,'rules-fallback');assert.equal(r.authority,'READ_ONLY_NO_TOOLS');assert.ok(r.answer.includes('недоступна'))});
test('HTTP profile/journal/budget require wallet HMAC; coach requires explicit aggregate-sharing consent',async()=>{const c=loadConfig({NODE_ENV:'test',DATABASE_PATH:':memory:'}),app=await buildServer(c);const headers=(url:string,body?:object)=>{const ts=Date.now().toString(),method=body?'POST':'GET';return {'x-mercenta-actor':a,'x-mercenta-timestamp':ts,'x-mercenta-signature':createHmac('sha256',c.BACKEND_PROXY_SECRET).update(`${ts}\n${method}\n${url}\n${a}\n${body?JSON.stringify(body):''}`).digest('hex')}};
 for(const url of ['/api/account/workspace','/api/account/journal'])assert.equal((await app.inject({url})).statusCode,401);
 const body={question:'Explain budgets',language:'en',shareAggregates:false},url='/api/account/journal/coach';assert.equal((await app.inject({method:'POST',url,headers:headers(url,body),payload:body})).statusCode,400);
 const ready=await app.inject({url:'/api/launch-readiness'});assert.equal(ready.json().mainnetEnabled,false);assert.ok(ready.json().gates.every((x:{status:string})=>x.status==='blocked'));
 const good=await app.inject({url:'/api/account/workspace',headers:headers('/api/account/workspace')});assert.equal(good.statusCode,200);assert.equal(good.json().budget,null);await app.close();});
test('public preview contains only simulated catalog fields and no account data',async()=>{const app=await buildServer(loadConfig({NODE_ENV:'test',DATABASE_PATH:':memory:'}));const r=await app.inject({url:'/api/account/catalog-preview'});assert.equal(r.statusCode,200);assert.equal(r.json().liveProcurement,false);assert.equal(r.json().products.length,5);assert.ok(r.json().products.every((p:{id:string})=>p.id.startsWith('test-')));assert.equal(r.json().wallet,undefined);await app.close()});
test('model coach receives numeric aggregates, not wallet identity or note text; output stays read-only',async()=>{const previous=globalThis.fetch;let sent='';globalThis.fetch=(async(_url:unknown,opts:RequestInit)=>{sent=String(opts.body);return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({answer:'Educational budget guidance.',suggestions:['Keep a reserve.']})}}]}),{status:200})}) as typeof fetch;try{const c=loadConfig({NODE_ENV:'test',LLM_API_URL:'https://model.example.test/v1/chat/completions',LLM_API_KEY:'dummy-test-credential-not-live',LLM_MODEL:'test-model'});const r=await financialCoach(c,{language:'en',question:'Explain the reserve',declaredIncomeUnits:'100',declaredExpenseUnits:'20',usage:{monthSpentUnits:'30',remainingUnits:'70'},budget:{monthly:'1',spendBps:7000,perOrder:'0.1',daily:'0.2'}});assert.equal(r.mode,'model-educational');assert.equal(r.authority,'READ_ONLY_NO_TOOLS');assert.ok(sent.includes('DECLARED ONLY'));assert.ok(!sent.includes('wallet:'));assert.ok(!sent.includes('Private observation'));assert.ok(!sent.includes('encrypted_text'));}finally{globalThis.fetch=previous}});
