export const HELP_TOPICS = [
 {id:'region',group:'catalogue',en:'Which region should I choose?',ru:'Какой регион выбрать?',answer:'Choose the region where you will redeem the product, not simply where you are browsing. One product card groups supported regions. Check the platform account and activation rules before choosing a denomination.',answerRu:'Выберите регион активации товара, а не просто своё местоположение. Одна карточка объединяет доступные регионы. Проверьте регион аккаунта платформы и правила активации до выбора номинала.'},
 {id:'stock',group:'catalogue',en:'Does a product card guarantee stock?',ru:'Карточка гарантирует наличие?',answer:'No. Saved catalogue data and artwork are not stock promises. Available options can change; price and stock must be checked again before an order. If the service cannot verify availability, do not treat an old listing as a payable quote.',answerRu:'Нет. Сохранённые данные каталога и изображение не гарантируют наличие. Доступность и цена проверяются перед заказом. Если сервис не может подтвердить наличие, старая карточка не становится котировкой для оплаты.'},
 {id:'wallet',group:'account',en:'Do I need a wallet to explore?',ru:'Нужен ли кошелёк для просмотра?',answer:'No. Browse products and prepare a task without signing in. Verified wallet sign-in is required to read private account data or run account tools. Never share a seed phrase or private key with Mercenta Support.',answerRu:'Нет. Можно просматривать товары и готовить задачу без входа. Для личных данных и инструментов счёта нужен подтверждённый вход кошельком. Никогда не передавайте seed-фразу или приватный ключ поддержке.'},
 {id:'balance',group:'account',en:'Why are wallet and account balances different?',ru:'Почему баланс кошелька и счёта отличается?',answer:'Your wallet and Mercenta prepaid account are separate. A connected wallet does not automatically fund the account. Testnet deposits require a deposit intent, a transfer and verified transaction processing. Testnet deposits are not withdrawable in this MVP; use test assets only.',answerRu:'Кошелёк и предоплаченный счёт Mercenta — разные балансы. Подключение кошелька не пополняет счёт. Для тестового пополнения нужны заявка, перевод и проверка транзакции. Тестовые депозиты в этом MVP не выводятся; используйте только тестовые активы.'},
 {id:'permission',group:'agent',en:'Can the agent spend without my approval?',ru:'Может ли агент тратить без разрешения?',answer:'A draft is not authorization. Start with “Review the plan first”. Delegation is a separate, explicit permission for one bounded Testnet order, with a spend cap, quantity, region, remaining-balance rule and expiry. Saved budget limits also apply.',answerRu:'Черновик — не разрешение. Начните с режима «Сначала проверить план». Делегирование — отдельное явное разрешение на один тестовый заказ с лимитом, количеством, регионом, минимальным остатком и сроком действия. Лимиты сохранённого бюджета тоже действуют.'},
 {id:'quote',group:'agent',en:'Is the displayed catalogue price my payment total?',ru:'Цена в каталоге — это итог оплаты?',answer:'No. Catalogue prices in USD are indicative, not USDC payment quotes. Review the exact quote for your environment, product, region and quantity. A proposal or planning result is not evidence that a payment settled.',answerRu:'Нет. Цена каталога в USD — ориентир, а не котировка оплаты в USDC. Проверьте точный расчёт для своей среды, товара, региона и количества. Предложение или план не доказывает, что платёж выполнен.'},
 {id:'networks',group:'safety',en:'What is available on Testnet and Mainnet?',ru:'Что доступно в Testnet и Mainnet?',answer:'Testnet offers a rehearsal with test USDC and non-redeemable delivery. Mainnet is pre-launch: real payments, deposits and financial actions are closed. Balances do not carry between environments. Do not send real funds to the Testnet flow.',answerRu:'Testnet — репетиция с test USDC и неактивируемой выдачей. Mainnet готовится к запуску: реальные платежи, депозиты и финансовые операции закрыты. Балансы между средами не переносятся. Не отправляйте реальные средства в тестовый сценарий.'},
 {id:'outage',group:'safety',en:'What if a request times out?',ru:'Что делать при таймауте?',answer:'A timeout alone does not prove an order failed. Check saved purchases and task activity before starting another purchase. If the result is uncertain, send the order reference and optional transaction hash to support. Never repeat a payment just to make a spinner disappear.',answerRu:'Таймаут сам по себе не означает, что заказ не выполнен. Перед новой покупкой проверьте историю заказов и ход задачи. Если результат неизвестен, передайте поддержке номер заказа и хеш транзакции при наличии. Не повторяйте платёж ради исчезновения индикатора загрузки.'},
 {id:'refund',group:'support',en:'How do refunds work?',ru:'Как оформить возврат?',answer:'Submit a refund-review request to Mercenta Support. The owner reviews eligibility and issues approved refunds manually. A submitted request is not an approved refund and does not move funds. Testnet delivery does not create a right to a real-money payout.',answerRu:'Отправьте заявку на проверку возврата в поддержку Mercenta. Владелец проверяет основания и выполняет одобренные возвраты вручную. Заявка не означает одобрение и не перемещает средства. Тестовая выдача не даёт права на выплату реальных денег.'},
 {id:'secrets',group:'support',en:'What should I include in a support request?',ru:'Что указать в обращении?',answer:'Include your Mercenta order reference, environment, a short description and a transaction hash if relevant. Never send passwords, seed phrases, private keys, purchased codes or access tokens. Only use the official contact details on this page.',answerRu:'Укажите номер заказа Mercenta, среду, краткое описание и хеш транзакции, если он относится к проблеме. Не отправляйте пароли, seed-фразы, приватные ключи, купленные коды или access token. Используйте официальные контакты на этой странице.'},
] as const;
export type HelpGroup='all'|typeof HELP_TOPICS[number]['group'];
export function searchHelp(query:string,group:HelpGroup){const q=query.trim().toLocaleLowerCase();return HELP_TOPICS.filter(t=>(group==='all'||t.group===group)&&[t.en,t.ru,t.answer,t.answerRu].some(s=>s.toLocaleLowerCase().includes(q)));}
