"use client";
import Link from 'next/link';
import {useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Search,X,ShoppingBag,Bot,SlidersHorizontal,ShieldCheck,Globe2,ReceiptText,ChevronDown,LifeBuoy,Compass,LockKeyhole,Mail} from 'lucide-react';
import BrandMark from '@/components/landing/BrandMark';
import {OfficialContacts} from '@/components/OfficialContacts';
import {useSurfaceMotion} from '@/lib/surface-motion';
import {searchHelp,type HelpGroup} from './guide-content';
import './guide-hub.css';
const GROUPS=[['all','All topics','Все темы'],['catalogue','Catalogue','Каталог'],['account','Account','Счёт'],['agent','Agent','Агент'],['safety','Safety','Безопасность'],['support','Support','Поддержка']] as const;
const PATHS=[{id:'catalogue',Icon:ShoppingBag,en:'Choose it yourself.',ru:'Выберите сами.',text:'Find a platform, select the redemption region and compare options.',textRu:'Найдите платформу, выберите регион активации и сравните номиналы.',href:'/catalog',cta:'Explore the catalogue',ctaRu:'Открыть каталог'},
 {id:'agent',Icon:Bot,en:'Give the search to your agent.',ru:'Поручите поиск агенту.',text:'Describe your goal, set a cap and review the plan before authorizing anything.',textRu:'Опишите цель, задайте лимит и проверьте план до разрешения на покупку.',href:'https://testnet.mercenta.xyz/app?section=agent-chat',cta:'Prepare a Testnet task',ctaRu:'Подготовить тестовую задачу'},
 {id:'budget',Icon:SlidersHorizontal,en:'Start with a spending plan.',ru:'Начните с бюджета.',text:'Set monthly, daily and per-order limits. Saving a plan does not move funds.',textRu:'Задайте месячный, дневной лимит и предел заказа. Сохранение плана не переводит средства.',href:'https://testnet.mercenta.xyz/app?section=budget',cta:'Open Testnet budget',ctaRu:'Открыть тестовый бюджет'}];
export function GuideHub({page}:{page:'start'|'support'}){
 const [ru,setRu]=useState(false),[query,setQuery]=useState(''),[group,setGroup]=useState<HelpGroup>('all');
 const root=useRef<HTMLDivElement>(null),search=useRef<HTMLInputElement>(null);useSurfaceMotion(root,page);
 const t=(en:string,rus:string)=>ru?rus:en,rows=searchHelp(query,group);
 return <div ref={root} className="gh" lang={ru?'ru':'en'}><a className="gh-skip" href="#guide-content">{t('Skip to content','Перейти к содержимому')}</a>
 <header className="gh-header gh-wrap"><Link href="/" className="gh-brand" aria-label={t('Mercenta home','Главная Mercenta')}><BrandMark/>mercenta.</Link><nav aria-label={t('Guide navigation','Навигация по справке')}><Link href={page==='start'?'/support':'/start'}>{page==='start'?t('Help centre','Помощь'):t('Getting started','С чего начать')}</Link><Link href="/catalog">{t('Catalogue','Каталог')} <ArrowUpRight size={14}/></Link></nav></header>
 <main id="guide-content" className="gh-wrap"><div className="gh-topline"><span className="gh-overline">MERCENTA / {page==='start'?'A CLEAR START':'HELP CENTRE'}</span><div className="gh-language" role="group" aria-label={t('Language','Язык')}><button type="button" aria-pressed={!ru} onClick={()=>setRu(false)}>EN</button><button type="button" aria-pressed={ru} onClick={()=>setRu(true)}>RU</button></div></div>
 <section className="gh-hero"><div><h1>{page==='start'?<>{t('Your next step.','Ваш следующий шаг.')}<br/><em>{t('Made clear.','Без лишних вопросов.')}</em></>:<>{t('A little clarity.','Немного ясности.')}<br/><em>{t('A lot less guesswork.','Гораздо меньше догадок.')}</em></>}</h1><p>{page==='start'?t('A product, an agent or a budget. Start where it makes sense for you—without handing over control.','Товар, агент или бюджет. Начните с нужного вам сценария — не теряя контроль.'):t('Straight answers about regions, accounts and your agent. If an order needs attention, Mercenta Support reviews it manually.','Понятные ответы о регионах, счёте и агенте. Если возникла проблема с заказом, поддержка Mercenta проверит её вручную.')}</p></div><aside className="gh-boundary"><ShieldCheck size={24}/><strong>{t('Two environments. Clear boundaries.','Две среды. Понятные границы.')}</strong><p>{t('Testnet uses test assets and non-redeemable delivery. Mainnet payments are closed. Exploring never authorizes spending.','В Testnet — тестовые активы и неактивируемая выдача. Оплата Mainnet закрыта. Просмотр не разрешает тратить деньги.')}</p></aside></section>
 {page==='start'?<>
 <section className="gh-paths" aria-label={t('Choose your starting point','Выберите, с чего начать')}>{PATHS.map((p,i)=><article key={p.id}><div className="gh-card-top"><p.Icon size={25} strokeWidth={1.5}/><span>0{i+1}</span></div><h2>{t(p.en,p.ru)}</h2><p>{t(p.text,p.textRu)}</p><a href={p.href}>{t(p.cta,p.ctaRu)} <ArrowRight size={17}/></a></article>)}</section>
 <section className="gh-section"><div className="gh-section-heading"><span className="gh-overline">{t('BEFORE YOU RUN','ДО ЗАПУСКА')}</span><h2>{t('Three checks. No surprises.','Три проверки. Без сюрпризов.')}</h2></div><ol className="gh-checklist">{[[Globe2,t('The right region','Подходящий регион'),t('Match the redemption rules and your platform account. “Any” is a search setting, not a promise of worldwide activation.','Сверьте правила активации и регион аккаунта. «Любой» — настройка поиска, а не гарантия активации по всему миру.')],[ReceiptText,t('The exact quote','Точная котировка'),t('Catalogue USD prices are indicative. A fresh payment quote belongs to one product, region, quantity and environment.','Цены каталога в USD ориентировочные. Свежая котировка относится к конкретному товару, региону, количеству и среде.')],[LockKeyhole,t('Your permission','Ваше разрешение'),t('A draft and a saved budget do not authorize a purchase. Begin with review-first mode; delegation is a separate bounded permission.','Черновик и сохранённый бюджет не разрешают покупку. Начните с проверки плана; делегирование требует отдельного разрешения с лимитами.')]].map(([Icon,title,text],i)=>{const I=Icon as typeof Globe2;return <li key={i}><I size={22}/><div><h3>{String(title)}</h3><p>{String(text)}</p></div></li>})}</ol></section>
 <section className="gh-next"><Compass size={27}/><div><h2>{t('No wallet needed for the first step.','Для первого шага кошелёк не нужен.')}</h2><p>{t('Explore first. Sign in when you want to read your account or run a task.','Сначала изучите возможности. Войдите, когда понадобятся данные счёта или запуск задачи.')}</p></div><Link href="/support">{t('Read the essentials','Узнать главное')} <ArrowRight size={17}/></Link></section>
 </>:<>
 <section className="gh-help" aria-labelledby="help-topics"><h2 id="help-topics" className="gh-sr">{t('Help topics','Темы справки')}</h2><label className="gh-search"><Search size={20} aria-hidden="true"/><input ref={search} value={query} maxLength={200} onChange={e=>setQuery(e.target.value)} placeholder={t('Search: regions, wallet, refunds…','Поиск: регионы, кошелёк, возврат…')} aria-label={t('Search help','Поиск по справке')}/>{query&&<button type="button" aria-label={t('Clear search','Очистить поиск')} onClick={()=>{setQuery('');search.current?.focus()}}><X size={17}/></button>}</label>
 <div className="gh-filters" role="group" aria-label={t('Filter help topics','Фильтр тем')}>{GROUPS.map(([id,en,rus])=><button type="button" key={id} aria-pressed={group===id} onClick={()=>setGroup(id)}>{t(en,rus)}</button>)}</div>
 <p className="gh-result-count" role="status" aria-live="polite">{t('Answers found: ','Найдено ответов: ')}{rows.length}</p><div className="gh-answers">{rows.length?rows.map(item=><details key={item.id}><summary>{t(item.en,item.ru)}<ChevronDown size={19} aria-hidden="true"/></summary><p>{t(item.answer,item.answerRu)}</p>{item.id==='refund'&&<Link href="/refund">{t('Request a manual refund review','Заявка на ручную проверку возврата')} <ArrowRight size={16}/></Link>}</details>):<div className="gh-empty"><Search size={28}/><h3>{t('Let’s try a different question.','Попробуем другой вопрос.')}</h3><p>{t('Try “region”, “wallet” or “refund”, or clear the filters.','Попробуйте «регион», «кошелёк» или «возврат» либо сбросьте фильтры.')}</p><button type="button" onClick={()=>{setQuery('');setGroup('all');search.current?.focus()}}>{t('Reset search and filters','Сбросить поиск и фильтры')}</button></div>}</div></section>
 <section className="gh-next"><LifeBuoy size={28}/><div><h2>{t('An order needs a closer look?','Нужно разобраться с заказом?')}</h2><p>{t('Send the order reference, environment and a short description. No passwords, private keys or purchased codes. Refunds are reviewed and issued manually.','Укажите номер заказа, среду и краткое описание. Без паролей, приватных ключей и купленных кодов. Возвраты проверяются и выполняются вручную.')}</p></div><Link href="/refund">{t('Request a review','Отправить заявку')} <ArrowRight size={17}/></Link></section>
 <a className="gh-mail" href="mailto:support@mercenta.xyz"><Mail size={18}/>support@mercenta.xyz <ArrowUpRight size={15}/></a>
 </>}
 </main><footer className="gh-wrap gh-footer"><div><span>Mercenta</span><Link href="/api-docs">OpenAPI / Swagger <ArrowUpRight size={14}/></Link></div><OfficialContacts ru={ru}/></footer></div>;
}
