import type {CatalogProduct,CategoryId,ProductType} from './supplier';
import {brandArtwork} from './brand-artwork';
export type ProductFamily={key:string;name:string;brand:string;category:CategoryId;type:ProductType;currency:string;products:CatalogProduct[];regions:string[];searchText:string;hasArtwork:boolean};
export const regionCode=(p:Pick<CatalogProduct,'countryCode'>)=>p.countryCode?.trim().toUpperCase()||'UNSPECIFIED';
export function isSteamAccountOffer(p:Pick<CatalogProduct,'name'|'brand'>){const name=p.name.normalize('NFKC'),text=name+' '+p.brand;if(!/\bsteam\b/i.test(text))return false;if(/steam\s+accounts?\b|аккаунт[а-яё]*\s+steam|accounts?\s*\|?\s*steam/i.test(name))return true;return /\baccounts?\b|аккаунт[а-яё]*|уч[её]тн[а-яё]*\s+запис[а-яё]*/i.test(text)&&!/\bwallet\b|gift\s*cards?|top[ -]?up|пополнени/i.test(name)}
const aliases:Record<string,string[]>={US:['US','USA'],GB:['GB','UK'],GLOB:['GLOB','GLOBAL','GL','WORLDWIDE'],RU:['RU','RUS'],BR:['BR','BRA']};
export function familyName(p:Pick<CatalogProduct,'name'|'countryCode'>){let name=p.name.trim().replace(/\s+/g,' ');const code=regionCode(p);const tokens=new Set([code,...(aliases[code]??[]),...(Object.values(aliases).find(a=>a.includes(code))??[])]);const suffix=name.match(/\s*(?:\||\s[-–—]\s|\(|\[)\s*([A-Z0-9_-]{2,12})\s*[)\]]?\s*$/i);if(suffix&&tokens.has(suffix[1].toUpperCase()))name=name.slice(0,suffix.index).trim();name=name.replace(/^amazon\.(?:com(?:\.(?:au|br|mx|tr))?|co\.uk|[a-z]{2})\b/i,'Amazon');return name||p.name}
export function groupCatalog(products:CatalogProduct[]):ProductFamily[]{const map=new Map<string,ProductFamily>();for(const p of products){if(isSteamAccountOffer(p))continue;const name=familyName(p),key=[p.category,p.type,p.currency,name.toLowerCase().replace(/\s+/g,' ')].join('::');let f=map.get(key);if(!f){f={key,name,brand:p.brand,category:p.category,type:p.type,currency:p.currency,products:[],regions:[],searchText:'',hasArtwork:false};map.set(key,f)}f.products.push(p);const code=regionCode(p);if(!f.regions.includes(code))f.regions.push(code);f.searchText+=' '+[p.name,p.brand,p.id,code,p.searchText??p.denominations.map(d=>d.name).join(' ')].join(' ').toLowerCase();f.hasArtwork ||= !!(p.imageSource==='supplier'&&p.imageUrl||brandArtwork(p.name))}return [...map.values()].map(f=>({...f,regions:f.regions.sort(),products:f.products.slice().sort((a,b)=>regionCode(a).localeCompare(regionCode(b))||a.name.localeCompare(b.name)||a.id.localeCompare(b.id))})).sort((a,b)=>Number(b.hasArtwork)-Number(a.hasArtwork))}
export function familyProducts(f:ProductFamily,region='all'){return region==='all'?f.products:f.products.filter(p=>regionCode(p)===region)}
export function familyPrice(f:ProductFamily,region='all'){const prices=familyProducts(f,region).filter(p=>(p.optionCount??p.denominations.length)>0&&Number.isFinite(p.minPrice)&&p.minPrice>=0).map(p=>p.minPrice);return prices.length?Math.min(...prices):null}
export function familyOptions(f:ProductFamily,region='all'){return familyProducts(f,region).reduce((n,p)=>n+(p.optionCount??p.denominations.length),0)}
const displayNames=new Map<string,Intl.DisplayNames>();
export function regionLabel(code:string,ru=false){const special:Record<string,[string,string]>={GLOB:['Worldwide','Весь мир'],GLOBAL:['Worldwide','Весь мир'],UNSPECIFIED:['Region not supplied','Регион не указан'],EU:['European Union','Европейский союз'],ROW:['Other supported regions','Другие доступные регионы'],CIS:['CIS region','Регион СНГ'],MENA:['Middle East & North Africa','Ближний Восток и Северная Африка'],ASIA:['Asia','Азия'],SEA:['Southeast Asia','Юго-Восточная Азия'],LATAM:['Latin America','Латинская Америка']};if(special[code])return special[code][ru?1:0];try{const locale=ru?'ru':'en';if(!displayNames.has(locale))displayNames.set(locale,new Intl.DisplayNames([locale],{type:'region'}));const alias=code==='UK'?'GB':code==='USA'?'US':code;const label=displayNames.get(locale)!.of(alias);return label&&label!==alias?`${label} (${code})`:code}catch{return code}}
export function familyMatches(f:ProductFamily,q:string,region='all',category='all',kind='all',stock=false){const candidates=familyProducts(f,region);return candidates.length>0&&(category==='all'||f.category===category)&&(kind==='all'||f.type===kind)&&(!stock||candidates.some(p=>p.inStock>0))&&(!q.trim()||f.searchText.includes(q.trim().toLowerCase())||f.name.toLowerCase().includes(q.trim().toLowerCase())||f.regions.some(r=>regionLabel(r).toLowerCase().includes(q.trim().toLowerCase())||regionLabel(r,true).toLowerCase().includes(q.trim().toLowerCase())))}
export const catalogCategories=[['gaming','Gaming','Игры'],['streaming','Streaming','Медиа'],['creator','Creators','Авторам'],['developer','Developer','Разработка'],['cloud','Compute','Вычисления']] as const;
