import {z} from 'zod';
const units=z.string().regex(/^(0|[1-9]\d{0,30})$/);
const address=z.string().regex(/^0x[a-fA-F0-9]{40}$/);
export const circleStatusSchema=z.object({configured:z.boolean(),enabled:z.boolean(),chainId:z.literal(5042002),provider:z.enum(['local-eoa','circle-mpc']).nullable(),custody:z.string().nullable(),walletAddress:address.nullable(),services:z.array(z.object({id:z.string().regex(/^[a-z][a-z0-9-]{0,49}$/),maxAmountUnits:units})).max(10),perPaymentLimitUnits:units,dailyLimitUnits:units,requiresConfirmation:z.literal(true)});
export const circlePaymentSchema=z.object({id:z.string().uuid(),serviceId:z.string(),status:z.enum(['PREPARED','SIGNING','SUBMITTING','QUEUED','UNKNOWN','COMPLETED','FAILED']),amountUnits:units,wallet:address,payTo:address,network:z.literal('eip155:5042002'),expiresAt:z.number().int(),responseDigest:z.string().nullable(),circleTransferId:z.string().nullable(),txHash:z.string().regex(/^0x[a-fA-F0-9]{64}$/).nullable(),settled:z.boolean(),requiresConfirmation:z.literal(true)}).superRefine((v,c)=>{if(v.settled!==(v.status==='COMPLETED')||v.settled&&!v.txHash)c.addIssue({code:'custom',message:'INCONSISTENT_SETTLEMENT'});});
export const circleBalanceSchema=z.object({chainId:z.literal(5042002),walletAddress:address,walletUsdc:z.string().regex(/^(0|[1-9]\d*)(\.\d{1,18})?$/),gatewayAvailableUnits:units,source:z.literal("rpc-and-circle-api"),availableForPrepaidAccount:z.literal(false)});
export type CircleBalance=z.infer<typeof circleBalanceSchema>;
export type CircleStatus=z.infer<typeof circleStatusSchema>;
export type CirclePayment=z.infer<typeof circlePaymentSchema>;
export function canConfirmCircle(s:CircleStatus|null,p:CirclePayment,readOnly:boolean,now=Date.now()){return !readOnly&&!!s?.configured&&s.enabled&&p.status==='PREPARED'&&p.expiresAt>now&&s.walletAddress?.toLowerCase()===p.wallet.toLowerCase()&&BigInt(p.amountUnits)>0n&&BigInt(p.amountUnits)<=BigInt(s.perPaymentLimitUnits)&&s.services.some(x=>x.id===p.serviceId&&BigInt(p.amountUnits)<=BigInt(x.maxAmountUnits));}
export function circleStatusLabel(p:CirclePayment){if(p.settled&&p.status==='COMPLETED')return 'Verified settlement';if(p.status==='PREPARED')return 'Quote only — no payment';if(p.status==='FAILED')return 'Failed';return 'Pending evidence — do not pay again';}
export async function circleRequest<T>(path:string,schema:z.ZodType<T>,body?:unknown,signal?:AbortSignal):Promise<T>{const r=await fetch('/api/account/circle/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store',signal});if(!r.ok)throw new Error(r.status===404?'CIRCLE_BACKEND_NOT_DEPLOYED':r.status===401?'SIGN_IN_REQUIRED':'CIRCLE_REQUEST_FAILED_'+r.status);try{return schema.parse(await r.json())}catch{throw new Error('CIRCLE_RESPONSE_INVALID')}}
