import {parseAbi} from 'viem';
export const EARN_MARKET=Object.freeze({id:'aave-v3-ethereum-usdc',chainId:1,network:'Ethereum Mainnet',protocol:'Aave V3',asset:'USDC',decimals:6,pool:'0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2' as const,usdc:'0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' as const,aToken:'0x98C23E9d8f34FEFb1B7BD6a91B7FF122F4e16F5c' as const,appUrl:'https://app.aave.com/',docsUrl:'https://aave.com/docs/aave-v3/smart-contracts/pool',addressBookCommit:'6a83d11893d6687bf6b9fd091a2a5320b3e1966e'});
export const EARN_RESERVE_ABI=parseAbi(['function getReserveData(address asset) view returns (((uint256 data) configuration,uint128 liquidityIndex,uint128 currentLiquidityRate,uint128 variableBorrowIndex,uint128 currentVariableBorrowRate,uint128 currentStableBorrowRate,uint40 lastUpdateTimestamp,uint16 id,address aTokenAddress,address stableDebtTokenAddress,address variableDebtTokenAddress,address interestRateStrategyAddress,uint128 accruedToTreasury,uint128 unbacked,uint128 isolationModeTotalDebt))']);
export const EARN_TOKEN_ABI=parseAbi(['function decimals() view returns(uint8)','function balanceOf(address) view returns(uint256)','function totalSupply() view returns(uint256)','function POOL() view returns(address)','function UNDERLYING_ASSET_ADDRESS() view returns(address)']);
export type EarnObservation={chainId:number;blockNumber:string;blockHash:string;blockTimestamp:number;rateRay:string;configuration:string;availableMicro:string;totalSupplyMicro:string;decimals:number;aToken:string;boundPool:string;boundAsset:string;codeHashes:Record<string,string>};
export type EarnSnapshot={status:'available'|'blocked'|'unavailable';reason:string;observedAt:number;expiresAt:number;chainId:1;network:string;protocol:string;asset:'USDC';annualRatePercent:string|null;rateKind:'VARIABLE_SUPPLY_APR';blockNumber:string|null;blockHash:string|null;availableMicro:string|null;externalExecutionOnly:true;mercentaCustody:false;principalGuaranteed:false;interestGuaranteed:false;arcNativeYield:false};
export function unavailableEarn(now=Date.now()):EarnSnapshot{return {status:'unavailable',reason:'LIVE_VERIFICATION_UNAVAILABLE',observedAt:now,expiresAt:now,chainId:1,network:EARN_MARKET.network,protocol:EARN_MARKET.protocol,asset:'USDC',annualRatePercent:null,rateKind:'VARIABLE_SUPPLY_APR',blockNumber:null,blockHash:null,availableMicro:null,externalExecutionOnly:true,mercentaCustody:false,principalGuaranteed:false,interestGuaranteed:false,arcNativeYield:false};}
const units=(v:string)=>/^\d{1,80}$/.test(v);
export function assessEarnObservations(rows:EarnObservation[],now=Date.now()):EarnSnapshot{
 const unknown=unavailableEarn(now);if(!Number.isSafeInteger(now)||rows.length!==2)return unknown;
 const [a,b]=rows;if(JSON.stringify(a)!==JSON.stringify(b))return {...unknown,reason:'RPC_WITNESS_DISAGREEMENT'};
 if(a.chainId!==1||a.decimals!==6||a.aToken.toLowerCase()!==EARN_MARKET.aToken.toLowerCase()||a.boundPool.toLowerCase()!==EARN_MARKET.pool.toLowerCase()||a.boundAsset.toLowerCase()!==EARN_MARKET.usdc.toLowerCase())return {...unknown,reason:'WRONG_NETWORK_OR_TOKEN'};
 if(!/^0x[0-9a-f]{64}$/i.test(a.blockHash)||!units(a.blockNumber)||!units(a.rateRay)||!units(a.configuration)||!units(a.availableMicro)||!units(a.totalSupplyMicro)||!Number.isSafeInteger(a.blockTimestamp)||a.blockTimestamp*1000>now||now-a.blockTimestamp*1000>120000||Object.keys(a.codeHashes).sort().join(',')!=='aToken,pool,usdc'||Object.values(a.codeHashes).some(h=>!/^0x[0-9a-f]{64}$/i.test(h)))return {...unknown,reason:'STALE_OR_INVALID_OBSERVATION'};
 const cfg=BigInt(a.configuration),active=!!(cfg&(1n<<56n)),frozen=!!(cfg&(1n<<57n)),paused=!!(cfg&(1n<<60n)),cap=(cfg>>116n)&((1n<<36n)-1n),decimals=Number((cfg>>48n)&255n);
 if(decimals!==6)return {...unknown,reason:'RESERVE_DECIMALS_MISMATCH'};
 const reason=!active?'RESERVE_INACTIVE':paused?'RESERVE_PAUSED':frozen?'RESERVE_FROZEN':cap>0n&&BigInt(a.totalSupplyMicro)>=cap*1000000n?'SUPPLY_CAP_REACHED':BigInt(a.availableMicro)===0n?'NO_OBSERVED_LIQUIDITY':'VERIFIED_EXTERNAL_MARKET';
 // Ray annual supply APR. Display-only rounded decimal; all money remains integer strings.
 const hundredth=(BigInt(a.rateRay)*10000n+5n*10n**26n)/(10n**27n);
 return {...unknown,status:reason==='VERIFIED_EXTERNAL_MARKET'?'available':'blocked',reason,expiresAt:now+30000,annualRatePercent:(hundredth/100n)+'.'+(hundredth%100n).toString().padStart(2,'0'),blockNumber:a.blockNumber,blockHash:a.blockHash,availableMicro:a.availableMicro};
}
export function canOpenExternalEarn(snapshot:EarnSnapshot|null,accepted:boolean,now=Date.now()){return !!snapshot&&accepted&&snapshot.status==='available'&&snapshot.chainId===1&&snapshot.expiresAt>now&&snapshot.observedAt<=now&&snapshot.externalExecutionOnly===true&&snapshot.mercentaCustody===false&&snapshot.principalGuaranteed===false&&snapshot.interestGuaranteed===false&&snapshot.arcNativeYield===false&&Number.isSafeInteger(snapshot.observedAt)&&Number.isSafeInteger(snapshot.expiresAt)&&snapshot.expiresAt<=snapshot.observedAt+30000&&snapshot.annualRatePercent!==null&&/^\d{1,8}\.\d{2}$/.test(snapshot.annualRatePercent)&&!!snapshot.blockHash&&/^0x[0-9a-f]{64}$/i.test(snapshot.blockHash);}
