export type Bump='major'|'minor'|'patch'|'none';
export function composeRelease(input:string,current:string){
 const groups:{features:string[];fixes:string[];breaking:string[]}={features:[],fixes:[],breaking:[]};let accepted=0,ignored=0;
 for(const raw of input.slice(0,30000).split(/\r?\n/)){const line=raw.trim();if(!line)continue;const footer=/^BREAKING[ -]CHANGE:\s+(.+)$/.exec(line);if(footer){groups.breaking.push(footer[1]);continue}const m=/^([a-z]+)(?:\(([^\r\n()]+)\))?(!)?:\s+(.+)$/.exec(line);if(!m||!['feat','fix','docs','chore','refactor','perf','test','build','ci','style','revert'].includes(m[1])){ignored++;continue}accepted++;const text=(m[2]?m[2]+': ':'')+m[4];if(m[3])groups.breaking.push(text);if(m[1]==='feat')groups.features.push(text);if(['fix','perf','revert'].includes(m[1]))groups.fixes.push(text)}
 const valid=/^\d{1,6}\.\d{1,6}\.\d{1,6}$/.test(current),version=valid?current:'0.1.0';const parts=version.split('.').map(Number);const bump:Bump=groups.breaking.length?'major':groups.features.length?'minor':accepted?'patch':'none';if(bump==='major'){parts[0]++;parts[1]=0;parts[2]=0}else if(bump==='minor'){parts[1]++;parts[2]=0}else if(bump==='patch')parts[2]++;
 const next=parts.join('.');const markdown=`## ${next}\n\n`+([['Features',groups.features],['Fixes',groups.fixes],['Breaking changes',groups.breaking]] as const).filter(([,rows])=>rows.length).map(([name,rows])=>`### ${name}\n${rows.map(r=>'- '+r).join('\n')}`).join('\n\n');return {next,bump,groups,accepted,ignored,valid,markdown};
}
export type DayState='operational'|'degraded'|'outage'|'unknown';
export function sampleHistory(seed:number):DayState[]{let s=seed>>>0;return Array.from({length:60},()=>{s=(Math.imul(1664525,s)+1013904223)>>>0;const n=s/4294967296;return n<.02?'outage':n<.06?'degraded':'operational'})}
export function uptime(days:DayState[]){const known=days.filter(d=>d!=='unknown');return known.length?100*known.reduce((n,d)=>n+(d==='operational'?1:d==='degraded'?.5:0),0)/known.length:null}
export function redactTrace(value:unknown,depth=0):unknown{if(depth>5)return '[truncated]';if(typeof value==='string')return value.slice(0,1000).replace(/(?:sk-|Bearer\s+)[\w.-]{8,}/gi,'[redacted]');if(Array.isArray(value))return value.slice(0,20).map(v=>redactTrace(v,depth+1));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).slice(0,30).map(([k,v])=>[k,/secret|token|password|signature|credential|voucher|codes|authorization|api.?key/i.test(k)?'[redacted]':redactTrace(v,depth+1)]));return value}
