import {Redis} from 'ioredis';
import {Pool} from 'pg';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
export type Snapshot={body:Record<string,unknown>;asOf:number};
export type TemporaryConfig={TEMP_REDIS_URL?:string;TEMP_POSTGRES_URL?:string;TEMP_POSTGRES_CA_PATH?:string;TEMP_POSTGRES_CA_BASE64?:string;TEMP_SERVICES_EXPIRES_AT?:string};
export function temporaryDeadline(c:TemporaryConfig,now=Date.now()){const expiry=Date.parse(c.TEMP_SERVICES_EXPIRES_AT??'');return {enabled:Number.isFinite(expiry)&&expiry>now,expiresAt:Number.isFinite(expiry)?new Date(expiry).toISOString():null,daysRemaining:Number.isFinite(expiry)?Math.max(0,Math.ceil((expiry-now)/86400000)):null};}
export function snapshotKey(actor:string,route:string){return createHash('sha256').update(actor+'\n'+route).digest('hex')}
export class TemporaryStores {
 private redis:Redis|null=null;private pg:Pool|null=null;private schemaReady=false;private timer:ReturnType<typeof setTimeout>|undefined;
 private redisState='not-configured';private pgState='not-configured';
 constructor(private c:TemporaryConfig){if(c.TEMP_REDIS_URL)this.redisState='configured-not-probed';if(c.TEMP_POSTGRES_URL)this.pgState='configured-not-probed';this.armExpiry()}
 private armExpiry(){const d=temporaryDeadline(this.c);if(!d.enabled)return;this.timer=setTimeout(()=>{if(temporaryDeadline(this.c).enabled)this.armExpiry();else void this.close()},Math.min(Date.parse(d.expiresAt!)-Date.now(),2147483647));this.timer.unref();}
 status(){const d=temporaryDeadline(this.c);return {...d,warning:d.daysRemaining!==null&&d.daysRemaining<=7?'Temporary services expire soon; core SQLite remains authoritative.':null,redis:d.enabled?this.redisState:'disabled-or-expired',postgres:d.enabled?this.pgState:'disabled-or-expired',primary:'persistent-sqlite-wal',snapshotAuthority:'read-only-never-settlement'};}
 private async clients(){if(!temporaryDeadline(this.c).enabled){await this.close();return;}
 if(this.c.TEMP_REDIS_URL&&!this.redis){const u=new URL(this.c.TEMP_REDIS_URL);if(u.protocol!=='rediss:')throw new Error('REDIS_TLS_REQUIRED');this.redis=new Redis(this.c.TEMP_REDIS_URL,{lazyConnect:true,maxRetriesPerRequest:0,retryStrategy:()=>null,connectTimeout:1800,commandTimeout:1800,tls:{rejectUnauthorized:true,servername:u.hostname},enableOfflineQueue:false});this.redis.on('error',()=>{this.redisState='unavailable'});try{await this.redis.connect();this.redisState='ready'}catch{this.redisState='unavailable';this.redis.disconnect();this.redis=null;}}
 if(this.c.TEMP_POSTGRES_URL&&!this.pg){const u=new URL(this.c.TEMP_POSTGRES_URL);u.searchParams.delete('sslmode');u.searchParams.delete('sslcert');u.searchParams.delete('sslkey');u.searchParams.delete('sslrootcert');const ca=this.c.TEMP_POSTGRES_CA_BASE64?Buffer.from(this.c.TEMP_POSTGRES_CA_BASE64,'base64').toString():this.c.TEMP_POSTGRES_CA_PATH?readFileSync(this.c.TEMP_POSTGRES_CA_PATH,'utf8'):undefined;this.pg=new Pool({connectionString:u.toString(),ssl:{rejectUnauthorized:true,...(ca?{ca}:{})},max:2,connectionTimeoutMillis:1800,idleTimeoutMillis:5000,statement_timeout:1800});this.pg.on('error',()=>{this.pgState='unavailable'});try{await this.pg.query('SELECT 1');if(!this.schemaReady){await this.pg.query('CREATE TABLE IF NOT EXISTS mercenta_read_snapshots (cache_key TEXT PRIMARY KEY, body JSONB NOT NULL, as_of BIGINT NOT NULL, expires_at BIGINT NOT NULL)');this.schemaReady=true;}this.pgState='ready'}catch{this.pgState='unavailable-or-ca-required';await this.pg.end().catch(()=>{});this.pg=null;}}
 }
 async put(key:string,snapshot:Snapshot){try{await this.clients();if(!temporaryDeadline(this.c).enabled)return;const text=JSON.stringify(snapshot),expires=Date.now()+3600000;await Promise.allSettled([this.redis?.set('mercenta:snapshot:'+key,text,'EX',3600),this.pg?.query('INSERT INTO mercenta_read_snapshots(cache_key,body,as_of,expires_at) VALUES($1,$2,$3,$4) ON CONFLICT(cache_key) DO UPDATE SET body=EXCLUDED.body,as_of=EXCLUDED.as_of,expires_at=EXCLUDED.expires_at WHERE mercenta_read_snapshots.as_of <= EXCLUDED.as_of',[key,snapshot.body,snapshot.asOf,expires])].filter(Boolean));}catch{/* Optional infrastructure must never decide money or availability of core writes. */}}
 async get(key:string):Promise<Snapshot|null>{try{await this.clients();if(!temporaryDeadline(this.c).enabled)return null;try{const value=await this.redis?.get('mercenta:snapshot:'+key);if(value){const s=JSON.parse(value) as Snapshot;if(Date.now()-s.asOf<=3600000)return s;}}catch{/* Try the read-only PostgreSQL mirror. */}if(this.pg){const r=await this.pg.query('SELECT body,as_of FROM mercenta_read_snapshots WHERE cache_key=$1 AND expires_at>$2',[key,Date.now()]);if(r.rows[0])return {body:r.rows[0].body,asOf:Number(r.rows[0].as_of)};}}catch{/* Fail closed: a snapshot miss does not invent account credit. */}return null;}
 async close(){if(this.timer)clearTimeout(this.timer);this.timer=undefined;this.redis?.disconnect();this.redis=null;if(this.pg){const p=this.pg;this.pg=null;await p.end().catch(()=>{});}this.redisState='disabled-or-expired';this.pgState='disabled-or-expired';}
}
