export const journey=[
 {id:'identity',section:'Funds',en:['Connect your wallet','Use Connect Wallet in the top-right, then sign the login message. Login is not a payment.','Open Funds'],ru:['Подключите кошелёк','Нажмите Connect Wallet справа сверху и подпишите сообщение входа. Вход не отправляет деньги.','Открыть Funds']},
 {id:'budget',section:'Budget',en:['Set a budget','Choose a monthly plan, per-order and daily caps. Percentages do not transfer or lock funds.','Plan my budget'],ru:['Распределите бюджет','Задайте бюджет на месяц, лимит заказа и дня. Проценты не переводят и не блокируют деньги.','Настроить бюджет']},
 {id:'funds',section:'Funds',en:['Fund the account','Top up USDC → create deposit intent → send test USDC → verify after confirmations. Wallet balance is not account balance.','See funding steps'],ru:['Пополните счёт','Top up USDC → создайте заявку → отправьте test USDC → подтвердите транзакцию. Баланс кошелька и счёта — разные.','Как пополнить']},
 {id:'shop',section:'Shop',en:['Find a digital product','Browse Shop, choose a product and country, review quantity and the exact total before confirming. Current goods are simulated.','Browse Shop'],ru:['Выберите цифровой товар','Откройте Shop, выберите товар и регион, проверьте количество и итоговую цену. Сейчас выдача тестовая.','Посмотреть товары']},
 {id:'orders',section:'Orders',en:['Track your purchase','Orders shows status; Transactions shows the account debit. A submitted transaction is not a completed delivery.','See my orders'],ru:['Проверьте покупку','В Orders — статус заказа, в Transactions — списание. Отправленная транзакция ещё не означает выдачу товара.','Мои заказы']},
 {id:'journal',section:'Financial Journal',en:['Keep a private financial journal','Record expenses, declared income and notes. They do not change balances or verify sales.','Open my journal'],ru:['Ведите финансовый дневник','Записывайте расходы, заявленные доходы и заметки. Записи не меняют баланс и не подтверждают продажи.','Открыть дневник']},
 {id:'agent',section:'Agent Chat',en:['Ask the agent for help','Ask for a purchase plan or fee calculation. Review each proposal; chat does not authorize automatic spending.','Talk to the agent'],ru:['Попросите агента помочь','Запросите план покупки или расчёт комиссий. Проверяйте предложение: сообщение не разрешает автоматические траты.','Открыть чат']},
 {id:'profit',section:'Profit First',en:['Reseller? Protect the margin','Separate COGS from margin. Profit First uses sale evidence and separate wallet signatures; the budget plan is not a vault deposit.','Explore Profit First'],ru:['Реселлер? Защитите маржу','Отделяйте закупку от маржи. Profit First требует доказательств продажи и отдельной подписи; бюджет — не депозит в контракт.','Открыть Profit First']}
] as const;
export type Language='en'|'ru';
export function planUnits(s:string){if(!/^(0|[1-9]\d*)(\.\d{1,6})?$/.test(s)||s.length>16)throw new Error('INVALID_AMOUNT');const [w,f='']=s.split('.');return BigInt(w)*1000000n+BigInt(f.padEnd(6,'0'))}
export function allocation(monthly:string,percentages:number[]){if(percentages.length!==4||percentages.some(p=>!Number.isInteger(p)||p<0||p>100)||percentages.reduce((a,b)=>a+b,0)!==100)throw new Error('ALLOCATION_MUST_EQUAL_100_PERCENT');const total=planUnits(monthly);const parts=percentages.map(p=>total*BigInt(p)/100n);parts[1]+=total-parts.reduce((a,b)=>a+b,0n);return parts.map(p=>p.toString())}
export function validBudget(monthly:string,perOrder:string,daily:string,percentages:number[]){const [spend]=allocation(monthly,percentages).map(BigInt),total=planUnits(monthly),day=planUnits(daily),order=planUnits(perOrder);if(total<=0n||day<=0n||order<=0n||day>spend||order>day)throw new Error('BUDGET_LIMITS_INVALID');return true}
export function friendlyWorkspaceError(code:string,lang:Language){const errors:Record<string,[string,string]>={WALLET_AUTH_REQUIRED:['Connect and sign in with your wallet first.','Сначала подключите кошелёк и подпишите вход.'],BUDGET_REVISION_CONFLICT:['Your plan changed elsewhere. Refresh and review before saving.','Бюджет изменён в другом окне. Обновите и проверьте его.'],ALLOCATION_MUST_EQUAL_100_PERCENT:['Allocation must total 100%.','Сумма процентов должна быть 100%.'],BUDGET_LIMITS_INVALID:['Use positive limits: per order ≤ daily ≤ monthly spending allocation.','Лимиты должны быть больше нуля: заказ ≤ день ≤ бюджет покупок на месяц.'],DO_NOT_STORE_SECRETS:['Do not store passwords, keys or seed phrases.','Не сохраняйте пароли, ключи и seed-фразы.'],DO_NOT_SHARE_SECRETS:['Do not send credentials to the coach.','Не отправляйте секреты коучу.'],JOURNAL_DATE_INVALID:['Choose a valid date, not in the future.','Выберите существующую дату, не в будущем.'],INVALID_REQUEST:['Review the required fields and amounts.','Проверьте обязательные поля и суммы.'],MEMORY_PRESSURE_READ_ONLY:['Service is read-only. Nothing new was saved; retry later.','Сервис временно только для чтения. Новые данные не сохранены.'],INSUFFICIENT_ACCOUNT_BALANCE:['Your account balance is too low. Check Funds.','Недостаточно средств на счёте. Проверьте Funds.']};return errors[code]?.[lang==='ru'?1:0]??(lang==='ru'?'Не удалось выполнить запрос. Обновите страницу и повторите.':'Request could not be completed. Refresh and retry.')}
