import {randomUUID,randomBytes,createHash} from 'node:crypto';
import type {DB} from '../db.js';
import {postJournal,balance} from './ledger/index.js';
import {parseMoney} from '../money.js';
import type {PaymentProof} from './arc/index.js';
export const TEST_PRODUCTS=[
 {id:'test-gaming',name:'Gaming voucher · test delivery',category:'gaming',country:'US',price:'5.273400',kind:'Shop'},
 {id:'test-creator',name:'Creator credits · test top-up',category:'creator',country:'GLOBAL',price:'1.532000',kind:'Direct Top-Up'},
 {id:'test-developer',name:'Developer API credits · test bundle',category:'developer',country:'GLOBAL',price:'6.000000',kind:'Shop'},
 {id:'test-cloud',name:'GPU compute · test voucher',category:'cloud',country:'GLOBAL',price:'9.500000',kind:'Shop'},
 {id:'test-streaming',name:'Media subscription · test voucher',category:'streaming',country:'EU',price:'4.500000',kind:'Shop'},
] as const;
export const SCOPES=['account:read','orders:read','orders:create'] as const;
export function initAccount(db:DB){db.exec(`
CREATE TABLE IF NOT EXISTS account_deposits(id TEXT PRIMARY KEY,actor TEXT NOT NULL,request_id TEXT NOT NULL,receiver TEXT NOT NULL,expected_units TEXT NOT NULL,amount_units TEXT,tx_hash TEXT UNIQUE,block_hash TEXT,status TEXT NOT NULL,created_at INTEGER NOT NULL,credited_at INTEGER,UNIQUE(actor,request_id));
CREATE TABLE IF NOT EXISTS account_orders(id TEXT PRIMARY KEY,actor TEXT NOT NULL,request_id TEXT NOT NULL,fingerprint TEXT NOT NULL,product_id TEXT NOT NULL,name TEXT NOT NULL,country TEXT NOT NULL,kind TEXT NOT NULL,quantity INTEGER NOT NULL,amount_units TEXT NOT NULL,status TEXT NOT NULL,initiator TEXT NOT NULL,reference TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(actor,request_id));
CREATE TABLE IF NOT EXISTS account_activity(id TEXT PRIMARY KEY,actor TEXT NOT NULL,category TEXT NOT NULL,available_delta TEXT NOT NULL,balance_units TEXT NOT NULL,order_id TEXT,deposit_id TEXT,comment TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS account_keys(id TEXT PRIMARY KEY,actor TEXT NOT NULL,name TEXT NOT NULL,key_hash TEXT UNIQUE NOT NULL,mask TEXT NOT NULL,scopes TEXT NOT NULL,expires_at INTEGER NOT NULL,last_used INTEGER,revoked_at INTEGER,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS account_orders_actor_date ON account_orders(actor,created_at);
CREATE INDEX IF NOT EXISTS account_activity_actor_date ON account_activity(actor,created_at);
CREATE TRIGGER IF NOT EXISTS deposit_replay_orders BEFORE UPDATE OF tx_hash ON account_deposits WHEN NEW.tx_hash IS NOT NULL AND EXISTS(SELECT 1 FROM payments WHERE tx_hash=NEW.tx_hash) BEGIN SELECT RAISE(ABORT,'PAYMENT_ALREADY_USED'); END;
CREATE TRIGGER IF NOT EXISTS order_replay_deposit BEFORE INSERT ON payments WHEN EXISTS(SELECT 1 FROM account_deposits WHERE tx_hash=NEW.tx_hash) BEGIN SELECT RAISE(ABORT,'PAYMENT_ALREADY_USED'); END;
CREATE TRIGGER IF NOT EXISTS deposit_immutable BEFORE UPDATE ON account_deposits WHEN OLD.status='CREDITED' BEGIN SELECT RAISE(ABORT,'IMMUTABLE_DEPOSIT'); END;
CREATE TRIGGER IF NOT EXISTS deposit_no_delete BEFORE DELETE ON account_deposits BEGIN SELECT RAISE(ABORT,'IMMUTABLE_DEPOSIT'); END;
CREATE TRIGGER IF NOT EXISTS activity_no_update BEFORE UPDATE ON account_activity BEGIN SELECT RAISE(ABORT,'IMMUTABLE_ACTIVITY'); END;
CREATE TRIGGER IF NOT EXISTS activity_no_delete BEFORE DELETE ON account_activity BEGIN SELECT RAISE(ABORT,'IMMUTABLE_ACTIVITY'); END;
CREATE TRIGGER IF NOT EXISTS account_order_immutable BEFORE UPDATE ON account_orders BEGIN SELECT RAISE(ABORT,'IMMUTABLE_ORDER'); END;
CREATE TRIGGER IF NOT EXISTS account_order_no_delete BEFORE DELETE ON account_orders BEGIN SELECT RAISE(ABORT,'IMMUTABLE_ORDER'); END;
`)}
function owner(actor:string){if(!/^wallet:0x[a-f0-9]{40}$/.test(actor))throw new Error('WALLET_AUTH_REQUIRED');return actor;}
const liability=(actor:string,bucket:string)=>'account:usdc:'+owner(actor)+':'+bucket;
export function funds(db:DB,actor:string){return {availableUnits:(-balance(db,liability(actor,'available'))).toString(),reservedUnits:(-balance(db,liability(actor,'reserved'))).toString(),currency:'USDC',chainId:5042002,network:'Arc Testnet',mode:'testnet'}};
export type Deposit={id:string;actor:string;request_id:string;receiver:string;expected_units:string;amount_units:string|null;tx_hash:string|null;block_hash:string|null;status:string;created_at:number;credited_at:number|null};
export function createDeposit(db:DB,actor:string,requestId:string,receiver:string,amount:string){owner(actor);if(!/^0x[a-fA-F0-9]{40}$/.test(receiver)||/^0x0{40}$/i.test(receiver)||receiver.toLowerCase()===actor.slice(7))throw new Error('DEPOSIT_RECEIVER_INVALID');const units=parseMoney(amount);if(units<=0n||units>1_000_000_000_000n)throw new Error('DEPOSIT_AMOUNT_INVALID');return db.transaction(()=>{const old=db.prepare('SELECT * FROM account_deposits WHERE actor=? AND request_id=?').get(actor,requestId) as Deposit|undefined;if(old){if(old.expected_units!==units.toString()||old.receiver!==receiver.toLowerCase())throw new Error('IDEMPOTENCY_CONFLICT');return old;}const id=randomUUID();db.prepare("INSERT INTO account_deposits(id,actor,request_id,receiver,expected_units,status,created_at) VALUES(?,?,?,?,?,'AWAITING_TRANSFER',?)").run(id,actor,requestId,receiver.toLowerCase(),units.toString(),Date.now());return db.prepare('SELECT * FROM account_deposits WHERE id=?').get(id) as Deposit;})()}
export function getDeposit(db:DB,actor:string,id:string){owner(actor);const d=db.prepare('SELECT * FROM account_deposits WHERE id=? AND actor=?').get(id,actor) as Deposit|undefined;if(!d)throw new Error('DEPOSIT_NOT_FOUND');return d;}
export function creditDeposit(db:DB,actor:string,id:string,p:PaymentProof & {blockTime:number}){return db.transaction(()=>{const d=getDeposit(db,actor,id);if(d.status==='CREDITED'){if(d.tx_hash!==p.txHash)throw new Error('IDEMPOTENCY_CONFLICT');return d;}if(p.confirmations<2n||p.amount<BigInt(d.expected_units)||p.blockTime<d.created_at-1000||p.blockTime>Date.now()+5000)throw new Error('DEPOSIT_EVIDENCE_REJECTED');if(Date.now()-d.created_at>86400000)throw new Error('DEPOSIT_EXPIRED');if(db.prepare('SELECT 1 FROM payments WHERE tx_hash=?').get(p.txHash)||db.prepare('SELECT 1 FROM account_deposits WHERE tx_hash=?').get(p.txHash))throw new Error('PAYMENT_ALREADY_USED');
postJournal(db,'account-deposit:'+id,p.txHash,[{account:'arc:usdc:customer-deposits',currency:'USDC',direction:'DEBIT',amount:p.amount},{account:liability(actor,'available'),currency:'USDC',direction:'CREDIT',amount:p.amount}]);
db.prepare("UPDATE account_deposits SET amount_units=?,tx_hash=?,block_hash=?,status='CREDITED',credited_at=? WHERE id=?").run(p.amount.toString(),p.txHash,p.blockHash,Date.now(),id);activity(db,actor,'Deposit',p.amount,null,id,'Verified Arc Testnet deposit');return getDeposit(db,actor,id);})()}
function activity(db:DB,actor:string,category:string,delta:bigint,order:string|null,deposit:string|null,comment:string){db.prepare('INSERT INTO account_activity VALUES(?,?,?,?,?,?,?,?,?)').run(randomUUID(),actor,category,delta.toString(),funds(db,actor).availableUnits,order,deposit,comment,Date.now());}
export type AccountOrder={id:string;actor:string;product_id:string;name:string;country:string;kind:string;quantity:number;amount_units:string;status:string;initiator:string;reference:string;created_at:number;fingerprint:string};
export function placeTestOrder(db:DB,actor:string,requestId:string,productId:string,quantity:number,reference:string,initiator='Portal'){
 owner(actor);if(!Number.isInteger(quantity)||quantity<1||quantity>100||reference.length>100)throw new Error('INVALID_ORDER');const product=TEST_PRODUCTS.find(p=>p.id===productId);if(!product)throw new Error('TEST_PRODUCT_NOT_FOUND');const amount=parseMoney(product.price)*BigInt(quantity);if(amount>10_000_000n)throw new Error('TESTNET_ORDER_LIMIT_10_USDC');
 const fp=createHash('sha256').update(JSON.stringify({productId,quantity,reference,initiator})).digest('hex');return db.transaction(()=>{const previous=db.prepare('SELECT * FROM account_orders WHERE actor=? AND request_id=?').get(actor,requestId) as AccountOrder|undefined;if(previous){if(previous.fingerprint!==fp)throw new Error('IDEMPOTENCY_CONFLICT');return previous;}if(BigInt(funds(db,actor).availableUnits)<amount)throw new Error('INSUFFICIENT_ACCOUNT_BALANCE');const id=randomUUID();
 // Atomic reserve and capture for the explicitly simulated fulfillment only. No upstream call or redeemable product is made.
 postJournal(db,'account-reserve:'+id,'testnet-order:'+id,[{account:liability(actor,'available'),currency:'USDC',direction:'DEBIT',amount},{account:liability(actor,'reserved'),currency:'USDC',direction:'CREDIT',amount}]);
 postJournal(db,'account-capture:'+id,'testnet-simulated:'+id,[{account:liability(actor,'reserved'),currency:'USDC',direction:'DEBIT',amount},{account:'testnet:simulated-sales',currency:'USDC',direction:'CREDIT',amount}]);
 db.prepare("INSERT INTO account_orders VALUES(?,?,?,?,?,?,?,?,?,?,'SIMULATED_FULFILLED',?,?,?)").run(id,actor,requestId,fp,product.id,product.name,product.country,product.kind,quantity,amount.toString(),initiator,reference,Date.now());activity(db,actor,product.kind,-amount,id,null,product.name+' x'+quantity);return db.prepare('SELECT * FROM account_orders WHERE id=?').get(id) as AccountOrder;})()
}
export type Filters={from?:number;to?:number;initiator?:string;status?:string;country?:string;product?:string;method?:string};
export function range(period:string,from?:string,to?:string,now=Date.now()):Filters {if(period==='all')return {};if(period==='7d'||period==='30d')return {from:now-(period==='7d'?7:30)*86400000,to:now};if(period!=='custom'||!from||!to||!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to))throw new Error('INVALID_DATE_RANGE');const a=Date.parse(from+'T00:00:00Z'),b=Date.parse(to+'T00:00:00Z');if(!Number.isFinite(a)||!Number.isFinite(b)||a>b||new Date(a).toISOString().slice(0,10)!==from||new Date(b).toISOString().slice(0,10)!==to)throw new Error('INVALID_DATE_RANGE');return {from:a,to:b+86400000-1}}
export function accountOrders(db:DB,actor:string,f:Filters={}){owner(actor);const rows=db.prepare('SELECT * FROM account_orders WHERE actor=? ORDER BY created_at DESC,id DESC').all(actor) as AccountOrder[];return rows.filter(r=>(f.from===undefined||r.created_at>=f.from)&&(f.to===undefined||r.created_at<=f.to)&&(!f.initiator||r.initiator===f.initiator)&&(!f.status||r.status===f.status)&&(!f.country||r.country===f.country)&&(!f.product||r.product_id===f.product));}
export function dashboard(db:DB,actor:string,f:Filters={}){const rows=accountOrders(db,actor,f),top=new Map<string,{name:string;units:bigint;orders:number}>();let spent=0n,shop=0n,dtu=0n;for(const r of rows){const u=BigInt(r.amount_units);spent+=u;if(r.kind==='Shop')shop+=u;else dtu+=u;const s=top.get(r.product_id)??{name:r.name,units:0n,orders:0};s.units+=u;s.orders++;top.set(r.product_id,s);}return {totalOrders:rows.length,shopOrders:rows.filter(r=>r.kind==='Shop').length,directTopUpOrders:rows.filter(r=>r.kind!=='Shop').length,totalSpentUnits:spent.toString(),shopSpentUnits:shop.toString(),directTopUpSpentUnits:dtu.toString(),topServices:[...top.values()].sort((a,b)=>a.units===b.units?0:a.units>b.units?-1:1).slice(0,10).map(r=>({...r,units:r.units.toString()})),recentActivity:rows.slice(0,10),filters:f,mode:'testnet-sandbox-fulfillment'}}
export function history(db:DB,actor:string,kind:'funds'|'transactions',f:Filters={}){owner(actor);const table=kind==='funds'?'account_deposits':'account_activity';const rows=db.prepare(`SELECT * FROM ${table} WHERE actor=? ORDER BY created_at DESC,id DESC`).all(actor) as Record<string,unknown>[];return rows.filter(r=>(f.from===undefined||Number(r.created_at)>=f.from)&&(f.to===undefined||Number(r.created_at)<=f.to)&&(!f.status||r.status===f.status)&&(!f.method||f.method==='arc'));}
export function listKeys(db:DB,actor:string){owner(actor);return db.prepare('SELECT id,name,mask,scopes,expires_at,last_used,revoked_at,created_at FROM account_keys WHERE actor=? ORDER BY created_at DESC').all(actor)}
export function createKey(db:DB,actor:string,name:string,scopes:string[],days:number){owner(actor);if(!name.trim()||name.length>60||!scopes.length||scopes.some(s=>!SCOPES.includes(s as typeof SCOPES[number]))||!Number.isInteger(days)||days<1||days>90)throw new Error('INVALID_KEY');const count=db.prepare('SELECT count(*) n FROM account_keys WHERE actor=? AND revoked_at IS NULL AND expires_at>?').get(actor,Date.now()) as {n:number};if(count.n>=10)throw new Error('API_KEY_LIMIT');const secret='mct_'+randomBytes(32).toString('base64url'),id=randomUUID(),mask=secret.slice(0,8)+'…'+secret.slice(-4);db.prepare('INSERT INTO account_keys VALUES(?,?,?,?,?,?,?,NULL,NULL,?)').run(id,actor,name.trim(),createHash('sha256').update(secret).digest('hex'),mask,JSON.stringify([...new Set(scopes)]),Date.now()+days*86400000,Date.now());return {id,name,mask,secret,expiresAt:Date.now()+days*86400000,scopes};}
export function revokeKey(db:DB,actor:string,id:string){owner(actor);const r=db.prepare('UPDATE account_keys SET revoked_at=? WHERE id=? AND actor=? AND revoked_at IS NULL').run(Date.now(),id,actor);if(!r.changes)throw new Error('KEY_NOT_FOUND');return {revoked:true}}
export function authenticateKey(db:DB,secret:string,scope:string){if(!/^mct_[A-Za-z0-9_-]{43}$/.test(secret))throw new Error('UNAUTHORIZED');const r=db.prepare('SELECT id,actor,scopes FROM account_keys WHERE key_hash=? AND revoked_at IS NULL AND expires_at>?').get(createHash('sha256').update(secret).digest('hex'),Date.now()) as {id:string;actor:string;scopes:string}|undefined;if(!r)throw new Error('UNAUTHORIZED');if(!(JSON.parse(r.scopes) as string[]).includes(scope))throw new Error('API_SCOPE_REQUIRED');db.prepare('UPDATE account_keys SET last_used=? WHERE id=?').run(Date.now(),r.id);return r;}
