import {memoryState} from './runtime.js';
import {gatewayAvailableUnits} from './circle-gateway-balance.js';
import {formatUnits,type Address} from 'viem';
import {randomUUID,createHash,createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {verifyConfiguredWallet,signGatewayPayload} from './circle-signers.js';
import type {DB} from '../db.js';import type {Config} from '../config.js';
import {postJournal} from './ledger/index.js';import {arcClient} from './arc/index.js';
import {agentConfigSchema,assertOwner,checkedRequirements,checkDailyLimit,loadAgentConfig,publicCircleStatus,matchTransfer,CHAIN,GATEWAY_API,NETWORK,type AgentConfig,type Requirements} from './circle-policy.js';
import {boundedHttps,type HttpResult} from './circle-http.js';
export type AgentRow={id:string;actor:string;request_id:string;fingerprint:string;service_id:string;wallet:string;recipient:string;amount:string;quote:string;status:string;nonce:string|null;encrypted_payload:string|null;response_digest:string|null;encrypted_response:string|null;circle_transfer_id:string|null;tx_hash:string|null;created_at:number;expires_at:number};
export type CirclePorts={http:(url:string,headers?:Record<string,string>)=>Promise<HttpResult>;walletCheck:(c:AgentConfig,amountUnits:string)=>Promise<void>;sign:(c:AgentConfig,requirements:Requirements)=>Promise<{x402Version:number;payload:{signature:string;authorization:{from:string;to:string;value:string;validAfter:string;validBefore:string;nonce:string}}}>;receipt:(hash:`0x${string}`)=>Promise<{blockHash:string;confirmed:boolean}>};
export function initCircleAgent(db:DB){db.exec(`CREATE TABLE IF NOT EXISTS circle_agent_payments(id TEXT PRIMARY KEY,actor TEXT NOT NULL,request_id TEXT NOT NULL,fingerprint TEXT NOT NULL,service_id TEXT NOT NULL,wallet TEXT NOT NULL,recipient TEXT NOT NULL,amount TEXT NOT NULL,quote TEXT NOT NULL,status TEXT NOT NULL,nonce TEXT UNIQUE,encrypted_payload TEXT,response_digest TEXT,encrypted_response TEXT,circle_transfer_id TEXT UNIQUE,tx_hash TEXT,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,UNIQUE(actor,request_id));CREATE INDEX IF NOT EXISTS circle_agent_actor_history ON circle_agent_payments(actor,created_at DESC,id DESC);CREATE TABLE IF NOT EXISTS circle_agent_events(seq INTEGER PRIMARY KEY,payment_id TEXT NOT NULL REFERENCES circle_agent_payments(id),event TEXT NOT NULL,details TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TRIGGER IF NOT EXISTS circle_payment_identity BEFORE UPDATE ON circle_agent_payments WHEN NEW.id<>OLD.id OR NEW.actor<>OLD.actor OR NEW.request_id<>OLD.request_id OR NEW.fingerprint<>OLD.fingerprint OR NEW.service_id<>OLD.service_id OR NEW.wallet<>OLD.wallet OR NEW.recipient<>OLD.recipient OR NEW.amount<>OLD.amount OR NEW.quote<>OLD.quote OR NEW.created_at<>OLD.created_at OR NEW.expires_at<>OLD.expires_at OR OLD.nonce IS NOT NULL AND NEW.nonce IS NOT OLD.nonce BEGIN SELECT RAISE(ABORT,'IMMUTABLE_CIRCLE_QUOTE'); END;CREATE TRIGGER IF NOT EXISTS circle_events_no_update BEFORE UPDATE ON circle_agent_events BEGIN SELECT RAISE(ABORT,'IMMUTABLE_CIRCLE_EVENT'); END;CREATE TRIGGER IF NOT EXISTS circle_events_no_delete BEFORE DELETE ON circle_agent_events BEGIN SELECT RAISE(ABORT,'IMMUTABLE_CIRCLE_EVENT'); END;`)}
function seal(secret:string,text:string){const key=createHash('sha256').update('mercenta:circle-payload:'+secret).digest(),iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);return JSON.stringify({iv:iv.toString('hex'),data:Buffer.concat([c.update(text,'utf8'),c.final()]).toString('hex'),tag:c.getAuthTag().toString('hex')})}
export function unseal(secret:string,blob:string){const b=JSON.parse(blob),key=createHash('sha256').update('mercenta:circle-payload:'+secret).digest(),d=createDecipheriv('aes-256-gcm',key,Buffer.from(b.iv,'hex'));d.setAuthTag(Buffer.from(b.tag,'hex'));return Buffer.concat([d.update(Buffer.from(b.data,'hex')),d.final()]).toString('utf8')}
function view(r:AgentRow){return {id:r.id,serviceId:r.service_id,status:r.status,amountUnits:r.amount,wallet:r.wallet,payTo:r.recipient,network:NETWORK,expiresAt:r.expires_at,responseDigest:r.response_digest,circleTransferId:r.circle_transfer_id,txHash:r.tx_hash,settled:r.status==='COMPLETED',requiresConfirmation:true};}
function event(db:DB,id:string,name:string,details:unknown={}){db.prepare('INSERT INTO circle_agent_events(payment_id,event,details,created_at) VALUES(?,?,?,?)').run(id,name,JSON.stringify(details),Date.now())}
function row(db:DB,actor:string,id:string){const r=db.prepare('SELECT * FROM circle_agent_payments WHERE id=? AND actor=?').get(id,actor) as AgentRow|undefined;if(!r)throw new Error('CIRCLE_PAYMENT_NOT_FOUND');return r}
function realPorts(c:Config):CirclePorts{
 return {http:boundedHttps,walletCheck:async (a,amountUnits)=>{await verifyConfiguredWallet(a);const client=arcClient(c.ARC_RPC_URL);if(await client.getChainId()!==5042002)throw new Error('WRONG_CHAIN');const code=await client.getCode({address:a.walletAddress as Address});if(code&&code!=='0x')throw new Error('CIRCLE_EOA_REQUIRED');if(await gatewayAvailableUnits(a)<BigInt(amountUnits))throw new Error('INSUFFICIENT_GATEWAY_BALANCE')},sign:signGatewayPayload,receipt:async hash=>{const client=arcClient(c.ARC_RPC_URL);if(await client.getChainId()!==5042002)throw new Error('WRONG_CHAIN');const r=await client.getTransactionReceipt({hash});if(r.status!=='success')throw new Error('CIRCLE_ONCHAIN_FAILED');const b=await client.getBlock({blockNumber:r.blockNumber});if(b.hash!==r.blockHash)throw new Error('BLOCK_MISMATCH');return {blockHash:r.blockHash,confirmed:await client.getBlockNumber()-r.blockNumber+1n>=2n}}};
}
export class CircleAgent {
 private ports:CirclePorts;constructor(private db:DB,private c:Config,ports?:CirclePorts,private configOverride?:AgentConfig){initCircleAgent(db);this.ports=ports??realPorts(c)}
 private config(){const a=this.configOverride?agentConfigSchema.parse(this.configOverride):loadAgentConfig(this.c.CIRCLE_AGENT_CONFIG_FILE);if(!a)throw new Error('CIRCLE_AGENT_NOT_CONFIGURED');return a}
 status(actor:string){let a:AgentConfig|null=null;try{a=this.config()}catch{}return publicCircleStatus(a,actor)}
 async balances(actor:string){const a=this.config();assertOwner(a,actor);const client=arcClient(this.c.ARC_RPC_URL);if(await client.getChainId()!==5042002)throw Error("WRONG_CHAIN");const [native,gateway]=await Promise.all([client.getBalance({address:a.walletAddress as Address}),gatewayAvailableUnits(a)]);return {chainId:5042002,walletAddress:a.walletAddress,walletUsdc:formatUnits(native,18),gatewayAvailableUnits:gateway.toString(),source:"rpc-and-circle-api",availableForPrepaidAccount:false}}
 list(actor:string){const records=this.db.prepare("SELECT * FROM circle_agent_payments WHERE actor=? ORDER BY created_at DESC,id DESC LIMIT 50").all(actor) as AgentRow[];return {items:records.map(view)}}
 get(actor:string,id:string){return view(row(this.db,actor,id))}
 async prepare(actor:string,requestId:string,serviceId:string){
 if(memoryState(this.c).pressured)throw Error('READ_ONLY_MODE');
 const a=this.config();assertOwner(a,actor);const s=a.services.find(x=>x.id===serviceId);if(!s)throw new Error('CIRCLE_SERVICE_NOT_ALLOWED');
 const fingerprint=createHash('sha256').update(JSON.stringify({service:s,wallet:a.walletAddress,provider:a.provider})).digest('hex');const previous=this.db.prepare('SELECT * FROM circle_agent_payments WHERE actor=? AND request_id=?').get(actor,requestId) as AgentRow|undefined;if(previous){if(previous.fingerprint!==fingerprint)throw new Error('CIRCLE_REQUEST_CONFLICT');return view(previous)}
 const count=this.db.prepare('SELECT count(*) n FROM circle_agent_payments WHERE actor=? AND created_at>?').get(actor,Date.now()-86400000) as {n:number};if(count.n>=40)throw new Error('CIRCLE_DAILY_QUOTE_LIMIT');
 const response=await this.ports.http(s.url);if(response.status!==402)throw new Error('X402_REQUIRED');const quote=checkedRequirements(response.headers['payment-required']??'',s);
 const id=randomUUID(),now=Date.now();this.db.prepare(`INSERT INTO circle_agent_payments(id,actor,request_id,fingerprint,service_id,wallet,recipient,amount,quote,status,created_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?,'PREPARED',?,?)`).run(id,actor,requestId,fingerprint,serviceId,a.walletAddress,s.payTo,quote.accepted.amount,JSON.stringify(quote),now,now+300000);event(this.db,id,'QUOTE_CHECKED',{maxAmountUnits:s.maxAmountUnits,noFundsMoved:true});return this.get(actor,id);
 }
 async confirm(actor:string,id:string,confirmed:boolean){
 if(memoryState(this.c).pressured)throw Error('READ_ONLY_MODE');if(confirmed!==true)throw new Error('CONFIRMATION_REQUIRED');const a=this.config();assertOwner(a,actor);if(!a.enabled)throw new Error('CIRCLE_EXECUTION_DISABLED');let r=row(this.db,actor,id);if(r.status!=='PREPARED')return view(r);if(r.expires_at<Date.now())throw new Error('CIRCLE_QUOTE_EXPIRED');
 const s=a.services.find(x=>x.id===r.service_id);if(!s||createHash('sha256').update(JSON.stringify({service:s,wallet:a.walletAddress,provider:a.provider})).digest('hex')!==r.fingerprint)throw new Error('CIRCLE_POLICY_CHANGED');
 await this.ports.walletCheck(a,r.amount);
 this.db.transaction(()=>{r=row(this.db,actor,id);if(r.status!=='PREPARED')throw new Error('CIRCLE_REQUEST_IN_PROGRESS');if(r.expires_at<Date.now())throw new Error('CIRCLE_QUOTE_EXPIRED');const reserved=this.db.prepare("SELECT amount FROM circle_agent_payments WHERE actor=? AND status NOT IN('PREPARED','FAILED') AND (created_at>? OR status<>'COMPLETED')").all(actor,Date.now()-86400000) as {amount:string}[];checkDailyLimit(reserved.reduce((n,x)=>n+BigInt(x.amount),0n).toString(),r.amount);this.db.prepare("UPDATE circle_agent_payments SET status='SIGNING' WHERE id=?").run(id);event(this.db,id,'CONFIRMED',{backendBudgetReserved:true})})();
 try{
  const quote=JSON.parse(r.quote),signed=await this.ports.sign(a,quote.accepted),auth=signed.payload.authorization;
  if(auth.from.toLowerCase()!==r.wallet||auth.to.toLowerCase()!==r.recipient||auth.value!==r.amount||!/^0x[a-fA-F0-9]{64}$/.test(auth.nonce))throw new Error('CIRCLE_AUTHORIZATION_MISMATCH');
  const current=this.config();assertOwner(current,actor);if(!current.enabled||current.walletAddress!==a.walletAddress)throw new Error('CIRCLE_EXECUTION_DISABLED');if(r.expires_at<Date.now())throw new Error('CIRCLE_QUOTE_EXPIRED');
  const activeService=current.services.find(x=>x.id===r.service_id);if(!activeService||createHash('sha256').update(JSON.stringify({service:activeService,wallet:current.walletAddress,provider:current.provider})).digest('hex')!==r.fingerprint)throw new Error('CIRCLE_POLICY_CHANGED');
  const encoded=Buffer.from(JSON.stringify({...signed,accepted:quote.accepted,resource:quote.resource})).toString('base64');
  this.db.transaction(()=>{this.db.prepare("UPDATE circle_agent_payments SET status='SUBMITTING',nonce=?,encrypted_payload=? WHERE id=?").run(auth.nonce.toLowerCase(),seal(this.c.DELIVERY_ENCRYPTION_KEY,encoded),id);event(this.db,id,'SIGNED',{nonce:auth.nonce,privateKeySentToProvider:false,signer:a.provider})})();
  const response=await this.ports.http(s.url,{'PAYMENT-SIGNATURE':encoded});
  this.db.prepare("UPDATE circle_agent_payments SET status=CASE WHEN status IN('COMPLETED','FAILED') THEN status ELSE 'QUEUED' END,response_digest=?,encrypted_response=? WHERE id=?").run(createHash('sha256').update(response.body).digest('hex'),response.status>=200&&response.status<300?seal(this.c.DELIVERY_ENCRYPTION_KEY,response.body):null,id);event(this.db,id,'PAID_REQUEST_RETURNED',{httpStatus:response.status,finalSettlement:false});
 }catch{this.db.prepare("UPDATE circle_agent_payments SET status='UNKNOWN' WHERE id=? AND status NOT IN('COMPLETED','FAILED')").run(id);event(this.db,id,'RECONCILIATION_REQUIRED',{automaticRetry:false})}
 return this.get(actor,id);
 }
 async reconcile(actor:string,id:string){
 const a=this.config();assertOwner(a,actor);const r=row(this.db,actor,id);if(r.status==='COMPLETED'||r.status==='FAILED'||!r.nonce)return view(r);
 const url=`${GATEWAY_API}/x402/transfers?nonce=${encodeURIComponent(r.nonce)}&network=${encodeURIComponent(NETWORK)}&pageSize=100`;
 const response=await this.ports.http(url);if(response.status!==200)throw new Error('CIRCLE_STATUS_UNAVAILABLE');const payload=JSON.parse(response.body);if(!Array.isArray(payload.transfers)||payload.transfers.length>1)throw new Error('CIRCLE_ATTRIBUTION_AMBIGUOUS');if(!payload.transfers.length)return view(r);
 const t=matchTransfer(payload.transfers[0],{nonce:r.nonce,from:r.wallet,to:r.recipient,amount:r.amount});
 if(t.status==='failed'){this.db.transaction(()=>{this.db.prepare("UPDATE circle_agent_payments SET status='FAILED',circle_transfer_id=? WHERE id=?").run(t.id,id);event(this.db,id,'CIRCLE_FAILED',{charged:false})})();return this.get(actor,id)}
 if(t.status!=='completed'){event(this.db,id,'CIRCLE_PENDING',{status:t.status});return view(r)}
 const proof=await this.ports.receipt(t.txHash as `0x${string}`);if(!proof.confirmed)throw new Error('CIRCLE_PAYMENT_NOT_FINAL');
 this.db.transaction(()=>{const fresh=row(this.db,actor,id);if(fresh.status==='COMPLETED')return;const amount=BigInt(r.amount);postJournal(this.db,'circle:'+id,JSON.stringify({circleTransferId:t.id,nonce:r.nonce,batchTxHash:t.txHash,blockHash:proof.blockHash,attribution:'Circle transfer API plus canonical batch receipt; not independent per-payment batch decoding'}),[{account:`circle-external:${actor}:api-expense`,currency:'USDC',direction:'DEBIT',amount},{account:`circle-external:${actor}:gateway`,currency:'USDC',direction:'CREDIT',amount}]);this.db.prepare("UPDATE circle_agent_payments SET status='COMPLETED',circle_transfer_id=?,tx_hash=? WHERE id=?").run(t.id,t.txHash,id);event(this.db,id,'COMPLETED',{amountUnits:r.amount,batchTxHash:t.txHash,prepaidAccountCredited:false})})();return this.get(actor,id);
 }
 resource(actor:string,id:string){const r=row(this.db,actor,id);if(!r.encrypted_response)throw new Error('CIRCLE_RESOURCE_UNAVAILABLE');return {payment:this.get(actor,id),content:unseal(this.c.DELIVERY_ENCRYPTION_KEY,r.encrypted_response),untrustedServiceOutput:true};}
 async recoverResource(actor:string,id:string){
 const a=this.config();assertOwner(a,actor);const r=row(this.db,actor,id);
 if(r.encrypted_response)return this.get(actor,id);
 if(r.status!=='COMPLETED'||!r.encrypted_payload||!r.nonce)throw Error('CIRCLE_RESOURCE_RECOVERY_NOT_READY');
 if(memoryState(this.c).pressured)throw Error('READ_ONLY_MODE');
 const s=a.services.find(s=>s.id===r.service_id);
 if(!s||createHash('sha256').update(JSON.stringify({service:s,wallet:a.walletAddress,provider:a.provider})).digest('hex')!==r.fingerprint)throw Error('CIRCLE_POLICY_CHANGED');
 const encoded=unseal(this.c.DELIVERY_ENCRYPTION_KEY,r.encrypted_payload);
 const response=await this.ports.http(s.url,{'PAYMENT-SIGNATURE':encoded,'X-Mercenta-Replay':'cached-only'});
 if(response.status!==200)throw Error('CIRCLE_ORIGINAL_RESOURCE_UNAVAILABLE');
 this.db.transaction(()=>{this.db.prepare('UPDATE circle_agent_payments SET response_digest=?,encrypted_response=? WHERE id=? AND encrypted_response IS NULL').run(createHash('sha256').update(response.body).digest('hex'),seal(this.c.DELIVERY_ENCRYPTION_KEY,response.body),id);event(this.db,id,'ORIGINAL_RESOURCE_RECOVERED',{newAuthorization:false,newPayment:false})})();
 return this.get(actor,id);
 }
 evidence(actor:string,id:string){const r=row(this.db,actor,id);return {payment:view(r),events:this.db.prepare('SELECT event,details,created_at FROM circle_agent_events WHERE payment_id=? ORDER BY seq').all(id),journal:this.db.prepare('SELECT account,currency,direction,amount_units FROM ledger_entries WHERE batch_id=?').all('circle:'+id),limits:{testnetOnly:true,backendGuardrails:true,onchainDelegation:false},custody:this.config().provider==='local-eoa'?'server-managed-local-eoa; server key holders can authorize spending':'developer-controlled-mpc; server credential holders can authorize spending',settlementAttribution:'Circle nonce-matched transfer API plus canonical batch receipt',resourceDelivery:'A response digest is not proof of useful delivery or business adoption'};}
}
