import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import {keccak256,toHex} from 'viem';
import type {DB} from '../db.js';
import {funds,TEST_PRODUCTS,placeTestOrder,type AccountOrder} from './account.js';
import {parseMoney} from '../money.js';
import {moneyInput,profitQuote} from './profit.js';
export const workflowInput=z.object({requestId:z.string().uuid(),budget:moneyInput,country:z.enum(['ANY','US','EU','GLOBAL']).default('ANY'),category:z.enum(['ANY','gaming','creator','developer','cloud','streaming']).default('ANY'),quantity:z.number().int().min(1).max(5).default(1),productIds:z.array(z.string().max(100)).min(1).max(3).optional()}).strict();
export const saleInput=z.object({requestId:z.string().uuid(),orderId:z.string().uuid(),gross:moneyInput,fees:moneyInput.default('0'),refundReserve:moneyInput.default('0'),reference:z.string().regex(/^[A-Za-z0-9._:-]{0,80}$/).default('')}).strict();
export const unitsMoney=(units:string|bigint)=>{const n=BigInt(units);return `${n/1000000n}.${(n%1000000n).toString().padStart(6,'0')}`};
const owner=(a:string)=>{if(!/^wallet:0x[a-f0-9]{40}$/.test(a))throw new Error('WALLET_AUTH_REQUIRED')};
export function initCommerce(db:DB){db.exec(`
CREATE TABLE IF NOT EXISTS commerce_workflows(id TEXT PRIMARY KEY,actor TEXT NOT NULL,request_id TEXT NOT NULL,fingerprint TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL,result TEXT,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,UNIQUE(actor,request_id));
CREATE INDEX IF NOT EXISTS commerce_workflow_actor_date ON commerce_workflows(actor,created_at);
CREATE TRIGGER IF NOT EXISTS commerce_quote_immutable BEFORE UPDATE OF actor,request_id,fingerprint,payload,created_at,expires_at ON commerce_workflows BEGIN SELECT RAISE(ABORT,'IMMUTABLE_WORKFLOW'); END;
CREATE TABLE IF NOT EXISTS commerce_events(id TEXT PRIMARY KEY,actor TEXT NOT NULL,workflow_id TEXT NOT NULL,kind TEXT NOT NULL,body TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TRIGGER IF NOT EXISTS commerce_event_no_update BEFORE UPDATE ON commerce_events BEGIN SELECT RAISE(ABORT,'IMMUTABLE_EVIDENCE'); END;
CREATE TRIGGER IF NOT EXISTS commerce_event_no_delete BEFORE DELETE ON commerce_events BEGIN SELECT RAISE(ABORT,'IMMUTABLE_EVIDENCE'); END;
CREATE TABLE IF NOT EXISTS commerce_sales(id TEXT PRIMARY KEY,actor TEXT NOT NULL,request_id TEXT NOT NULL,fingerprint TEXT NOT NULL,order_id TEXT UNIQUE NOT NULL,gross_units TEXT NOT NULL,cogs_units TEXT NOT NULL,fees_units TEXT NOT NULL,reserve_units TEXT NOT NULL,reference TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(actor,request_id));
CREATE TRIGGER IF NOT EXISTS commerce_sale_no_update BEFORE UPDATE ON commerce_sales BEGIN SELECT RAISE(ABORT,'IMMUTABLE_SALE'); END;
CREATE TRIGGER IF NOT EXISTS commerce_sale_no_delete BEFORE DELETE ON commerce_sales BEGIN SELECT RAISE(ABORT,'IMMUTABLE_SALE'); END;
CREATE TABLE IF NOT EXISTS commerce_sale_payments(sale_id TEXT PRIMARY KEY,actor TEXT NOT NULL,tx_hash TEXT UNIQUE NOT NULL,buyer TEXT NOT NULL,receiver TEXT NOT NULL,amount_units TEXT NOT NULL,block_hash TEXT NOT NULL,block_number TEXT NOT NULL,confirmed_at INTEGER NOT NULL);
CREATE TRIGGER IF NOT EXISTS sale_payment_no_update BEFORE UPDATE ON commerce_sale_payments BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PAYMENT'); END;
CREATE TRIGGER IF NOT EXISTS sale_payment_no_delete BEFORE DELETE ON commerce_sale_payments BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PAYMENT'); END;
CREATE TRIGGER IF NOT EXISTS sale_payment_not_replayed BEFORE INSERT ON commerce_sale_payments WHEN EXISTS(SELECT 1 FROM payments WHERE tx_hash=NEW.tx_hash) OR EXISTS(SELECT 1 FROM account_deposits WHERE tx_hash=NEW.tx_hash) BEGIN SELECT RAISE(ABORT,'PAYMENT_ALREADY_USED'); END;
CREATE TRIGGER IF NOT EXISTS account_deposit_not_sale BEFORE UPDATE OF tx_hash ON account_deposits WHEN NEW.tx_hash IS NOT NULL AND EXISTS(SELECT 1 FROM commerce_sale_payments WHERE tx_hash=NEW.tx_hash) BEGIN SELECT RAISE(ABORT,'PAYMENT_ALREADY_USED'); END;
CREATE TRIGGER IF NOT EXISTS supplier_payment_not_sale BEFORE INSERT ON payments WHEN EXISTS(SELECT 1 FROM commerce_sale_payments WHERE tx_hash=NEW.tx_hash) BEGIN SELECT RAISE(ABORT,'PAYMENT_ALREADY_USED'); END;
CREATE TABLE IF NOT EXISTS commerce_sale_allocations(sale_id TEXT NOT NULL,plan_id TEXT PRIMARY KEY,created_at INTEGER NOT NULL);
CREATE TRIGGER IF NOT EXISTS sale_allocation_no_update BEFORE UPDATE ON commerce_sale_allocations BEGIN SELECT RAISE(ABORT,'IMMUTABLE_ALLOCATION_LINK'); END;
CREATE TRIGGER IF NOT EXISTS sale_allocation_no_delete BEFORE DELETE ON commerce_sale_allocations BEGIN SELECT RAISE(ABORT,'IMMUTABLE_ALLOCATION_LINK'); END;
`)}
type Line={requestId:string;productId:string;name:string;country:string;category:string;quantity:number;unitPriceUnits:string;amountUnits:string};
type Quote={budgetUnits:string;totalUnits:string;lines:Line[];country:string;category:string;budgetSource:string;steps:{tool:string;status:string;explanation:string}[];limits:{maxActions:number;maxSpendUSDC:string;fulfillment:string;signing:string}};
type Workflow={id:string;actor:string;request_id:string;fingerprint:string;payload:string;status:string;result:string|null;created_at:number;expires_at:number};
export function getWorkflow(db:DB,a:string,id:string){owner(a);const w=db.prepare('SELECT * FROM commerce_workflows WHERE id=? AND actor=?').get(id,a) as Workflow|undefined;if(!w)throw new Error('WORKFLOW_NOT_FOUND');return w}
export function workflowView(db:DB,a:string,w:Workflow){const q=JSON.parse(w.payload) as Quote,current=BigInt(funds(db,a).availableUnits),shortfall=BigInt(q.totalUnits)>current?BigInt(q.totalUnits)-current:0n;return {id:w.id,status:w.status,quote:q,result:w.result?JSON.parse(w.result):null,createdAt:w.created_at,expiresAt:w.expires_at,currentAvailableUnits:current.toString(),fundingShortfallUnits:shortfall.toString(),canConfirm:w.status==='PROPOSED'&&w.expires_at>Date.now()&&shortfall===0n,evidenceUrl:'/api/account/evidence/workflows/'+w.id}}
export function listWorkflows(db:DB,a:string){owner(a);return (db.prepare('SELECT * FROM commerce_workflows WHERE actor=? ORDER BY created_at DESC LIMIT 30').all(a) as Workflow[]).map(w=>workflowView(db,a,w))}
function event(db:DB,a:string,w:string,kind:string,body:unknown){db.prepare('INSERT INTO commerce_events VALUES(?,?,?,?,?,?)').run(randomUUID(),a,w,kind,JSON.stringify(body),Date.now())}
export function createWorkflow(db:DB,a:string,raw:unknown,budgetSource='user-form'){owner(a);const b=workflowInput.parse(raw),budget=parseMoney(b.budget);if(budget<=0n||budget>10000000n)throw new Error('WORKFLOW_BUDGET_LIMIT_10_USDC');if(b.productIds&&new Set(b.productIds).size!==b.productIds.length)throw new Error('DUPLICATE_PRODUCT');const ids=b.productIds?[...b.productIds].sort():null,fp=createHash('sha256').update(JSON.stringify({budget:budget.toString(),country:b.country,category:b.category,quantity:b.quantity,ids,budgetSource})).digest('hex');return db.transaction(()=>{const old=db.prepare('SELECT * FROM commerce_workflows WHERE actor=? AND request_id=?').get(a,b.requestId) as Workflow|undefined;if(old){if(old.fingerprint!==fp)throw new Error('IDEMPOTENCY_CONFLICT');return workflowView(db,a,old)}
 const recent=db.prepare('SELECT count(*) n FROM commerce_workflows WHERE actor=? AND created_at>?').get(a,Date.now()-86400000) as {n:number};if(recent.n>=60)throw new Error('WORKFLOW_DAILY_LIMIT');
 const eligible=TEST_PRODUCTS.filter(p=>(b.country==='ANY'||p.country===b.country)&&(b.category==='ANY'||p.category===b.category)).sort((x,y)=>parseMoney(x.price)<parseMoney(y.price)?-1:1);let selected=ids?ids.map(id=>{const p=eligible.find(x=>x.id===id);if(!p)throw new Error('PRODUCT_CONSTRAINT_MISMATCH');return p}):eligible.filter(p=>parseMoney(p.price)*BigInt(b.quantity)<=budget).slice(0,1);if(!selected.length)throw new Error('NO_PRODUCT_WITHIN_BUDGET');const lines:Line[]=selected.map(p=>({requestId:randomUUID(),productId:p.id,name:p.name,country:p.country,category:p.category,quantity:b.quantity,unitPriceUnits:parseMoney(p.price).toString(),amountUnits:(parseMoney(p.price)*BigInt(b.quantity)).toString()})),total=lines.reduce((s,p)=>s+BigInt(p.amountUnits),0n);if(total>budget||total>10000000n)throw new Error('WORKFLOW_OVER_BUDGET');
 const quote:Quote={budgetUnits:budget.toString(),totalUnits:total.toString(),lines,country:b.country,category:b.category,budgetSource,steps:[{tool:'account.balance',status:'CHECKED',explanation:'Current spendable balance read from the authoritative ledger; rechecked at confirmation.'},{tool:'catalog.search',status:'CHECKED',explanation:`Trusted test catalogue filtered by ${b.country} / ${b.category}. ${ids?'Requested allowed products.':'Lowest-price eligible product selected deterministically.'}`},{tool:'pricing.quote',status:'PINNED',explanation:'Six-decimal backend prices, explicit quantities. No added purchase execution fee; funding gas is separate.'},{tool:'policy.check',status:'CHECKED',explanation:'Maximum three line items, five units per line and ten test USDC total. No arbitrary addresses or contracts.'},{tool:'purchase',status:'AWAITING_CONFIRMATION',explanation:'One explicit confirmation executes the bounded bundle atomically. No purchase occurred while planning.'}],limits:{maxActions:3,maxSpendUSDC:'10.000000',fulfillment:'SIMULATED_ONLY',signing:'No LLM signing authority'}};const id=randomUUID(),now=Date.now();db.prepare("INSERT INTO commerce_workflows VALUES(?,?,?,?,?,'PROPOSED',NULL,?,?)").run(id,a,b.requestId,fp,JSON.stringify(quote),now,now+600000);event(db,a,id,'PLAN_PROPOSED',{totalUnits:total.toString(),budgetUnits:budget.toString(),authority:'PROPOSAL_ONLY'});return workflowView(db,a,getWorkflow(db,a,id))})()}
export function confirmWorkflow(db:DB,a:string,id:string,confirmed:boolean){if(confirmed!==true)throw new Error('CONFIRMATION_REQUIRED');return db.transaction(()=>{const w=getWorkflow(db,a,id);if(w.status==='EXECUTED')return workflowView(db,a,w);if(w.status!=='PROPOSED')throw new Error('WORKFLOW_NOT_EXECUTABLE');if(w.expires_at<Date.now())throw new Error('QUOTE_EXPIRED');const q=JSON.parse(w.payload) as Quote,total=BigInt(q.totalUnits);if(total>BigInt(q.budgetUnits)||total>10000000n||q.lines.length>3)throw new Error('WORKFLOW_POLICY_REJECTED');if(BigInt(funds(db,a).availableUnits)<total)throw new Error('INSUFFICIENT_ACCOUNT_BALANCE');for(const line of q.lines){const p=TEST_PRODUCTS.find(p=>p.id===line.productId);if(!p||parseMoney(p.price).toString()!==line.unitPriceUnits||parseMoney(p.price)*BigInt(line.quantity)!==BigInt(line.amountUnits))throw new Error('QUOTE_CHANGED')}
 const orders=q.lines.map(l=>placeTestOrder(db,a,l.requestId,l.productId,l.quantity,'workflow:'+id,'Agent Workflow'));const result={orders:orders.map(o=>({id:o.id,name:o.name,country:o.country,quantity:o.quantity,amountUnits:o.amount_units,status:o.status})),totalUnits:q.totalUnits,availableUnits:funds(db,a).availableUnits,mode:'SIMULATED_FULFILLMENT',confirmedAt:Date.now()};db.prepare("UPDATE commerce_workflows SET status='EXECUTED',result=? WHERE id=? AND actor=?").run(JSON.stringify(result),id,a);event(db,a,id,'BUNDLE_EXECUTED',{orderIds:orders.map(o=>o.id),totalUnits:q.totalUnits,mode:'SIMULATED_ONLY'});return workflowView(db,a,getWorkflow(db,a,id))})()}
export function cancelWorkflow(db:DB,a:string,id:string){return db.transaction(()=>{const w=getWorkflow(db,a,id);if(w.status==='EXECUTED')throw new Error('WORKFLOW_ALREADY_EXECUTED');if(w.status==='PROPOSED'){db.prepare("UPDATE commerce_workflows SET status='CANCELLED' WHERE actor=? AND id=?").run(a,id);event(db,a,id,'PLAN_CANCELLED',{fundsMoved:false})}return workflowView(db,a,getWorkflow(db,a,id))})()}
export type Sale={id:string;actor:string;request_id:string;fingerprint:string;order_id:string;gross_units:string;cogs_units:string;fees_units:string;reserve_units:string;reference:string;created_at:number};
export function getSale(db:DB,a:string,id:string){owner(a);const s=db.prepare('SELECT * FROM commerce_sales WHERE actor=? AND id=?').get(a,id) as Sale|undefined;if(!s)throw new Error('SALE_NOT_FOUND');return s}
export function saleQuote(s:Sale){return profitQuote({gross:unitsMoney(s.gross_units),cogs:unitsMoney(s.cogs_units),fees:unitsMoney(s.fees_units),refundReserve:unitsMoney(s.reserve_units)})}
export function saleView(db:DB,a:string,s:Sale){const payment=db.prepare('SELECT tx_hash,buyer,receiver,amount_units,block_hash,block_number,confirmed_at FROM commerce_sale_payments WHERE sale_id=? AND actor=?').get(s.id,a) as Record<string,unknown>|undefined,allocations=db.prepare('SELECT p.id,p.status,p.result,p.payload,p.expires_at FROM commerce_sale_allocations l JOIN agent_chat_plans p ON p.id=l.plan_id WHERE l.sale_id=? AND p.actor=? ORDER BY l.created_at DESC').all(s.id,a) as {id:string;status:string;result:string|null;payload:string;expires_at:number}[];return {id:s.id,orderId:s.order_id,grossUnits:s.gross_units,cogsUnits:s.cogs_units,feesUnits:s.fees_units,refundReserveUnits:s.reserve_units,reference:s.reference,createdAt:s.created_at,paymentStatus:payment?'TESTNET_PAYMENT_VERIFIED':'DECLARED_UNVERIFIED',payment:payment??null,costSource:'Actual test-order ledger debit; goods fulfillment remains simulated.',grossSource:payment?'Verified testnet transfer; not a production invoice':'Seller-declared scenario, not proof of received revenue',quote:saleQuote(s),allocations:allocations.map(p=>({id:p.id,status:p.status,expiresAt:p.expires_at,preview:JSON.parse(p.payload),result:p.result?JSON.parse(p.result):null})),evidenceUrl:'/api/account/evidence/sales/'+s.id}}
export function listSales(db:DB,a:string){owner(a);return (db.prepare('SELECT * FROM commerce_sales WHERE actor=? ORDER BY created_at DESC LIMIT 30').all(a) as Sale[]).map(s=>saleView(db,a,s))}
export function createSale(db:DB,a:string,raw:unknown){owner(a);const b=saleInput.parse(raw),o=db.prepare('SELECT * FROM account_orders WHERE actor=? AND id=?').get(a,b.orderId) as AccountOrder|undefined;if(!o||o.status!=='SIMULATED_FULFILLED')throw new Error('ELIGIBLE_ORDER_NOT_FOUND');const gross=parseMoney(b.gross),fees=parseMoney(b.fees),reserve=parseMoney(b.refundReserve);profitQuote({gross:b.gross,cogs:unitsMoney(o.amount_units),fees:b.fees,refundReserve:b.refundReserve});const fp=createHash('sha256').update(JSON.stringify({order:b.orderId,gross:gross.toString(),fees:fees.toString(),reserve:reserve.toString(),reference:b.reference})).digest('hex');return db.transaction(()=>{const old=db.prepare('SELECT * FROM commerce_sales WHERE actor=? AND request_id=?').get(a,b.requestId) as Sale|undefined;if(old){if(old.fingerprint!==fp)throw new Error('IDEMPOTENCY_CONFLICT');return saleView(db,a,old)}if(db.prepare('SELECT 1 FROM commerce_sales WHERE order_id=?').get(b.orderId))throw new Error('ORDER_ALREADY_HAS_SALE');const id=randomUUID();db.prepare('INSERT INTO commerce_sales VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,a,b.requestId,fp,o.id,gross.toString(),o.amount_units,fees.toString(),reserve.toString(),b.reference,Date.now());return saleView(db,a,getSale(db,a,id))})()}
export type SalePaymentProof={txHash:string;buyer:string;amount:bigint;blockHash:string;blockNumber:bigint;blockTime:number;confirmations:bigint};
export function recordSalePayment(db:DB,a:string,id:string,p:SalePaymentProof){return db.transaction(()=>{const s=getSale(db,a,id),buyer=p.buyer.toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(buyer)||buyer===a.slice(7))throw new Error('BUYER_MUST_DIFFER_FROM_SELLER');if(p.amount!==BigInt(s.gross_units)||p.confirmations<2n||p.blockTime<s.created_at-1000||p.blockTime>Date.now()+5000||p.blockTime>s.created_at+86400000)throw new Error('SALE_PAYMENT_EVIDENCE_REJECTED');const old=db.prepare('SELECT tx_hash,buyer FROM commerce_sale_payments WHERE sale_id=?').get(id) as {tx_hash:string;buyer:string}|undefined;if(old){if(old.tx_hash!==p.txHash.toLowerCase()||old.buyer!==buyer)throw new Error('IDEMPOTENCY_CONFLICT');return saleView(db,a,s)}db.prepare('INSERT INTO commerce_sale_payments VALUES(?,?,?,?,?,?,?,?,?)').run(id,a,p.txHash.toLowerCase(),buyer,a.slice(7),p.amount.toString(),p.blockHash,p.blockNumber.toString(),Date.now());return saleView(db,a,s)})()}
export const saleSettlementId=(id:string)=>keccak256(toHex('mercenta:sale:'+id));
export function saleMetrics(db:DB,a:string){owner(a);const rows=db.prepare('SELECT s.*,EXISTS(SELECT 1 FROM commerce_sale_payments p WHERE p.sale_id=s.id) paid,EXISTS(SELECT 1 FROM commerce_sale_allocations l JOIN agent_chat_plans p ON p.id=l.plan_id WHERE l.sale_id=s.id AND p.status=\'EXECUTED\') allocated FROM commerce_sales s WHERE s.actor=?').all(a) as (Sale&{paid:number;allocated:number})[];let declared=0n,verified=0n,margin=0n,allocated=0n;for(const s of rows){declared+=BigInt(s.gross_units);if(s.paid){verified+=BigInt(s.gross_units);margin+=BigInt(s.gross_units)-BigInt(s.cogs_units)-BigInt(s.fees_units)-BigInt(s.reserve_units)}if(s.allocated)allocated+=BigInt(saleQuote(s).profitUnits)}return {scenarioGrossUnits:declared.toString(),verifiedTestnetGrossUnits:verified.toString(),verifiedTestnetMarginUnits:margin.toString(),allocatedProfitUnits:allocated.toString(),sales:rows.length,verifiedSales:rows.filter(s=>s.paid).length,earnEnabled:false,accounting:'Testnet transfers and simulated goods; not certified production revenue. Scenario declarations are excluded from verified revenue.'}}
function journals(db:DB,a:string,orderId:string){const o=db.prepare('SELECT id FROM account_orders WHERE actor=? AND id=?').get(a,orderId);if(!o)throw new Error('ORDER_NOT_FOUND');return ['account-reserve:'+orderId,'account-capture:'+orderId].map(id=>{const b=db.prepare('SELECT id,witness,created_at,sealed FROM ledger_batches WHERE id=?').get(id) as {sealed:number}|undefined,entries=db.prepare('SELECT account,currency,direction,amount_units FROM ledger_entries WHERE batch_id=? ORDER BY id').all(id) as {account:string;currency:string;direction:string;amount_units:string}[];const net=entries.reduce((n,e)=>n+(e.direction==='DEBIT'?1n:-1n)*BigInt(e.amount_units),0n);return {batch:b,entries,balanced:!!b?.sealed&&entries.length>=2&&net===0n}})}
export function workflowEvidence(db:DB,a:string,id:string){const w=getWorkflow(db,a,id),result=w.result?JSON.parse(w.result) as {orders:{id:string}[]}:null;return {version:1,kind:'workflow',network:'Arc Testnet',chainId:5042002,asOf:new Date().toISOString(),wallet:a.slice(7),workflow:workflowView(db,a,w),events:(db.prepare('SELECT kind,body,created_at FROM commerce_events WHERE actor=? AND workflow_id=? ORDER BY created_at,id').all(a,id) as {kind:string;body:string;created_at:number}[]).map(e=>({...e,body:JSON.parse(e.body)})),journals:result?.orders.flatMap(o=>journals(db,a,o.id))??[],boundaries:{goods:'SIMULATED_ONLY',ledger:'Persistent SQLite WAL, immutable sealed double-entry journals',accountCustody:'Platform prepaid account; not the noncustodial vault',modelAuthority:'PROPOSAL_ONLY',earn:'DISABLED'}}}
export function saleEvidence(db:DB,a:string,id:string){const s=getSale(db,a,id);return {version:1,kind:'sale',network:'Arc Testnet',chainId:5042002,asOf:new Date().toISOString(),wallet:a.slice(7),sale:saleView(db,a,s),journals:journals(db,a,s.order_id),boundaries:{payment:'A verified transfer proves testnet funds received, not real goods delivered or a certified commercial invoice',allocation:'Each sale uses a stable contract saleId. Approval or broadcasting is not settlement.',yield:'No Earn integration or APY'},settlementId:saleSettlementId(id)}}
