import {compatibleCompletion,compatibleConfigured,configuredModels,resetCompatibleCircuits} from './compatible-model.js';
import {readFileSync,statSync} from 'node:fs';import {createHash} from 'node:crypto';import {z} from 'zod';import type {Config} from '../config.js';
export const intentSchema=z.object({action:z.enum(['balance','catalog','purchase','profit','earn','fees','plan','help']),productId:z.string().max(100).optional(),quantity:z.number().int().min(1).max(100).optional(),budgetUsdc:z.string().regex(/^(0|[1-9]\d*)(\.\d{1,6})?$/).max(15).optional(),productIds:z.array(z.string().max(100)).min(1).max(3).optional(),country:z.enum(['ANY','US','EU','GLOBAL']).optional(),category:z.enum(['ANY','gaming','creator','developer','cloud','streaming']).optional(),answer:z.string().trim().min(1).max(1800).optional()}).strict();
export type Intent=z.infer<typeof intentSchema>;
type Message={role:'system'|'user';content:string};
const endpoints={groq:{kind:'openai',url:'https://api.groq.com/openai/v1/chat/completions'},gemini:{kind:'gemini',url:'https://generativelanguage.googleapis.com/v1beta'},mistral:{kind:'openai',url:'https://api.mistral.ai/v1/chat/completions'},openrouter:{kind:'openai',url:'https://openrouter.ai/api/v1/chat/completions'}} as const;
const schema=z.object({id:z.enum(['groq','gemini','mistral','openrouter']),kind:z.enum(['gemini','openai']),url:z.string().url(),model:z.string().min(1).max(100).regex(/^[A-Za-z0-9._/-]+$/),keys:z.array(z.string().min(16).max(200)).min(1).max(32),initialCooldownUntil:z.number().optional()}).strict();type Provider=z.infer<typeof schema>;
const providerCooldown=new Map<string,number>(),keyCooldown=new Map<string,number>();
let cached:{path:string;mtime:number;providers:Provider[]}|undefined;
function configured(c:Config):Provider[]{const file=c.LLM_PROVIDERS_FILE;if(!file)return [];try{const st=statSync(file);if(st.size>32768||(process.platform!=='win32'&&(st.mode&0o027)!==0))return [];if(cached?.path===file&&cached.mtime===st.mtimeMs)return cached.providers;const providers=z.array(schema).max(4).parse(JSON.parse(readFileSync(file,'utf8')));if(new Set(providers.map(p=>p.id)).size!==providers.length)return [];for(const p of providers){const expected=endpoints[p.id];if(expected.kind!==p.kind||expected.url!==p.url)return [];}cached={path:file,mtime:st.mtimeMs,providers};return providers}catch{return []}}
export function modelAvailability(c:Config){const ps=configured(c);return {configured:ps.length>0||compatibleConfigured(c),providers:(ps.length?ps:compatibleConfigured(c)?configuredModels(c).map(model=>({id:'configured-model',model,initialCooldownUntil:0})):[]).map(p=>({provider:p.id,model:p.model,status:Math.max(providerCooldown.get(p.id)??0,p.initialCooldownUntil??0)>Date.now()?'cooldown':'configured'}))}}
function retryUntil(raw:string|null,now:number){if(!raw)return now+60000;const sec=Number(raw),date=Date.parse(raw);const ms=Number.isFinite(sec)?sec*1000:Number.isFinite(date)?date-now:60000;return now+Math.max(5000,Math.min(ms,3600000));}
async function limitedJson(r:Response){if(Number(r.headers.get('content-length')??0)>65536)throw new Error('MODEL_RESPONSE_TOO_LARGE');const reader=r.body?.getReader();if(!reader)throw new Error('MODEL_EMPTY');const chunks:Uint8Array[]=[];let count=0;for(;;){const {value,done}=await reader.read();if(done)break;count+=value.length;if(count>65536){await reader.cancel();throw new Error('MODEL_RESPONSE_TOO_LARGE')}chunks.push(value)}const bytes=new Uint8Array(count);let offset=0;for(const v of chunks){bytes.set(v,offset);offset+=v.length}return JSON.parse(new TextDecoder().decode(bytes)) as Record<string,unknown>}
function responseText(d:Record<string,unknown>,gemini:boolean){if(gemini){const c=d.candidates as {content?:{parts?:{text?:string;thought?:boolean}[]}}[]|undefined;return c?.[0]?.content?.parts?.filter(p=>!p.thought).map(p=>p.text??'').join('')??''}const choices=d.choices as {message?:{content?:string}}[]|undefined;return choices?.[0]?.message?.content??''}
export async function completeIntent(c:Config,messages:Message[],fetcher:typeof fetch=fetch,now=Date.now()):Promise<{intent:Intent;provider:string;model:string}|null>{const ps=configured(c),deadline=now+12000;for(const p of ps){if(Math.max(providerCooldown.get(p.id)??0,p.initialCooldownUntil??0)>Date.now())continue;const key=p.keys.find(k=>(keyCooldown.get(createHash('sha256').update(k).digest('hex'))??0)<Date.now());if(!key)continue;const remaining=deadline-Date.now();if(remaining<500)break;let url=p.url,body:Record<string,unknown>,headers:Record<string,string>={'Content-Type':'application/json'};if(p.kind==='gemini'){url+='/models/'+encodeURIComponent(p.model)+':generateContent';headers['x-goog-api-key']=key;body={systemInstruction:{parts:[{text:messages.filter(m=>m.role==='system').map(m=>m.content).join('\n')}]},contents:messages.filter(m=>m.role==='user').map(m=>({role:'user',parts:[{text:m.content}]})),generationConfig:{temperature:0,maxOutputTokens:512,responseMimeType:'application/json'}}}else{headers.Authorization='Bearer '+key;body={model:p.model,messages,temperature:0,max_tokens:1024,response_format:{type:'json_object'}};if(p.id==='groq')body.reasoning_effort='low'}
 try{const r=await fetcher(url,{method:'POST',redirect:'error',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(Math.min(5000,remaining))});if(!r.ok){await r.body?.cancel();if(r.status===429){providerCooldown.set(p.id,retryUntil(r.headers.get('Retry-After'),Date.now()));continue}if(r.status===401){keyCooldown.set(createHash('sha256').update(key).digest('hex'),Date.now()+3600000);providerCooldown.set(p.id,Date.now()+30000);continue}providerCooldown.set(p.id,Date.now()+(r.status===403?3600000:30000));continue}const raw=responseText(await limitedJson(r),p.kind==='gemini');const intent=intentSchema.parse(JSON.parse(raw.replace(/^```(?:json)?\s*|\s*```$/g,'').trim()));return {intent,provider:p.id,model:p.model};}catch{providerCooldown.set(p.id,Date.now()+30000);}}
 // Preserve the previous single-provider configuration only when no registry is installed.
 if(!ps.length){const r=await compatibleCompletion(c,messages,v=>intentSchema.parse(v),fetcher,now);return r?{intent:r.value,provider:r.provider,model:r.model}:null;}
 return null;
}
// Used only by unit tests to isolate in-memory circuit state; contains no credentials.
export function resetProviderCircuits(){providerCooldown.clear();keyCooldown.clear();cached=undefined;resetCompatibleCircuits()}

export function containsProviderCredential(c:Config,message:string){return !!c.LLM_API_KEY&&message.includes(c.LLM_API_KEY)||configured(c).some(p=>p.keys.some(key=>message.includes(key)))}

const coachSchema=z.object({answer:z.string().min(1).max(1800),suggestions:z.array(z.string().min(1).max(500)).min(1).max(5)}).strict();
export async function completeCoach(c:Config,messages:Message[],fetcher:typeof fetch=fetch,now=Date.now()):Promise<{value:{answer:string;suggestions:string[]};provider:string;model:string}|null>{const ps=configured(c),deadline=now+12000;for(const p of ps){if(Math.max(providerCooldown.get(p.id)??0,p.initialCooldownUntil??0)>Date.now())continue;const key=p.keys.find(k=>(keyCooldown.get(createHash('sha256').update(k).digest('hex'))??0)<Date.now());if(!key)continue;const remaining=deadline-Date.now();if(remaining<500)break;let url=p.url,body:Record<string,unknown>,headers:Record<string,string>={'Content-Type':'application/json'};if(p.kind==='gemini'){url+='/models/'+encodeURIComponent(p.model)+':generateContent';headers['x-goog-api-key']=key;body={systemInstruction:{parts:[{text:messages.filter(m=>m.role==='system').map(m=>m.content).join('\n')}]},contents:messages.filter(m=>m.role==='user').map(m=>({role:'user',parts:[{text:m.content}]})),generationConfig:{temperature:0,maxOutputTokens:512,responseMimeType:'application/json'}}}else{headers.Authorization='Bearer '+key;body={model:p.model,messages,temperature:0,max_tokens:1024,response_format:{type:'json_object'}};if(p.id==='groq')body.reasoning_effort='low'}
 try{const r=await fetcher(url,{method:'POST',redirect:'error',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(Math.min(5000,remaining))});if(!r.ok){await r.body?.cancel();if(r.status===429){providerCooldown.set(p.id,retryUntil(r.headers.get('Retry-After'),Date.now()));continue}if(r.status===401){keyCooldown.set(createHash('sha256').update(key).digest('hex'),Date.now()+3600000);providerCooldown.set(p.id,Date.now()+30000);continue}providerCooldown.set(p.id,Date.now()+(r.status===403?3600000:30000));continue}const raw=responseText(await limitedJson(r),p.kind==='gemini');const value=coachSchema.parse(JSON.parse(raw.replace(/^```(?:json)?\s*|\s*```$/g,'').trim()));return {value,provider:p.id,model:p.model};}catch{providerCooldown.set(p.id,Date.now()+30000);}}
 // Preserve the previous single-provider configuration only when no registry is installed.
 if(!ps.length)return compatibleCompletion(c,messages,v=>coachSchema.parse(v),fetcher,now);
 return null;
}

export const operatorStepSchema=z.object({tool:z.enum(['account.balance','budget.read','catalog.search','catalog.options','checkout.quote','finish']),query:z.string().max(120).optional(),productId:z.string().max(100).optional(),itemId:z.string().max(100).optional(),quantity:z.number().int().min(1).max(10).optional(),reason:z.string().min(1).max(500)}).strict();
export type OperatorStep=z.infer<typeof operatorStepSchema>;
export async function completeToolStep(c:Config,messages:Message[],fetcher:typeof fetch=fetch,now=Date.now()):Promise<{value:OperatorStep;provider:string;model:string}|null>{const ps=configured(c),deadline=now+12000;for(const p of ps){if(Math.max(providerCooldown.get(p.id)??0,p.initialCooldownUntil??0)>Date.now())continue;const key=p.keys.find(k=>(keyCooldown.get(createHash('sha256').update(k).digest('hex'))??0)<Date.now());if(!key)continue;const remaining=deadline-Date.now();if(remaining<500)break;let url=p.url,body:Record<string,unknown>,headers:Record<string,string>={'Content-Type':'application/json'};if(p.kind==='gemini'){url+='/models/'+encodeURIComponent(p.model)+':generateContent';headers['x-goog-api-key']=key;body={systemInstruction:{parts:[{text:messages.filter(m=>m.role==='system').map(m=>m.content).join('\n')}]},contents:messages.filter(m=>m.role==='user').map(m=>({role:'user',parts:[{text:m.content}]})),generationConfig:{temperature:0,maxOutputTokens:512,responseMimeType:'application/json'}}}else{headers.Authorization='Bearer '+key;body={model:p.model,messages,temperature:0,max_tokens:1024,response_format:{type:'json_object'}};if(p.id==='groq')body.reasoning_effort='low'}
 try{const r=await fetcher(url,{method:'POST',redirect:'error',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(Math.min(5000,remaining))});if(!r.ok){await r.body?.cancel();if(r.status===429){providerCooldown.set(p.id,retryUntil(r.headers.get('Retry-After'),Date.now()));continue}if(r.status===401){keyCooldown.set(createHash('sha256').update(key).digest('hex'),Date.now()+3600000);providerCooldown.set(p.id,Date.now()+30000);continue}providerCooldown.set(p.id,Date.now()+(r.status===403?3600000:30000));continue}const raw=responseText(await limitedJson(r),p.kind==='gemini');const value=operatorStepSchema.parse(JSON.parse(raw.replace(/^```(?:json)?\s*|\s*```$/g,'').trim()));return {value,provider:p.id,model:p.model};}catch{providerCooldown.set(p.id,Date.now()+30000);}}
 // Preserve the previous single-provider configuration only when no registry is installed.
 if(!ps.length)return compatibleCompletion(c,messages,v=>operatorStepSchema.parse(v),fetcher,now);
 return null;
}
