import {z} from 'zod';import {generateReceiptProof,type WitnessPorts} from './receipt-proof-generator.js';
const hash=z.string().regex(/^0x[\da-f]{64}$/i),address=z.string().regex(/^0x[\da-f]{40}$/i);
export const pilotManifestSchema=z.object({schemaVersion:z.literal(1),network:z.literal('arc-testnet'),businessReference:z.string().min(4).max(100),synthetic:z.literal(false),consent:z.object({reference:z.string().min(8).max(150),recordedAt:z.string().datetime(),ownerAttested:z.literal(true),publishReceiptLinks:z.literal(true)}).strict(),events:z.array(z.object({externalEventId:z.string().min(1).max(100),kind:z.literal('business-operational-mirror'),category:z.enum(['Gaming Keys & Platform Vouchers','Streaming & Media Subscriptions','Creator & Game Micro-Donations','Developer API & Token Bundles','Cloud Compute & GPU Vouchers']),occurredAt:z.string().datetime(),sourceDigest:z.string().regex(/^[\da-f]{64}$/i),amountMicro:z.string().regex(/^[1-9]\d{0,11}$/),txHash:hash,sender:address,recipient:address}).strict()).min(1).max(100)}).strict();
export async function verifyPilotEvidence(raw:unknown,witnesses:{primaryWitness:WitnessPorts;secondaryWitness:WitnessPorts},excludedHashes:ReadonlySet<string>=new Set(),now=Date.now()){
 const input=pilotManifestSchema.parse(raw);if(Date.parse(input.consent.recordedAt)>now)throw Error('FUTURE_CONSENT_INVALID');
 const seenEvents=new Set<string>(),seenHashes=new Set<string>();const verified=[];
 for(const event of input.events){const key=event.txHash.toLowerCase();if(seenEvents.has(event.externalEventId)||seenHashes.has(key))throw Error('DUPLICATE_PILOT_EVIDENCE');if(excludedHashes.has(key))throw Error('PLATFORM_FUNDING_IS_NOT_BUSINESS_PILOT');if(Date.parse(event.occurredAt)>now||Date.parse(event.occurredAt)<Date.parse(input.consent.recordedAt))throw Error('EVENT_OUTSIDE_CONSENT_WINDOW');seenEvents.add(event.externalEventId);seenHashes.add(key);
 const proof=await generateReceiptProof({hash:event.txHash,expectedSender:event.sender,expectedRecipient:event.recipient,expectedAmountMicro:BigInt(event.amountMicro),chainId:5042002,minConfirmations:2,assetKind:'erc20'},witnesses);if(proof.status!=='VERIFIED')throw Error('PILOT_SETTLEMENT_NOT_VERIFIED');verified.push({externalEventId:event.externalEventId,sourceDigest:event.sourceDigest,amountMicro:event.amountMicro,txHash:proof.hash,confirmations:proof.confirmations,verificationDigest:proof.evidenceDigest});
 }
 return {schemaVersion:1,status:'OWNER_ATTESTED_LOGS_WITH_VERIFIED_TESTNET_RECEIPTS',businessIdentityValidation:'OWNER_ATTESTED_NOT_INDEPENDENTLY_VERIFIED',network:'arc-testnet',consentReference:input.consent.reference,synthetic:false,verifiedEventCount:verified.length,totalTestnetVolumeMicro:verified.reduce((sum,v)=>sum+BigInt(v.amountMicro),0n).toString(),realRevenueUsd:'0.000000',mainnetEnabled:false,events:verified};
}
