import {PublicCommerceApi} from './fulfillment/public-commerce-api.js';import {z} from 'zod';import type {DB} from '../db.js';import type {Config} from '../config.js';import {parseMoney} from '../money.js';
export const MIN_PROCUREMENT_USD=10000000n,REOPEN_PROCUREMENT_USD=12000000n,MAX_BALANCE_AGE_MS=30000;
export const creditSchema=z.object({currency:z.literal('USD'),available:z.string().regex(/^(0|[1-9]\d{0,9})(\.\d{1,6})?$/),observedAt:z.number().int().nonnegative()}).strict();
export function initProcurementHealth(db:DB){db.exec(`CREATE TABLE IF NOT EXISTS procurement_health(id INTEGER PRIMARY KEY CHECK(id=1),available_units TEXT,observed_at INTEGER NOT NULL,latched INTEGER NOT NULL,reason TEXT NOT NULL);CREATE TABLE IF NOT EXISTS procurement_reservations(ref TEXT PRIMARY KEY,cost_units TEXT NOT NULL,created_at INTEGER NOT NULL);`)}
export function recordProcurementHealth(db:DB,raw:unknown,now=Date.now()){initProcurementHealth(db);const old=db.prepare('SELECT latched,observed_at,available_units FROM procurement_health WHERE id=1').get() as {latched:number;observed_at:number;available_units:string|null}|undefined;const v=creditSchema.safeParse(raw);if(v.success&&old?.available_units!==null&&old?.available_units!==undefined&&v.data.observedAt<old.observed_at)return procurementHealth(db,now);let units:bigint|null=null,reason='BALANCE_UNVERIFIED',latched=old?.latched??0;if(v.success&&v.data.observedAt<=now+5000&&now-v.data.observedAt<=MAX_BALANCE_AGE_MS){units=parseMoney(v.data.available);if(units<MIN_PROCUREMENT_USD){latched=1;reason='SERVICE_FUNDS_LOW'}else if(latched&&units<REOPEN_PROCUREMENT_USD){reason='SERVICE_FUNDS_RECOVERING'}else{latched=0;reason='READY'}}db.prepare('INSERT INTO procurement_health VALUES(1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET available_units=excluded.available_units,observed_at=excluded.observed_at,latched=excluded.latched,reason=excluded.reason').run(units?.toString()??null,v.success?v.data.observedAt:now,latched,reason);return procurementHealth(db,now)}
export function procurementHealth(db:DB,now=Date.now()){initProcurementHealth(db);const r=db.prepare('SELECT * FROM procurement_health WHERE id=1').get() as {available_units:string|null;observed_at:number;latched:number;reason:string}|undefined;const fresh=!!r&&r.observed_at<=now+5000&&now-r.observed_at<=MAX_BALANCE_AGE_MS;const held=(db.prepare('SELECT cost_units FROM procurement_reservations').all() as {cost_units:string}[]).reduce((n,x)=>n+BigInt(x.cost_units),0n);const usable=fresh&&r?.available_units!==null&&r?.available_units!==undefined?BigInt(r.available_units)-held:null;return {availableUnits:usable===null?null:(usable>0n?usable:0n).toString(),checkedAt:r?.observed_at??null,reason:!fresh?'BALANCE_UNVERIFIED':usable!==null&&usable<MIN_PROCUREMENT_USD?'SERVICE_FUNDS_LOW':r!.reason,open:!!fresh&&r!.reason==='READY'&&!r!.latched&&usable!==null&&usable>=MIN_PROCUREMENT_USD,thresholdUnits:MIN_PROCUREMENT_USD.toString()}}
export async function refreshProcurementHealth(db:DB,c:Config,fetcher:typeof fetch=fetch){if(!c.SUPPLIER_API_URL||!c.SUPPLIER_API_KEY||!c.SUPPLIER_BALANCE_PATH)return recordProcurementHealth(db,null);const u=new URL(c.SUPPLIER_API_URL);if(u.origin!=='https://approute.io'||u.username||u.password||u.search)return recordProcurementHealth(db,null);try{if(c.SUPPLIER_BALANCE_PATH==='/api/v1/accounts'){const cash=await new PublicCommerceApi(c.SUPPLIER_API_KEY,fetcher).procurementCashUsd();const n=BigInt(cash.availableUnits);return recordProcurementHealth(db,{currency:'USD',available:""+n/1000000n+'.'+(n%1000000n).toString().padStart(6,'0'),observedAt:cash.observedAt})}const res=await fetcher(new URL(c.SUPPLIER_BALANCE_PATH,u.origin),{headers:{'X-API-Key':c.SUPPLIER_API_KEY,Accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(6000)});if(!res.ok){await res.body?.cancel();return recordProcurementHealth(db,null)}const reader=res.body?.getReader();if(!reader)return recordProcurementHealth(db,null);let text='',size=0;const decoder=new TextDecoder();for(;;){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>8192){await reader.cancel();return recordProcurementHealth(db,null)}text+=decoder.decode(value,{stream:true})}text+=decoder.decode();return recordProcurementHealth(db,creditSchema.parse(JSON.parse(text)))}catch{return recordProcurementHealth(db,null)}}
export function requireProcurementFunds(db:DB,costUsdUnits:string,now=Date.now()){if(!/^[1-9]\d{0,14}$/.test(costUsdUnits))throw Error('PROCUREMENT_COST_UNVERIFIED');const h=procurementHealth(db,now);if(!h.open||h.availableUnits===null)throw Error('SERVICE_PURCHASES_PAUSED');if(BigInt(h.availableUnits)-BigInt(costUsdUnits)<MIN_PROCUREMENT_USD)throw Error('SERVICE_RESERVE_LIMIT');return h}
export function publicProcurementHealth(db:DB,c:Config,executionReady=false){const h=procurementHealth(db);const contract=executionReady&&c.ENABLE_FULFILLMENT==='true'&&c.FULFILLMENT_CONTRACT_VERIFIED==='true';return {realPurchasesEnabled:contract&&h.open,lotsEnabled:contract&&h.open,state:contract&&h.open?'available':'paused',message:contract&&h.open?'Purchases available after current funding and integration verification.':'Purchases are temporarily unavailable. Browse the catalogue or use the separate testnet rehearsal.',testnetRehearsalEnabled:true,checkedAt:h.checkedAt,balanceVerified:h.availableUnits!==null,mainnetEnabled:false}}
export function startProcurementMonitor(db:DB,c:Config){initProcurementHealth(db);if(!c.SUPPLIER_BALANCE_PATH)return ()=>{};let running=false;const tick=async()=>{if(running)return;running=true;try{await refreshProcurementHealth(db,c)}finally{running=false}};void tick().catch(()=>{});const timer=setInterval(()=>void tick().catch(()=>{}),15000);timer.unref();return ()=>clearInterval(timer)}

// Uncertain procurement keeps its reserve. A timeout is never permission to reuse funds or POST a replacement order.
export function reserveProcurement(db:DB,ref:string,costUsdUnits:string,now=Date.now()){initProcurementHealth(db);if(!/^[a-zA-Z0-9_-]{8,128}$/.test(ref))throw Error('PROCUREMENT_REFERENCE_INVALID');return db.transaction(()=>{const old=db.prepare('SELECT cost_units FROM procurement_reservations WHERE ref=?').get(ref) as {cost_units:string}|undefined;if(old){if(old.cost_units!==costUsdUnits)throw Error('IDEMPOTENCY_CONFLICT');return false}const h=requireProcurementFunds(db,costUsdUnits,now);const rows=db.prepare('SELECT cost_units FROM procurement_reservations').all() as {cost_units:string}[];if(rows.length>=1000)throw Error('PROCUREMENT_REVIEW_REQUIRED');if(BigInt(h.availableUnits!)-BigInt(costUsdUnits)<MIN_PROCUREMENT_USD)throw Error('SERVICE_RESERVE_LIMIT');db.prepare('INSERT INTO procurement_reservations VALUES(?,?,?)').run(ref,costUsdUnits,now);return true})()}
