import {createHash} from 'node:crypto';
export type TxReceipt={status:'0x1'|'0x0'|number;blockNumber:bigint;blockHash:string;from:string;to:string;logs?:{address:string;data:string;topics:string[]}[]};
export type TxData={hash:string;from:string;to:string;value:bigint;chainId:number};
export type WitnessPorts={name:string;endpoint:string;getChainId:()=>Promise<number>;getTransaction:(hash:string)=>Promise<TxData|null>;getReceipt:(hash:string)=>Promise<TxReceipt|null>;getBlock:(height:string|bigint)=>Promise<{hash:string;number:bigint;timestamp?:bigint}|null>;getHead:()=>Promise<bigint>};
export type DualWitnessPorts={primaryWitness:WitnessPorts;secondaryWitness:WitnessPorts};
export type ReceiptProofInput={hash:string;expectedSender:string;expectedRecipient:string;expectedAmountMicro:bigint;chainId?:number;minConfirmations?:number;assetKind?:'erc20'|'native'};
export type ProofStatus='VERIFIED'|'REJECTED'|'UNAVAILABLE';
export type ReceiptProofResult={status:ProofStatus;hash:string;chainId:number;confirmations:number;evidenceDigest:string;markdownSummary:string;reason?:string;witnessA:string;witnessB:string};
const TOKEN='0x3600000000000000000000000000000000000000',TRANSFER='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',address=/^0x[\da-f]{40}$/i,hash32=/^0x[\da-f]{64}$/i,UINT256=(1n<<256n)-1n;
const lower=(s:string)=>s.toLowerCase();
function endpointHost(endpoint:string){try{const u=new URL(endpoint);return u.protocol==='https:'?u.hostname.toLowerCase():null}catch{return null}}
function transferAmount(receipt:TxReceipt,input:ReceiptProofInput){let sum=0n,count=0;for(const log of receipt.logs??[]){if(lower(log.address)!==TOKEN||lower(log.topics[0]??'')!==TRANSFER)continue;if(log.topics.length!==3||!hash32.test(log.data)||!log.topics.every(t=>hash32.test(t))||!/^0x0{24}/i.test(log.topics[1]??'')||!/^0x0{24}/i.test(log.topics[2]??''))throw Error('MALFORMED_TRANSFER_LOG');const sender='0x'+(log.topics[1]??'').slice(-40),recipient='0x'+(log.topics[2]??'').slice(-40);if(lower(sender)===lower(input.expectedSender)&&lower(recipient)===lower(input.expectedRecipient)){sum+=BigInt(log.data);count++}}return {sum,count}}
async function withDeadline<T>(work:Promise<T>):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([work,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(Error('RPC_TIMEOUT')),5000)})])}finally{if(timer)clearTimeout(timer)}}
/** Pure verification only. Endpoint diversity is a configuration check, not proof of independent providers. */
export async function generateReceiptProof(input:ReceiptProofInput,ports:DualWitnessPorts):Promise<ReceiptProofResult>{
 const chainId=input.chainId??5042002,min=input.minConfirmations??2,kind=input.assetKind??'erc20',a=ports.primaryWitness,b=ports.secondaryWitness;
 const result=(status:ProofStatus,reason?:string,confirmations=0,observed?:unknown):ReceiptProofResult=>{const evidence={version:2,status,chainId,hash:input.hash,sender:input.expectedSender,recipient:input.expectedRecipient,amountMicro:String(input.expectedAmountMicro),assetKind:kind,token:kind==='erc20'?TOKEN:null,confirmations,reason,observed};return {status,hash:input.hash,chainId,confirmations,reason,witnessA:a.name,witnessB:b.name,evidenceDigest:createHash('sha256').update(JSON.stringify(evidence)).digest('hex'),markdownSummary:status==='VERIFIED'?`| Network | Transaction | Amount (test USDC) | Confirmations | Evidence |\n|---|---|---|---|---|\n| Arc Testnet | [${input.hash}](https://testnet.arcscan.app/tx/${input.hash}) | ${input.expectedAmountMicro/1000000n}.${(input.expectedAmountMicro%1000000n).toString().padStart(6,'0')} | ${confirmations} | CANONICAL_CONSENSUS_VERIFIED |`:`No verified settlement: ${reason??status}.`}};
 if(chainId!==5042002)return result('REJECTED','UNSUPPORTED_CHAIN');
 if(!hash32.test(input.hash)||!address.test(input.expectedSender)||!address.test(input.expectedRecipient)||typeof input.expectedAmountMicro!=='bigint'||input.expectedAmountMicro<=0n||input.expectedAmountMicro>UINT256||!Number.isSafeInteger(min)||min<2||!['erc20','native'].includes(kind))return result('REJECTED','INVALID_PROOF_INPUT');
 const hostA=endpointHost(a.endpoint),hostB=endpointHost(b.endpoint);if(!hostA||!hostB)return result('UNAVAILABLE','WITNESS_ENDPOINT_METADATA_REQUIRED');if(a===b||a.name===b.name||hostA===hostB)return result('UNAVAILABLE','IDENTICAL_RPC_ENDPOINTS_REJECTED');
 try{
  const [ca,cb,ta,tb,ra,rb,ha,hb]=await withDeadline(Promise.all([a.getChainId(),b.getChainId(),a.getTransaction(input.hash),b.getTransaction(input.hash),a.getReceipt(input.hash),b.getReceipt(input.hash),a.getHead(),b.getHead()]));
  if(ca!==chainId||cb!==chainId)return result('REJECTED','WRONG_CHAIN_ID');if(!ta||!tb||!ra||!rb)return result('UNAVAILABLE','TRANSACTION_OR_RECEIPT_NOT_FOUND');
  if(lower(ra.blockHash)!==lower(rb.blockHash))return result('REJECTED','WITNESS_BLOCK_HASH_MISMATCH');
  if(ra.blockNumber!==rb.blockNumber)return result('REJECTED','WITNESS_BLOCK_NUMBER_MISMATCH');
  if(![ra.status,rb.status].every(s=>s===1||s==='0x1'))return result('REJECTED','TRANSACTION_REVERTED');
  if(!hash32.test(ra.blockHash)||ra.blockNumber<0n||ha<ra.blockNumber||hb<ra.blockNumber)return result('REJECTED','INVALID_BLOCK_HEIGHT');
  for(const [t,r] of [[ta,ra],[tb,rb]] as const){if(!hash32.test(t.hash)||lower(t.hash)!==lower(input.hash)||t.chainId!==chainId||!address.test(t.from)||!address.test(t.to)||lower(t.from)!==lower(r.from)||lower(t.to)!==lower(r.to)||t.value<0n||t.value>UINT256)return result('REJECTED','TRANSACTION_IDENTITY_MISMATCH')}
  if(lower(ta.from)!==lower(tb.from)||lower(ta.to)!==lower(tb.to)||ta.value!==tb.value)return result('REJECTED','WITNESS_TRANSACTION_MISMATCH');
  const [ba,bb]=await withDeadline(Promise.all([a.getBlock(ra.blockNumber),b.getBlock(rb.blockNumber)]));if(!ba||!bb)return result('UNAVAILABLE','CANONICAL_BLOCK_UNAVAILABLE');if(ba.number!==ra.blockNumber||bb.number!==rb.blockNumber||lower(ba.hash)!==lower(ra.blockHash)||lower(bb.hash)!==lower(rb.blockHash))return result('REJECTED','NON_CANONICAL_RECEIPT');
  const confBig=(ha<hb?ha:hb)-ra.blockNumber+1n;if(confBig>BigInt(Number.MAX_SAFE_INTEGER))return result('REJECTED','INVALID_CONFIRMATIONS');const conf=Number(confBig);if(conf<min)return result('UNAVAILABLE','INSUFFICIENT_CONFIRMATIONS',conf);
  if(kind==='native'){if(lower(ta.from)!==lower(input.expectedSender)||lower(ta.to)!==lower(input.expectedRecipient))return result('REJECTED','SENDER_OR_RECIPIENT_MISMATCH',conf);if(ta.value!==input.expectedAmountMicro*1000000000000n)return result('REJECTED','AMOUNT_MISMATCH',conf)}else{const aa=transferAmount(ra,input),ab=transferAmount(rb,input);if(!aa.count||!ab.count)return result('REJECTED','SENDER_OR_RECIPIENT_MISMATCH',conf);if(aa.sum!==ab.sum||aa.count!==ab.count)return result('REJECTED','WITNESS_TRANSFER_MISMATCH',conf);if(aa.sum!==input.expectedAmountMicro)return result('REJECTED','AMOUNT_MISMATCH',conf)}
  return result('VERIFIED',undefined,conf,{blockHash:lower(ra.blockHash),blockNumber:String(ra.blockNumber),transactionFrom:lower(ta.from),transactionTo:lower(ta.to),transactionValue:String(ta.value),witnessHosts:[hostA,hostB]});
 }catch{return result('UNAVAILABLE','RPC_FETCH_ERROR_OR_MALFORMED_EVIDENCE')}
}
