import type {WitnessPorts,TxData,TxReceipt} from './receipt-proof-generator.js';
const HEX=/^0x[\da-f]{1,64}$/i,ADDR=/^0x[\da-f]{40}$/i;
const numberHex=(v:unknown)=>{if(typeof v!=='string'||!HEX.test(v))throw Error('RPC_INVALID_INTEGER');return BigInt(v)};
const text=(v:unknown)=>{if(typeof v!=='string')throw Error('RPC_INVALID_STRING');return v};
/** Read-only JSON-RPC adapter: no signing, broadcasts, wallet keys or vendor credentials. */
export function createReceiptRpcWitness(name:string,endpoint:string,fetcher:typeof fetch=fetch):WitnessPorts{
 const url=new URL(endpoint);if(url.protocol!=='https:'||url.username||url.password)throw Error('INVALID_RPC_ENDPOINT');let sequence=0;
 async function rpc(method:string,params:unknown[]=[]):Promise<any>{const id=++sequence;const response=await fetcher(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id,method,params}),redirect:'error',signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error('RPC_HTTP_ERROR');const reader=response.body?.getReader();if(!reader)throw Error('RPC_EMPTY_RESPONSE');let size=0,body='';const decoder=new TextDecoder();for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>131072){await reader.cancel();throw Error('RPC_RESPONSE_TOO_LARGE')}body+=decoder.decode(value,{stream:true})}body+=decoder.decode();const result=JSON.parse(body);if(result.jsonrpc!=='2.0'||result.id!==id||result.error||!Object.prototype.hasOwnProperty.call(result,'result'))throw Error('RPC_INVALID_ENVELOPE');return result.result}
 const chain=async()=>{const n=numberHex(await rpc('eth_chainId'));if(n>BigInt(Number.MAX_SAFE_INTEGER))throw Error('RPC_INVALID_CHAIN_ID');return Number(n)};
 return {name,endpoint,getChainId:chain,getHead:async()=>numberHex(await rpc('eth_blockNumber')),getTransaction:async(hash):Promise<TxData|null>=>{const tx=await rpc('eth_getTransactionByHash',[hash]);if(!tx)return null;if(!ADDR.test(tx.from)||!ADDR.test(tx.to))throw Error('RPC_INVALID_TRANSACTION');return {hash:text(tx.hash),from:tx.from,to:tx.to,value:numberHex(tx.value),chainId:tx.chainId?Number(numberHex(tx.chainId)):await chain()}},getReceipt:async(hash):Promise<TxReceipt|null>=>{const r=await rpc('eth_getTransactionReceipt',[hash]);if(!r)return null;if(typeof r.transactionHash!=='string'||r.transactionHash.toLowerCase()!==hash.toLowerCase())throw Error('RPC_RECEIPT_HASH_MISMATCH');if(!Array.isArray(r.logs)||r.logs.some((l:any)=>l.removed===true||!Array.isArray(l.topics)))throw Error('RPC_INVALID_LOGS');return {status:Number(numberHex(r.status)),blockNumber:numberHex(r.blockNumber),blockHash:text(r.blockHash),from:text(r.from),to:text(r.to),logs:r.logs.map((l:any)=>({address:text(l.address),data:text(l.data),topics:l.topics.map(text)}))}},getBlock:async(height)=>{const b=await rpc(typeof height==='bigint'?'eth_getBlockByNumber':'eth_getBlockByHash',[typeof height==='bigint'?'0x'+height.toString(16):height,false]);return b?{hash:text(b.hash),number:numberHex(b.number)}:null}};
}
