import type {FastifyInstance,FastifyRequest} from 'fastify';import type {DB} from '../db.js';import type {Config} from '../config.js';import {accountActor} from '../routes/account.js';
import {TemporaryStores,snapshotKey,type Snapshot} from './temp-stores.js';import {memoryState,canMutate} from './runtime.js';
export const SNAPSHOT_ROUTES=new Set(['summary','dashboard','funds','orders','transactions','settings']);
export function snapshotRoute(url:string){const p=url.split('?')[0]??'';const m=/^\/api\/account\/([a-z]+)$/.exec(p);return m&&SNAPSHOT_ROUTES.has(m[1]!)?true:false;}
export function staleBody(s:Snapshot){return {...s.body,stale:true,readOnly:true,asOf:new Date(s.asOf).toISOString(),authority:'SNAPSHOT_NOT_SETTLEMENT'};}
export function registerResilience(app:FastifyInstance,db:DB,c:Config){
 db.pragma('cache_size = -8192');db.exec('CREATE TABLE IF NOT EXISTS read_snapshots(cache_key TEXT PRIMARY KEY,body TEXT NOT NULL,as_of INTEGER NOT NULL)');
 const stores=new TemporaryStores(c);let active=0,running=false;const admitted=new WeakSet<FastifyRequest>();const queue:{key:string;s:Snapshot}[]=[];
 const drain=async()=>{if(running)return;running=true;try{while(queue.length){const item=queue.shift()!;await stores.put(item.key,item.s);}}finally{running=false}};
 app.addHook('onRequest',async(req,reply)=>{if(active>=(c.MAX_INFLIGHT_REQUESTS??32)){return reply.code(503).header('Retry-After','15').send({code:'BACKEND_BUSY',readOnly:true,authority:'NO_SETTLEMENT_REPORTED'})}active++;admitted.add(req);const m=memoryState(c);if(!canMutate(req.method,m.pressured))return reply.code(503).header('Retry-After','15').send({code:'MEMORY_PRESSURE_READ_ONLY',readOnly:true,authority:'NO_SETTLEMENT_REPORTED'});});
 app.addHook('preHandler',async(req,reply)=>{if(req.method!=='GET'||!snapshotRoute(req.url)||!memoryState(c).pressured)return;const actor=accountActor(req,c),key=snapshotKey(actor,req.url);const local=db.prepare('SELECT body,as_of FROM read_snapshots WHERE cache_key=? AND as_of>?').get(key,Date.now()-3600000) as {body:string;as_of:number}|undefined;const snapshot=local?{body:JSON.parse(local.body),asOf:local.as_of}:await stores.get(key);if(snapshot)return reply.header('Cache-Control','no-store').send(staleBody(snapshot));return reply.code(503).header('Retry-After','15').send({code:'READ_ONLY_SNAPSHOT_UNAVAILABLE',readOnly:true});});
 app.addHook('onSend',async(req,reply,payload)=>{if(req.method==='GET'&&reply.statusCode===200&&snapshotRoute(req.url)&&typeof payload==='string'&&payload.length<262144){try{const actor=String(req.headers['x-mercenta-actor']??'');if(!/^wallet:0x[a-f0-9]{40}$/.test(actor))return payload;const body=JSON.parse(payload);if(body.stale)return payload;const s={body,asOf:Date.now()},key=snapshotKey(actor,req.url);db.prepare('INSERT INTO read_snapshots VALUES(?,?,?) ON CONFLICT(cache_key) DO UPDATE SET body=excluded.body,as_of=excluded.as_of').run(key,payload,s.asOf);if(queue.length<16){queue.push({key,s});void drain()}}catch{/* Snapshots cannot roll back a successful account read. */}}return payload;});
 const release=(req:FastifyRequest)=>{if(admitted.has(req)){admitted.delete(req);active=Math.max(0,active-1)}};app.addHook('onResponse',async(req)=>release(req));app.addHook('onTimeout',async(req)=>release(req));app.addHook('onRequestAbort',async(req)=>release(req));
 const cleanup=setInterval(()=>{try{db.prepare('DELETE FROM read_snapshots WHERE as_of<?').run(Date.now()-3600000)}catch{/* SQLite owns authoritative records; cleanup is noncritical. */}},3600000);cleanup.unref();
 app.get('/api/resilience/status',()=>({...memoryState(c),inflight:active,temporary:stores.status(),supervisor:'systemd-on-vps',snapshots:'read-only-with-one-hour-maximum-age'}));
 app.addHook('onClose',async()=>{clearInterval(cleanup);queue.length=0;await stores.close()});
 return stores;
}
