import {redactSupplierIdentity,supplierEndpoint} from './supplier-endpoint.js';
import type {Config} from '../config.js';
import {z} from 'zod';
const item=z.object({id:z.union([z.string(),z.number()]).transform(String),name:z.string().max(250).optional(),nominal:z.number().optional(),price:z.number().finite().nonnegative(),currency:z.string().regex(/^[A-Z]{3,6}$/),inStock:z.number().int().nonnegative().optional(),available:z.boolean().optional(),stock:z.number().int().nonnegative().optional(),isLongOrder:z.boolean().optional()});
const product=z.object({id:z.union([z.string(),z.number()]).transform(String),name:z.string().min(1).max(250),type:z.string().max(50).optional(),countryCode:z.string().max(20).optional(),categoryName:z.string().max(100).optional(),subcategoryName:z.string().max(100).nullish().transform(v=>v??undefined),imageUrl:z.string().max(2048).optional(),image:z.string().max(2048).optional(),items:z.array(item).max(1000)});
export type SupplierPreview=Awaited<ReturnType<typeof supplierPreview>>;
export async function supplierPreview(c:Config,fetcher:typeof fetch=fetch){
 const base={supplier:'Mercenta catalogue',purchasingEnabled:false,coverage:'unverified',fetchedAt:new Date().toISOString()};
 const empty=(status:string)=>({...base,status,products:[] as z.infer<typeof product>[],httpStatus:null as number|null});
 if(!c.SUPPLIER_API_URL||!c.SUPPLIER_API_KEY)return empty('unconfigured');
 let u:URL;try{u=supplierEndpoint(c.SUPPLIER_API_URL,c.SUPPLIER_ALLOWED_ORIGIN)}catch{return empty('invalid-config')}
 try{const res=await fetcher(u.href.replace(/\/$/,'')+'/services',{headers:{'X-API-Key':c.SUPPLIER_API_KEY,Accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(8000)});if(!res.ok){await res.body?.cancel();return {...empty(res.status===401||res.status===403?'access-denied':'unavailable'),httpStatus:res.status}}if(Number(res.headers.get('content-length')??0)>4000000){await res.body?.cancel();return empty('invalid-response')}const reader=res.body?.getReader();if(!reader)return empty('invalid-response');const chunks:Uint8Array[]=[];let size=0;for(;;){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>4000000){await reader.cancel();return empty('invalid-response')}chunks.push(value)}const bytes=new Uint8Array(size);let pos=0;for(const a of chunks){bytes.set(a,pos);pos+=a.length}const data=z.object({data:z.object({items:z.array(product).max(10000)})}).safeParse(JSON.parse(new TextDecoder().decode(bytes)));if(!data.success)return empty('invalid-response');const products=data.data.data.items.map(p=>{const clean={...p,name:redactSupplierIdentity(p.name,c),items:p.items.filter(x=>redactSupplierIdentity(x.id,c)===x.id).map(x=>({...x,...(x.name?{name:redactSupplierIdentity(x.name,c)}:{})}))};for(const field of ['categoryName','subcategoryName','type'] as const){const text=clean[field];if(text)clean[field]=redactSupplierIdentity(text,c)}for(const key of ['imageUrl','image'] as const){const raw=clean[key];if(!raw)continue;if(redactSupplierIdentity(raw,c)!==raw){delete clean[key];continue}try{const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password||u.port||!u.hostname.includes('.')||/^(localhost|127\.|10\.|192\.168\.|169\.254\.|0\.|\[)/i.test(u.hostname)||/\.(local|internal|localhost)$/.test(u.hostname)||/^172\.(1[6-9]|2\d|3[01])\./.test(u.hostname)||[...u.searchParams.keys()].some(k=>/key|token|secret|signature|auth/i.test(k)))delete clean[key];}catch{delete clean[key]}}return clean}).filter(p=>redactSupplierIdentity(p.id,c)===p.id);return {...base,status:'ready',products,httpStatus:200};}catch{return empty('unavailable')}
}
let cached:SupplierPreview|undefined;let expires=0;let pending:Promise<SupplierPreview>|undefined;
export function cachedSupplierPreview(c:Config){if(cached&&Date.now()<expires)return Promise.resolve(cached);if(pending)return pending;pending=supplierPreview(c).then(v=>{cached=v;expires=Date.now()+60000;return v}).finally(()=>{pending=undefined});return pending}
