import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import type {DB} from '../db.js';
import {parseMoney} from '../money.js';
import {encryptCode,decryptCode} from './fulfillment/index.js';
export const STEPS=['identity','budget','funds','shop','orders','journal','agent','profit'] as const;
const money=z.string().regex(/^(0|[1-9]\d*)(\.\d{1,6})?$/).max(16);
export const profileInput=z.object({language:z.enum(['en','ru']),role:z.enum(['buyer','reseller']),reviewed:z.array(z.enum(STEPS)).max(8),dismissed:z.boolean()}).strict();
export const budgetInput=z.object({requestId:z.string().uuid(),expectedRevision:z.number().int().min(0),monthly:money,perOrder:money,daily:money,spendBps:z.number().int().min(0).max(10000),reserveBps:z.number().int().min(0).max(10000),profitBps:z.number().int().min(0).max(10000),taxBps:z.number().int().min(0).max(10000)}).strict();
export const journalInput=z.object({requestId:z.string().uuid(),kind:z.enum(['expense','income','note']),amount:money,date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),category:z.enum(['digital-goods','business','personal','fees','other']),title:z.string().trim().min(1).max(120),note:z.string().max(3000)}).strict();
function owner(a:string){if(!/^wallet:0x[a-f0-9]{40}$/.test(a))throw new Error('WALLET_AUTH_REQUIRED')}
export function initWorkspace(db:DB){db.exec(`
 CREATE TABLE IF NOT EXISTS workspace_profiles(actor TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS workspace_budgets(actor TEXT PRIMARY KEY,revision INTEGER NOT NULL,value TEXT NOT NULL,updated_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS workspace_budget_requests(actor TEXT NOT NULL,request_id TEXT NOT NULL,fingerprint TEXT NOT NULL,response TEXT NOT NULL,PRIMARY KEY(actor,request_id));
 CREATE TABLE IF NOT EXISTS finance_notes(id TEXT PRIMARY KEY,actor TEXT NOT NULL,request_id TEXT NOT NULL,fingerprint TEXT NOT NULL,kind TEXT NOT NULL,amount_units TEXT NOT NULL,entry_date TEXT NOT NULL,category TEXT NOT NULL,encrypted_text TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(actor,request_id));
 CREATE INDEX IF NOT EXISTS finance_notes_actor_date ON finance_notes(actor,entry_date,created_at);
 `)}
const defaultProfile={language:'en',role:'buyer',reviewed:[],dismissed:false};
export function profile(db:DB,a:string){owner(a);const r=db.prepare('SELECT value FROM workspace_profiles WHERE actor=?').get(a) as {value:string}|undefined;return r?JSON.parse(r.value):defaultProfile}
export function saveProfile(db:DB,a:string,raw:unknown){owner(a);const v=profileInput.parse(raw);v.reviewed=[...new Set(v.reviewed)];db.prepare('INSERT INTO workspace_profiles VALUES(?,?,?) ON CONFLICT(actor) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').run(a,JSON.stringify(v),Date.now());return v}
export function getBudget(db:DB,a:string){owner(a);const r=db.prepare('SELECT revision,value,updated_at FROM workspace_budgets WHERE actor=?').get(a) as {revision:number;value:string;updated_at:number}|undefined;return r?{...JSON.parse(r.value),revision:r.revision,updatedAt:r.updated_at}:null}
export function saveBudget(db:DB,a:string,raw:unknown){owner(a);const b=budgetInput.parse(raw),fp=createHash('sha256').update(JSON.stringify(b)).digest('hex');if(b.spendBps+b.reserveBps+b.profitBps+b.taxBps!==10000)throw new Error('ALLOCATION_MUST_EQUAL_100_PERCENT');const total=parseMoney(b.monthly),daily=parseMoney(b.daily),cap=parseMoney(b.perOrder),spend=total*BigInt(b.spendBps)/10000n;if(total<=0n||cap<=0n||daily<=0n||daily>spend||cap>daily)throw new Error('BUDGET_LIMITS_INVALID');return db.transaction(()=>{const old=db.prepare('SELECT fingerprint,response FROM workspace_budget_requests WHERE actor=? AND request_id=?').get(a,b.requestId) as {fingerprint:string;response:string}|undefined;if(old){if(old.fingerprint!==fp)throw new Error('IDEMPOTENCY_CONFLICT');return JSON.parse(old.response)}const current=getBudget(db,a);if((current?.revision??0)!==b.expectedRevision)throw new Error('BUDGET_REVISION_CONFLICT');const {requestId,expectedRevision,...value}=b;const response={...value,revision:expectedRevision+1,updatedAt:Date.now()};db.prepare('INSERT INTO workspace_budgets VALUES(?,?,?,?) ON CONFLICT(actor) DO UPDATE SET revision=excluded.revision,value=excluded.value,updated_at=excluded.updated_at').run(a,response.revision,JSON.stringify(value),response.updatedAt);db.prepare('INSERT INTO workspace_budget_requests VALUES(?,?,?,?)').run(a,requestId,fp,JSON.stringify(response));return response})()}
export function budgetUsage(db:DB,a:string,now=Date.now()){owner(a);const date=new Date(now).toISOString().slice(0,10),month=date.slice(0,7);const monthStart=Date.parse(month+'-01T00:00:00Z'),dayStart=Date.parse(date+'T00:00:00Z');const rows=db.prepare('SELECT amount_units,created_at FROM account_orders WHERE actor=? AND created_at>=? AND created_at<=?').all(a,monthStart,now) as {amount_units:string;created_at:number}[];let monthSpent=0n,daySpent=0n;for(const r of rows){monthSpent+=BigInt(r.amount_units);if(r.created_at>=dayStart)daySpent+=BigInt(r.amount_units)}const b=getBudget(db,a),limit=b?parseMoney(b.monthly)*BigInt(b.spendBps)/10000n:null;return {month,day:date,monthSpentUnits:monthSpent.toString(),daySpentUnits:daySpent.toString(),spendLimitUnits:limit?.toString()??null,remainingUnits:limit===null?null:(limit>monthSpent?limit-monthSpent:0n).toString(),scope:'prepaid-shop-orders-only',excludes:'Gateway payments, external wallet transfers and manually declared journal entries'};}
// Invoked inside the same SQLite transaction as the authoritative prepaid debit.
export function checkBudget(db:DB,a:string,amount:bigint,now=Date.now()){const b=getBudget(db,a);if(!b)return;const u=budgetUsage(db,a,now);if(amount>parseMoney(b.perOrder))throw new Error('BUDGET_PER_ORDER_LIMIT');if(BigInt(u.daySpentUnits)+amount>parseMoney(b.daily))throw new Error('BUDGET_DAILY_LIMIT');if(BigInt(u.monthSpentUnits)+amount>BigInt(u.spendLimitUnits!))throw new Error('BUDGET_MONTHLY_LIMIT')}
export function sensitiveText(s:string){return /(?:0x)?[a-f0-9]{64}|(?:gsk_|sk-or-v1-|AIza|AVNS_)[A-Za-z0-9_\-]{12,}|-----BEGIN.*PRIVATE KEY/i.test(s)}
export function addNote(db:DB,a:string,raw:unknown,key:string){owner(a);const b=journalInput.parse(raw),d=new Date(b.date+'T00:00:00Z');if(!Number.isFinite(d.valueOf())||d.toISOString().slice(0,10)!==b.date||b.date>new Date().toISOString().slice(0,10))throw new Error('JOURNAL_DATE_INVALID');if(sensitiveText(b.title+' '+b.note))throw new Error('DO_NOT_STORE_SECRETS');const amount=parseMoney(b.amount);if((b.kind==='note'&&amount!==0n)||(b.kind!=='note'&&amount<=0n))throw new Error('JOURNAL_AMOUNT_INVALID');const fp=createHash('sha256').update(JSON.stringify(b)).digest('hex');return db.transaction(()=>{const old=db.prepare('SELECT * FROM finance_notes WHERE actor=? AND request_id=?').get(a,b.requestId) as NoteRow|undefined;if(old){if(old.fingerprint!==fp)throw new Error('IDEMPOTENCY_CONFLICT');return noteView(old,key)}const count=db.prepare('SELECT count(*) n FROM finance_notes WHERE actor=?').get(a) as {n:number};if(count.n>=5000)throw new Error('JOURNAL_CAPACITY_REACHED');const id=randomUUID(),now=Date.now();db.prepare('INSERT INTO finance_notes VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,a,b.requestId,fp,b.kind,amount.toString(),b.date,b.category,encryptCode(JSON.stringify({title:b.title,note:b.note}),key),now);return noteView(db.prepare('SELECT * FROM finance_notes WHERE id=?').get(id) as NoteRow,key)})()}
type NoteRow={id:string;actor:string;request_id:string;fingerprint:string;kind:string;amount_units:string;entry_date:string;category:string;encrypted_text:string;created_at:number};
function noteView(r:NoteRow,key:string){return {id:r.id,kind:r.kind,amountUnits:r.amount_units,date:r.entry_date,category:r.category,...JSON.parse(decryptCode(r.encrypted_text,key)),createdAt:r.created_at,source:'manually-declared-not-verified-revenue'}}
export function journal(db:DB,a:string,key:string,page=1){owner(a);const total=(db.prepare('SELECT count(*) n FROM finance_notes WHERE actor=?').get(a) as {n:number}).n;const rows=db.prepare('SELECT * FROM finance_notes WHERE actor=? ORDER BY entry_date DESC,created_at DESC,id DESC LIMIT 25 OFFSET ?').all(a,(page-1)*25) as NoteRow[];const month=new Date().toISOString().slice(0,7);const amounts=db.prepare('SELECT kind,amount_units FROM finance_notes WHERE actor=? AND entry_date LIKE ?').all(a,month+'%') as {kind:string;amount_units:string}[];let income=0n,expense=0n;for(const r of amounts){if(r.kind==='income')income+=BigInt(r.amount_units);if(r.kind==='expense')expense+=BigInt(r.amount_units)}return {items:rows.map(r=>noteView(r,key)),total,page,pageSize:25,month,declaredIncomeUnits:income.toString(),declaredExpenseUnits:expense.toString(),authority:'journal-only-no-ledger-mutations'};}
