const {test}=require('node:test'),assert=require('node:assert/strict'),ganache=require('ganache'),fs=require('fs'),path=require('path'),solc=require('solc');
const {createPublicClient,createWalletClient,custom,keccak256,toHex,hashTypedData,encodeFunctionData,decodeEventLog,parseAbi}=require('viem');
const {privateKeyToAccount}=require('viem/accounts');
const C=require('../artifacts/MercentaCheckout.json'),T=require('../artifacts/MockUSDC.json');
const TOKEN='0x3600000000000000000000000000000000000000',ZERO='0x'+'0'.repeat(40),ZERO32='0x'+'0'.repeat(64),SCALE=1000000000000n;
const types={Quote:[['orderId','bytes32'],['buyer','address'],['skuHash','bytes32'],['quantity','uint32'],['unitCostMicro','uint256'],['amountMicro','uint256'],['assetKind','uint8'],['validAfter','uint48'],['deadline','uint48'],['nonce','uint256'],['signerEpoch','uint256']].map(([name,type])=>({name,type}))};
const id=s=>keccak256(toHex(s));let sequence=0;
function compileMock(source,name){const o=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'Mock.sol':{content:'// SPDX-License-Identifier: MIT\npragma solidity 0.8.28;'+source}},settings:{optimizer:{enabled:true,runs:200},evmVersion:'paris',outputSelection:{'*':{'*':['abi','evm.bytecode.object','evm.deployedBytecode.object']}}}}),{import:p=>({contents:fs.readFileSync(path.join(__dirname,'../node_modules',p),'utf8')})}));assert.equal(o.errors?.filter(e=>e.severity==='error').length??0,0);const c=o.contracts['Mock.sol'][name];return {abi:c.abi,bytecode:'0x'+c.evm.bytecode.object,deployedBytecode:'0x'+c.evm.deployedBytecode.object};}
const receiver=()=>compileMock('contract Receiver{bool public rejectFunds;bool public blocked;address public target;bytes public reentry;function configure(address t,bytes calldata d,bool r)external{target=t;reentry=d;rejectFunds=r;}receive()external payable{require(!rejectFunds);if(reentry.length>0){(bool ok,bytes memory why)=target.call(reentry);require(!ok&&bytes4(why)==bytes4(keccak256("ReentrancyGuardReentrantCall()")));blocked=true;}}}','Receiver');
async function fixture(opts={}){
 const provider=ganache.provider({chain:{chainId:opts.chainId??5042},logging:{quiet:true},wallet:{totalAccounts:6}}),p=createPublicClient({transport:custom(provider),cacheTime:0}),accounts=await provider.request({method:'eth_accounts',params:[]});
 const chain={id:opts.chainId??5042,name:'Local isolated EVM, not live Mainnet',nativeCurrency:{name:'USDC',symbol:'USDC',decimals:18},rpcUrls:{default:{http:[]}}};
 const wallets=accounts.map(a=>createWalletClient({account:privateKeyToAccount(provider.getInitialAccounts()[a].secretKey),chain,transport:custom(provider)}));
 await provider.request({method:'evm_setAccountCode',params:[TOKEN,opts.tokenCode??T.deployedBytecode]});
 const deploy=async(artifact,args=[])=>{const x=await p.waitForTransactionReceipt({hash:await wallets[0].deployContract({abi:artifact.abi,bytecode:artifact.bytecode,args,gas:6000000n})});assert.equal(x.status,'success');return x.contractAddress};
 let merchant=accounts[3],signer=accounts[2],R;
 if(opts.receiver){R=receiver();merchant=await deploy(R);}
 if(opts.contractSigner){const a=compileMock('import{ECDSA}from"@openzeppelin/contracts/utils/cryptography/ECDSA.sol";contract Signer{address public immutable key;constructor(address k){key=k;}function isValidSignature(bytes32 h,bytes calldata s)external view returns(bytes4){return ECDSA.recover(h,s)==key?bytes4(0x1626ba7e):bytes4(0xffffffff);}}','Signer');signer=await deploy(a,[accounts[2]]);}
 const router=await deploy(C,[accounts[0],signer,merchant,opts.orderCap??1000000000n,opts.dayCap??10000000000n]);
 const tx=async(fn,args=[],i=0,value=0n,address=router,abi=C.abi)=>{const x=await p.waitForTransactionReceipt({hash:await wallets[i].writeContract({address,abi,functionName:fn,args,value,gas:1000000n})});assert.equal(x.status,'success');return x};
 const read=(fn,args=[])=>p.readContract({address:router,abi:C.abi,functionName:fn,args});
 const reject=(fn,args=[],i=0,value=0n)=>assert.rejects(p.simulateContract({account:accounts[i],address:router,abi:C.abi,functionName:fn,args,value}));
 const token=(fn,args=[],i=0)=>tx(fn,args,i,0n,TOKEN,T.abi);
 await token('mint',[accounts[1],100000000000n]);await token('mint',[merchant,100000000000n]);
 const quote=async(change={})=>{const b=await p.getBlock();const q={orderId:id('order-'+(++sequence)),buyer:accounts[1],skuHash:id('SKU-and-region-commitment'),quantity:1,unitCostMicro:10000000n,amountMicro:10900000n,assetKind:0,validAfter:b.timestamp,deadline:b.timestamp+200n,nonce:BigInt(sequence),signerEpoch:await read('signerEpoch'),...change};return q};
 const domain={name:'MercentaCheckout',version:'1',chainId:5042,verifyingContract:router};
 const sign=(q,i=2,d=domain)=>wallets[i].signTypedData({domain:d,types,primaryType:'Quote',message:q});
 const pay=async(q)=>{const s=await sign(q);if(q.assetKind===0){await token('approve',[router,q.amountMicro],1);return tx('payUSDC',[q,s],1);}return tx('payNativeUSDC',[q,s],1,q.amountMicro*SCALE)};
 return {provider,p,accounts,wallets,router,merchant,signer,R,deploy,tx,read,reject,token,quote,sign,pay,domain,close:()=>provider.disconnect()};
}
async function run(work,opts={}){const f=await fixture(opts);try{return await work(f)}finally{await f.close();}}

test('Mainnet checkout deploys paused with immutable merchant and six-decimal token pins',()=>run(async f=>{assert.equal(await f.read('paused'),true);assert.equal(Number(await f.read('CHAIN_ID')),5042);assert.equal((await f.read('merchant')).toLowerCase(),f.merchant.toLowerCase());const q=await f.quote();await f.reject('payUSDC',[q,await f.sign(q)],1);await f.reject('unpauseSales',[],2);await f.tx('unpauseSales');}));
test('EOA EIP-712 digest matches viem, payment emits canonical order event and forwards exact amount',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote();assert.equal(await f.read('quoteDigest',[q]),hashTypedData({domain:f.domain,types,primaryType:'Quote',message:q}));const before=await f.p.readContract({address:TOKEN,abi:T.abi,functionName:'balanceOf',args:[f.merchant]});const r=await f.pay(q);const events=r.logs.filter(l=>l.address.toLowerCase()===f.router.toLowerCase()).map(l=>decodeEventLog({abi:C.abi,data:l.data,topics:l.topics}));const e=events.find(e=>e.eventName==='OrderPaid');assert.equal(e.args.orderId,q.orderId);assert.equal(e.args.quoteHash,hashTypedData({domain:f.domain,types,primaryType:'Quote',message:q}));assert.equal(e.args.amountMicro,q.amountMicro);assert.equal(await f.read('totalGrossMicro'),q.amountMicro);assert.equal(await f.p.readContract({address:TOKEN,abi:T.abi,functionName:'balanceOf',args:[f.merchant]}),before+q.amountMicro);assert.equal(await f.p.readContract({address:TOKEN,abi:T.abi,functionName:'balanceOf',args:[f.router]}),0n);}));
test('ERC-1271 quote signer accepts only its valid typed signature',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote();await f.reject('payUSDC',[q,await f.sign(q,4)],1);await f.pay(q);},{contractSigner:true}));
test('retail rounding is per unit and quantity arithmetic rejects invalid boundaries',()=>run(async f=>{assert.equal(await f.read('retailAmount',[1n,3]),6n);for(const [u,n] of [[0n,1],[1n,0],[1n,101],[1000000000000000001n,1]])await assert.rejects(f.read('retailAmount',[u,n]));}));
for(const change of [{amountMicro:10900001n},{unitCostMicro:10000001n},{skuHash:id('tampered')},{quantity:2},{buyer:ZERO},{assetKind:1},{orderId:ZERO32},{signerEpoch:2n}])test('tampering quote invalidates signature or price binding: '+Object.keys(change)[0],()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote(),s=await f.sign(q);await f.reject('payUSDC',[{...q,...change},s],1);}));
test('wrong signing key, domain chain, contract and malformed signature fail closed',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote();for(const s of [await f.sign(q,4),await f.sign(q,2,{...f.domain,chainId:5042002}),await f.sign(q,2,{...f.domain,verifyingContract:f.accounts[4]}),'0x1234'])await f.reject('payUSDC',[q,s],1);assert.equal(await f.read('totalGrossMicro'),0n);}));
test('third party cannot spend buyer allowance with a stolen signed quote',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote();await f.token('approve',[f.router,q.amountMicro],1);await f.reject('payUSDC',[q,await f.sign(q)],4);assert.equal(await f.read('nonceUsed',[q.buyer,q.nonce]),false);}));
test('order, nonce and cancelled quote replay are rejected',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote();await f.pay(q);await f.reject('payUSDC',[q,await f.sign(q)],1);const reused=await f.quote({nonce:q.nonce});await f.reject('payUSDC',[reused,await f.sign(reused)],1);const order=await f.quote({orderId:q.orderId});await f.reject('payUSDC',[order,await f.sign(order)],1);const c=await f.quote();await f.tx('cancelOrder',[c.orderId],2);await f.reject('payUSDC',[c,await f.sign(c)],1);const n=await f.quote();await f.tx('cancelNonce',[n.nonce],1);await f.reject('payUSDC',[n,await f.sign(n)],1);}));
test('not-yet-valid, exact expiry, empty SKU and excessive validity window reject',()=>run(async f=>{await f.tx('unpauseSales');for(const make of [q=>({...q,validAfter:q.validAfter+100n,deadline:q.deadline+100n}),q=>({...q,deadline:q.validAfter}),q=>({...q,skuHash:ZERO32}),q=>({...q,deadline:q.validAfter+301n})]){const q=make(await f.quote());await f.reject('payUSDC',[q,await f.sign(q)],1);}const q=await f.quote();await f.provider.request({method:'evm_setTime',params:[Number(q.deadline)*1000]});await f.provider.request({method:'evm_mine',params:[]});await f.reject('payUSDC',[q,await f.sign(q)],1);}));
test('failed ERC20 transfer rolls back nonce, volume and paid marker',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote();const hash=await f.wallets[1].writeContract({address:f.router,abi:C.abi,functionName:'payUSDC',args:[q,await f.sign(q)],gas:1000000n});assert.equal((await f.p.waitForTransactionReceipt({hash})).status,'reverted');assert.equal((await f.read('orders',[q.orderId]))[0],ZERO);assert.equal(await f.read('nonceUsed',[q.buyer,q.nonce]),false);assert.equal(await f.read('totalGrossMicro'),0n);await f.pay(q);}));
test('native USDC uses exact six-to-eighteen conversion, neither underpayment nor dust accepted',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote({assetKind:1}),s=await f.sign(q);await f.reject('payNativeUSDC',[q,s],1,q.amountMicro*SCALE-1n);await f.reject('payNativeUSDC',[q,s],1,q.amountMicro*SCALE+1n);const before=await f.p.getBalance({address:f.merchant});await f.tx('payNativeUSDC',[q,s],1,q.amountMicro*SCALE);assert.equal(await f.p.getBalance({address:f.merchant}),before+q.amountMicro*SCALE);assert.equal(await f.p.getBalance({address:f.router}),0n);}));
test('native merchant refusal rolls back every order field and permits original retry',()=>run(async f=>{await f.tx('unpauseSales');await f.tx('configure',[f.router,'0x',true],0,0n,f.merchant,f.R.abi);const q=await f.quote({assetKind:1});await f.reject('payNativeUSDC',[q,await f.sign(q)],1,q.amountMicro*SCALE);assert.equal(await f.read('nonceUsed',[q.buyer,q.nonce]),false);assert.equal(await f.read('totalGrossMicro'),0n);await f.tx('configure',[f.router,'0x',false],0,0n,f.merchant,f.R.abi);await f.pay(q);},{receiver:true}));
test('native recipient callback hits exact reentrancy guard without duplicate settlement',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote({assetKind:1}),s=await f.sign(q),d=encodeFunctionData({abi:C.abi,functionName:'payNativeUSDC',args:[q,s]});await f.tx('configure',[f.router,d,false],0,0n,f.merchant,f.R.abi);await f.pay(q);assert.equal(await f.p.readContract({address:f.merchant,abi:f.R.abi,functionName:'blocked'}),true);assert.equal(await f.read('totalGrossMicro'),q.amountMicro);},{receiver:true}));
test('fee-on-transfer token is rejected with atomic rollback',async()=>{const a=compileMock('import{ERC20}from"@openzeppelin/contracts/token/ERC20/ERC20.sol";contract Fee is ERC20{constructor()ERC20("Synthetic","S"){}function decimals()public pure override returns(uint8){return 6;}function mint(address a,uint256 n)external{_mint(a,n);}function _update(address a,address b,uint256 n)internal override{if(a!=address(0)&&b!=address(0)&&n>0){super._update(a,b,n-1);super._update(a,address(0),1);}else super._update(a,b,n);}}','Fee');await run(async f=>{await f.tx('unpauseSales');const q=await f.quote();await f.token('approve',[f.router,q.amountMicro],1);await f.reject('payUSDC',[q,await f.sign(q)],1);assert.equal(await f.read('nonceUsed',[q.buyer,q.nonce]),false);},{tokenCode:a.deployedBytecode});});
test('manual partial token refunds work during pause and cannot exceed the original payment',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote();await f.pay(q);await f.tx('pauseSales',[],2);await f.token('approve',[f.router,q.amountMicro],3);await f.reject('refundUSDC',[q.orderId,1n,id('support')],1);await f.reject('refundUSDC',[q.orderId,1n,id('support')],2);await f.reject('refundUSDC',[q.orderId,1n,ZERO32]);await f.tx('refundUSDC',[q.orderId,4000000n,id('support-1')]);await f.tx('refundUSDC',[q.orderId,q.amountMicro-4000000n,id('support-2')]);assert.equal(await f.read('totalRefundedMicro'),q.amountMicro);await f.reject('refundUSDC',[q.orderId,1n,id('support-3')]);assert.equal(await f.read('totalGrossMicro'),q.amountMicro);}));
test('insufficient merchant refund allowance never records a fictitious refund',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote();await f.pay(q);await f.reject('refundUSDC',[q.orderId,1n,id('support')]);assert.equal((await f.read('orders',[q.orderId]))[3],0n);assert.equal(await f.read('totalRefundedMicro'),0n);}));
test('manual native refunds are owner funded, exact and available while paused',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote({assetKind:1});await f.pay(q);await f.tx('pauseSales');await f.reject('refundNativeUSDC',[q.orderId,1n,id('support')],1,SCALE);await f.reject('refundNativeUSDC',[q.orderId,1n,id('support')],0,SCALE+1n);const before=await f.p.getBalance({address:q.buyer});await f.tx('refundNativeUSDC',[q.orderId,q.amountMicro,id('support')],0,q.amountMicro*SCALE);assert.equal(await f.p.getBalance({address:q.buyer}),before+q.amountMicro*SCALE);await f.reject('refundUSDC',[q.orderId,1n,id('support')]);}));
test('order and UTC-day limits cannot be bypassed through refunds; next day resets only volume',()=>run(async f=>{await f.tx('unpauseSales');const a=await f.quote();await f.pay(a);await f.token('approve',[f.router,a.amountMicro],3);await f.tx('refundUSDC',[a.orderId,a.amountMicro,id('support')]);const b=await f.quote();await f.reject('payUSDC',[b,await f.sign(b)],1);const block=await f.p.getBlock(),next=(block.timestamp/86400n+1n)*86400n+2n;await f.provider.request({method:'evm_setTime',params:[Number(next)*1000]});await f.provider.request({method:'evm_mine',params:[]});const c=await f.quote();await f.pay(c);assert.equal(await f.read('totalGrossMicro'),2n*a.amountMicro);const high=await f.quote({unitCostMicro:20000000n,amountMicro:21800000n});await f.reject('payUSDC',[high,await f.sign(high)],1);},{orderCap:11000000n,dayCap:11000000n}));
test('signer rotation requires owner delay, bumps epoch, pauses intake and invalidates old quotes',()=>run(async f=>{await f.tx('unpauseSales');const old=await f.quote();await f.reject('proposeQuoteSigner',[f.accounts[4]],2);await f.tx('proposeQuoteSigner',[f.accounts[4]]);await f.reject('activateQuoteSigner');await f.provider.request({method:'evm_increaseTime',params:[86400]});await f.provider.request({method:'evm_mine',params:[]});await f.tx('activateQuoteSigner');assert.equal(await f.read('paused'),true);assert.equal(await f.read('signerEpoch'),2n);await f.tx('unpauseSales');await f.reject('payUSDC',[old,await f.sign(old)],1);const q=await f.quote();await f.reject('payUSDC',[q,await f.sign(q)],1);await f.token('approve',[f.router,q.amountMicro],1);await f.tx('payUSDC',[q,await f.sign(q,4)],1);}));
test('governance uses two-step ownership, cannot renounce; signer cannot unpause or rescue',()=>run(async f=>{await f.reject('renounceOwnership');await f.reject('recoverTokenSurplus',[TOKEN,1n],2);await f.reject('unpauseSales',[],2);await f.tx('transferOwnership',[f.accounts[4]]);assert.equal((await f.read('owner')).toLowerCase(),f.accounts[0].toLowerCase());await f.reject('acceptOwnership',[],1);await f.tx('acceptOwnership',[],4);assert.equal((await f.read('owner')).toLowerCase(),f.accounts[4].toLowerCase());await f.reject('unpauseSales');await f.tx('unpauseSales',[],4);}));
test('plain native sends are rejected; unrelated token surplus is never an order or customer credit',()=>run(async f=>{await assert.rejects(f.p.estimateGas({account:f.accounts[1],to:f.router,value:1n}));await f.token('transfer',[f.router,123n],1);assert.equal(await f.read('totalGrossMicro'),0n);await f.reject('recoverTokenSurplus',[TOKEN,123n],1);await f.tx('recoverTokenSurplus',[TOKEN,123n]);assert.equal(await f.p.readContract({address:TOKEN,abi:T.abi,functionName:'balanceOf',args:[f.router]}),0n);}));
test('deterministic settlement conservation across twenty quotes and partial refunds',()=>run(async f=>{await f.tx('unpauseSales');let gross=0n,refunded=0n;await f.token('approve',[f.router,100000000000n],3);for(let i=1;i<=20;i++){const q=await f.quote({unitCostMicro:BigInt(i),quantity:3,amountMicro:((BigInt(i)*10900n+9999n)/10000n)*3n});await f.pay(q);gross+=q.amountMicro;await f.tx('refundUSDC',[q.orderId,1n,id('support-'+i)]);refunded+=1n;assert.equal(await f.read('totalGrossMicro'),gross);assert.equal(await f.read('totalRefundedMicro'),refunded);assert.equal(await f.p.readContract({address:TOKEN,abi:T.abi,functionName:'balanceOf',args:[f.router]}),0n);assert(refunded<=gross);}}));
test('constructor refuses Testnet chain and zero signer/merchant or invalid caps',async()=>{const provider=ganache.provider({chain:{chainId:5042002},logging:{quiet:true}}),p=createPublicClient({transport:custom(provider)}),accounts=await provider.request({method:'eth_accounts',params:[]});try{await provider.request({method:'evm_setAccountCode',params:[TOKEN,T.deployedBytecode]});const {encodeDeployData}=require('viem');await assert.rejects(p.estimateGas({account:accounts[0],data:encodeDeployData({abi:C.abi,bytecode:C.bytecode,args:[accounts[0],accounts[2],accounts[3],1n,1n]})}));}finally{await provider.disconnect();}await run(async f=>{const {encodeDeployData}=require('viem');for(const args of [[f.accounts[0],ZERO,f.merchant,1n,1n],[f.accounts[0],f.signer,ZERO,1n,1n],[f.accounts[0],f.signer,f.merchant,0n,1n],[f.accounts[0],f.signer,f.merchant,2n,1n]])await assert.rejects(f.p.estimateGas({account:f.accounts[0],data:encodeDeployData({abi:C.abi,bytecode:C.bytecode,args})}));});});

test('ERC20 transfer callback hits reentrancy guard and cannot settle a second order',async()=>{const a=compileMock('import{ERC20}from"@openzeppelin/contracts/token/ERC20/ERC20.sol";contract Callback is ERC20{address public target;bytes public payload;bool public blocked;constructor()ERC20("Synthetic","S"){}function decimals()public pure override returns(uint8){return 6;}function mint(address a,uint256 n)external{_mint(a,n);}function configure(address t,bytes calldata p)external{target=t;payload=p;}function _update(address a,address b,uint256 n)internal override{if(a!=address(0)&&b!=address(0)&&target!=address(0)){(bool ok,bytes memory why)=target.call(payload);require(!ok&&bytes4(why)==bytes4(keccak256("ReentrancyGuardReentrantCall()")));blocked=true;}super._update(a,b,n);}}','Callback');await run(async f=>{await f.tx('unpauseSales');const q=await f.quote(),s=await f.sign(q);await f.tx('configure',[f.router,encodeFunctionData({abi:C.abi,functionName:'payUSDC',args:[q,s]})],0,0n,TOKEN,a.abi);await f.pay(q);assert.equal(await f.p.readContract({address:TOKEN,abi:a.abi,functionName:'blocked'}),true);assert.equal(await f.read('totalGrossMicro'),q.amountMicro);},{tokenCode:a.deployedBytecode});});
test('false-return ERC20 cannot create a paid order or consume buyer nonce',async()=>{const a=compileMock('import{ERC20}from"@openzeppelin/contracts/token/ERC20/ERC20.sol";contract FalseToken is ERC20{constructor()ERC20("Synthetic","S"){}function decimals()public pure override returns(uint8){return 6;}function mint(address a,uint256 n)external{_mint(a,n);}function transferFrom(address,address,uint256)public pure override returns(bool){return false;}}','FalseToken');await run(async f=>{await f.tx('unpauseSales');const q=await f.quote();await f.token('approve',[f.router,q.amountMicro],1);await f.reject('payUSDC',[q,await f.sign(q)],1);assert.equal(await f.read('totalGrossMicro'),0n);assert.equal(await f.read('nonceUsed',[q.buyer,q.nonce]),false);},{tokenCode:a.deployedBytecode});});
test('cancelled signer proposal cannot later activate or change existing authorization',()=>run(async f=>{await f.tx('unpauseSales');await f.tx('proposeQuoteSigner',[f.accounts[4]]);await f.tx('cancelQuoteSignerProposal');await f.provider.request({method:'evm_increaseTime',params:[86400]});await f.provider.request({method:'evm_mine',params:[]});await f.reject('activateQuoteSigner');assert.equal(await f.read('signerEpoch'),1n);await f.pay(await f.quote());}));
test('constructor rejects missing token code and an eighteen-decimal ERC20 impostor',()=>run(async f=>{const{encodeDeployData}=require('viem');const d=encodeDeployData({abi:C.abi,bytecode:C.bytecode,args:[f.accounts[0],f.signer,f.merchant,1n,1n]});await f.provider.request({method:'evm_setAccountCode',params:[TOKEN,'0x']});await assert.rejects(f.p.estimateGas({account:f.accounts[0],data:d}));const a=compileMock('contract DecimalImpostor{function decimals()external pure returns(uint8){return 18;}}','DecimalImpostor');await f.provider.request({method:'evm_setAccountCode',params:[TOKEN,a.deployedBytecode]});await assert.rejects(f.p.estimateGas({account:f.accounts[0],data:d}));}));
test('high-S malleable ECDSA and zero signature cannot authorize payment',()=>run(async f=>{await f.tx('unpauseSales');const q=await f.quote(),s=await f.sign(q);const n=BigInt('0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141');const highS=(n-BigInt('0x'+s.slice(66,130))).toString(16).padStart(64,'0'),v=parseInt(s.slice(130,132),16)===27?'1c':'1b';await f.reject('payUSDC',[q,s.slice(0,66)+highS+v],1);await f.reject('payUSDC',[q,'0x'+'0'.repeat(130)],1);assert.equal(await f.read('nonceUsed',[q.buyer,q.nonce]),false);}));
