/** Read-only procurement monitor. No financial route, purchase transport call or signer. */
import Fastify from 'fastify';import Database from 'better-sqlite3';import {loadConfig,type Config} from './config.js';import {supplierPreview} from './services/supplier-preview.js';import {PublicCommerceApi} from './services/fulfillment/public-commerce-api.js';import {availableQuantity} from './services/catalog-stock.js';import {retailPrice,RETAIL_PRICE_POLICY} from './services/retail-pricing.js';import {recordProcurementHealth,procurementHealth} from './services/procurement-health.js';import {fileURLToPath} from 'node:url';import {resolve} from 'node:path';
export class SupplyMonitor {
 private stock:Awaited<ReturnType<typeof supplierPreview>>|null=null;private pendingStock?:Promise<void>;private pendingBalance?:Promise<void>;private stockAt=0;private failedStock=false;
 constructor(readonly db:Database.Database,private config:Config,private fetcher:typeof fetch=fetch){}
 refreshBalance(){if(this.pendingBalance)return this.pendingBalance;this.pendingBalance=(async()=>{try{if(!this.config.SUPPLIER_API_KEY)throw Error();const v=await new PublicCommerceApi(this.config.SUPPLIER_API_KEY,this.fetcher,this.config.SUPPLIER_API_URL,this.config.SUPPLIER_ALLOWED_ORIGIN).procurementCashUsd();const n=BigInt(v.availableUnits);recordProcurementHealth(this.db,{currency:'USD',available:(n/1000000n)+'.'+(n%1000000n).toString().padStart(6,'0'),observedAt:v.observedAt})}catch{recordProcurementHealth(this.db,null)}})().finally(()=>{this.pendingBalance=undefined});return this.pendingBalance;}
 refreshStock(){if(this.pendingStock)return this.pendingStock;this.pendingStock=(async()=>{const v=await supplierPreview(this.config,this.fetcher);if(v.status==='ready'){this.stock=v;this.stockAt=Date.now();this.failedStock=false}else this.failedStock=true;})().finally(()=>{this.pendingStock=undefined});return this.pendingStock;}
 catalog(now=Date.now()){const current=!!this.stock&&!this.failedStock&&now-this.stockAt<=90000&&now>=this.stockAt;return {supplier:'Mercenta catalogue',status:current?'ready':'unavailable',coverage:current?'live-stock':'unverified',fetchedAt:new Date(current?this.stockAt:now).toISOString(),pricingPolicy:RETAIL_PRICE_POLICY,purchasingEnabled:false,products:current?this.stock!.products.map(p=>({...p,items:p.items.filter(i=>availableQuantity(i)>0&&i.price>0&&Number(i.price.toFixed(6))===i.price).map(i=>({...i,price:retailPrice(i.price),inStock:availableQuantity(i)}))})).filter(p=>p.items.length>0):[]};}
 availability(now=Date.now()){const h=procurementHealth(this.db,now),catalog=this.catalog(now);return {supplyReady:h.open,inventoryReady:catalog.status==='ready',maintenance:!h.open,checkedAt:h.checkedAt,stockCheckedAt:this.stockAt||null,pricingPolicy:RETAIL_PRICE_POLICY,realPurchasesEnabled:false,existingOrdersAccessible:true,refundMode:'support-owner-manual',message:h.open?'Catalogue available. Checkout is not enabled yet.':'Technical maintenance. New purchases are temporarily unavailable; existing orders and support remain accessible.'};}
 start(){void this.refreshBalance();void this.refreshStock();const b=setInterval(()=>void this.refreshBalance(),15000),s=setInterval(()=>void this.refreshStock(),65000);b.unref();s.unref();return()=>{clearInterval(b);clearInterval(s)}}
}
export function createSupplyMonitorServer(monitor:SupplyMonitor){const app=Fastify({logger:false,bodyLimit:1024});app.addHook('onRequest',async(req,reply)=>{reply.header('Cache-Control','no-store').header('Vary','Origin');const o=req.headers.origin;if(o&&['https://mercenta.xyz','https://app.mercenta.xyz','https://mainnet.mercenta.xyz','https://testnet.mercenta.xyz'].includes(o))reply.header('Access-Control-Allow-Origin',o);if(req.method!=='GET'&&req.method!=='OPTIONS')return reply.code(405).send({code:'READ_ONLY_MONITOR'});});app.options('/:action',(_q,r)=>r.header('Access-Control-Allow-Methods','GET, OPTIONS').code(204).send());app.get('/health',()=>({ok:true,service:'mercenta-supply-monitor',readOnly:true,signingEnabled:false,purchasesEnabled:false}));app.get('/availability',()=>monitor.availability());app.get('/catalog',()=>monitor.catalog());return app;}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const c=loadConfig({...process.env,NODE_ENV:'test'});if(!c.SUPPLIER_API_KEY||!c.SUPPLIER_API_URL||!c.SUPPLIER_ALLOWED_ORIGIN)throw Error('READ_ONLY_SUPPLY_CONFIG_REQUIRED');const db=new Database('/var/lib/mercenta-supply/monitor.sqlite');db.pragma('journal_mode = WAL');db.pragma('synchronous = FULL');const m=new SupplyMonitor(db,c),stop=m.start(),app=createSupplyMonitorServer(m);await app.listen({host:'127.0.0.1',port:3015});const close=async()=>{stop();await app.close();db.close();process.exit(0)};process.on('SIGTERM',()=>void close());process.on('SIGINT',()=>void close());}
