import {initSettings,settings,saveSettings} from '../services/settings.js';
import {memoryState} from '../services/runtime.js';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';
import type {DB} from '../db.js';import type {Config} from '../config.js';
import {arcClient,verifyArc} from '../services/arc/index.js';import type {Address,Hash} from 'viem';
import {initAccount,funds,createDeposit,getDeposit,creditDeposit,TEST_PRODUCTS,SCOPES,dashboard,range,accountOrders,history,listKeys,createKey,revokeKey,authenticateKey,placeTestOrder} from '../services/account.js';
export function accountActor(req:FastifyRequest,c:Config){const a=req.headers['x-mercenta-actor'],ts=req.headers['x-mercenta-timestamp'],sig=req.headers['x-mercenta-signature'];if(typeof a!=='string'||!/^wallet:0x[a-f0-9]{40}$/.test(a))throw new Error('WALLET_AUTH_REQUIRED');if(typeof ts!=='string'||typeof sig!=='string'||!/^\d{13}$/.test(ts)||Math.abs(Date.now()-Number(ts))>30000)throw new Error('UNAUTHORIZED');const expected=createHmac('sha256',c.BACKEND_PROXY_SECRET).update(`${ts}\n${req.method}\n${req.url}\n${a}\n${req.body?JSON.stringify(req.body):''}`).digest('hex');const x=Buffer.from(sig),y=Buffer.from(expected);if(x.length!==y.length||!timingSafeEqual(x,y))throw new Error('UNAUTHORIZED');return a;}
const uuid=z.string().uuid(),money=z.string().regex(/^(0|[1-9]\d*)(\.\d{1,6})?$/).max(30);
const query=z.object({period:z.enum(['24h','7d','30d','90d','all','custom']).default('30d'),from:z.string().optional(),to:z.string().optional(),initiator:z.string().max(100).optional(),status:z.string().max(40).optional(),country:z.string().max(20).optional(),product:z.string().max(100).optional(),method:z.string().max(40).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25)});
function filters(req:FastifyRequest){const q=query.parse(req.query);return {q,f:{...range(q.period,q.from,q.to),initiator:q.initiator,status:q.status,country:q.country,product:q.product,method:q.method}}}
function page<T>(rows:T[],q:{page:number;pageSize:number}){return {items:rows.slice((q.page-1)*q.pageSize,q.page*q.pageSize),total:rows.length,page:q.page,pageSize:q.pageSize}}
export function registerAccountRoutes(app:FastifyInstance,db:DB,c:Config){initAccount(db);initSettings(db);
 app.get('/api/account/settings',req=>{const a=accountActor(req,c);return {...settings(db,a),wallet:a.slice(7),merchantAddress:c.MERCHANT_WALLET??null,resources:memoryState(c)}});
 app.post('/api/account/settings',req=>{const a=accountActor(req,c),b=z.object({theme:z.enum(['dark','light','system'])}).parse(req.body);return {...saveSettings(db,a,b.theme),wallet:a.slice(7),merchantAddress:c.MERCHANT_WALLET??null,resources:memoryState(c)}});
 app.get('/api/account/summary',async req=>{const a=accountActor(req,c);let walletBalanceUnits:string|null=null;try{walletBalanceUnits=((await arcClient(c.ARC_RPC_URL).getBalance({address:a.slice(7) as Address}))/1_000_000_000_000n).toString()}catch{/* RPC outage cannot create money. */}return {...funds(db,a),wallet:a.slice(7),walletBalanceUnits,depositConfigured:!!c.MERCHANT_WALLET,merchantAddress:c.MERCHANT_WALLET??null,bridge:{enabled:false,reason:'Reviewed CCTP/Gateway route and destination receipt attribution required'},onramp:{enabled:false,reason:'Circle onboarding and validated hosted sandbox settlement required'},withdrawals:{enabled:false},fulfillment:'simulated-only'};});
 app.get('/api/account/dashboard',req=>{const a=accountActor(req,c),{f}=filters(req);return dashboard(db,a,f)});
 app.get('/api/account/catalog',req=>{accountActor(req,c);return {products:TEST_PRODUCTS,mode:'testnet-sandbox',message:'Test USDC only. No real digital goods or live supplier stock.'}});
 app.get('/api/account/orders',req=>{const a=accountActor(req,c),{f,q}=filters(req);return page(accountOrders(db,a,f),q)});
 app.post('/api/account/orders',req=>{const a=accountActor(req,c),b=z.object({requestId:uuid,productId:z.string().max(100),quantity:z.number().int().min(1).max(100),reference:z.string().max(100).default('')}).parse(req.body);return placeTestOrder(db,a,b.requestId,b.productId,b.quantity,b.reference)});
 for(const type of ['funds','transactions'] as const)app.get('/api/account/'+type,req=>{const a=accountActor(req,c),{q,f}=filters(req);return page(history(db,a,type,f),q)});
 app.post('/api/account/deposits',req=>{const a=accountActor(req,c);if(!c.MERCHANT_WALLET)throw new Error('DEPOSIT_RECEIVER_NOT_CONFIGURED');const b=z.object({requestId:uuid,amount:money}).parse(req.body);return createDeposit(db,a,b.requestId,c.MERCHANT_WALLET,b.amount)});
 app.post('/api/account/deposits/:id/verify',async req=>{const a=accountActor(req,c),p=z.object({id:uuid}).parse(req.params),b=z.object({txHash:z.string().regex(/^0x[a-fA-F0-9]{64}$/)}).parse(req.body),d=getDeposit(db,a,p.id);if(d.status==='CREDITED'){if(d.tx_hash!==b.txHash.toLowerCase())throw new Error('IDEMPOTENCY_CONFLICT');return d;}const client=arcClient(c.ARC_RPC_URL),proof=await verifyArc(client,b.txHash as Hash,d.receiver as Address,a.slice(7) as Address),receipt=await client.getTransactionReceipt({hash:b.txHash as Hash}),block=await client.getBlock({blockNumber:receipt.blockNumber});if(block.hash!==proof.blockHash)throw new Error('BLOCK_MISMATCH');return creditDeposit(db,a,p.id,{...proof,blockTime:Number(block.timestamp)*1000});});
 app.get('/api/account/keys',req=>({items:listKeys(db,accountActor(req,c)),scopes:SCOPES}));
 app.post('/api/account/keys',req=>{const a=accountActor(req,c),b=z.object({name:z.string().min(1).max(60),scopes:z.array(z.enum(SCOPES)).min(1),expiresDays:z.number().int().min(1).max(90)}).parse(req.body);return createKey(db,a,b.name,b.scopes,b.expiresDays)});
 app.post('/api/account/keys/:id/revoke',req=>revokeKey(db,accountActor(req,c),z.object({id:uuid}).parse(req.params).id));
 app.get('/api/account/support',req=>{accountActor(req,c);return {manager:null,email:null,newsRU:null,newsEN:null,message:'Contact channels are not configured. Do not send seed phrases, private keys, API secrets or delivery codes.'}});
 const key=(req:FastifyRequest,scope:string)=>authenticateKey(db,String(req.headers.authorization??'').replace(/^Bearer /,''),scope);
 app.get('/api/v1/account',req=>funds(db,key(req,'account:read').actor));
 app.get('/api/v1/dashboard',req=>dashboard(db,key(req,'account:read').actor,filters(req).f));
 app.get('/api/v1/orders',req=>{const k=key(req,'orders:read'),{q,f}=filters(req);return page(accountOrders(db,k.actor,f),q)});
 app.post('/api/v1/orders',req=>{const k=key(req,'orders:create'),b=z.object({requestId:uuid,productId:z.string().max(100),quantity:z.number().int().min(1).max(100),reference:z.string().max(100).default('')}).parse(req.body);return placeTestOrder(db,k.actor,b.requestId,b.productId,b.quantity,b.reference,'API key:'+k.id)});
}
