import type {FastifyInstance} from 'fastify';import {z} from 'zod';import type {Address,Hash} from 'viem';import type {DB} from '../db.js';import type {Config} from '../config.js';import {accountActor} from './account.js';import {arcClient,verifyArc} from '../services/arc/index.js';import {splitPlan,getPlan,rejectSecrets} from '../services/agent-chat.js';import {containsProviderCredential} from '../services/llm-providers.js';import {initCommerce,workflowInput,saleInput,createWorkflow,confirmWorkflow,cancelWorkflow,listWorkflows,getWorkflow,workflowView,listSales,createSale,getSale,saleView,saleQuote,recordSalePayment,saleSettlementId,saleMetrics,workflowEvidence,saleEvidence} from '../services/commerce.js';
export function registerCommerce(app:FastifyInstance,db:DB,c:Config){initCommerce(db);const id=z.object({id:z.string().uuid()});const safe=(b:unknown)=>{const s=JSON.stringify(b);rejectSecrets(s);if(containsProviderCredential(c,s))throw new Error('DO_NOT_SEND_SECRETS')};
 app.get('/api/account/workflows',req=>({items:listWorkflows(db,accountActor(req,c))}));
 app.post('/api/account/workflows',req=>{const a=accountActor(req,c);safe(req.body);return createWorkflow(db,a,workflowInput.parse(req.body))});
 app.get('/api/account/workflows/:id',req=>{const a=accountActor(req,c);return workflowView(db,a,getWorkflow(db,a,id.parse(req.params).id))});
 app.post('/api/account/workflows/:id/confirm',req=>{const a=accountActor(req,c);z.object({confirmed:z.literal(true)}).strict().parse(req.body);return confirmWorkflow(db,a,id.parse(req.params).id,true)});
 app.post('/api/account/workflows/:id/cancel',req=>{const a=accountActor(req,c);z.object({confirmed:z.literal(true)}).strict().parse(req.body);return cancelWorkflow(db,a,id.parse(req.params).id)});
 app.get('/api/account/sales',req=>{const a=accountActor(req,c);return {items:listSales(db,a),metrics:saleMetrics(db,a)}});
 app.post('/api/account/sales',req=>{const a=accountActor(req,c);safe(req.body);return createSale(db,a,saleInput.parse(req.body))});
 app.get('/api/account/sales/:id',req=>saleView(db,accountActor(req,c),getSale(db,accountActor(req,c),id.parse(req.params).id)));
 app.post('/api/account/sales/:id/payment',async req=>{const a=accountActor(req,c),saleId=id.parse(req.params).id,b=z.object({txHash:z.string().regex(/^0x[a-fA-F0-9]{64}$/),buyerAddress:z.string().regex(/^0x[a-fA-F0-9]{40}$/)}).strict().parse(req.body),s=getSale(db,a,saleId),buyer=b.buyerAddress.toLowerCase();if(buyer===a.slice(7))throw new Error('BUYER_MUST_DIFFER_FROM_SELLER');const old=db.prepare('SELECT tx_hash,buyer FROM commerce_sale_payments WHERE sale_id=?').get(saleId) as {tx_hash:string;buyer:string}|undefined;if(old){if(old.tx_hash!==b.txHash.toLowerCase()||old.buyer!==buyer)throw new Error('IDEMPOTENCY_CONFLICT');return saleView(db,a,s)}const client=arcClient(c.ARC_RPC_URL),proof=await verifyArc(client,b.txHash as Hash,a.slice(7) as Address,buyer as Address),receipt=await client.getTransactionReceipt({hash:b.txHash as Hash}),block=await client.getBlock({blockNumber:receipt.blockNumber});if(block.hash!==proof.blockHash)throw new Error('BLOCK_MISMATCH');return recordSalePayment(db,a,saleId,{...proof,buyer,blockNumber:receipt.blockNumber,blockTime:Number(block.timestamp)*1000})});
 app.post('/api/account/sales/:id/allocation',req=>{const a=accountActor(req,c),saleId=id.parse(req.params).id,b=z.object({confirmed:z.literal(true),allowDeclaredScenario:z.boolean().default(false)}).strict().parse(req.body);return db.transaction(()=>{const s=getSale(db,a,saleId),payment=!!db.prepare('SELECT 1 FROM commerce_sale_payments WHERE sale_id=?').get(saleId);if(!payment&&!b.allowDeclaredScenario)throw new Error('SALE_PAYMENT_NOT_VERIFIED');const links=db.prepare('SELECT p.* FROM commerce_sale_allocations l JOIN agent_chat_plans p ON p.id=l.plan_id WHERE l.sale_id=? AND p.actor=? ORDER BY l.created_at DESC').all(saleId,a) as ReturnType<typeof getPlan>[];const existing=links.find(p=>p.status==='EXECUTED')??links.find(p=>p.status==='WALLET_SIGNATURE_REQUIRED'&&p.expires_at>Date.now());if(existing)return {id:existing.id,kind:existing.kind,status:existing.status,preview:JSON.parse(existing.payload),result:existing.result?JSON.parse(existing.result):null,expiresAt:existing.expires_at};const q=saleQuote(s),p=splitPlan(db,a,q.input,{saleId:saleSettlementId(saleId),saleRecordId:saleId,fundingSource:payment?'VERIFIED_TESTNET_SALE':'DECLARED_SCENARIO_NOT_REVENUE'});db.prepare('INSERT INTO commerce_sale_allocations VALUES(?,?,?)').run(saleId,p.id,Date.now());return p})()});
 app.get('/api/account/evidence/workflows/:id',req=>workflowEvidence(db,accountActor(req,c),id.parse(req.params).id));
 app.get('/api/account/evidence/sales/:id',req=>saleEvidence(db,accountActor(req,c),id.parse(req.params).id));
}
