import Link from 'next/link'
import {ArrowRight, ShoppingBag, Wallet, SlidersHorizontal, Code2, ShieldCheck} from 'lucide-react'
const tasks = [
 {title:'Find and buy a product',text:'Browse first. Check the region and exact total. Confirm only when you are ready.',href:'/docs/account/orders',Icon:ShoppingBag,tag:'SHOP'},
 {title:'Understand your balances',text:'Your wallet, prepaid account and Gateway are separate. Know what you are funding.',href:'/docs/account/funds',Icon:Wallet,tag:'ACCOUNT'},
 {title:'Set a spending limit',text:'Build an editable plan. Learn which purchases your limits cover.',href:'/docs/account/budget',Icon:SlidersHorizontal,tag:'BUDGET'},
 {title:'Build with the API',text:'Authenticate, request a quote and reconcile the same operation safely.',href:'/docs/api-reference/authentication',Icon:Code2,tag:'DEVELOPERS'}
]
export function MercentaDocsHome(){return <div className="md-home"><section className="md-intro"><p className="md-eyebrow">MERCENTA / DOCUMENTATION</p><h1>Find the answer.<br/><span>Take the next step.</span></h1><p className="md-lede">A practical guide to digital purchases, your budget and the controls behind every action.</p><Link className="md-button" href="/docs/account/getting-started">Make your first purchase <ArrowRight size={17}/></Link><Link className="md-secondary-link" href="/docs/quickstart">Developer quickstart <ArrowRight size={15}/></Link></section><section className="md-task-section" aria-labelledby="task-heading"><div className="md-section-heading"><h2 id="task-heading">What would you like to do?</h2><span>Start with your task</span></div><div className="md-task-grid">{tasks.map(({title,text,href,Icon,tag})=><Link key={href} href={href} className="md-task"><div className="md-task-top"><Icon size={21} strokeWidth={1.5}/><span className="md-eyebrow">{tag}</span></div><h3>{title}</h3><p>{text}</p><ArrowRight className="md-task-arrow" size={18}/></Link>)}</div></section><section className="md-trust-strip"><ShieldCheck size={21}/><div><h2>Know what is live.</h2><p>Arc Testnet payments use test USDC. Product delivery is simulated. supplier procurement, mainnet and live Earn are not enabled.</p></div><Link href="/docs/guides/mainnet-readiness">Check release gates <ArrowRight size={16}/></Link></section><section className="md-further"><h2>Go a little deeper.</h2><div><Link href="/docs/agents/ai-advisor">Assistant & confirmations <ArrowRight size={16}/></Link><Link href="/docs/account/journal">Financial journal & privacy <ArrowRight size={16}/></Link><Link href="/docs/guides/troubleshooting">Troubleshooting <ArrowRight size={16}/></Link></div></section></div>}
