"use client";
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';import Image from 'next/image';
import {ArrowUpRight,ArrowRight,ShieldCheck,Bot,Globe2,Check,Pause,Play,ReceiptText,Wallet,ChevronDown} from 'lucide-react';
import BrandMark from './BrandMark';import {OfficialContacts} from '@/components/OfficialContacts';
const STEPS=[{label:'Your goal',title:'Find Steam for my region.',text:'Start with a product, your region and a spending cap. You do not need a wallet to browse.',detail:'A draft. No permission to spend.'},{label:'The boundaries',title:'A task with clear limits.',text:'Choose how much the task may spend and how much must remain in your account. Saved budget limits also apply.',detail:'Testnet rehearsal · one order per task.'},{label:'The proposal',title:'An option. An exact quote.',text:'The agent checks the catalogue and your account. Review the product, region, quantity and test total before deciding.',detail:'Example only. This panel does not call the agent.'},{label:'Your decision',title:'Nothing hidden in the last step.',text:'Confirm a quote yourself, or give explicit, time-limited permission for one bounded test purchase. The result appears in task activity.',detail:'Non-redeemable test delivery. No real goods.'}];
const CATEGORIES=['Gaming Keys & Platform Vouchers','Streaming & Media Subscriptions','Creator & Game Micro-Donations','Developer API & Token Bundles','Cloud Compute & GPU Vouchers'];
export default function CommerceLanding(){
 const [step,setStep]=useState(0),[motion,setMotion]=useState(true);const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');if(!motion||media.matches||!('IntersectionObserver' in window))return;
 const animations:Animation[]=[];const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){animations.push(e.target.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:500,easing:'cubic-bezier(.22,1,.36,1)'}));observer.unobserve(e.target);}}, {threshold:.12});
 root.current?.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));const stop=()=>animations.forEach(a=>a.cancel());media.addEventListener('change',stop);return()=>{observer.disconnect();stop();media.removeEventListener('change',stop);};},[motion]);
 const active=STEPS[step];
 return <div className="cl" ref={root} data-motion={motion?'on':'off'}><a className="cl-skip" href="#content">Skip to content</a>
 <header className="cl-header cl-wrap"><Link className="cl-brand" href="/" aria-label="Mercenta home"><BrandMark/>mercenta.</Link><nav aria-label="Main navigation"><a href="#how">How it works</a><Link href="/catalog">Catalogue</Link><Link href="/refund">Support & refunds</Link><a className="cl-button cl-small" href="https://testnet.mercenta.xyz/app">Open workspace <ArrowUpRight size={16}/></a></nav></header>
 <main id="content"><section className="cl-hero cl-wrap"><div data-reveal><p className="cl-eyebrow"><span className="cl-dot"/> DIGITAL COMMERCE. HUMAN CONTROL.</p><h1>You set the goal.<br/><em>Your agent finds<br className="cl-mobile-break"/> the way.</em></h1><p className="cl-lead">Digital products, the right region and a budget that stays yours. Mercenta turns a request into a checked proposal — then a decision you control.</p><div className="cl-actions"><a className="cl-button cl-primary" href="https://testnet.mercenta.xyz/app?section=agent-chat">Try the agent <ArrowRight size={18}/></a><Link className="cl-text-link" href="/catalog">Explore products <ArrowUpRight size={18}/></Link></div><p className="cl-caption">No wallet to explore. Testnet purchases use test assets and non-redeemable delivery.</p></div>
 <div className="cl-scene" data-reveal><div className="cl-scene-top"><span><Bot size={18}/> MERCENTA / OPERATOR</span><span className="cl-demo">INTERACTIVE EXAMPLE</span></div><div className="cl-scene-content" key={step}><p className="cl-step-number">0{step+1} / 04</p><h2>{active.title}</h2><p>{active.text}</p><div className="cl-example-meta"><ShieldCheck size={18}/><span>{active.detail}</span></div></div><div className="cl-step-tabs" role="group" aria-label="Explore the agent journey">{STEPS.map((s,i)=><button type="button" key={s.label} aria-pressed={step===i} onClick={()=>setStep(i)}><span>0{i+1}</span>{s.label}</button>)}</div></div></section>
 <section className="cl-network cl-wrap" aria-labelledby="network-title"><div><p className="cl-eyebrow">CHOOSE YOUR ENVIRONMENT</p><h2 id="network-title">Two networks. No mixed balances.</h2></div><a href="https://testnet.mercenta.xyz/app"><span className="cl-dot"/><strong>Arc Testnet</strong><span>Agent, budgets & test orders</span><ArrowUpRight size={18}/></a><a href="https://mainnet.mercenta.xyz/app"><Globe2 size={17}/><strong>Arc Mainnet</strong><span>Pre-launch · payments closed</span><ArrowUpRight size={18}/></a></section>
 <section id="how" className="cl-section cl-wrap"><div className="cl-heading" data-reveal><p className="cl-eyebrow">LESS CHECKOUT. MORE CLARITY.</p><h2>One request.<br/>A visible path to the result.</h2><p>No black-box spending. Product discovery, account checks and execution have separate steps.</p></div><div className="cl-principles">{[[Bot,'Ask for what you need','Use ordinary words. The agent searches within your region and task limits.'],[ShieldCheck,'Keep the boundaries explicit','A spend cap, a remaining balance and your confirmation are not optional decoration.'],[ReceiptText,'See what actually happened','Task activity shows real checks, quotes and the result. A proposal is never presented as a settled payment.']].map(([Icon,title,text])=>{const I=Icon as typeof Bot;return <article key={String(title)} data-reveal><I size={25}/><h3>{String(title)}</h3><p>{String(text)}</p></article>;})}</div></section>
 <section className="cl-section cl-wrap"><div className="cl-heading cl-heading-row" data-reveal><div><p className="cl-eyebrow">FAMILIAR PLATFORMS. THE RIGHT REGION.</p><h2>Know what you are choosing.</h2></div><Link className="cl-text-link" href="/catalog">Full catalogue <ArrowUpRight size={18}/></Link></div><div className="cl-products">{['Steam','Roblox','Spotify'].map(name=><a key={name} href={'/catalog?q='+encodeURIComponent(name)} data-reveal><div className="cl-product-art"><Image src={'/product-covers/'+name.toLowerCase()+'.webp'} alt={name+' platform artwork'} width={640} height={360}/></div><div className="cl-product-copy"><h3>{name}</h3><span>Choose region & option <ArrowRight size={17}/></span></div></a>)}</div><p className="cl-caption">Platform examples, not stock promises. Available options are checked against the current catalogue; prices are indicative USD, not payment quotes.</p><details className="cl-categories"><summary>Five Mercenta categories <ChevronDown size={16}/></summary><ul>{CATEGORIES.map(c=><li key={c}>{c}</li>)}</ul></details></section>
 <section className="cl-section cl-wrap cl-foundation"><div data-reveal><p className="cl-eyebrow">BUILT ON ARC. BOUNDED BY DESIGN.</p><h2>Useful automation.<br/>Without invisible risk.</h2><p>Testnet brings the operator, spending rules and test delivery together. Circle Gateway / x402 has a separate technical acceptance proof. Treasury liquidity planning and secret-isolated execution remain engineering labs — not live yield or attested TEE services.</p><a className="cl-text-link" href="https://docs.mercenta.xyz">Explore the architecture <ArrowUpRight size={18}/></a><div className="cl-recorded-proof"><a className="cl-text-link" href="https://testnet.arcscan.app/tx/0xef8037362a4b0e7f07b3c6d81b3327389b9271ab57fd7c5e537e4c7a578835b6" target="_blank" rel="noopener noreferrer"><ReceiptText size={16}/> Recorded Testnet x402 receipt <ArrowUpRight size={16}/></a><p className="cl-caption">Technical acceptance evidence, not a customer pilot or production uptime claim.</p></div></div><div className="cl-facts" data-reveal><div><Wallet size={19}/><strong>Separate environments</strong><span>No account balance carried into Mainnet.</span></div><div><Check size={19}/><strong>Exact amounts</strong><span>Financial decisions use integer USDC units.</span></div><div><ShieldCheck size={19}/><strong>Fail closed</strong><span>Unknown execution is not reported as success.</span></div><div><ReceiptText size={19}/><strong>Human support</strong><span>Refund requests are reviewed by Mercenta, manually.</span></div></div></section>
 <section className="cl-section cl-wrap cl-support" data-reveal><p className="cl-eyebrow">A PERSON WHEN YOU NEED ONE.</p><h2>Support is part of the product.</h2><p>Have a delivery or payment issue? Send the order reference to Mercenta Support. Refunds are reviewed and issued manually by the owner — never automatically by an agent.</p><Link className="cl-button" href="/refund">Request refund review <ArrowRight size={18}/></Link></section>
 <section className="cl-wrap cl-final" data-reveal><h2>Start with a need.<br/><em>Leave with a clear next step.</em></h2><a className="cl-button cl-primary" href="https://testnet.mercenta.xyz/app">Open Testnet workspace <ArrowUpRight size={18}/></a><p className="cl-caption">Mainnet checkout remains closed until production acceptance.</p></section></main>
 <footer className="cl-wrap cl-footer"><div><Link className="cl-brand" href="/" aria-label="Mercenta home"><BrandMark/>mercenta.</Link><p>Digital commerce. Under your control.</p></div><div className="cl-footer-links"><a href="https://docs.mercenta.xyz">Documentation</a><Link href="/api-docs">OpenAPI / Swagger</Link><Link href="/refund">Refund requests</Link><a href="https://mainnet.mercenta.xyz/app?section=launch">Mainnet launch status</a></div><OfficialContacts/><button type="button" className="cl-motion" aria-pressed={!motion} onClick={()=>setMotion(v=>!v)}>{motion?<Pause size={15}/>:<Play size={15}/>} {motion?'Pause motion':'Enable motion'}</button></footer></div>;
}
