// Source-derived route and input schema catalogue. No backend handlers are executed.
const fs=require('fs'),path=require('path'),vm=require('vm'),ts=require('../web/node_modules/typescript'),{z}=require('../backend/node_modules/zod');
const cache=new Map(),issues=[];function walk(n,cb){cb(n);ts.forEachChild(n,c=>walk(c,cb))}
function moduleInfo(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const src=fs.readFileSync(file,'utf8'),sf=ts.createSourceFile(file,src,99,true),decl=new Map(),imports=new Map();walk(sf,n=>{if(ts.isVariableDeclaration(n)&&ts.isIdentifier(n.name)&&n.initializer)decl.set(n.name.text,n.initializer);if(ts.isImportDeclaration(n)&&n.importClause?.namedBindings&&ts.isNamedImports(n.importClause.namedBindings)){const name=n.moduleSpecifier.text;if(name.startsWith('.'))for(const e of n.importClause.namedBindings.elements)imports.set(e.name.text,{file:path.resolve(path.dirname(file),name.replace(/\.js$/,'.ts')),name:e.propertyName?.text??e.name.text})}});const info={sf,decl,imports,values:new Map()};cache.set(file,info);return info}
function resolve(file,name,stack=[]){if(name==='z')return z;if(stack.includes(file+name))throw Error('recursive');const m=moduleInfo(file);if(m.values.has(name))return m.values.get(name);if(m.imports.has(name)){const im=m.imports.get(name);return resolve(im.file,im.name,[...stack,file+name])}const node=m.decl.get(name);if(!node)throw Error('unresolved '+name);const value=evaluate(file,node,[...stack,file+name]);m.values.set(name,value);return value}
function evaluate(file,node,stack=[]){const m=moduleInfo(file),text=node.getText(m.sf),ctx={z};walk(node,n=>{if(!ts.isIdentifier(n))return;const name=n.text;if(name==='z'||name in ctx)return;if(m.decl.has(name)||m.imports.has(name)){try{ctx[name]=resolve(file,name,stack)}catch{}}});const js=ts.transpile('('+text+')',{target:ts.ScriptTarget.ES2022});return vm.runInNewContext(js,ctx,{timeout:1000})}
function schema(file,node){try{const value=ts.isIdentifier(node)?resolve(file,node.text):evaluate(file,node);const result=z.toJSONSchema(value,{io:'input',unrepresentable:'any'});delete result.$schema;return result}catch(e){issues.push({file:path.basename(file),expression:node.getText(moduleInfo(file).sf).slice(0,90),reason:e.message});return null}}
function input(file,handler,kind){let found=null;walk(handler,n=>{if(ts.isCallExpression(n)&&ts.isPropertyAccessExpression(n.expression)&&n.expression.name.text==='parse'&&n.arguments[0]?.getText(moduleInfo(file).sf)==='req.'+kind)found=schema(file,n.expression.expression)});return found}
const records=[];for(const f of fs.readdirSync('backend/src/routes').filter(x=>x.endsWith('.ts'))){const file='backend/src/routes/'+f,m=moduleInfo(file);walk(m.sf,n=>{if(!ts.isCallExpression(n)||!ts.isPropertyAccessExpression(n.expression)||!['get','post','put','patch','delete'].includes(n.expression.name.text)||n.expression.expression.getText(m.sf)!=='app')return;const method=n.expression.name.text,a=n.arguments[0],h=n.arguments.at(-1);let routes=ts.isStringLiteral(a)?[a.text]:a.getText(m.sf).includes("type")?['/api/account/funds','/api/account/transactions']:a.getText(m.sf).includes('action')?['/api/liquidity/earn/deposit','/api/liquidity/earn/withdraw']:[];for(const route of routes)records.push({route,method,file,body:input(file,h,'body'),query:input(file,h,'query'),params:input(file,h,'params'),text:h.getText(m.sf)})})}
const serviceInputs={'/api/account/workspace/profile':'profileInput','/api/account/workspace/budget':'budgetInput','/api/account/journal':'journalInput'};for(const r of records)if(r.method==='post'&&serviceInputs[r.route])r.body=z.toJSONSchema(resolve('backend/src/services/workspace.ts',serviceInputs[r.route]),{io:'input'});
const paths={},excluded=[];const errors={description:'Request rejected: invalid input, session, ownership, origin, configured capability, budget or idempotency conflict.',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}};
function add(route,method,body,query,params,source){route=route.replace(/:([a-zA-Z]+)/g,'{$1}');const tag=route.includes('/operator/')?'Agent operator':route.includes('/catalog-checkout/')?'Test checkout':route.includes('/circle/')?'Circle Gateway':route.includes('/workspace')?'Budget & onboarding':route.includes('/journal')?'Financial journal':route.includes('/v1/')?'Integration API':route.includes('/liquidity/')?'Finance sandbox':route.includes('/auth/')?'Authentication':route.includes('/catalog')?'Catalogue':route.includes('/sales')||route.includes('/workflows')||route.includes('/evidence')?'Commerce evidence':route.includes('/agent')?'Assistant':'Account';const parameters=[];for(const m of route.matchAll(/\{([^}]+)\}/g))parameters.push({name:m[1],in:'path',required:true,schema:params?.properties?.[m[1]]??{type:'string',format:'uuid'}});if(query?.properties)for(const [name,s] of Object.entries(query.properties))parameters.push({name,in:'query',required:query.required?.includes(name)??false,schema:s});if(method==='get'&&/dashboard$|\/orders$|\/funds$|\/transactions$/.test(route)&&!parameters.some(x=>x.in==='query'))for(const [name,s]of Object.entries({period:{type:'string',enum:['24h','7d','30d','90d','all','custom'],default:'30d'},from:{type:'string'},to:{type:'string'},page:{type:'integer',minimum:1,default:1},pageSize:{type:'integer',minimum:1,maximum:100,default:25}}))parameters.push({name,in:'query',required:false,schema:s});
const publicRoute=['/api/catalog','/api/network','/api/openapi','/api/status','/api/health','/api/auth/nonce','/api/auth/verify','/api/auth/logout','/api/account/catalog-preview','/api/account/supplier-catalog','/api/account/service-availability','/api/account/agent/preview'].includes(route);
const o={tags:[tag],operationId:method+'_'+route.replace(/[^a-zA-Z0-9]+/g,'_'),summary:method.toUpperCase()+' '+route,description:route.includes('catalog-checkout')||route==='/api/account/orders'||route==='/api/v1/orders'?'Test USDC only. Delivery is simulated and non-redeemable; never a real-product invoice.':'Wallet sessions are host-only. Account operations require verified wallet ownership. Monetary strings use six fractional decimals; amountUnits are integer micro-USDC strings.',security:publicRoute?[]:route.includes('/v1/')?[{bearerAuth:[]}]:[{walletSession:[]}],parameters,responses:{'200':{description:'JSON result. Response shape depends on this operation; no universal success envelope is imposed.',content:{'application/json':{schema:{type:'object',additionalProperties:true}}}},'400':errors,'401':errors,'403':errors,'409':errors,'429':errors,'503':errors},'x-source':source,'x-runtime':'testnet','x-real-purchases-enabled':false};if(method!=='get'){o['x-try-it-disabled']=true;o.description+=' Mutating Try it out is disabled in the documentation. Session mutations additionally require same-origin Origin header.';o.requestBody={required:!!body?.required?.length,content:{'application/json':{schema:body??{type:'object',additionalProperties:false,description:'No JSON fields required by this handler.'}}}}}paths[route]??={};paths[route][method]=o;}
for(const r of records){if(r.route==='/api/x402/margin-report'||r.route==='/api/launch-readiness'){excluded.push({path:r.route,method:r.method,reason:'Backend-only; not exposed by the public web proxy.'});continue}add(r.route,r.method,r.body,r.query,r.params,r.file.replace('backend/src/',''))}
for(const [route,method,body] of [['/api/network','get'],['/api/openapi','get'],['/api/auth/logout','post'],['/api/me','get']])add(route,method,body,null,null,'web route');
const catalogOp=paths['/api/catalog'].get;catalogOp.parameters=[{name:'id',in:'query',schema:{type:'string',maxLength:200},description:'Return one public catalogue product.'},{name:'view',in:'query',schema:{type:'string',enum:['browse']},description:'Compact catalogue tuples; prices USD, purchasingEnabled false.'}];catalogOp.description='Public catalogue metadata. Prices are indicative USD, not payment quotes. Responses may be cached snapshots. Query id returns a product, view=browse returns compact tuples.';catalogOp['x-source']='web/src/app/api/catalog/route.ts';
for(const route of ['/api/agent/quota','/api/agent/chat']){const o=paths[route][route.endsWith('chat')?'post':'get'];o.deprecated=true;o.responses={'410':{description:'Legacy agent replaced by account operator and assistant preview.'},'401':errors,'503':errors};}
// Export-only response contracts used by the frontend (not evaluated application services).
for(const f of ['web/src/lib/operator-client.ts','web/src/lib/catalog-test-client.ts'])if(fs.existsSync(f)){const m=moduleInfo(f);for(const [name,node]of m.decl)if(/schema$/i.test(name)){const s=schema(f,node);if(s){for(const p of Object.values(paths))for(const o of Object.values(p))if(name==='operatorRunSchema'&&o.tags.includes('Agent operator')&&!o.operationId.includes('runs_'))o.responses['200'].content['application/json'].schema=s;}}}
// Engineering lab contracts are not procurement-run or financial response envelopes.
for(const [route,p] of Object.entries(paths)){if(!route.includes('/operator/lab/'))continue;for(const [method,o] of Object.entries(p)){
 o.tags=['Engineering lab'];o.description='Authenticated Testnet engineering lab. Synthetic credentials only; software isolation is NOT hardware TEE. Treasury plans use user-supplied hypothetical amounts, not account balances. No USYC execution, real provider call or money movement. Mutation retries retain the original requestId; UNKNOWN outcomes retain quota and are never executed again.';
 o['x-money-moved']=false;o['x-attestation-verified']=false;o['x-production-ingestion-enabled']=false;
 o.responses['200']={description:'Engineering result; never a procurement order or financial receipt.',content:{'application/json':{schema:{type:'object',additionalProperties:true}}}};
 const m=moduleInfo('web/src/lib/operator-lab-client.ts');const grant=schema('web/src/lib/operator-lab-client.ts',m.decl.get('blindGrantSchema'));const receipt=schema('web/src/lib/operator-lab-client.ts',m.decl.get('blindReceiptSchema'));
 if(route.includes('/blind/grants'))o.responses['200'].content['application/json'].schema=grant;
 if(route.endsWith('/blind/execute'))o.responses['200'].content['application/json'].schema=receipt;
 if(route.endsWith('/blind/receipts'))o.responses['200'].content['application/json'].schema={type:'object',required:['items','attestationVerified','realProviderCall'],additionalProperties:false,properties:{items:{type:'array',items:receipt},attestationVerified:{const:false},realProviderCall:{const:false}}};
 if(method!=='get')o.description+=' Same-origin Origin header is required. Mutating Try it out remains disabled.';
}}

// Support submission is a nonfinancial, public, same-origin claim. No wallet signing or refund execution.
const supportOp=paths['/api/support/refund'].post;supportOp.tags=['Support'];supportOp.security=[];supportOp['x-money-moved']=false;supportOp['x-runtime']='nonfinancial-support';supportOp.description='Submit an unverified claim for manual Mercenta owner review. No automatic refund, ledger credit or ownership proof. Same-origin Origin required; rate limited. No public ticket reader. Do not send credentials or purchased codes.';
supportOp.requestBody={required:true,content:{'application/json':{schema:z.toJSONSchema(resolve('backend/src/services/refund-input.ts','refundInput'),{io:'input',unrepresentable:'any'})}}};
delete supportOp.responses['200'];supportOp.responses['202']={description:'Request durably saved for manual review; no refund executed.',content:{'application/json':{schema:{type:'object',required:['ticketId','status','manualReview','refundExecuted'],properties:{ticketId:{type:'string',format:'uuid'},status:{type:'string',enum:['SUBMITTED','IN_REVIEW','CLOSED']},manualReview:{const:true},refundExecuted:{const:false}},additionalProperties:false}}}};

const base={openapi:'3.1.0',info:{title:'Mercenta API — Testnet',version:'1.0.0',description:'Source-derived public API reference. Testnet is a rehearsal with test assets and simulated digital delivery. Catalogue supplier prices in USD are not USDC payment quotes. Generic response objects are explicitly untyped until a stable response schema exists. Never submit passwords, seed phrases or provider keys.',contact:{email:'support@mercenta.xyz'}},servers:[{url:'https://testnet.mercenta.xyz',description:'Arc Testnet — chain 5042002'},{url:'https://app.mercenta.xyz',description:'Default testnet workspace'}],paths,components:{securitySchemes:{walletSession:{type:'apiKey',in:'cookie',name:'mercenta_session',description:'HttpOnly, host-only verified wallet session. Obtain through wallet challenge in the app. No session carry across networks.'},bearerAuth:{type:'http',scheme:'bearer',description:'Mercenta integration key generated in Account. /api/v1 supports account, dashboard and orders with key scopes; testnet only.'}},schemas:{Error:{type:'object',properties:{code:{type:'string'},message:{type:'string'}},additionalProperties:true},MainnetClosed:{type:'object',properties:{code:{const:'MAINNET_CHECKOUT_NOT_ENABLED'},network:{const:'mainnet'},chainId:{const:5042},realPurchasesEnabled:{const:false}}}}},'x-network':'testnet','x-chain-id':5042002,'x-coverage':{sourceRoutes:records.length,documentedOperations:Object.values(paths).reduce((n,p)=>n+Object.keys(p).length,0),excluded},'x-schema-notes':'Input constraints are generated from Zod definitions. Runtime business rules (budget sums, reserves, stock, idempotency and ownership) are enforced by the server. Generic response schemas are not a typed SDK guarantee.'};
const main=structuredClone(base);main.info.title='Mercenta API — Mainnet release contract';main.info.description='Mainnet domain has read-only commerce metadata and a nonfinancial manual support submission endpoint on Arc chain 5042. Real purchases, deposits, agent execution and wallet sessions are CLOSED. Requests are never forwarded to the testnet account backend. The inherited paths describe the intended surface, not enabled real buying. A production checkout contract must be finalized before activation.';main.servers=[{url:'https://mainnet.mercenta.xyz',description:'Preview only — financial API closed'}];main['x-network']='mainnet';main['x-chain-id']=5042;main['x-real-purchases-enabled']=false;main['x-release-state']='closed';for(const [route,p] of Object.entries(main.paths))for(const [method,o] of Object.entries(p)){o['x-runtime']='mainnet';o['x-enabled']=(route==='/api/support/refund'&&method==='post')||method==='get'&&['/api/catalog','/api/network','/api/openapi'].includes(route);o['x-try-it-disabled']=true;if(!o['x-enabled']){o.responses={'503':{description:'Mainnet release gate. No testnet fallback and no financial operation.',content:{'application/json':{schema:{$ref:'#/components/schemas/MainnetClosed'},example:{code:'MAINNET_CHECKOUT_NOT_ENABLED',network:'mainnet',chainId:5042,realPurchasesEnabled:false}}}}};o.description='CLOSED. This path is not a real-buy endpoint. No invoice, debit, agent execution or testnet forwarding.';delete o.requestBody;o.security=[];}}
const preparation=JSON.parse(fs.readFileSync('web/public/submission/mainnet-preparation.json','utf8')); main.paths['/api/mainnet-readiness']={get:{tags:['Network readiness'],operationId:'get_api_mainnet_readiness',summary:'Recorded Mainnet preparation status',description:'Read-only preparation snapshot, not launch approval or live runtime health. Payments and signing remain closed.',security:[],parameters:[], 'x-enabled':true,'x-runtime':'mainnet','x-try-it-disabled':true,responses:{'200':{description:'Recorded preparation snapshot; no secrets.',content:{'application/json':{schema:{type:'object',required:['kind','chainId','purchasesEnabled','walletSigningEnabled','gates'],properties:{kind:{const:'PREPARATION_NOT_GO_LIVE_APPROVAL'},chainId:{const:5042},purchasesEnabled:{const:false},walletSigningEnabled:{const:false},gates:{type:'array',minItems:5,maxItems:5}},additionalProperties:true},example:preparation}}},'404':{description:'Mainnet host required.'}}}};
fs.mkdirSync('work',{recursive:true});fs.mkdirSync('docs/openapi',{recursive:true});fs.writeFileSync('web/src/lib/openapi-testnet.json',JSON.stringify(base));fs.writeFileSync('web/src/lib/openapi-mainnet.json',JSON.stringify(main));fs.writeFileSync('docs/openapi/testnet.json',JSON.stringify(base,null,2));fs.writeFileSync('docs/openapi/mainnet.json',JSON.stringify(main,null,2));fs.writeFileSync('work/openapi-schema-issues.json',JSON.stringify(issues,null,2));console.log(JSON.stringify({operations:base['x-coverage'].documentedOperations,sourceRoutes:records.length,inputSchemas:records.filter(r=>r.body).length,issues,excluded}));
