// @vitest-environment jsdom
import {it,expect,vi,afterEach} from 'vitest';import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';
import {CatalogFamilyDialog} from '@/components/product/CatalogFamilyDialog';import {groupCatalog} from '@/lib/catalog-families';import type {CatalogProduct} from '@/lib/supplier';
const calls=vi.hoisted(()=>({load:vi.fn()}));vi.mock('@/lib/public-catalog-client',()=>({loadPublicProduct:calls.load}));vi.mock('@/components/product/ProductShell',()=>({Modal:({children}:{children:React.ReactNode})=>React.createElement('div',{role:'dialog'},children)}));vi.mock('@/components/product/ProductImage',()=>({ProductImage:()=>React.createElement('div')}));
vi.mock('@/components/product/TestCheckout',()=>({TestCheckout:({productId,itemId,quantity}:{productId:string;itemId:string;quantity:number})=>React.createElement('div',{'data-checkout':true},`${productId}/${itemId}/${quantity}`)}));
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const p=(id:string,region:string,deferred=false):CatalogProduct=>({id,name:'Roblox | '+region,brand:'Roblox',category:'gaming',type:'voucher',countryCode:region,denominations:deferred?[]:[{id:id+'-denom',name:'10 credits',price:3,currency:'USD',available:true,stock:10}],optionsDeferred:deferred,optionCount:1,minPrice:3,maxPrice:3,currency:'USD',inStock:1,totalStock:10});
let root:Root|undefined,el:HTMLDivElement;
afterEach(async()=>{if(root)await act(async()=>root!.unmount());document.body.innerHTML='';calls.load.mockReset()});
async function render(deferred=false,previewOnly=false){el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(React.createElement(CatalogFamilyDialog,{family:groupCatalog([p('us','US',deferred),p('br','BR',deferred)])[0],onClose:vi.fn(),previewOnly})))}
async function region(id:string){await act(async()=>{const s=el.querySelector<HTMLSelectElement>('#family-region')!;s.value=id;s.dispatchEvent(new Event('change',{bubbles:true}))})}
it('remounts denomination, quantity and checkout when the region changes',async()=>{await render();await region('us');expect(el.querySelector('[data-checkout]')?.textContent).toBe('us/us-denom/1');await region('br');expect(el.querySelector<HTMLSelectElement>('#catalogue-option')?.value).toBe('br-denom');expect(el.querySelector<HTMLInputElement>('#catalogue-quantity')?.value).toBe('1');expect(el.querySelector('[data-checkout]')?.textContent).toBe('br/br-denom/1')});
it('ignores a late detail response for the previously selected region',async()=>{let resolveUs!:(p:CatalogProduct)=>void;calls.load.mockImplementation((id:string)=>id==='us'?new Promise(r=>{resolveUs=r}):Promise.resolve(p('br','BR')));await render(true);expect(calls.load).not.toHaveBeenCalled();await region('us');await region('br');await act(async()=>resolveUs(p('us','US')));expect(calls.load.mock.calls.map(c=>c[0])).toEqual(['us','br']);expect(el.querySelector('[data-checkout]')?.textContent).toBe('br/br-denom/1')});
it('never mounts test checkout in mainnet preview even after details load',async()=>{calls.load.mockResolvedValue(p('br','BR'));await render(true,true);await region('br');expect(el.querySelector('[data-checkout]')).toBeNull();expect(el.textContent).toContain('Mainnet checkout is closed')});
