// @vitest-environment jsdom
import {it,expect,vi,afterEach} from 'vitest';import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';
import {sortFamilies,productCount} from '@/lib/catalog-presentation';import {groupCatalog} from '@/lib/catalog-families';import type {CatalogProduct} from '@/lib/supplier';import {CatalogCollection} from '@/components/product/CatalogCollection';
vi.mock('@/components/product/ProductImage',()=>({ProductImage:()=>React.createElement('div',{className:'product-image'})}));
vi.mock('@/components/product/CatalogFamilyDialog',()=>({CatalogFamilyDialog:({previewOnly}:{previewOnly:boolean})=>React.createElement('div',{'data-preview':String(previewOnly)})}));
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const p=(id:string,name:string,price:number,region='US'):CatalogProduct=>({id,name,brand:name,category:'gaming',type:'voucher',countryCode:region,denominations:[],optionsDeferred:true,optionCount:2,minPrice:price,maxPrice:price,currency:'USD',inStock:1,totalStock:1});
const products=[p('r','Roblox | US',4),p('s','Steam | US',2),p('b','Roblox | BR',1,'BR')];
let root:Root|undefined,el:HTMLDivElement;
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.innerHTML='';vi.unstubAllGlobals();});
async function render(){el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(<CatalogCollection products={products} previewOnly/>));}
async function select(label:string,value:string){const s=el.querySelector('select[aria-label="'+label+'"]')! as HTMLSelectElement;await act(async()=>{s.value=value;s.dispatchEvent(new Event('change',{bubbles:true}));});}
it('keeps artwork-first order untouched until explicitly sorted',()=>{const f=groupCatalog(products);expect(sortFamilies(f,'recommended','all',false)).toBe(f);expect(sortFamilies(f,'price','US',false)[0].name).toBe('Steam');expect(sortFamilies(f,'price','BR',false).at(-1)?.name).toBe('Steam');expect(sortFamilies(f,'name','all',false)[0].name).toBe('Roblox');});
it('uses correct English and Russian result grammar',()=>{expect(productCount(1,false)).toBe('1 product');expect(productCount(21,true)).toBe('21 товар');expect(productCount(2,true)).toBe('2 товара');expect(productCount(12,true)).toBe('12 товаров');});
it('compact view retains region/options actions and never fetches on display changes',async()=>{const f=vi.fn();vi.stubGlobal('fetch',f);await render();await act(async()=>{(el.querySelector('[aria-label="Compact view"]') as HTMLButtonElement).click()});expect(el.querySelector('.pd-compact')).toBeTruthy();expect(el.querySelectorAll('.cf-card')).toHaveLength(2);await select('Sort catalogue','price');expect(el.querySelector('.cf-card h2')?.textContent).toBe('Roblox');expect(f).not.toHaveBeenCalled();});
it('selected region changes sort prices while keeping exact preview-only detail mode',async()=>{await render();await select('Catalogue region','US');await select('Sort catalogue','price');expect(el.querySelector('.cf-card h2')?.textContent).toBe('Steam');await act(async()=>{(el.querySelector('.cf-card-bottom button') as HTMLButtonElement).click()});expect(el.querySelector('[data-preview]')?.getAttribute('data-preview')).toBe('true');});
it('category filters include decorative SVG and result counts',async()=>{await render();expect(el.querySelector('.cf-categories button svg')).toBeTruthy();expect(el.querySelector('[role=status]')?.textContent).toContain('2 products');expect(el.querySelector('.pd-catalog-guide')).toBeTruthy();});
