import {describe,it,expect} from 'vitest';
import type {CatalogProduct} from '@/lib/supplier';
import {groupCatalog,isSteamAccountOffer,familyPrice,familyProducts,regionLabel,familyMatches} from '@/lib/catalog-families';
const product=(id:string,name:string,countryCode:string,extra:Partial<CatalogProduct>={}):CatalogProduct=>({id,name,brand:'Roblox',category:'gaming',type:'voucher',countryCode,denominations:[{id:id+'-denom',name:'10 credits',price:3,currency:'USD',available:true}],minPrice:3,maxPrice:3,currency:'USD',inStock:1,totalStock:1,...extra});
describe('regional catalogue families',()=>{
 it('groups regional variants and preserves exact SKU objects',()=>{const us=product('us','Roblox Gift Card | US','US'),br=product('br','Roblox Gift Card | BR','BR');const families=groupCatalog([us,br]);expect(families).toHaveLength(1);expect(families[0].name).toBe('Roblox Gift Card');expect(families[0].products).toContain(us);expect(families[0].products).toContain(br);expect(familyProducts(families[0],'BR')[0].denominations[0].id).toBe('br-denom')});
 it('does not group unrelated products, formats or currencies by brand',()=>{expect(groupCatalog([product('a','Roblox Gift Card','US'),product('b','Roblox Premium','US'),product('c','Roblox Gift Card','BR',{type:'direct_topup'}),product('d','Roblox Gift Card','BR',{currency:'EUR'})])).toHaveLength(4)});
 it('prices and region filters apply to the selected original variant',()=>{const f=groupCatalog([product('a','Roblox | US','US',{minPrice:8}),product('b','Roblox | BR','BR',{minPrice:2})])[0];expect(familyPrice(f,'US')).toBe(8);expect(familyPrice(f,'BR')).toBe(2);expect(familyPrice(f,'RU')).toBeNull();expect(familyMatches(f,'roblox','RU')).toBe(false)});
 it('never invents a global region or corrects unknown codes silently',()=>{expect(regionLabel('UNSPECIFIED')).toBe('Region not supplied');expect(regionLabel('BP')).toBe('BP');expect(regionLabel('BR')).toContain('Brazil');expect(groupCatalog([product('a','Roblox','')])[0].regions).toEqual(['UNSPECIFIED'])});
 it('blocks account resale in English and Russian without blocking legitimate wallet top-ups',()=>{for(const name of ['Steam Accounts','Auto-regs | Steam Accounts','Аккаунт Steam','Steam account for sale'])expect(isSteamAccountOffer({name,brand:'Steam'})).toBe(true);for(const name of ['Steam Wallet','Steam Gift Cards','Steam Wallet Top Up for my account'])expect(isSteamAccountOffer({name,brand:'Steam'})).toBe(false)});
 it('excludes Steam account offers from every grouped storefront',()=>{expect(groupCatalog([product('a','Steam Accounts','RU',{brand:'Steam'}),product('b','Steam Wallet','RU',{brand:'Steam'})]).map(f=>f.name)).toEqual(['Steam Wallet'])});
 it('does not strip a nonregional title suffix',()=>{expect(groupCatalog([product('a','Roblox | Premium','US')])[0].name).toBe('Roblox | Premium')});
});
