import {describe,it,expect,vi,afterEach} from 'vitest';
import {circlePaymentSchema,circleStatusSchema,canConfirmCircle,circleStatusLabel,circleRequest} from '@/lib/circle-agent-client';
const w='0x'+'1'.repeat(40),to='0x'+'2'.repeat(40);
const status={configured:true,enabled:true,chainId:5042002 as const,provider:'local-eoa' as const,custody:'server-managed-local-eoa',walletAddress:w,services:[{id:'quotes',maxAmountUnits:'10000'}],perPaymentLimitUnits:'10000',dailyLimitUnits:'100000',requiresConfirmation:true as const};
const p={id:'11111111-1111-4111-8111-111111111111',serviceId:'quotes',status:'PREPARED' as const,amountUnits:'1000',wallet:w,payTo:to,network:'eip155:5042002' as const,expiresAt:2000,responseDigest:null,circleTransferId:null,txHash:null,settled:false,requiresConfirmation:true as const};
afterEach(()=>vi.unstubAllGlobals());
describe('Circle UI boundaries',()=>{
 it('requires active policy, matching wallet, service cap, writable account and unexpired quote',()=>{expect(canConfirmCircle(status,p,false,1000)).toBe(true);for(const s of [null,{...status,enabled:false},{...status,configured:false},{...status,walletAddress:to},{...status,services:[]},{...status,services:[{id:'quotes',maxAmountUnits:'999'}]}])expect(canConfirmCircle(s,p,false,1000)).toBe(false);expect(canConfirmCircle(status,p,true,1000)).toBe(false);expect(canConfirmCircle(status,p,false,2000)).toBe(false);expect(canConfirmCircle(status,{...p,status:'UNKNOWN'},false,1000)).toBe(false);});
 it('does not label queued/confirmed evidence as final settlement',()=>{expect(circleStatusLabel({...p,status:'QUEUED'})).toContain('Pending');expect(circleStatusLabel(p)).toContain('no payment');expect(()=>circlePaymentSchema.parse({...p,status:'QUEUED',settled:true})).toThrow();expect(()=>circlePaymentSchema.parse({...p,status:'COMPLETED',settled:true})).toThrow();expect(circleStatusLabel(circlePaymentSchema.parse({...p,status:'COMPLETED',settled:true,txHash:'0x'+'a'.repeat(64)}))).toBe('Verified settlement');});
 it('rejects mainnet and malformed values',()=>{expect(()=>circleStatusSchema.parse({...status,chainId:1})).toThrow();expect(()=>circlePaymentSchema.parse({...p,network:'eip155:1'})).toThrow();expect(()=>circlePaymentSchema.parse({...p,amountUnits:'0.01'})).toThrow();});
 it('requests read-only status/history without automatic confirmation',async()=>{const f=vi.fn().mockResolvedValue(new Response(JSON.stringify(status),{status:200}));vi.stubGlobal('fetch',f);await circleRequest('status',circleStatusSchema);expect(f).toHaveBeenCalledTimes(1);expect(f.mock.calls[0][1].method).toBe('GET');expect(f.mock.calls[0][1].body).toBeUndefined();});
 it('sends explicit confirmation once to the same saved id',async()=>{const f=vi.fn().mockResolvedValue(new Response(JSON.stringify({...p,status:'QUEUED'}),{status:200}));vi.stubGlobal('fetch',f);await circleRequest('payments/'+p.id+'/confirm',circlePaymentSchema,{confirmed:true});expect(f).toHaveBeenCalledTimes(1);expect(f.mock.calls[0][0]).toBe('/api/account/circle/payments/'+p.id+'/confirm');expect(f.mock.calls[0][1].body).toBe('{"confirmed":true}');});
 it('does not retry an unavailable backend or malformed response',async()=>{const f=vi.fn().mockResolvedValue(new Response('{}',{status:404}));vi.stubGlobal('fetch',f);await expect(circleRequest('status',circleStatusSchema)).rejects.toThrow('NOT_DEPLOYED');expect(f).toHaveBeenCalledTimes(1);f.mockResolvedValue(new Response('{}'));await expect(circleRequest('status',circleStatusSchema)).rejects.toThrow('INVALID');expect(f).toHaveBeenCalledTimes(2);});
});
