// @vitest-environment jsdom
import {it,expect,vi,afterEach,beforeEach} from 'vitest';import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {ContextHelp} from '@/components/product/ContextHelp';import {OperatorGuide} from '@/components/product/OperatorGuide';
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;let root:Root|undefined,el:HTMLDivElement;
beforeEach(()=>{HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};vi.stubGlobal('matchMedia',()=>({matches:true}));HTMLElement.prototype.scrollIntoView=vi.fn()});
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.innerHTML='';vi.unstubAllGlobals()});
async function render(element:React.ReactNode){el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(element))}
it('help opens on keyboard focus with connected tooltip semantics',async()=>{await render(React.createElement(ContextHelp,{label:'Explain task cap'},'Never spends above your limit'));const b=el.querySelector('button')!;await act(async()=>b.focus());const tip=el.querySelector('[role=tooltip]')!;expect(tip.textContent).toContain('Never spends');expect(b.getAttribute('aria-describedby')).toBe(tip.id);expect(b.getAttribute('aria-expanded')).toBe('true')});
it('Escape dismisses help without submitting or moving funds',async()=>{const submit=vi.fn();await render(React.createElement('form',{onSubmit:submit},React.createElement(ContextHelp,{label:'Explain reserve'},'A floor, not a fund lock')));await act(async()=>el.querySelector('button')!.click());await act(async()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));expect(el.querySelector('[role=tooltip]')).toBeNull();expect(submit).not.toHaveBeenCalled()});
it('outside touch dismisses a help popup',async()=>{await render(React.createElement(ContextHelp,{label:'Region help'},'Region restrictions'));await act(async()=>el.querySelector('button')!.click());await act(async()=>document.body.dispatchEvent(new Event('pointerdown',{bubbles:true})));expect(el.querySelector('[role=tooltip]')).toBeNull()});
it('guide has three actionable steps, applies example only, never calls network',async()=>{const onExample=vi.fn(),fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render(React.createElement(OperatorGuide,{lang:'en',onExample}));await act(async()=>el.querySelector('button')!.click());expect(el.querySelector('dialog')!.hasAttribute('open')).toBe(true);const find=(text:string)=>[...el.querySelectorAll('button')].find(x=>x.textContent?.includes(text))!;await act(async()=>find('Use this example').click());expect(onExample).toHaveBeenCalledTimes(1);expect(el.textContent).toContain('Set a spending boundary');await act(async()=>find('Next').click());expect(el.textContent).toContain('Review the proposed purchase');await act(async()=>find('Go to my task').click());expect(el.querySelector('dialog')!.hasAttribute('open')).toBe(false);expect(fetch).not.toHaveBeenCalled()});
it('guide can be closed and reopened at first step in Russian',async()=>{await render(React.createElement(OperatorGuide,{lang:'ru',onExample:vi.fn()}));await act(async()=>el.querySelector('button')!.click());expect(el.textContent).toContain('Скажите, что ищете');await act(async()=>el.querySelector<HTMLButtonElement>('[aria-label="Закрыть подсказку"]')!.click());expect(el.querySelector('dialog')!.hasAttribute('open')).toBe(false)});
