// @vitest-environment jsdom
import {afterEach,it,expect,vi} from 'vitest';import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {DepositIntentForm} from '@/components/product/DepositIntentForm';
let root:Root|undefined,container:HTMLDivElement;(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const wallet='0x'+'a'.repeat(40),receiver='0x'+'b'.repeat(40);const base={wallet,receiver,readOnly:false,busy:false,lang:'en' as const,onCreated:vi.fn(),onSwitchWallet:vi.fn()};
async function render(extra:object={}){container=document.createElement('div');document.body.append(container);root=createRoot(container);await act(async()=>root!.render(React.createElement(DepositIntentForm,{...base,create:vi.fn(),...extra})));}
const button=()=>[...container.querySelectorAll('button')].find(b=>b.textContent?.includes('Create deposit intent'))!;
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.innerHTML='';vi.clearAllMocks()});
it('same receiver prevents any request and explains wallet switch',async()=>{const create=vi.fn();await render({receiver:wallet,create});expect(container.textContent).toContain('Use a different funding wallet');expect(button().disabled).toBe(true);await act(async()=>button().click());expect(create).not.toHaveBeenCalled();await act(async()=>[...container.querySelectorAll('button')].find(b=>b.textContent?.includes('Sign out'))!.click());expect(base.onSwitchWallet).toHaveBeenCalledTimes(1)});
it('distinct wallet explicitly creates an intent, never sends a transaction',async()=>{const create=vi.fn(async()=>({id:'intent',status:'AWAITING_TRANSFER'}));await render({create});expect(create).not.toHaveBeenCalled();await act(async()=>button().click());expect(create).toHaveBeenCalledTimes(1);expect(create.mock.calls[0][0]).toMatchObject({amount:'10.000000'});expect(base.onCreated).toHaveBeenCalledWith({id:'intent',status:'AWAITING_TRANSFER'})});
it('ambiguous retries use the same request id',async()=>{const ids:string[]=[];const create=vi.fn(async(b:{requestId:string})=>{ids.push(b.requestId);throw Error('BACKEND_UNAVAILABLE')});await render({create});await act(async()=>button().click());expect(container.textContent).toContain('Retry keeps the same request');await act(async()=>button().click());expect(ids).toHaveLength(2);expect(ids[0]).toBe(ids[1])});
it('rapid double-click cannot create duplicate concurrent requests',async()=>{let resolve:(v:Record<string,string>)=>void=()=>{};const create=vi.fn(()=>new Promise<Record<string,string>>(r=>{resolve=r}));await render({create});await act(async()=>{button().click();button().click()});expect(create).toHaveBeenCalledTimes(1);await act(async()=>resolve({id:'intent'}))});
