// @vitest-environment jsdom
import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {it,expect,vi,afterEach} from 'vitest';import {EarnHub} from '@/components/earn/EarnHub';import {unavailableEarn,type EarnSnapshot} from '@/lib/earn-market';
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined,host:HTMLDivElement;
afterEach(async()=>{if(root)await act(async()=>root?.unmount());root=undefined;document.body.innerHTML='';vi.useRealTimers();vi.unstubAllGlobals()});
async function render(s:EarnSnapshot){vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>s}));host=document.createElement('div');document.body.append(host);root=createRoot(host);await act(async()=>root?.render(<EarnHub/>));}
const ready=()=>({...unavailableEarn(),status:'available',reason:'VERIFIED_EXTERNAL_MARKET',observedAt:Date.now(),expiresAt:Date.now()+30000,annualRatePercent:'4.32',blockNumber:'100',blockHash:'0x'+'1'.repeat(64)} as EarnSnapshot);
it('external link requires explicit risk consent and is pinned to official provider',async()=>{await render(ready());expect(host.querySelector('a[href="https://app.aave.com/"]')).toBeNull();await act(async()=>host.querySelector('input')!.click());expect(host.querySelector('a[href="https://app.aave.com/"]')?.getAttribute('rel')).toContain('noopener');expect(host.textContent).toContain('Not Arc');expect(host.textContent).toContain('4.32%');expect(fetch).toHaveBeenCalledWith('/api/earn/market',expect.objectContaining({cache:'no-store'}));});
it('unavailable data never displays a fake percent or permits continuation',async()=>{await render(unavailableEarn());await act(async()=>host.querySelector('input')!.click());expect(host.querySelector('a[href="https://app.aave.com/"]')).toBeNull();expect(host.textContent).not.toContain('4.32%');expect(host.textContent).toContain('Verification unavailable')});
it('expired verification disables a previously consented link',async()=>{vi.useFakeTimers();await render(ready());await act(async()=>host.querySelector('input')!.click());expect(host.querySelector('a[href="https://app.aave.com/"]')).not.toBeNull();await act(async()=>vi.advanceTimersByTime(31000));expect(host.querySelector('a[href="https://app.aave.com/"]')).toBeNull();});
it('Russian copy explains separate funds and protocol losses',async()=>{await render(ready());const ru=Array.from(host.querySelectorAll('button')).find(b=>b.textContent==='RU')!;await act(async()=>ru.click());expect(host.textContent).toContain('Не Arc');expect(host.textContent).toContain('компенсировать потери протокола')});
