// @vitest-environment jsdom
import React,{act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {it,expect,vi,afterEach,beforeEach} from 'vitest';
import {composeRelease,sampleHistory,uptime,redactTrace} from '@/lib/release-composer';
import {DeveloperBlock,SDKHero,API_SNIPPETS,INSTALL_COMMANDS,WorkflowContrast} from '@/components/experience/LandingBlocks';
import {PrivacyConsent,SecretReveal,FirstRun,ToastStack,notify} from '@/components/experience/Primitives';
import {ServiceHistory} from '@/components/experience/ServiceHistory';
import {AccountOverview} from '@/components/experience/AccountOverview';
import OperationsLab from '@/components/experience/OperationsLab';
import ReleaseComposer from '@/components/experience/ReleaseComposer';
import {RunTrace} from '@/components/experience/RunTrace';
import type {OperatorRun} from '@/lib/operator-client';
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined,host:HTMLElement;
beforeEach(()=>{localStorage.clear();sessionStorage.clear();HTMLDialogElement.prototype.showModal=function(){this.open=true};HTMLDialogElement.prototype.close=function(){this.open=false};vi.stubGlobal('matchMedia',()=>({matches:false}));Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:vi.fn().mockResolvedValue(undefined)}})});
afterEach(async()=>{if(root)await act(async()=>root?.unmount());root=undefined;document.body.innerHTML='';vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals()});
async function render(element:React.ReactNode){host=document.createElement('div');document.body.append(host);root=createRoot(host);await act(async()=>root?.render(element))}
async function click(text:string){const button=Array.from(host.querySelectorAll('button')).find(b=>b.textContent?.trim()===text);expect(button).toBeTruthy();await act(async()=>button!.click())}
it('release: minor feature and scoped fix grouping',()=>{const r=composeRelease('feat(catalog): group regions\nfix: repair labels','1.2.3');expect(r.next).toBe('1.3.0');expect(r.groups.features).toEqual(['catalog: group regions']);expect(r.groups.fixes).toEqual(['repair labels'])});
it('release: breaking marker wins over feature',()=>{expect(composeRelease('feat(api)!: new contract','1.2.3').next).toBe('2.0.0')});
it('release: breaking footer triggers major',()=>{expect(composeRelease('fix: change\nBREAKING CHANGE: contract','0.1.2').bump).toBe('major')});
it('release: malformed and unknown types ignored',()=>{const r=composeRelease('bad\nunknown: nope\nfix: valid','0.1.0');expect(r.ignored).toBe(2);expect(r.next).toBe('0.1.1')});
it('release: empty input causes no bump',()=>{expect(composeRelease('','1.2.3').bump).toBe('none')});
it('release: rejects non-semver input and bounds workload',()=>{expect(composeRelease('feat: hi','no').valid).toBe(false);expect(composeRelease('a'.repeat(40000),'1.0.0').ignored).toBe(1)});
it('history is stable and weights degradation without treating unknown as healthy',()=>{expect(sampleHistory(75)).toEqual(sampleHistory(75));expect(sampleHistory(75)).toHaveLength(60);expect(uptime(['unknown','unknown'])).toBeNull();expect(uptime(['operational','degraded','outage'])).toBe(50)});
it('trace redacts credentials and bounds nested output',()=>{const result=redactTrace({apiKey:'private',codes:['private'],nested:{authorization:'private'},text:'Bearer abcdefghijklmnop'});expect(JSON.stringify(result)).not.toContain('private');expect(JSON.stringify(result)).not.toContain('abcdefghijklmnop')});
it('contrast presents five matched topics per card',async()=>{await render(<WorkflowContrast/>);expect(host.querySelectorAll('article')).toHaveLength(2);expect(host.querySelectorAll('article li')).toHaveLength(10);expect(host.textContent).not.toContain('Median setup')});
it('language tabs render and copy current real read-only snippet',async()=>{await render(<DeveloperBlock/>);await click('Python');expect(host.querySelector('pre')?.textContent).toBe(API_SNIPPETS.Python);await click('Copy');expect(navigator.clipboard.writeText).toHaveBeenCalledWith(API_SNIPPETS.Python);expect(host.textContent).toContain('Copied')});
it('SDK tabs copy commands without a shell prompt',async()=>{await render(<SDKHero/>);await click('pnpm');await click('Copy');expect(navigator.clipboard.writeText).toHaveBeenCalledWith(INSTALL_COMMANDS.pnpm);expect(host.textContent).not.toContain('12k stars')});
it('consent emits and persists rejection',async()=>{const listener=vi.fn();window.addEventListener('cookie-consent',listener);await render(<PrivacyConsent/>);await click('Reject optional');expect(JSON.parse(localStorage.getItem('mercenta-privacy-choice')!).decision).toBe('rejected');expect(listener).toHaveBeenCalledOnce();window.removeEventListener('cookie-consent',listener);expect(host.querySelector('aside')).toBeNull()});
it('consent remains usable when browser storage throws',async()=>{vi.spyOn(Storage.prototype,'getItem').mockImplementation(()=>{throw Error('private')});vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('private')});await render(<PrivacyConsent/>);await click('Accept optional');expect(host.querySelector('aside')).toBeNull()});
it('welcome tour choice remembers opt-out without granting spending',async()=>{const tour=vi.fn();await render(<FirstRun onTour={tour}/>);expect(host.querySelector('dialog')?.open).toBe(true);const checkbox=host.querySelector('input')!;await act(async()=>checkbox.click());await click('Take the tour');expect(tour).toHaveBeenCalledOnce();expect(localStorage.getItem('mercenta-welcome-v1')).toBe('hidden');expect(host.querySelector('dialog')?.open).toBe(false)});
it('secret starts masked, gates confirmation and remasks at thirty seconds',async()=>{vi.useFakeTimers();const stored=vi.fn();await render(<SecretReveal secret="synthetic-example-only" name="Test" scopes={['account:read']} onStored={stored}/>);expect(host.textContent).not.toContain('synthetic-example-only');const confirm=Array.from(host.querySelectorAll('button')).find(b=>b.textContent==='Confirm & clear secret')!;expect(confirm.disabled).toBe(true);await click('Reveal');expect(host.textContent).toContain('synthetic-example-only');await act(async()=>vi.advanceTimersByTime(30000));expect(host.textContent).not.toContain('synthetic-example-only');await act(async()=>host.querySelector('input')!.click());await click('Confirm & clear secret');expect(stored).toHaveBeenCalledOnce()});
it('unknown status renders sixty neutral bars per service; demo is explicit',async()=>{await render(<ServiceHistory/>);expect(host.querySelectorAll('.me-day.unknown')).toHaveLength(241);expect(host.textContent).toContain('Uptime unavailable');await click('Preview sample history');expect(host.textContent).toContain('SAMPLE');expect(host.textContent).toContain('Not measured Mercenta uptime')});
it('dashboard uses account values and no fake revenue or growth',async()=>{const change=vi.fn();await render(<AccountOverview stats={{totalOrders:2,shopOrders:1,directTopUpOrders:1,totalSpentUnits:'2000000'}} loading={false} period="30d" onPeriod={change}/>);expect(host.textContent).toContain('2.000000');expect(host.textContent).toContain('Not business sales');await click('7d');expect(change).toHaveBeenCalledWith('7d')});
it('operations start disconnected and do not fetch when browsing demos',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render(<OperationsLab/>);expect(host.textContent).toContain('NOT CONNECTED');await click('Inspect a demonstration');await click('DEMO-API-01');expect(host.textContent).toContain('Developer token bundle');expect(fetch).not.toHaveBeenCalled()});
it('demo webhook retries wait 2, 4, 8 seconds, preserve attempts and send nothing',async()=>{vi.useFakeTimers();const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render(<OperationsLab/>);await click('Inspect a demonstration');await click('Webhooks');await click('Simulate 2s / 4s / 8s retry');await act(async()=>vi.advanceTimersByTimeAsync(2000));expect(host.textContent).toContain('#2 · 503');await act(async()=>vi.advanceTimersByTimeAsync(4000));expect(host.textContent).toContain('#3 · 503');await act(async()=>vi.advanceTimersByTimeAsync(8000));expect(host.textContent).toContain('#4 · 200');expect(host.textContent).toContain('Simulated success');expect(fetch).not.toHaveBeenCalled()});
it('run visual replay does not invoke backend tools and hides secret output',async()=>{vi.useFakeTimers();const fetch=vi.fn();vi.stubGlobal('fetch',fetch);const run={id:'synthetic-run',status:'QUOTED',createdAt:10,updatedAt:30,events:[{seq:1,tool:'catalog.search',status:'SUCCESS',reason:'Public catalogue',result:{count:1,apiKey:'hidden-value'},provider:null}]} as unknown as OperatorRun;await render(<RunTrace run={run}/>);await act(async()=>host.querySelector<HTMLButtonElement>('.me-trace-row')!.click());expect(host.textContent).not.toContain('hidden-value');await click('Replay view');expect(host.querySelectorAll('.me-trace-row')).toHaveLength(0);await act(async()=>vi.advanceTimersByTimeAsync(350));expect(host.querySelectorAll('.me-trace-row')).toHaveLength(1);expect(fetch).not.toHaveBeenCalled()});
it('toast stack pauses under pointer and expires after five unpaused seconds',async()=>{vi.useFakeTimers({toFake:['setTimeout','clearTimeout','setInterval','clearInterval','Date','performance']});await render(<ToastStack/>);await act(async()=>notify('Saved','Synthetic test'));expect(host.textContent).toContain('Saved');await act(async()=>vi.advanceTimersByTime(1000));await act(async()=>host.querySelector('.me-toast').dispatchEvent(new MouseEvent('mouseover',{bubbles:true})));await act(async()=>vi.advanceTimersByTime(6000));expect(host.textContent).toContain('Saved');await act(async()=>host.querySelector('.me-toast').dispatchEvent(new MouseEvent('mouseout',{bubbles:true})));await act(async()=>vi.advanceTimersByTime(4300));expect(host.textContent).not.toContain('Saved')});

it("release fields have stable accessible names independent of seeded values",async()=>{await render(<ReleaseComposer/>);expect(host.querySelector("textarea")?.getAttribute("aria-label")).toBe("Conventional commits");expect(host.querySelector("input")?.getAttribute("aria-label")).toBe("Current version")});
