// @vitest-environment jsdom
import {it,expect,vi,afterEach,beforeEach} from 'vitest';
import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';
import {WorkspaceNavigator} from '@/components/product/WorkspaceNavigator';import {HelpTip} from '@/components/product/HelpTip';
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined,el:HTMLDivElement;
beforeEach(()=>{HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};});
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.innerHTML='';document.body.style.overflow='';vi.unstubAllGlobals();});
async function render(node:React.ReactNode){el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(node));}
async function click(selector:string){await act(async()=>{(document.querySelector(selector) as HTMLButtonElement).click()});}
async function key(key:string,extra:KeyboardEventInit={}){await act(async()=>document.activeElement!.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,...extra})));}
async function type(value:string){const input=document.querySelector('input')!;const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!;await act(async()=>{setter.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));});}
it('quick navigation opens with Ctrl K, focuses search and executes navigation only',async()=>{const nav=vi.fn(),fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render(<WorkspaceNavigator onNavigate={nav}/>);await key('k',{ctrlKey:true});expect(document.querySelector('dialog[open]')).toBeTruthy();expect(document.activeElement?.getAttribute('aria-label')).toBe('Search workspace');await click('[data-nav-result]:nth-child(2)');expect(nav).toHaveBeenCalledWith('Shop');expect(document.querySelector('dialog')).toBeNull();expect(fetch).not.toHaveBeenCalled();});
it('filters bilingual destinations and has a helpful empty state',async()=>{await render(<WorkspaceNavigator ru onNavigate={vi.fn()}/>);await click('.pd-nav-trigger');await type('бюджет');expect(document.querySelectorAll('[data-nav-result]').length).toBe(1);await type('zzzz');expect(document.querySelector('[role=status]')?.textContent).toContain('Раздел не найден');});
it('mainnet navigation cannot expose account, orders or budget actions',async()=>{await render(<WorkspaceNavigator network="mainnet" onNavigate={vi.fn()}/>);await click('.pd-nav-trigger');const titles=Array.from(document.querySelectorAll('[data-nav-result] strong')).map(e=>e.textContent);expect(titles).toContain('Launch status');expect(titles).not.toContain('Account');expect(titles).not.toContain('Budget');expect(titles).not.toContain('Purchases');expect(document.querySelector('a[href="/refund"]')).toBeTruthy();});
it('Escape restores trigger focus and releases scroll lock',async()=>{await render(<WorkspaceNavigator onNavigate={vi.fn()}/>);const b=document.querySelector('.pd-nav-trigger') as HTMLButtonElement;b.focus();await click('.pd-nav-trigger');expect(document.body.style.overflow).toBe('hidden');await key('Escape');expect(document.activeElement).toBe(b);expect(document.body.style.overflow).toBe('');});
it('arrow navigation visits results and disabled controls ignore hotkeys',async()=>{await render(<WorkspaceNavigator onNavigate={vi.fn()}/>);await click('.pd-nav-trigger');await key('ArrowDown');expect(document.activeElement?.hasAttribute('data-nav-result')).toBe(true);await key('Escape');await act(async()=>root!.render(<WorkspaceNavigator disabled onNavigate={vi.fn()}/>));await key('k',{ctrlKey:true});expect(document.querySelector('dialog')).toBeNull();});
it('never stacks a command dialog over another confirmation',async()=>{await render(<WorkspaceNavigator onNavigate={vi.fn()}/>);const d=document.createElement('div');d.setAttribute('aria-modal','true');document.body.append(d);await key('k',{ctrlKey:true});expect(document.querySelector('dialog')).toBeNull();});
it('SVG help is portalled within the viewport and dismisses on Escape',async()=>{await render(<HelpTip label="Region help">Match redemption rules.</HelpTip>);await click('.mc-help-trigger');const tip=document.querySelector('[role=tooltip]') as HTMLElement;expect(tip?.parentElement).toBe(document.body);expect(tip.textContent).toContain('Match redemption');expect(parseFloat(tip.style.left)).toBeGreaterThanOrEqual(16);expect(document.querySelector('.mc-help-trigger svg')).toBeTruthy();await key('Escape');expect(document.querySelector('[role=tooltip]')).toBeNull();});
it('help dismisses on outside pointer or scroll without changing a form',async()=>{await render(<HelpTip label="Amount help">No authorization.</HelpTip>);await click('.mc-help-trigger');await act(async()=>document.body.dispatchEvent(new Event('pointerdown',{bubbles:true})));expect(document.querySelector('[role=tooltip]')).toBeNull();await click('.mc-help-trigger');await act(async()=>window.dispatchEvent(new Event('scroll')));expect(document.querySelector('[role=tooltip]')).toBeNull();});
