// @vitest-environment jsdom
import {it,expect,vi,afterEach} from 'vitest';import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {LiquidityCockpit} from '@/components/product/LiquidityCockpit';import {ServiceAvailability} from '@/components/product/ServiceAvailability';
vi.mock('@/components/product/finance-hub.css',()=>({}));(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;let root:Root|undefined,el:HTMLDivElement;const caps={mainnetEnabled:false,earn:{configured:false,executionEnabled:false},borrow:{configured:false,executionEnabled:false},onramp:{configured:false,executionEnabled:false}};
async function render(component:React.ReactNode){el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(component))}afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.innerHTML='';vi.unstubAllGlobals()});const button=(text:string)=>[...el.querySelectorAll('button')].find(x=>x.textContent?.includes(text))!;
it('no configured integration shows no invented funds or yield and disables SDK action',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json(caps)));await render(React.createElement(LiquidityCockpit));expect(el.textContent).toContain('No invented treasury balance');expect(button('Check SDK discovery').disabled).toBe(true);expect(el.textContent).toContain('0.00 USDC')});
it('borrow remains scenario-only and never originates a loan',async()=>{const fetch=vi.fn(async()=>Response.json(caps));vi.stubGlobal('fetch',fetch);await render(React.createElement(LiquidityCockpit));await act(async()=>button('Borrow').click());expect(el.textContent).toContain('no live market');expect(button('Live borrowing').disabled).toBe(true);expect(fetch.mock.calls.length).toBe(1)});
it('onramp does not create hosted session or collect card data with missing credentials',async()=>{const fetch=vi.fn(async()=>Response.json(caps));vi.stubGlobal('fetch',fetch);await render(React.createElement(LiquidityCockpit));await act(async()=>button('Onramp').click());expect(button('Hosted Onramp').disabled).toBe(true);expect(el.querySelector('input[autocomplete="cc-number"]')).toBeNull();expect(fetch.mock.calls.length).toBe(1)});
it('maintenance status fails closed on unknown or failed balance checks',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>{throw Error('offline')}));await render(React.createElement(ServiceAvailability,{lang:'en'}));expect(el.textContent).toContain('Technical maintenance');expect(el.textContent).toContain('Existing orders and support remain accessible')});
it('unsupported mainnet capability payload cannot enable finance controls',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json({...caps,mainnetEnabled:true,earn:{configured:true,executionEnabled:true}})));await render(React.createElement(LiquidityCockpit));expect(button('Check SDK discovery').disabled).toBe(true);expect(el.textContent).toContain('could not be verified')});

it('SDK vault metadata renders addresses, not raw APY or a live deposit button',async()=>{const address='0x'+'a'.repeat(40);vi.stubGlobal('fetch',vi.fn(async(url:string)=>Response.json(url.includes('earn-discovery')?{mode:'sdk-metadata',chainId:5042002,executionEnabled:false,currentYieldVerified:false,vaults:[{name:'SDK test vault',asset:'USDC',address,currentApy:99}]}:{...caps,earn:{configured:true,executionEnabled:false}})));await render(React.createElement(LiquidityCockpit));expect(button('Check SDK discovery').disabled).toBe(false);await act(async()=>button('Check SDK discovery').click());expect(el.textContent).toContain('SDK test vault');expect(el.textContent).toContain(address);expect(el.textContent).not.toContain('99%');expect(el.textContent).toContain('not verified live yield')});
