// @vitest-environment jsdom
import {it,expect,vi,afterEach} from 'vitest';
import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';
import {GuideHub} from '@/components/guides/GuideHub';
import {HELP_TOPICS,searchHelp} from '@/components/guides/guide-content';
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined;
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.innerHTML='';vi.unstubAllGlobals()});
async function render(page:'start'|'support'){const el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(<GuideHub page={page}/>))}
it('finds bilingual answers and intersects query with category',()=>{expect(searchHelp('seed','support').map(x=>x.id)).toContain('secrets');expect(searchHelp('возврат','support').map(x=>x.id)).toContain('refund');expect(searchHelp('zzzz','all')).toEqual([]);expect(searchHelp('wallet','catalogue')).toEqual([]);expect(new Set(HELP_TOPICS.map(t=>t.id)).size).toBe(HELP_TOPICS.length)});
it('getting started has three useful paths and never calls a payment API',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render('start');expect(document.querySelectorAll('.gh-paths article')).toHaveLength(3);expect(document.querySelector('.gh-paths a[href="/catalog"]')).toBeTruthy();expect(document.body.textContent).toContain('Mainnet payments are closed');expect(fetch).not.toHaveBeenCalled();});
it('switches all guide content to Russian without replacing official contact details',async()=>{await render('support');await act(async()=>{Array.from(document.querySelectorAll('.gh-language button')).find(b=>b.textContent==='RU')!.dispatchEvent(new MouseEvent('click',{bubbles:true}))});expect(document.querySelector('.gh')?.getAttribute('lang')).toBe('ru');expect(document.body.textContent).toContain('Как оформить возврат');expect(document.querySelector('a[href="mailto:support@mercenta.xyz"]')).toBeTruthy()});
it('filters help, shows a recovery action, resets search and preserves focus',async()=>{await render('support');const input=document.querySelector('input')!;const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!;await act(async()=>{set.call(input,'zzzz');input.dispatchEvent(new Event('input',{bubbles:true}))});expect(document.querySelector('.gh-empty')).toBeTruthy();expect(document.querySelectorAll('details')).toHaveLength(0);await act(async()=>{(document.querySelector('.gh-empty button') as HTMLButtonElement).click()});expect(document.querySelectorAll('details')).toHaveLength(HELP_TOPICS.length);expect(document.activeElement).toBe(input)});
it('uses accessible native disclosures and routes refunds to manual review only',async()=>{await render('support');expect(document.querySelectorAll('details>summary')).toHaveLength(HELP_TOPICS.length);const refund=Array.from(document.querySelectorAll('details')).find(d=>d.textContent?.includes('How do refunds work'))!;expect(refund.textContent).toContain('manually');expect(refund.querySelector('a')?.getAttribute('href')).toBe('/refund');expect(document.querySelector('[role=status]')?.textContent).toContain('10');});
