import {it,expect,vi,beforeEach} from 'vitest';
import {MORPHO_VAULTS,MORPHO_ARC} from '@/lib/morpho-market';
const state=vi.hoisted(()=>({failRpc:false,chain:5042}));
vi.mock('viem',async original=>{const real=await original<typeof import('viem')>();return {...real,createPublicClient:()=>({getChainId:async()=>state.chain,getBlockNumber:async()=>100n,getBlock:async()=>({hash:'0x'+'1'.repeat(64),timestamp:BigInt(Math.floor(Date.now()/1000)-2)}),getCode:async()=>{if(state.failRpc)throw Error('SENSITIVE_RPC_BODY');return '0x1234'},readContract:async({functionName}:{functionName:string})=>functionName==='asset'?MORPHO_ARC.usdc:functionName==='totalAssets'?1000000000n:functionName.endsWith('Gate')?'0x'+'0'.repeat(40):0n}),keccak256:()=>MORPHO_VAULTS[0].codeHash};});
beforeEach(()=>{vi.resetModules();state.failRpc=false;state.chain=5042;vi.unstubAllGlobals()});
const payload=()=>({data:{vaultV2s:{items:MORPHO_VAULTS.map(v=>({address:v.address,asset:{address:MORPHO_ARC.usdc,decimals:6},chain:{id:5042},listed:true,netApy:.023,performanceFee:0,managementFee:0,liquidity:'100000000',warnings:[]})),pageInfo:{countTotal:3,count:3}}}});
function fetchResponse(body=JSON.stringify(payload()),status=200){vi.stubGlobal('fetch',vi.fn().mockImplementation(async()=>new Response(body,{status,headers:{'Content-Type':'application/json'}})));}
it('coalesces bounded API read and pins endpoint/query without customer values',async()=>{fetchResponse();const {readMorphoMarket}=await import('@/lib/morpho-market-server');const [a,b]=await Promise.all([readMorphoMarket(),readMorphoMarket()]);expect(a).toEqual(b);expect(fetch).toHaveBeenCalledTimes(1);expect(fetch).toHaveBeenCalledWith(MORPHO_ARC.apiUrl,expect.objectContaining({method:'POST',redirect:'error',cache:'no-store'}));const args=vi.mocked(fetch).mock.calls[0][1];expect(args?.body).toContain('first:10');expect(args?.body).not.toContain('wallet');},15000);
it.each(['http','malformed','oversized','incomplete','errors','rpc','wrong-chain'])('fails closed without body leakage for %s',async kind=>{const d=payload();if(kind==='incomplete')d.data.vaultV2s.pageInfo.countTotal=4;fetchResponse(kind==='malformed'?'SECRET_BAD_JSON':kind==='oversized'?'x'.repeat(25000):kind==='errors'?JSON.stringify({errors:['SECRET_FAILURE']}):JSON.stringify(d),kind==='http'?503:200);state.failRpc=kind==='rpc';state.chain=kind==='wrong-chain'?1:5042;const {readMorphoMarket}=await import('@/lib/morpho-market-server');const s=await readMorphoMarket();expect(s.vaults.every(v=>v.status==='unavailable')).toBe(true);expect(JSON.stringify(s)).not.toContain('SECRET');expect(JSON.stringify(s)).not.toContain('SENSITIVE')});
