import {describe,it,expect} from 'vitest';
import {assessMorpho,unavailableMorpho,MORPHO_VAULTS,MORPHO_ARC,canExploreMorpho,morphoSnapshotSchema,formatMorphoUsdc,type MorphoWitness} from '@/lib/morpho-market';
const now=1800000000000;
function fixtures(){const row:MorphoWitness={chainId:5042,blockNumber:'1000',blockHash:'0x'+'1'.repeat(64),timestamp:now/1000-5,vaults:MORPHO_VAULTS.map(v=>({address:v.address,codeHash:v.codeHash,asset:MORPHO_ARC.usdc,totalAssets:'1000000000',performanceFee:'0',managementFee:'0',gates:Array(4).fill('0x'+'0'.repeat(40))}))};return {rows:[row,structuredClone(row)],api:{items:MORPHO_VAULTS.map(v=>({address:v.address,asset:{address:MORPHO_ARC.usdc,decimals:6},chain:{id:5042},listed:true,netApy:.023,performanceFee:0,managementFee:0,liquidity:'100000000',warnings:[]}))}};}
describe('Morpho read-only market',()=>{
 it('uses pinned vaults, excludes money operations and labels API rates',()=>{const f=fixtures(),s=assessMorpho(f.api,f.rows,now);expect(s.vaults.every(v=>v.status==='observed')).toBe(true);expect(s.vaults[0].netApyPercent).toBe('2.30');expect(s.rateKind).toBe('API_REPORTED_VARIABLE_NET_APY');expect(s.indexerFreshness).toBe('not_verified');expect(s.mercentaCustody).toBe(false);expect(morphoSnapshotSchema.safeParse(s).success).toBe(true)});
 it('fails closed for RPC disagreement',()=>{const f=fixtures();f.rows[1].blockHash='0x'+'2'.repeat(64);expect(assessMorpho(f.api,f.rows,now).vaults[0].netApyPercent).toBeNull()});
 it.each(['chain','stale','future','asset','code','fee','gates','empty'])('rejects %s',kind=>{const f=fixtures();for(const row of f.rows){const v=row.vaults[0];if(kind==='chain')row.chainId=1;if(kind==='stale')row.timestamp-=121;if(kind==='future')row.timestamp+=10;if(kind==='asset')v.asset='0x'+'1'.repeat(40);if(kind==='code')v.codeHash='0x'+'9'.repeat(64);if(kind==='fee')v.performanceFee='100000000000000000';if(kind==='gates')v.gates[0]='0x'+'1'.repeat(40);if(kind==='empty')v.totalAssets='0';}expect(assessMorpho(f.api,f.rows,now).vaults[0].status).not.toBe('observed')});
 it.each(['NaN','bad-amount','wrong-chain','wrong-asset','unlisted','warning','no-rate','no-liquidity','duplicate','missing','unsafe-number'])('fails closed for API %s',kind=>{const f=fixtures();const v=f.api.items[0];if(kind==='NaN')v.netApy=NaN;if(kind==='bad-amount')v.liquidity='-1';if(kind==='wrong-chain')v.chain.id=1;if(kind==='wrong-asset')v.asset.address='0x'+'1'.repeat(40);if(kind==='unlisted')v.listed=false;if(kind==='warning')v.warnings=[{type:'risk',level:'RED'}] as never[];if(kind==='no-rate')(v as unknown as {netApy:null}).netApy=null;if(kind==='no-liquidity')v.liquidity='0';if(kind==='duplicate')f.api.items[1].address=v.address;if(kind==='missing')f.api.items.pop();if(kind==='unsafe-number')(v as unknown as {liquidity:number}).liquidity=Number.MAX_SAFE_INTEGER+1;expect(assessMorpho(f.api,f.rows,now).vaults[0].status).not.toBe('observed')});
 it('external exploration requires consent and fresh validated snapshot',()=>{const f=fixtures(),s=assessMorpho(f.api,f.rows,now);expect(canExploreMorpho(s,'galaxy',false,now)).toBe(false);expect(canExploreMorpho(s,'galaxy',true,now)).toBe(true);expect(canExploreMorpho(s,'galaxy',true,now+30000)).toBe(false);expect(canExploreMorpho({...s,expiresAt:now+31000},'galaxy',true,now)).toBe(false);expect(canExploreMorpho(s,'arbitrary',true,now)).toBe(false)});
 it('rejects tampered client snapshot and quantities retain integer precision',()=>{const f=fixtures(),s=assessMorpho(f.api,f.rows,now);s.vaults[0].address='0x'+'9'.repeat(40);expect(morphoSnapshotSchema.safeParse(s).success).toBe(false);expect(formatMorphoUsdc('1000000000000000000000000')).toBe('1,000,000,000,000,000,000 USDC');expect(unavailableMorpho(now).expiresAt).toBe(now)});
});
