// @vitest-environment jsdom
import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {it,expect,vi,afterEach} from 'vitest';
import {MorphoPanel} from '@/components/earn/MorphoPanel';import {unavailableMorpho,type MorphoSnapshot} from '@/lib/morpho-market';
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined,host:HTMLDivElement;
afterEach(async()=>{if(root)await act(async()=>root?.unmount());root=undefined;document.body.innerHTML='';vi.useRealTimers();vi.unstubAllGlobals()});
const ready=()=>{const s=unavailableMorpho();s.expiresAt=s.observedAt+30000;s.blockNumber='100';s.blockHash='0x'+'1'.repeat(64);s.vaults=s.vaults.map(v=>({...v,status:'observed',netApyPercent:'2.30',performanceFeePercent:'0.00',managementFeePercent:'0.00',totalAssetsMicro:'1000000000',reportedLiquidityMicro:'100000000'}));return s;};
async function render(s:MorphoSnapshot,ru=false){vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>s}));host=document.createElement('div');document.body.append(host);root=createRoot(host);await act(async()=>root?.render(<MorphoPanel ru={ru}/>));}
it('does not fetch user addresses or request wallet access; consent gates fixed official URL',async()=>{await render(ready());expect(host.textContent).toContain('2.30%');expect(host.textContent).toContain('Indexer freshness is not verified');expect(host.querySelector('a[href="https://app.morpho.org/"]')).toBeNull();await act(async()=>host.querySelector('input')!.click());expect(host.querySelector('a[href="https://app.morpho.org/"]')?.getAttribute('rel')).toContain('noopener');expect(fetch).toHaveBeenCalledWith('/api/earn/morpho',expect.objectContaining({cache:'no-store'}));});
it('changing the exact vault clears consent and updates details',async()=>{await render(ready());await act(async()=>host.querySelector('input')!.click());const button=Array.from(host.querySelectorAll('button')).find(b=>b.textContent?.includes('Bitwise'))!;await act(async()=>button.click());expect(host.querySelector('input')!.checked).toBe(false);expect(host.querySelector('a[href="https://app.morpho.org/"]')).toBeNull();expect(host.querySelector('a[href*="0x7610094B"]')).not.toBeNull()});
it('missing data has no fabricated yield or official continuation',async()=>{await render(unavailableMorpho());await act(async()=>host.querySelector('input')!.click());expect(host.textContent).not.toContain('2.30%');expect(host.querySelector('a[href="https://app.morpho.org/"]')).toBeNull();});
it('expiry disables exploration even after consent',async()=>{vi.useFakeTimers();await render(ready());await act(async()=>host.querySelector('input')!.click());expect(host.querySelector('a[href="https://app.morpho.org/"]')).not.toBeNull();await act(async()=>vi.advanceTimersByTime(31000));expect(host.querySelector('a[href="https://app.morpho.org/"]')).toBeNull()});
it('Russian copy discloses incomplete review and separation from purchases',async()=>{await render(ready(),true);expect(host.textContent).toContain('Проверка аллокаций');expect(host.textContent).toContain('Отдельно от покупок');expect(host.textContent).toContain('Это не гарантия дохода')});
it('wrong network or tampered pinned address fails closed in browser',async()=>{const s=ready();s.vaults[0].address='0x'+'0'.repeat(40);await render(s);expect(host.textContent).not.toContain('2.30%');await act(async()=>host.querySelector('input')!.click());expect(host.querySelector('a[href="https://app.morpho.org/"]')).toBeNull()});
