import {describe,it,expect} from 'vitest';import {NextRequest} from 'next/server';import {networkFromHost,networkDestination,allowedMainnetApi,NETWORKS} from '@/lib/network-profile';import {middleware} from '@/middleware';import {GET as openapi} from '@/app/api/openapi/route';import {GET as network} from '@/app/api/network/route';import testnet from '@/lib/openapi-testnet.json';import mainnet from '@/lib/openapi-mainnet.json';
describe('Network boundaries',()=>{
 it('recognizes exact hosts only',()=>{expect(networkFromHost('mainnet.mercenta.xyz')).toBe('mainnet');expect(networkFromHost('MAINNET.MERCENTA.XYZ:443')).toBe('mainnet');for(const host of ['app.mercenta.xyz','testnet.mercenta.xyz','localhost','mainnet.mercenta.xyz.evil.tld'])expect(networkFromHost(host)).toBe('testnet')});
 it('uses distinct chain IDs and closed real purchases',()=>{expect(NETWORKS.mainnet.chainId).toBe(5042);expect(NETWORKS.testnet.chainId).toBe(5042002);expect(NETWORKS.mainnet.realPurchasesEnabled).toBe(false);expect(NETWORKS.mainnet.tokenDecimals).toBe(6);expect(NETWORKS.mainnet.nativeDecimals).toBe(18)});
 it('cannot carry a token or arbitrary destination across networks',()=>{const u=new URL(networkDestination('mainnet','https://evil.tld?token=x'));expect(u.origin).toBe('https://mainnet.mercenta.xyz');expect(u.search).not.toContain('token');expect(u.search).not.toContain('evil');});
 it.each(['/api/account/summary','/api/account/orders','/api/account/operator/runs','/api/v1/orders','/api/auth/verify','/api/me','/api/orders','/api/backend/account/summary','/api/liquidity/earn/deposit'])('mainnet blocks %s before proxying',async path=>{for(const method of ['GET','POST']){const r=middleware(new NextRequest('https://mainnet.mercenta.xyz'+path,{method,headers:{cookie:'mercenta_session=untrusted',authorization:'Bearer test-only'}}));expect(r.status).toBe(503);expect((await r.json()).code).toBe('MAINNET_CHECKOUT_NOT_ENABLED');expect(r.headers.get('set-cookie')).toBeNull();expect(r.headers.get('x-middleware-next')).toBeNull()}});
 it('allowlists only readonly metadata on mainnet',()=>{for(const p of ['/api/catalog','/api/network','/api/openapi']){expect(allowedMainnetApi(p,'GET')).toBe(true);expect(allowedMainnetApi(p,'POST')).toBe(false)}expect(allowedMainnetApi('/api/catalog/../account/summary','GET')).toBe(false)});
 it('overwrites forged network request header on app host',()=>{const r=middleware(new NextRequest('https://app.mercenta.xyz/app',{headers:{'x-mercenta-network':'mainnet'}}));expect(r.headers.get('x-middleware-request-x-mercenta-network')).toBe('testnet')});
 it('rewrites mainnet catalogue to preview, discards query secrets',()=>{const r=middleware(new NextRequest('https://mainnet.mercenta.xyz/catalog?token=secret'));expect(r.headers.get('x-middleware-rewrite')).toBe('https://mainnet.mercenta.xyz/app?section=shop');expect(r.headers.get('x-middleware-request-x-mercenta-network')).toBe('mainnet')});
 it('network metadata never advertises mainnet checkout',async()=>{const r=await network(new Request('https://mainnet.mercenta.xyz/api/network'));const data=await r.json();expect(data.checkoutEnabled).toBe(false);expect(data.walletSigningEnabled).toBe(false);expect(data.balancesSharedAcrossNetworks).toBe(false)});
});
describe('OpenAPI contracts',()=>{
 it('has >90 operations and unique operation IDs with complete path parameters',()=>{const ids:string[]=[];for(const [path,item]of Object.entries(testnet.paths))for(const op of Object.values(item)){ids.push(op.operationId);for(const m of path.matchAll(/\{([^}]+)\}/g))expect(op.parameters.some(p=>p.in==='path'&&p.name===m[1]&&p.required)).toBe(true)}expect(ids.length).toBeGreaterThan(90);expect(new Set(ids).size).toBe(ids.length)});
 it('represents monetary bounds and explicit test consent',()=>{const schema=testnet.paths['/api/account/operator/runs'].post.requestBody.content['application/json'].schema;expect(schema.properties.budgetUsdc.pattern).toContain('6');expect(schema.properties.execution.enum).toEqual(['review','delegated']);expect(schema.required).toContain('authorizeTestSpend');expect(testnet.paths['/api/account/catalog-checkout/confirm'].post.requestBody.content['application/json'].schema.properties.confirmNonRedeemable.const).toBe(true)});
 it('contains no enabled mainnet financial operation or successful closed response',()=>{expect(mainnet['x-chain-id']).toBe(5042);for(const [p,item]of Object.entries(mainnet.paths))for(const [m,raw]of Object.entries(item)){const o=raw as unknown as {'x-enabled':boolean;responses:Record<string,unknown>};if(!(p==='/api/support/refund'&&m==='post')&&(!['/api/catalog','/api/network','/api/openapi','/api/mainnet-readiness'].includes(p)||m!=='get')){expect(o['x-enabled']).toBe(false);expect(Object.keys(o.responses)).toEqual(['503'])}}});
 it('rejects invalid profile and defaults to request host',async()=>{expect((await openapi(new Request('https://app.mercenta.xyz/api/openapi?network=evil'))).status).toBe(400);expect((await(await openapi(new Request('https://mainnet.mercenta.xyz/api/openapi'))).json())['x-network']).toBe('mainnet')});
});
