import {it,expect,vi,afterEach} from 'vitest';import {operatorRunSchema,operatorRequest,operatorError} from '@/lib/operator-client';
const id='12345678-1234-4234-8234-123456789012';const run={id,status:'PLANNING',input:{message:'Find Roblox',budgetUsdc:'3',reserveUsdc:'0',budgetUnits:'3000000',reserveUnits:'0',region:'US',quantity:1,execution:'review'},step:0,maxSteps:6,provider:null,error:null,leaseUntil:0,createdAt:1,updatedAt:1,expiresAt:2,events:[],quote:null,receipt:null,scope:{chainId:5042002,maxOrders:1,supplierOrders:0,realPurchasingEnabled:false}};
afterEach(()=>vi.unstubAllGlobals());
it('accepts bounded testnet task',()=>expect(operatorRunSchema.parse(run).scope.maxOrders).toBe(1));
it('refuses mainnet and supplier execution payloads',()=>{expect(operatorRunSchema.safeParse({...run,scope:{...run.scope,chainId:1}}).success).toBe(false);expect(operatorRunSchema.safeParse({...run,scope:{...run.scope,supplierOrders:1}}).success).toBe(false)});
it('rejects malformed tool observations',()=>expect(operatorRunSchema.safeParse({...run,events:[{seq:1,tool:'catalog.search',status:'CHECKED',reason:'',provider:null,result:null}]}).success).toBe(false));
it('private requests are no-store and exact posted body',async()=>{const fetch=vi.fn(async()=>new Response(JSON.stringify(run)));vi.stubGlobal('fetch',fetch);await operatorRequest('runs',operatorRunSchema,{requestId:id});expect(fetch.mock.calls[0][1]).toMatchObject({cache:'no-store',method:'POST',body:JSON.stringify({requestId:id})})});
it('malformed success never becomes financial success',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({status:'EXECUTED'}))));await expect(operatorRequest('runs',operatorRunSchema)).rejects.toThrow('OPERATOR_RESPONSE_INVALID')});
it('errors do not expose raw backend details',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({message:'private stack'}),{status:500})));await expect(operatorRequest('runs',operatorRunSchema)).rejects.toThrow('SERVICE_UNAVAILABLE');expect(operatorError('unknown',false)).not.toContain('unknown')});
