import {describe,it,expect} from 'vitest';import {NextRequest} from 'next/server';import {middleware} from '@/middleware';import {scenarioUnits,blindGrantSchema,blindReceiptSchema} from '@/lib/operator-lab-client';import {planCapital,type CapitalSnapshot} from '@/lib/capital-policy';
const snapshot:CapitalSnapshot={settledCashUnits:'500000000',reserveFloorUnits:'100000000',reservedOrderUnits:'25000000',refundLiabilityUnits:'25000000',liquidityBufferUnits:'25000000',burn30dUnits:'0',pendingPurchaseUnits:'0',yieldRedeemableUnits:'500000000',pendingIncomingUnits:'0',maxActionUnits:'250000000',observedAt:100000,redemptionDelayMs:86400000,obligations:[{id:'bill',dueAt:101000,amountUnits:'50000000'}],redemptionState:'NONE',paused:false,eligibilityVerified:false,quoteFresh:true};
describe('capital lab boundaries',()=>{
 it('uses exact six-decimal amounts, not floating point',()=>{expect(scenarioUnits('500')).toBe('500000000');expect(scenarioUnits('0.000001')).toBe('1');expect(scenarioUnits('1.234567')).toBe('1234567');});
 it.each(['-1','1e6','1.1234567','01','','Infinity'])('rejects malformed amount %s',v=>expect(()=>scenarioUnits(v)).toThrow());
 it('never presents a plan as live yield execution',()=>{const p=planCapital(snapshot,100000);expect(p.executionEnabled).toBe(false);expect(p.actualYieldUnits).toBeNull();expect(p.aprVerified).toBe(false);expect(p.candidateSurplusUnits).toBe('275000000');});
 it('pending redemption and unknown result do not advance purchase',()=>{expect(planCapital({...snapshot,redemptionState:'PENDING'},100000).decision).toBe('WAIT_FOR_SETTLEMENT');expect(planCapital({...snapshot,redemptionState:'UNKNOWN'},100000).decision).toBe('RECONCILE');});
 it.each(['/api/account/operator/lab/plan','/api/account/operator/lab/blind/grants','/api/account/operator/lab/blind/execute'])('mainnet blocks lab mutations %s',url=>{expect(middleware(new NextRequest('https://mainnet.mercenta.xyz'+url,{method:'POST'})).status).toBe(503);});
 it('rejects claims of TEE or production credential ingestion',()=>{const g={handle:'00000000-0000-4000-8000-000000000001',operation:'demo.digest',kind:'SYNTHETIC_DEMO',expiresAt:100000,status:'ACTIVE',callsRemaining:1,isolation:'SOFTWARE_ISOLATION_DEMO',attestationVerified:false,productionIngestionEnabled:false};expect(blindGrantSchema.safeParse(g).success).toBe(true);expect(blindGrantSchema.safeParse({...g,attestationVerified:true}).success).toBe(false);expect(blindGrantSchema.safeParse({...g,cipher:'private'}).success).toBe(false);});
 it('rejects secret-bearing receipts or real-provider claims',()=>{const r={id:'00000000-0000-4000-8000-000000000001',handle:'00000000-0000-4000-8000-000000000002',operation:'demo.digest',state:'SUCCEEDED',inputDigest:'a'.repeat(64),outputDigest:'b'.repeat(64),isolation:'SOFTWARE_ISOLATION_DEMO',attestationVerified:false,realProviderCall:false,moneyMoved:false,quotaReservedUnits:'1000',createdAt:1};expect(blindReceiptSchema.safeParse(r).success).toBe(true);expect(blindReceiptSchema.safeParse({...r,secret:'plaintext'}).success).toBe(false);expect(blindReceiptSchema.safeParse({...r,realProviderCall:true}).success).toBe(false);});
});
