// @vitest-environment jsdom
import {it,expect,vi,afterEach} from 'vitest';import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {OperatorCapitalLab} from '@/components/product/OperatorCapitalLab';
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined,el:HTMLDivElement;const props={wallet:null,readOnly:false,lang:'en' as const,onConnect:vi.fn()};
async function render(extra:object={}){el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(React.createElement(OperatorCapitalLab,{...props,...extra})));(el.querySelector('details') as HTMLDetailsElement).open=true;}
const btn=(text:string)=>[...el.querySelectorAll('button')].find(b=>b.textContent?.includes(text))!;
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.innerHTML='';vi.unstubAllGlobals();vi.clearAllMocks();});
it('capital presets preserve obligations and never call a financial API',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render();const dl=el.querySelector('.op-lab-plan dl')!;expect(dl.textContent).toContain('225.000000');expect(dl.textContent).toContain('275.000000');await act(async()=>btn('Redemption pending').click());expect(el.textContent).toContain('Wait for settled funds');await act(async()=>btn('Unknown outcome').click());expect(el.textContent).toContain('Reconcile first');expect(fetch).not.toHaveBeenCalled();});
it('tab keyboard end and home retain focused selected controls',async()=>{await render();const first=el.querySelector('#lab-tab-capital') as HTMLButtonElement;first.focus();await act(async()=>first.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true})));expect(document.activeElement?.id).toBe('lab-tab-blind');expect(document.activeElement?.getAttribute('aria-selected')).toBe('true');expect(el.textContent).toContain('not hardware TEE');await act(async()=>document.activeElement!.dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true})));expect(document.activeElement?.id).toBe('lab-tab-capital');});
it('anonymous blind demo requests wallet ownership without calling backend',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render();await act(async()=>btn('Blind execution').click());await act(async()=>btn('Sign in with wallet').click());expect(props.onConnect).toHaveBeenCalledTimes(1);expect(fetch).not.toHaveBeenCalled();expect(el.textContent).toContain('synthetic secret');});
it('ambiguous grant retry keeps the original idempotency key',async()=>{const ids:string[]=[];vi.stubGlobal('fetch',vi.fn(async(_url:string,init?:RequestInit)=>{ids.push(JSON.parse(String(init?.body)).requestId);throw Error('timeout');}));await render({wallet:'0x'+'a'.repeat(40)});await act(async()=>btn('Blind execution').click());await act(async()=>btn('Create demo permission').click());await act(async()=>btn('Create demo permission').click());expect(ids).toHaveLength(2);expect(ids[0]).toBe(ids[1]);});
it('read-only disables synthetic mutations as well as financial ones',async()=>{await render({wallet:'0x'+'a'.repeat(40),readOnly:true});await act(async()=>btn('Blind execution').click());expect(btn('Create demo permission').disabled).toBe(true);expect(btn('Run one demo operation').disabled).toBe(true);});
