// @vitest-environment jsdom
vi.mock('@/components/product/agent-operator.css',()=>({}));
import {it,expect,vi,afterEach} from 'vitest';import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {AgentOperator} from '@/components/product/AgentOperator';
vi.mock('@/components/product/ProductImage',()=>({ProductImage:()=>React.createElement('div',null,'artwork')}));vi.mock('@/components/product/CircleAgentPanel',()=>({CircleAgentPanel:()=>React.createElement('div',null,'Gateway')}));
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined,el:HTMLDivElement;const id='12345678-1234-4234-8234-123456789012';const run={id,status:'QUOTED',input:{message:'Find Roblox',budgetUsdc:'3',reserveUsdc:'0',budgetUnits:'3000000',reserveUnits:'0',region:'US',quantity:1,execution:'review'},step:3,maxSteps:6,provider:'mock-model',error:null,leaseUntil:0,createdAt:1,updatedAt:1,expiresAt:Date.now()+600000,events:[{seq:1,tool:'catalog.search',status:'CHECKED',reason:'',provider:null,result:{receivedProducts:1298}}],quote:{id,productName:'Roblox',optionName:'Voucher',quantity:1,region:'US',amountUnits:'1000000',sourcePrice:8.3,sourceCurrency:'USD',expiresAt:Date.now()+300000,nonRedeemable:true},receipt:null,scope:{chainId:5042002,maxOrders:1,supplierOrders:0,realPurchasingEnabled:false}};
const props={wallet:null,readOnly:false,lang:'en' as const,onChange:vi.fn(),onHelp:vi.fn(),onConnect:vi.fn()};
async function render(extra:object={}){el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(React.createElement(AgentOperator,{...props,...extra})))}const btn=(text:string)=>[...el.querySelectorAll('button')].find(b=>b.textContent?.includes(text))!;
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.innerHTML='';vi.unstubAllGlobals();vi.clearAllMocks()});
it('guest may draft but cannot invoke account tools',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render();await act(async()=>btn('Roblox').click());expect((el.querySelector('textarea') as HTMLTextAreaElement).value).toContain('Roblox');expect(btn('Run the agent').disabled).toBe(true);expect(fetch).not.toHaveBeenCalled()});
it('delegation requires separate explicit scoped consent',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({items:[],model:{configured:true}}))));await render({wallet:'0x'+'a'.repeat(40)});await act(async()=>{btn('Roblox').click();btn('Delegate one test purchase').click()});expect(btn('Authorize and run').disabled).toBe(true);expect(el.textContent).toContain('Permission lasts 10 minutes');await act(async()=>(el.querySelector('input[type=checkbox]') as HTMLInputElement).click());expect(btn('Authorize and run').disabled).toBe(false)});
it('review quote shows observed tools and exact consent, never auto confirms',async()=>{const fetch=vi.fn(async()=>new Response(JSON.stringify({items:[run],model:{configured:true}})));vi.stubGlobal('fetch',fetch);await render({wallet:'0x'+'a'.repeat(40)});expect(el.textContent).toContain('1298');expect(el.textContent).toContain('mock-model');expect(btn('Confirm test purchase').disabled).toBe(true);expect(fetch.mock.calls.length).toBe(1);await act(async()=>(el.querySelector('input[type=checkbox]') as HTMLInputElement).click());expect(btn('Confirm test purchase').disabled).toBe(false)});
it('read-only prevents financial confirmation even after consent',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({items:[run],model:{configured:true}}))));await render({wallet:'0x'+'a'.repeat(40),readOnly:true});await act(async()=>(el.querySelector('input[type=checkbox]') as HTMLInputElement).click());expect(btn('Confirm test purchase').disabled).toBe(true)});
it('ambiguous task-creation retries retain one request id',async()=>{const ids:string[]=[];vi.stubGlobal('fetch',vi.fn(async(_url:string,opt?:RequestInit)=>{if(opt?.method==='POST'){ids.push(JSON.parse(String(opt.body)).requestId);throw Error('network')}return new Response(JSON.stringify({items:[],model:{configured:true}}))}));await render({wallet:'0x'+'a'.repeat(40)});await act(async()=>btn('Roblox').click());await act(async()=>btn('Run the agent').click());await act(async()=>btn('Run the agent').click());expect(ids).toHaveLength(2);expect(ids[0]).toBe(ids[1])});
it('restored planning task advances original id to quote without automatic confirmation',async()=>{const urls:string[]=[];vi.stubGlobal('fetch',vi.fn(async(url:string)=>{urls.push(url);return new Response(JSON.stringify(url.endsWith('/advance')?run:{items:[{...run,status:'PLANNING',quote:null,step:1}],model:{configured:true}}))}));await render({wallet:'0x'+'a'.repeat(40)});expect(urls).toContain('/api/account/operator/runs/'+id+'/advance');expect(urls.some(u=>u.endsWith('/confirm'))).toBe(false);expect(btn('Confirm test purchase').disabled).toBe(true)});
it('manual confirmation posts exactly the shown amount and saved receipt is rendered',async()=>{let body:unknown;vi.stubGlobal('fetch',vi.fn(async(url:string,opt?:RequestInit)=>{if(url.endsWith('/confirm')){body=JSON.parse(String(opt?.body));return new Response(JSON.stringify({...run,status:'EXECUTED',receipt:{orderId:id,availableUnits:'9000000',delivery:{orderId:id,codes:['MCT-TEST-FIXTURE'],nonRedeemable:true,amountUnits:'1000000'}}}))}return new Response(JSON.stringify({items:[run],model:{configured:true}}))}));await render({wallet:'0x'+'a'.repeat(40)});await act(async()=>(el.querySelector('input[type=checkbox]') as HTMLInputElement).click());await act(async()=>btn('Confirm test purchase').click());expect(body).toEqual({acceptedAmountUnits:'1000000',confirmNonRedeemable:true});expect(el.textContent).toContain('MCT-TEST-FIXTURE');expect(el.textContent).toContain('Codes cannot be redeemed');expect(props.onChange).toHaveBeenCalledTimes(1)});

it('invalid cap is explained and prevents task creation',async()=>{const fetch=vi.fn(async()=>new Response(JSON.stringify({items:[],model:{configured:true}})));vi.stubGlobal('fetch',fetch);await render({wallet:'0x'+'a'.repeat(40)});await act(async()=>btn('Roblox').click());await act(async()=>{const cap=el.querySelector('#task-cap') as HTMLInputElement;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(cap,'0.500000');cap.dispatchEvent(new Event('input',{bubbles:true}));});expect(btn('Run the agent').disabled).toBe(true);expect(el.textContent).toContain('The test total exceeds your task cap');expect(fetch.mock.calls.length).toBe(1);});
it('guest gets a concrete next step, not an unexplained disabled action',async()=>{vi.stubGlobal('fetch',vi.fn());await render();await act(async()=>btn('Roblox').click());expect(el.querySelector('#operator-readiness')?.textContent).toContain('Sign in with your wallet');expect(btn('Run the agent').getAttribute('aria-describedby')).toBe('operator-readiness');});
