// @vitest-environment jsdom
import {it,expect,vi,afterEach} from 'vitest';import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {RefundForm} from '@/components/support/RefundForm';
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined,el:HTMLDivElement;
async function render(status:number,payload:object){vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json(payload,{status})));el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(React.createElement(RefundForm)));const input=(name:string,value:string)=>(el.querySelector(`[name="${name}"]`) as HTMLInputElement).value=value;input('email','technical@example.invalid');input('orderReference','TEST-001');input('details','Engineering test only. No real customer payment.');(el.querySelector('[name="acknowledged"]') as HTMLInputElement).checked=true;await act(async()=>el.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));}
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.replaceChildren();vi.unstubAllGlobals();});
it('unavailable server gives an explicit manual email draft, never a saved ticket',async()=>{await render(503,{code:'SUPPORT_UNAVAILABLE'});expect(el.querySelector('.rf-success')).toBeNull();expect(el.textContent).toContain('not a saved ticket');const a=el.querySelector('.rf-error a') as HTMLAnchorElement;expect(a.getAttribute('href')).toContain('mailto:support@mercenta.xyz?subject=');expect(decodeURIComponent(a.getAttribute('href')!)).toContain('TEST-001');expect(decodeURIComponent(a.getAttribute('href')!)).toContain('No automatic refund authorized');});
it('only a durable 202 result with no refund reports a saved ticket',async()=>{await render(202,{ticketId:'00000000-0000-4000-8000-000000000001',status:'SUBMITTED',refundExecuted:false});expect(el.querySelector('.rf-success')).toBeTruthy();expect(el.textContent).toContain('This form has not issued a refund');expect(el.textContent).toContain('00000000-0000-4000-8000-000000000001');});
it('an unexpected paid response is not treated as support success',async()=>{await render(202,{ticketId:'00000000-0000-4000-8000-000000000001',refundExecuted:true});expect(el.querySelector('.rf-success')).toBeNull();expect(el.querySelector('.rf-error')).toBeTruthy();});
