// @vitest-environment jsdom
vi.mock('@/components/product/network-workspace.css',()=>({}));vi.mock('@/components/product/agent-operator.css',()=>({}));
import {it,expect,vi,afterEach,beforeAll} from 'vitest';import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {StartJourney} from '@/components/product/StartJourney';import {NetworkSelector} from '@/components/product/NetworkSelector';import {AgentOperator} from '@/components/product/AgentOperator';
vi.mock('@/components/product/ProductImage',()=>({ProductImage:()=>React.createElement('div')}));vi.mock('@/components/product/CircleAgentPanel',()=>({CircleAgentPanel:()=>React.createElement('div')}));
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined,el:HTMLDivElement;beforeAll(()=>{HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')}});
async function render(component:React.ReactNode){el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root!.render(component))}const click=async(text:string)=>{const b=[...el.querySelectorAll('button')].find(b=>b.textContent?.includes(text));expect(b).toBeTruthy();await act(async()=>b!.click())};
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.replaceChildren();sessionStorage.clear();vi.unstubAllGlobals();vi.clearAllMocks()});
it('guided start prepares the agent, never spends or connects a wallet',async()=>{const nav=vi.fn(),funds=vi.fn(),fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render(React.createElement(StartJourney,{ru:false,onNavigate:nav,onBudget:funds}));await click('Help me get started');expect(el.querySelector('dialog')?.hasAttribute('open')).toBe(true);await click('Continue');expect(nav).toHaveBeenCalledWith('Agent Chat');expect(JSON.parse(sessionStorage.getItem('mercenta-agent-draft')!).mode).toBe('testnet');expect(fetch).not.toHaveBeenCalled();expect(funds).not.toHaveBeenCalled()});
it('budget choice opens the existing editor, without creating an agent draft',async()=>{const nav=vi.fn(),budget=vi.fn();await render(React.createElement(StartJourney,{ru:false,onNavigate:nav,onBudget:budget}));await click('Help me get started');await click('Plan my budget');await click('Continue');expect(budget).toHaveBeenCalledOnce();expect(nav).not.toHaveBeenCalled();expect(sessionStorage.getItem('mercenta-agent-draft')).toBeNull()});
it('network switch requires a confirmation and never requests a signature',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await render(React.createElement(NetworkSelector,{mode:'testnet'}));await click('Arc Mainnet');expect(el.querySelector('dialog')?.hasAttribute('open')).toBe(true);const a=el.querySelector('dialog a')!;expect(a.getAttribute('href')).toContain('https://mainnet.mercenta.xyz/app');expect(el.textContent).toContain('Do not send funds');expect(fetch).not.toHaveBeenCalled();await click('Stay here');expect(el.querySelector('dialog')).toBeNull()});
it('agent consumes a draft but does not authorize or execute it',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);sessionStorage.setItem('mercenta-agent-draft',JSON.stringify({goal:'Find Spotify for my region',mode:'testnet',authorizeTestSpend:true}));await render(React.createElement(AgentOperator,{wallet:null,readOnly:false,lang:'en',onChange:vi.fn(),onHelp:vi.fn()}));expect((el.querySelector('textarea') as HTMLTextAreaElement).value).toBe('Find Spotify for my region');expect([...el.querySelectorAll('input[type=checkbox]')].filter(input=>!input.closest('.op-lab'))).toHaveLength(0);expect((el.querySelector('.op-lab input[type=checkbox]') as HTMLInputElement).checked).toBe(false);expect([...el.querySelectorAll('button')].find(b=>b.textContent==='Run the agent')?.disabled).toBe(true);expect(fetch).not.toHaveBeenCalled();expect(sessionStorage.getItem('mercenta-agent-draft')).toBeNull()});
