// @vitest-environment jsdom
import {afterEach,describe,it,expect,vi} from 'vitest';
import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';
import {HelpTip} from '@/components/product/HelpTip';
import {TestCheckout} from '@/components/product/TestCheckout';
let root:Root|undefined;let container:HTMLDivElement;
(globalThis as unknown as {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const props={productId:'p',itemId:'i',quantity:1,wallet:'0x'+'1'.repeat(40),readOnly:false,ru:false};
const quote={id:'q',productName:'Product',optionName:'Option',region:'US',quantity:1,amountUnits:'1000000',sourcePrice:53,sourceCurrency:'USD',expiresAt:Date.now()+300000,mode:'TESTNET_SIMULATED'};
function response(d:unknown){return {ok:true,json:async()=>d}}
async function render(p=props){container=document.createElement('div');document.body.append(container);root=createRoot(container);await act(async()=>{root!.render(React.createElement(TestCheckout,p))})}
async function click(text:string){const b=[...container.querySelectorAll('button')].find(b=>b.textContent?.includes(text));expect(b).toBeDefined();await act(async()=>{b!.click()})}
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=undefined;document.body.innerHTML='';sessionStorage.clear();vi.unstubAllGlobals()});
describe('test checkout interaction',()=>{
 it('Escape dismisses the tooltip and cancels native dialog Escape default',async()=>{container=document.createElement('div');document.body.append(container);root=createRoot(container);await act(async()=>root!.render(React.createElement(HelpTip,{label:'Help'},'Explanation')));const trigger=container.querySelector('button')!;await act(async()=>trigger.focus());expect(document.querySelector('[role="tooltip"]')).not.toBeNull();const event=new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true});await act(async()=>trigger.dispatchEvent(event));expect(event.defaultPrevented).toBe(true);expect(document.querySelector('[role="tooltip"]')).toBeNull();const next=new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true});await act(async()=>trigger.dispatchEvent(next));expect(next.defaultPrevented).toBe(false)});

 it('guest sign-in has no checkout or charge request',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await render({...props,wallet:null as unknown as string});expect(container.textContent).toContain('Sign in with wallet');expect(fetcher).not.toHaveBeenCalled()});
 it('read-only state pauses checkout',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>response({availableUnits:'20000000'})));await render({...props,readOnly:true});expect(container.textContent).toContain('Checkout paused');expect(container.textContent).not.toContain('Get test checkout quote')});
 it('quote alone cannot confirm without separate consent',async()=>{const f=vi.fn(async(url:string)=>response(url.endsWith('/summary')?{availableUnits:'20000000'}:quote));vi.stubGlobal('fetch',f);await render();await click('Get test checkout quote');const button=[...container.querySelectorAll('button')].find(b=>b.textContent?.startsWith('Confirm debit'));expect(button?.disabled).toBe(true);expect(f.mock.calls.filter(([u])=>u.endsWith('/confirm'))).toHaveLength(0);});
 it('explicit confirmation returns only the test receipt with bounded amount',async()=>{const f=vi.fn(async(url:string,init?:RequestInit)=>{if(url.endsWith('/confirm')){const body=JSON.parse(String(init?.body));expect(body.acceptedAmountUnits).toBe('1000000');expect(body.confirmNonRedeemable).toBe(true);expect(body.mode).toBe('TESTNET_SIMULATED');return response({delivery:{orderId:'order',productName:'Product',optionName:'Option',quantity:1,amountUnits:'1000000',codes:['MCT-TEST-EXAMPLE'],nonRedeemable:true}})}return response(url.endsWith('/summary')?{availableUnits:'20000000'}:quote)});vi.stubGlobal('fetch',f);await render();await click('Get test checkout quote');await act(async()=>container.querySelector<HTMLInputElement>('input[type="checkbox"]')!.click());await click('Confirm debit');expect(container.textContent).toContain('Your test order is complete');expect(container.textContent).toContain('MCT-TEST-EXAMPLE');expect(container.textContent).toContain('cannot be activated');expect(f.mock.calls.filter(([u])=>u.endsWith('/confirm'))).toHaveLength(1)});
 it('ambiguous confirmation retry retains the same request ID',async()=>{const ids:string[]=[];let attempt=0;const f=vi.fn(async(url:string,init?:RequestInit)=>{if(url.endsWith('/confirm')){ids.push(JSON.parse(String(init?.body)).requestId);if(attempt++===0)throw Error('NETWORK');return response({delivery:{orderId:'order',optionName:'Option',quantity:1,amountUnits:'1000000',codes:['MCT-TEST-EXAMPLE']}})}return response(url.endsWith('/summary')?{availableUnits:'20000000'}:quote)});vi.stubGlobal('fetch',f);await render();await click('Get test checkout quote');await act(async()=>container.querySelector<HTMLInputElement>('input[type="checkbox"]')!.click());await click('Confirm debit');expect(container.textContent).toContain('retry the same order');await click('retry the same order');expect(ids).toHaveLength(2);expect(ids[0]).toBe(ids[1]);expect(container.textContent).toContain('Your test order is complete')});
 it('too-large quantity cannot request checkout quote',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>response({availableUnits:'20000000'})));await render({...props,quantity:11});expect([...container.querySelectorAll('button')].find(b=>b.textContent?.includes('Get test checkout quote'))?.disabled).toBe(true)});
});
