'use client';
import {useEffect,useState} from 'react';import {Moon,Sun,Monitor,ShieldCheck,Server,Wallet,Clock} from 'lucide-react';import {type AccountTheme,validTheme} from '@/lib/account-theme';
type Resource={rssMb:number;softLimitMb:number;pressured:boolean;temporary:{expiresAt:string|null;daysRemaining:number|null;enabled:boolean}};
type Preferences={theme:AccountTheme;wallet:string;merchantAddress:string|null;network:string;currency:string;timezone:string;resources:Resource};
export function AccountSettings({theme,onTheme,wallet}:{theme:AccountTheme;onTheme:(theme:AccountTheme)=>void;wallet:string|null}){
 const [data,setData]=useState<Preferences|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;fetch('/api/account/settings',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error((await r.json()).code??'SETTINGS_UNAVAILABLE');return r.json()}).then(d=>{if(active){setData(d);if(!localStorage.getItem('mercenta-account-theme')&&validTheme(d.theme))onTheme(d.theme)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[wallet,onTheme]);
 async function save(next:AccountTheme){onTheme(next);setSaving(true);setError('');setMessage('Theme applied on this device.');try{const r=await fetch('/api/account/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({theme:next})});if(!r.ok)throw new Error((await r.json()).code??'SETTINGS_UNAVAILABLE');setData(await r.json());setMessage('Theme saved to your account and this device.')}catch{setMessage('Theme saved on this device. Sign in or retry when backend is available to sync it.')}finally{setSaving(false)}}
 return <div className="ma-settings-grid"><section className="ma-panel"><span className="ma-eyebrow">YOUR WORKSPACE / APPEARANCE</span><h2>Built around your preference.</h2><p>The same Mercenta design system. Two ways to see it.</p><div className="ma-theme-options">{(['dark','light','system'] as const).map((mode)=>{const Icon=mode==='dark'?Moon:mode==='light'?Sun:Monitor;return <button disabled={saving} key={mode} aria-pressed={theme===mode} onClick={()=>void save(mode)}><span className={'ma-theme-preview '+mode}><i/><i/><i/></span><Icon size={16}/><strong>{mode==='light'?'White':mode==='dark'?'Dark':'System'}</strong>{theme===mode&&<small>ACTIVE</small>}</button>})}</div>{message&&<p role="status" className="ma-setting-message">{message}</p>}{error&&<p className="ma-error">{error==='WALLET_AUTH_REQUIRED'?'Sign in to sync account settings. Local theme selection still works.':error}</p>}</section>
 <section className="ma-panel"><span className="ma-eyebrow">IDENTITY / NETWORK</span><h2><Wallet size={18}/>Your account</h2><dl className="ma-settings-details"><div><dt>Signed-in wallet</dt><dd className="ma-address">{wallet??'Not signed in'}</dd></div><div><dt>Network</dt><dd>Arc Testnet · 5042002</dd></div><div><dt>Settlement currency</dt><dd>USDC · exact six-decimal accounting</dd></div><div><dt>History timezone</dt><dd>UTC</dd></div><div><dt>Deposit receiver</dt><dd className="ma-address">{data?.merchantAddress??'Load settings after sign-in'}</dd></div></dl><p><ShieldCheck size={14}/> Wallet authentication does not give the AI transaction-signing authority.</p></section>
 <section className="ma-panel"><span className="ma-eyebrow">INFRASTRUCTURE / RESILIENCE</span><h2><Server size={18}/>Safe under pressure.</h2><p>Persistent SQLite WAL is the source of truth. During memory pressure or backend outage, snapshots are read-only and monetary mutations fail closed.</p><dl className="ma-settings-details"><div><dt>Backend memory</dt><dd>{data?`${data.resources.rssMb} / ${data.resources.softLimitMb} MB soft limit`:'Unavailable'}</dd></div><div><dt>Write mode</dt><dd>{data?.resources.pressured?'Paused · memory pressure':'Normal when backend is healthy'}</dd></div><div><dt>Redis / PostgreSQL</dt><dd>Temporary optional services · never authoritative balances</dd></div><div><dt>Temporary deadline</dt><dd>{data?.resources.temporary.expiresAt?new Date(data.resources.temporary.expiresAt).toISOString().slice(0,10):'Not configured'}</dd></div></dl>{data?.resources.temporary.daysRemaining!==null&&data?.resources.temporary.daysRemaining!==undefined&&<p className="ma-setting-message"><Clock size={14}/>{data.resources.temporary.daysRemaining} days to configured deadline. Core data stays on the VPS after temporary services expire.</p>}</section>
 <section className="ma-panel"><span className="ma-eyebrow">SECURITY / INTEGRATIONS</span><h2><ShieldCheck size={18}/>Keep control of access.</h2><p>Create scoped keys in API Access. Revoke unused keys and keep secrets server-side. Credentials and private keys never appear in Settings.</p><a className="ma-button secondary" href="https://docs.mercenta.xyz/docs/guides/security">Read the security guide</a><p>Only test USDC and simulated goods are enabled. Live Onramp, cross-chain credit, withdrawals and Mainnet still require reviewed settlement integrations.</p></section></div>
}
