"use client";
import './product-refinement.css';
import {useDeferredValue,useEffect,useMemo,useRef,useState} from 'react';
import {Search,X,Globe,SlidersHorizontal,LayoutGrid,Rows3,ArrowDownWideNarrow,Gamepad2,Clapperboard,Heart,Code2,Cpu,ChevronDown,Check} from 'lucide-react';
import type {CatalogProduct} from '@/lib/supplier';import type {ProductFamily} from '@/lib/catalog-families';
import {catalogCategories,familyMatches,groupCatalog,regionLabel,familyProducts} from '@/lib/catalog-families';
import {sortFamilies,productCount,type CatalogueSort} from '@/lib/catalog-presentation';
import type {Language} from '@/lib/workspace-plan';import {CatalogFamilyCard} from './CatalogFamilyCard';import {CatalogFamilyDialog} from './CatalogFamilyDialog';import {HelpTip} from './HelpTip';
const ICONS={gaming:Gamepad2,streaming:Clapperboard,creator:Heart,developer:Code2,cloud:Cpu};
export function CatalogCollection({products,lang='en',wallet=null,readOnly=false,previewOnly=false,isMainnet=false,onConnect,onDraft,initialQuery='',initialRegion='all',initialProductId}:{products:CatalogProduct[];lang?:Language;wallet?:string|null;readOnly?:boolean;previewOnly?:boolean;isMainnet?:boolean;onConnect?:(p:CatalogProduct)=>void;onDraft?:(s:{product:CatalogProduct;denom:import('@/lib/supplier').CatalogDenomination;quantity:number})=>void;initialQuery?:string;initialRegion?:string;initialProductId?:string}){
 const ru=lang==='ru',[families,setFamilies]=useState(()=>groupCatalog(products,false)),[query,setQuery]=useState(initialQuery),[region,setRegion]=useState(initialRegion),[category,setCategory]=useState('all'),[kind,setKind]=useState('all'),[shown,setShown]=useState(24),[sort,setSort]=useState<CatalogueSort>('recommended'),[view,setView]=useState<'grid'|'compact'>('grid');
 useEffect(()=>{setFamilies(groupCatalog(products,true));},[products]);
 const [selection,setSelection]=useState<{family:ProductFamily;initialProductId?:string}|null>(null),handled=useRef<string|undefined>(undefined),search=useRef<HTMLInputElement>(null),collection=useRef<HTMLElement>(null);
 useEffect(()=>{if(!initialProductId||handled.current===initialProductId)return;const family=families.find(f=>f.products.some(p=>p.id===initialProductId));if(family){handled.current=initialProductId;setSelection({family,initialProductId})}},[initialProductId,families]);
 useEffect(()=>{const focus=(e:KeyboardEvent)=>{if(e.key!=='/'||e.ctrlKey||e.metaKey||e.altKey||e.isComposing||document.querySelector('dialog[open],[aria-modal="true"]'))return;const target=e.target as HTMLElement;if(target?.closest('input,textarea,select,[contenteditable="true"]')||!collection.current?.getClientRects().length)return;e.preventDefault();search.current?.focus();};document.addEventListener('keydown',focus);return()=>document.removeEventListener('keydown',focus);},[]);
 const regions=useMemo(()=>[...new Set(families.flatMap(f=>f.regions))].sort((a,b)=>regionLabel(a,ru).localeCompare(regionLabel(b,ru))),[families,ru]);const deferredQuery=useDeferredValue(query);
 const rows=useMemo(()=>sortFamilies(families.filter(f=>familyMatches(f,deferredQuery,region,category,kind)),sort,region,ru),[families,deferredQuery,region,category,kind,sort,ru]);
 const reset=()=>{setQuery('');setRegion('all');setCategory('all');setKind('all');setShown(24)};
 const open=(family:ProductFamily)=>setSelection({family,initialProductId:region==='all'?undefined:familyProducts(family,region)[0]?.id});
 const active=!!(query||region!=='all'||category!=='all'||kind!=='all');
 return <section ref={collection} className="cf-collection pd-collection" aria-busy={query!==deferredQuery}>
 <details className="pd-catalog-guide"><summary><Globe size={16} aria-hidden="true"/>{ru?'Как выбрать товар для своего региона':'Choose a product for your region'}<ChevronDown size={16} aria-hidden="true"/></summary><ol><li><span>01</span>{ru?'Найдите платформу. Один товар объединяет доступные регионы.':'Find the platform. One product groups its supported regions.'}</li><li><span>02</span>{ru?'Выберите регион активации, затем номинал или вариант.':'Choose the redemption region, then the denomination or option.'}</li><li><span>03</span>{ru?'Сверьте условия. Цена каталога — не котировка оплаты.':'Review the rules. A catalogue price is not a payment quote.'}</li></ol></details>
 <div className="cf-toolbar"><label className="cf-search"><Search size={18} aria-hidden="true"/><input ref={search} aria-label={ru?'Поиск товаров':'Search products'} placeholder={ru?'Найдите товар или платформу':'Find a product or platform'} value={query} onChange={e=>{setQuery(e.target.value);setShown(24)}}/>{query?<button type="button" aria-label={ru?'Очистить поиск':'Clear search'} onClick={()=>{setQuery('');setShown(24);search.current?.focus()}}><X size={16}/></button>:<kbd aria-hidden="true">/</kbd>}</label>
 <div className="pd-region-filter"><label className="cf-filter"><span><Globe size={14} aria-hidden="true"/>{ru?'Ваш регион':'Your region'}</span><select aria-label={ru?'Регион каталога':'Catalogue region'} value={region} onChange={e=>{setRegion(e.target.value);setShown(24)}}><option value="all">{ru?'Все доступные регионы':'All supported regions'}</option>{regions.map(r=><option key={r} value={r}>{regionLabel(r,ru)}</option>)}</select></label><HelpTip label={ru?'Как выбрать регион':'How to choose a region'}>{ru?'Регион должен совпадать с аккаунтом или условиями активации товара. Не выбирайте страну только ради меньшей цены.':'Match the region to your account or the product’s redemption rules. Do not choose a country only for a lower price.'}</HelpTip></div>
 <label className="cf-filter"><span><SlidersHorizontal size={14} aria-hidden="true"/>{ru?'Формат':'Format'}</span><select aria-label={ru?'Тип товара':'Product format'} value={kind} onChange={e=>{setKind(e.target.value);setShown(24)}}><option value="all">{ru?'Все форматы':'All formats'}</option><option value="voucher">{ru?'Коды и карты':'Vouchers & cards'}</option><option value="direct_topup">{ru?'Пополнения':'Top-ups'}</option><option value="esim">eSIM</option></select></label></div>
 <nav className="cf-categories" aria-label={ru?'Категории товаров':'Product categories'}><button type="button" aria-pressed={category==='all'} onClick={()=>{setCategory('all');setShown(24)}}><LayoutGrid size={15} aria-hidden="true"/>{ru?'Все товары':'All products'}</button>{catalogCategories.filter(([id])=>families.some(f=>f.category===id)).map(([id,en,r])=>{const Icon=ICONS[id];return <button type="button" key={id} aria-pressed={category===id} onClick={()=>{setCategory(id);setShown(24)}}><Icon size={15} aria-hidden="true"/>{ru?r:en}</button>})}</nav>
 {active&&<div className="cf-active-filters" aria-label={ru?'Активные фильтры':'Active filters'}>{region!=='all'&&<button onClick={()=>{setRegion('all');setShown(24)}} aria-label={(ru?'Убрать регион: ':'Remove region: ')+regionLabel(region,ru)}>{regionLabel(region,ru)}<X size={12}/></button>}{category!=='all'&&<button onClick={()=>{setCategory('all');setShown(24)}}>{catalogCategories.find(([id])=>id===category)?.[ru?2:1]}<X size={12}/></button>}{kind!=='all'&&<button onClick={()=>{setKind('all');setShown(24)}}>{kind==='voucher'?(ru?'Коды и карты':'Vouchers & cards'):kind==='esim'?'eSIM':(ru?'Пополнения':'Top-ups')}<X size={12}/></button>}<button onClick={reset}>{ru?'Сбросить всё':'Clear all filters'}<X size={12}/></button></div>}
 <div className="pd-results-bar"><div className="cf-results" role="status" aria-atomic="true"><span>{productCount(rows.length,ru)}{region!=='all'?' · '+regionLabel(region,ru):''}</span><span>{ru?'Один товар — выбор доступных регионов':'One product. Its supported regions.'}</span></div><div className="pd-catalog-controls"><label><ArrowDownWideNarrow size={15} aria-hidden="true"/><select aria-label={ru?'Сортировка каталога':'Sort catalogue'} value={sort} onChange={e=>{setSort(e.target.value as CatalogueSort);setShown(24)}}><option value="recommended">{ru?'Сначала с изображениями':'Artwork first'}</option><option value="name">{ru?'По названию':'Name: A–Z'}</option><option value="price">{ru?'Цена: по возрастанию':'Price: low to high'}</option></select></label><div role="group" aria-label={ru?'Вид каталога':'Catalogue view'}><button type="button" aria-label={ru?'Карточки':'Card view'} aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={17}/></button><button type="button" aria-label={ru?'Компактный вид':'Compact view'} aria-pressed={view==='compact'} onClick={()=>setView('compact')}><Rows3 size={17}/></button></div></div></div>
 {rows.length?<div className={'cf-grid'+(view==='compact'?' pd-compact':'')}>{rows.slice(0,shown).map((family,i)=><CatalogFamilyCard key={family.key} family={family} ru={ru} region={region} priority={i<3} onOpen={()=>open(family)}/>)}</div>:<div className="cf-empty pd-empty"><div className="pd-empty-icon"><Search size={26}/><span><X size={12}/></span></div><h2>{ru?'Нет подходящих вариантов':'No matching products'}</h2><p>{ru?'Попробуйте другой запрос или регион. Фильтры можно сбросить.':'Try another search or region. You can clear the filters to explore again.'}</p><button className="ma-button secondary" onClick={reset}>{ru?'Сбросить фильтры':'Reset filters'}</button><div className="pd-empty-suggestions">{['Steam','Roblox','Spotify'].map(s=><button type="button" key={s} onClick={()=>{reset();setQuery(s);search.current?.focus()}}>{s}</button>)}</div></div>}
 {shown<rows.length&&<div className="pd-more"><span>{ru?'Показано':'Showing'} {Math.min(shown,rows.length)} / {rows.length}</span><button className="ma-button secondary cf-more" onClick={()=>setShown(n=>n+24)}>{ru?'Показать ещё '+Math.min(24,rows.length-shown):'Show '+Math.min(24,rows.length-shown)+' more'}<ChevronDown size={16}/></button></div>}
 <p className="pd-catalog-footnote"><Check size={13} aria-hidden="true"/>{ru?'Просмотр и выбор региона не списывают средства.':'Browsing and choosing a region never charge funds.'}</p>
 {selection&&<CatalogFamilyDialog key={selection.family.key} {...selection} lang={lang} wallet={wallet} readOnly={readOnly} previewOnly={previewOnly} isMainnet={isMainnet} onDraft={onDraft} onClose={()=>setSelection(null)} onConnect={onConnect?product=>{setSelection(null);requestAnimationFrame(()=>onConnect(product))}:undefined}/>}</section>;
}
