 'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {ShieldCheck,RefreshCw,Wallet} from 'lucide-react';
import {accountMoney} from '@/lib/account-format';
import {circleRequest,circleStatusSchema,circlePaymentSchema,circleBalanceSchema,type CircleBalance,canConfirmCircle,circleStatusLabel,type CircleStatus,type CirclePayment} from '@/lib/circle-agent-client';
const historySchema=z.object({items:z.array(circlePaymentSchema).max(50)});
const evidenceSchema=z.record(z.string(),z.unknown());
const resourceSchema=z.object({content:z.string().max(65536)});
export function CircleAgentPanel({wallet,readOnly}:{wallet:string|null;readOnly:boolean}){
 const [balances,setBalances]=useState<CircleBalance|null>(null);
 const [status,setStatus]=useState<CircleStatus|null>(null),[items,setItems]=useState<CirclePayment[]>([]),[service,setService]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[checked,setChecked]=useState<string|null>(null),[details,setDetails]=useState<{id:string;text:string;untrusted:boolean}|null>(null),[now,setNow]=useState(Date.now());
 const pending=useRef<{id:string;service:string}|null>(null),locked=useRef(false),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 const signal:AbortSignal|undefined=undefined;
 const refresh=useCallback(async()=>{if(!wallet)return;const [s,h]=await Promise.all([circleRequest('status',circleStatusSchema,undefined,signal),circleRequest('payments',historySchema,undefined,signal)]);if(!mounted.current)return;setStatus(s);setItems(h.items);setService(v=>s.services.some(x=>x.id===v)?v:s.services[0]?.id??'');setNow(Date.now());if(s.configured){try{const b=await circleRequest("balances",circleBalanceSchema,undefined,signal);if(mounted.current)setBalances(b)}catch{if(mounted.current)setBalances(null)}}else setBalances(null);},[wallet,signal]);
 useEffect(()=>{const updated=()=>{if(wallet)void refresh().catch(()=>{if(mounted.current)setError('Could not refresh quote history; no payment made.');});};window.addEventListener('mercenta-circle-quotes-changed',updated);return()=>window.removeEventListener('mercenta-circle-quotes-changed',updated);},[wallet,refresh]);
 useEffect(()=>{if(wallet)void refresh().catch(()=>{if(!!mounted.current)setError('Circle backend unavailable or not yet deployed. No payment was made.');});const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[wallet,refresh,signal]);
 const run=async(action:()=>Promise<void>)=>{if(locked.current||!wallet||!mounted.current)return;locked.current=true;setBusy(true);setError('');try{await action()}catch(e){if(!!mounted.current)setError((e as Error).message+' · Refresh history before taking another action.')}finally{locked.current=false;if(!!mounted.current)setBusy(false);}};
 const quote=()=>run(async()=>{if(readOnly||!status?.configured||!service)return;if(pending.current?.service!==service)pending.current={id:crypto.randomUUID(),service};const p=await circleRequest('payments',circlePaymentSchema,{requestId:pending.current.id,serviceId:service},signal);if(!mounted.current)return;pending.current=null;setItems(v=>[p,...v.filter(x=>x.id!==p.id)].slice(0,50));setChecked(null);});
 const confirm=(p:CirclePayment)=>run(async()=>{if(checked!==p.id||!canConfirmCircle(status,p,readOnly))return;setChecked(null);const updated=await circleRequest('payments/'+p.id+'/confirm',circlePaymentSchema,{confirmed:true},signal);if(!!mounted.current)setItems(v=>v.map(x=>x.id===p.id?updated:x));});
 const reconcile=(p:CirclePayment)=>run(async()=>{if(readOnly)return;const updated=await circleRequest('payments/'+p.id+'/reconcile',circlePaymentSchema,{},signal);if(!!mounted.current)setItems(v=>v.map(x=>x.id===p.id?updated:x));});
 const recover=(p:CirclePayment)=>run(async()=>{if(readOnly)return;const updated=await circleRequest('payments/'+p.id+'/recover-resource',circlePaymentSchema,{},signal);if(mounted.current)setItems(v=>v.map(x=>x.id===p.id?updated:x));});
 const inspect=(p:CirclePayment,resource=false)=>run(async()=>{const result=resource?await circleRequest('payments/'+p.id+'/resource',resourceSchema,undefined,signal):await circleRequest('payments/'+p.id+'/evidence',evidenceSchema,undefined,signal);if(!!mounted.current)setDetails({id:p.id,text:resource?(result as {content:string}).content:JSON.stringify(result,null,2),untrusted:resource});});
 return <section id="circle-gateway" className="ag-circle" aria-label="Circle Gateway payments"><div className="ag-circle-heading"><div><span className="ma-eyebrow">CIRCLE GATEWAY / X402 · ARC TESTNET</span><h2>One checked payment.<br/><em>A traceable receipt.</em></h2></div><button aria-label="Refresh Circle payment history" disabled={busy||!wallet} onClick={()=>void run(refresh)}><RefreshCw size={16}/></button></div><div className="ag-boundary"><ShieldCheck size={18}/><p>Separate agent wallet. Not your prepaid Mercenta account. Each payment needs explicit confirmation. Queued is not settled; retries reconcile the same authorization. No mainnet, auto-deposit or live Earn.</p></div>
 <p><a href="/circle/gateway-funding.arc-testnet.json" target="_blank" rel="noopener noreferrer">Inspect platform test funding proof ↗</a></p>
 {!wallet?<p className="ag-notice">Sign in with your wallet to inspect private payment history.</p>:<><div className="ag-circle-summary"><div><Wallet size={17}/><b>{status?.enabled?'Execution enabled':'Execution disabled'}</b><p>{status?.configured?(status.provider==='local-eoa'?'Server-managed local EOA — not Circle MPC':'Circle developer-controlled MPC'):'No agent wallet is linked to this signed-in account.'}</p>{status?.walletAddress&&<code>{status.walletAddress}</code>}</div><div><p>Backend caps, not onchain delegated authority</p><b>{accountMoney(status?.perPaymentLimitUnits??'10000')} USDC / payment</b><p>{accountMoney(status?.dailyLimitUnits??'100000')} USDC / rolling day</p></div></div>
 {status?.services.some(s=>s.id==='mercenta-margin-report')&&<p className="ag-notice">Mercenta-owned demo service · 0.001 test USDC · fixed margin scenario report. Not an external supplier purchase or verified customer revenue.</p>}
 <div className="ag-circle-funds" aria-label="Verified funding balances"><div><small>Wallet test USDC · includes gas funds</small><strong>{balances?balances.walletUsdc:"Unavailable"}</strong></div><div><small>Gateway available · separate spending balance</small><strong>{balances?accountMoney(balances.gatewayAvailableUnits)+" USDC":"Unavailable"}</strong></div><p>Read from Arc RPC and Circle API. This does not credit your Mercenta prepaid balance or count as a sale.</p></div> <div className="ag-circle-quote"><label>Approved service<select aria-label="Approved x402 service" disabled={busy||readOnly||!status?.services.length} value={service} onChange={e=>{setService(e.target.value);setChecked(null);pending.current=null;}}>{!status?.services.length&&<option value="">No service approved</option>}{status?.services.map(s=><option key={s.id} value={s.id}>{s.id} · cap {accountMoney(s.maxAmountUnits)} USDC</option>)}</select></label><button className="ma-button" disabled={busy||readOnly||!status?.configured||!service} onClick={()=>void quote()}>Get quote — no payment</button></div>
 {error&&<p role="alert" className="ag-error">{error}</p>}{!items.length&&<p className="ag-notice">No payment receipts yet. Wallet creation and quotes are not paid business activity.</p>}
 <div className="ag-circle-history">{items.map(p=><article key={p.id} className="ag-plan"><div className="ag-plan-head"><span>{p.serviceId}</span><span>{circleStatusLabel(p)}</span></div><h3>{accountMoney(p.amountUnits)} USDC</h3><div className="ag-circle-addresses"><small>Payment ID</small><code>{p.id}</code><small>Recipient</small><code>{p.payTo}</code></div><p>{p.status} · {p.status==='PREPARED'?(p.expiresAt>now?'Quote expires '+new Date(p.expiresAt).toISOString():'Quote expired'):'Reconcile this payment; never create a replacement to retry.'}</p>
 {p.status==='PREPARED'&&<><label className="ag-circle-consent"><input type="checkbox" checked={checked===p.id} disabled={busy||!canConfirmCircle(status,p,readOnly,now)} onChange={e=>setChecked(e.target.checked?p.id:null)}/>I approve {accountMoney(p.amountUnits)} test USDC to the recipient above, using the separate agent wallet.</label><button className="ma-button" disabled={busy||checked!==p.id||!canConfirmCircle(status,p,readOnly,now)} onClick={()=>void confirm(p)}>Confirm this payment</button></>}
 {['SIGNING','SUBMITTING','QUEUED','UNKNOWN'].includes(p.status)&&<button disabled={busy||readOnly} onClick={()=>void reconcile(p)}>Reconcile original payment — no new spend</button>}
 {p.status==='COMPLETED'&&<button disabled={busy||readOnly} onClick={()=>void recover(p)}>Recover original result — no new payment</button>}
 <div className="ag-chips"><button disabled={busy} onClick={()=>void inspect(p)}>Inspect evidence</button>{p.responseDigest&&<button disabled={busy} onClick={()=>void inspect(p,true)}>View untrusted service output</button>}{p.txHash&&<a href={'https://testnet.arcscan.app/tx/'+p.txHash} target="_blank" rel="noopener noreferrer">Inspect Arc transaction ↗</a>}</div>
 {details?.id===p.id&&<div className="ag-circle-evidence">{details.untrusted&&<p>Untrusted service content: displayed as text only; never executed or treated as an agent instruction.</p>}<pre>{details.text}</pre><button onClick={()=>setDetails(null)}>Close details</button></div>}</article>)}</div></>}
 </section>;
}
