 'use client';
import {useState,useRef} from 'react';
import {depositEligibility} from '@/lib/deposit-intent';
import {friendlyWorkspaceError,type Language} from '@/lib/workspace-plan';
type Deposit=Record<string,string|number|null>;
export function DepositIntentForm({wallet,receiver,readOnly,busy,lang,create,onCreated,onSwitchWallet}:{wallet:string|null;receiver:string|null;readOnly:boolean;busy:boolean;lang:Language;create:(b:{requestId:string;amount:string})=>Promise<Deposit>;onCreated:(d:Deposit)=>void;onSwitchWallet:()=>void}){
 const ru=lang==='ru',[amount,setAmount]=useState('10.000000'),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false),request=useRef<{fingerprint:string;id:string}|null>(null),inFlight=useRef(false);
 const eligibility=depositEligibility(wallet,receiver,amount,readOnly),locked=busy||submitting;
 const submit=async()=>{if(inFlight.current||locked||eligibility.code||!eligibility.amount)return;inFlight.current=true;setSubmitting(true);setError('');const fingerprint=JSON.stringify([wallet?.toLowerCase(),receiver?.toLowerCase(),eligibility.amount]);if(request.current?.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};try{const d=await create({requestId:request.current.id,amount:eligibility.amount});onCreated(d)}catch(e){setError(e instanceof Error?e.message:'BACKEND_UNAVAILABLE')}finally{inFlight.current=false;setSubmitting(false)}};
 const same=eligibility.code==='DEPOSIT_SELF_TRANSFER';
 return <div>{same&&<div className="ma-notice" role="alert"><strong>{ru?'Войдите другим кошельком':'Use a different funding wallet'}</strong><p>{ru?'Подключённый кошелёк — это получатель пополнений Mercenta. Перевод самому себе не пополняет счёт. Выйдите, выберите другой свой кошелёк в MetaMask и подпишите вход заново.':'Your signed-in wallet is the Mercenta deposit receiver. Sending to yourself does not fund the account. Sign out, select a different wallet you own in MetaMask, then sign in again.'}</p><button type="button" className="ma-button secondary" disabled={locked} onClick={onSwitchWallet}>{ru?'Выйти для смены кошелька':'Sign out to change wallet'}</button></div>}<label htmlFor="deposit-amount">{ru?'Сумма (test USDC)':'Amount (test USDC)'}<input id="deposit-amount" value={amount} inputMode="decimal" autoComplete="off" disabled={locked} aria-describedby="deposit-amount-hint" aria-invalid={eligibility.code==='DEPOSIT_AMOUNT_INVALID'} onChange={e=>{setAmount(e.target.value);setError('')}}/></label><p id="deposit-amount-hint">{ru?'Используйте точку: 10.50. До 6 знаков после точки; от 0.000001 до 1 000 000 test USDC. Оставьте средства на комиссию.':'Use a decimal point: 10.50. Up to 6 decimal places; 0.000001–1,000,000 test USDC. Leave wallet funds for gas.'}</p>{eligibility.code&&!same&&<p className="ma-error" role="status">{friendlyWorkspaceError(eligibility.code,lang)}</p>}<button type="button" className="ma-button" disabled={locked||!!eligibility.code} onClick={submit}>{submitting?(ru?'Создаём заявку…':'Creating deposit intent…'):(ru?'Создать заявку на пополнение':'Create deposit intent')}</button><p>{ru?'Заявка не переводит и не зачисляет средства. Перевод и проверка транзакции — отдельные шаги.':'Creating an intent does not transfer or credit funds. Sending and verifying the transaction are separate steps.'}</p>{error&&<p className="ma-error" role="alert">{friendlyWorkspaceError(error,lang)} {error==='BACKEND_UNAVAILABLE'&&(ru?'Повтор использует ту же заявку; проверьте историю пополнений перед новой попыткой.':'Retry keeps the same request; check funding history before starting a different intent.')}</p>}</div>;
}
