'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,ShieldCheck,Wallet,Calculator,FileCheck2,RefreshCw,Download,ShoppingBag,LockKeyhole,Route,AlertTriangle} from 'lucide-react';
import {accountMoney} from '@/lib/account-format';
import {commerceApi as api,signCommerceAllocation,verifyCommerceAllocation,type AllocationPlan} from '@/lib/commerce-wallet';
import './commerce.css';
type Line={productId:string;name:string;country:string;quantity:number;unitPriceUnits:string;amountUnits:string};
type Workflow={id:string;status:string;quote:{budgetUnits:string;totalUnits:string;lines:Line[];budgetSource:string;steps:{tool:string;status:string;explanation:string}[]};result:{orders:{id:string;name:string;quantity:number;amountUnits:string;status:string}[]}|null;expiresAt:number;currentAvailableUnits:string;fundingShortfallUnits:string;canConfirm:boolean};
type Order={id:string;name:string;quantity:number;amount_units:string;status:string};
type Sale={id:string;orderId:string;grossUnits:string;cogsUnits:string;feesUnits:string;refundReserveUnits:string;paymentStatus:string;grossSource:string;costSource:string;payment:{tx_hash:string;block_number:string;confirmed_at:number}|null;quote:Record<string,unknown>;allocations:AllocationPlan[]};
type Metrics={scenarioGrossUnits:string;verifiedTestnetGrossUnits:string;verifiedTestnetMarginUnits:string;allocatedProfitUnits:string;sales:number;verifiedSales:number};
const money=(x:unknown)=>accountMoney(typeof x==='string'?x:'0');
const transaction=(hash:string)=>'https://testnet.arcscan.app/tx/'+hash;
export function CommerceMetrics({wallet}:{wallet:string|null}){const [data,setData]=useState<Metrics|null>(null);useEffect(()=>{let active=true;setData(null);if(wallet)void api<{metrics:Metrics}>('sales').then(d=>{if(active)setData(d.metrics)}).catch(()=>{});return()=>{active=false}},[wallet]);return <section className="mc-metrics"><div className="mc-section-heading"><span className="ma-eyebrow">SALE ECONOMICS / ALL TIME / TESTNET ONLY</span><a href="/demo">Open guided flow <ArrowUpRight size={13}/></a></div><div className="ma-stats">{[['Verified testnet sales',data?.verifiedTestnetGrossUnits],['Verified testnet margin',data?.verifiedTestnetMarginUnits],['Sale-linked allocated profit',data?.allocatedProfitUnits]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value!==undefined?money(value):'—'} <small>USDC</small></strong><p>Declarations are excluded from verified sales. Allocation is not earned yield.</p></article>)}</div></section>}
export function GuidedCommerce({wallet,readOnly,onChange}:{wallet:string|null;readOnly:boolean;onChange:()=>void}){
 const [workflows,setWorkflows]=useState<Workflow[]>([]),[sales,setSales]=useState<Sale[]>([]),[orders,setOrders]=useState<Order[]>([]),[metrics,setMetrics]=useState<Metrics|null>(null),[selected,setSelected]=useState(''),[saleId,setSaleId]=useState(''),[stage,setStage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[evidence,setEvidence]=useState<Record<string,unknown>|null>(null);
 const [form,setForm]=useState({budget:'2.000000',country:'ANY',category:'creator',quantity:1}),[saleForm,setSaleForm]=useState({orderId:'',gross:'2.000000',fees:'0.010000',refundReserve:'0.020000'}),[buyer,setBuyer]=useState(''),[paymentHash,setPaymentHash]=useState(''),[scenario,setScenario]=useState(false),[allocationHash,setAllocationHash]=useState(''),[allocationId,setAllocationId]=useState('');
 const pending=useRef<{id:string;fingerprint:string}|null>(null),saleRequest=useRef<{id:string;fingerprint:string}|null>(null),epoch=useRef(0);const w=workflows.find(x=>x.id===selected)??null,sale=sales.find(x=>x.id===saleId)??null,allocation=sale?.allocations.find(x=>x.status==='EXECUTED')??sale?.allocations.find(x=>x.id===allocationId)??sale?.allocations[0]??null;
 const refresh=async()=>{const g=epoch.current;if(!wallet)return;const [wf,sa,or]=await Promise.all([api<{items:Workflow[]}>('workflows'),api<{items:Sale[];metrics:Metrics}>('sales'),api<{items:Order[]}>('orders?period=all&pageSize=100')]);if(g!==epoch.current)return;setWorkflows(wf.items);setSales(sa.items);setOrders(or.items);setMetrics(sa.metrics);setSelected(old=>old||wf.items[0]?.id||'');setSaleId(old=>old||sa.items[0]?.id||'');};
 useEffect(()=>{epoch.current++;setBusy(false);setWorkflows([]);setSales([]);setOrders([]);setMetrics(null);setSelected('');setSaleId('');setEvidence(null);setError('');setNotice('');setBuyer('');setPaymentHash('');setScenario(false);setAllocationId('');setAllocationHash('');setSaleForm(f=>({...f,orderId:''}));pending.current=null;saleRequest.current=null;const params=new URLSearchParams(location.search);const workflow=params.get('workflow');if(workflow&&/^[a-f0-9-]{36}$/i.test(workflow))setSelected(workflow);if(wallet)void refresh().catch(e=>setError((e as Error).message))},[wallet]);
 useEffect(()=>{setAllocationHash('');if(allocation&&wallet)try{setAllocationHash(sessionStorage.getItem('mercenta-commerce:'+wallet+':'+allocation.id)??'')}catch{}},[allocation?.id,wallet]);
 const run=async(fn:()=>Promise<void>)=>{if(busy||!wallet||readOnly)return;const g=epoch.current;setBusy(true);setError('');try{await fn()}catch(e){if(g===epoch.current)setError((e as Error).message)}finally{if(g===epoch.current)setBusy(false)}};
 const plan=()=>run(async()=>{const fingerprint=JSON.stringify(form);if(pending.current?.fingerprint!==fingerprint)pending.current={id:crypto.randomUUID(),fingerprint};const g=epoch.current,d=await api<Workflow>('workflows',{requestId:pending.current.id,...form});if(g!==epoch.current)return;setSelected(d.id);pending.current=null;setStage(2);setNotice('Plan created. Prices and quantities are pinned; nothing has been purchased.');await refresh()});
 const confirm=()=>run(async()=>{if(!w)return;const g=epoch.current,d=await api<Workflow>('workflows/'+w.id+'/confirm',{confirmed:true});if(g!==epoch.current)return;setSelected(d.id);setStage(3);setNotice('Bundle executed atomically. These are simulated goods, not real redeemable vouchers.');setSaleForm(s=>({...s,orderId:d.result?.orders[0]?.id??''}));onChange();await refresh()});
 const record=()=>run(async()=>{const fingerprint=JSON.stringify(saleForm);if(saleRequest.current?.fingerprint!==fingerprint)saleRequest.current={id:crypto.randomUUID(),fingerprint};const g=epoch.current,d=await api<Sale>('sales',{requestId:saleRequest.current.id,...saleForm});if(g!==epoch.current)return;setSaleId(d.id);saleRequest.current=null;setStage(4);setScenario(false);setNotice('Sale scenario recorded. COGS comes from the purchased order; gross sales are not verified until a buyer payment is checked.');await refresh()});
 const verifyPayment=()=>run(async()=>{if(!sale)return;const g=epoch.current;await api('sales/'+sale.id+'/payment',{txHash:paymentHash,buyerAddress:buyer});if(g!==epoch.current)return;setStage(5);setNotice('Exact testnet payment verified. No Mercenta account credit was created from this seller-wallet transfer.');await refresh()});
 const prepare=()=>run(async()=>{if(!sale)return;const g=epoch.current;await api('sales/'+sale.id+'/allocation',{confirmed:true,allowDeclaredScenario:scenario});if(g!==epoch.current)return;setStage(5);setNotice('Wallet allocation prepared. It moves wallet USDC, not prepaid account funds. Review the signatures.');await refresh()});
 const sign=()=>run(async()=>{if(!allocation||!wallet)return;const g=epoch.current;await signCommerceAllocation(allocation,wallet,()=>g===epoch.current,hash=>{sessionStorage.setItem('mercenta-commerce:'+wallet+':'+allocation.id,hash);if(g===epoch.current){setAllocationHash(hash);setNotice('Allocation broadcast. Not yet verified. Keep this hash and verify after confirmations.')}})});
 const verifyAllocation=()=>run(async()=>{if(!allocation||!allocationHash)return;const g=epoch.current;await verifyCommerceAllocation(allocation.id,allocationHash);if(g!==epoch.current)return;setNotice('Verified allocation receipt. Profit locking is not staking and has no APY.');setStage(6);await refresh()});
 const inspect=(kind:'workflows'|'sales',id:string)=>run(async()=>{const g=epoch.current,d=await api<Record<string,unknown>>('evidence/'+kind+'/'+id);if(g!==epoch.current)return;setEvidence(d);setStage(6)});
 const download=()=>{if(!evidence)return;const blob=new Blob([JSON.stringify(evidence,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mercenta-testnet-evidence.json';a.click();URL.revokeObjectURL(url)};
 const disabled=busy||!wallet||readOnly;
 const stages=[['Plan','Budget and catalogue'],['Confirm','Explicit bounded spend'],['Sale','Separate resale from funding'],['Payment','Verify the buyer transfer'],['Allocate','Wallet-owned profit vault'],['Evidence','Inspect the receipts']];
 return <section className="mc"><div className="mc-banner"><ShieldCheck size={20}/><div><b>From intent to protected margin.</b><p>Arc Testnet funds are real test transfers. Digital goods remain simulated. Customer deposits are not sales; declarations are not verified revenue.</p></div><a href="https://docs.mercenta.xyz/docs/guides/guided-commerce" target="_blank" rel="noreferrer">Demo guide <ArrowUpRight size={14}/></a></div><div className="mc-stepper">{stages.map(([name,detail],i)=><button key={name} className={stage===i+1?'active':''} onClick={()=>setStage(i+1)}><span>{i+1}</span><div><b>{name}</b><small>{detail}</small></div></button>)}</div>{!wallet&&<div className="mc-info"><Wallet size={19}/><p>Connect and sign in with your wallet first. Fund your Mercenta account for purchases; keep separate wallet test USDC for gas and vault allocations. <a href="/app?section=funds">Open Funds ↗</a></p></div>}{readOnly&&<p className="mc-error">Backend is read-only. No new spending or settlement is reported.</p>}{error&&<p role="alert" className="mc-error">{error.replaceAll('_',' ')}</p>}{notice&&<p role="status" className="mc-info">{notice}</p>}<div className="mc-layout"><div className="mc-main">
 {stage===1&&<article className="mc-card"><span className="ma-eyebrow">01 / BOUNDED PLANNING</span><h2>Your budget.<br/><em>A checked plan.</em></h2><p>Choose constraints. The backend selects the lowest-price eligible test product, reads account funds, pins the quote and checks policy. Planning never spends money.</p><div className="mc-fields"><label>Budget (test USDC)<input value={form.budget} inputMode="decimal" onChange={e=>setForm(f=>({...f,budget:e.target.value}))}/></label><label>Quantity per product<input type="number" min="1" max="5" value={form.quantity} onChange={e=>setForm(f=>({...f,quantity:Number(e.target.value)}))}/></label><label>Country<select value={form.country} onChange={e=>setForm(f=>({...f,country:e.target.value}))}>{['ANY','US','EU','GLOBAL'].map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value}))}>{['ANY','gaming','creator','developer','cloud','streaming'].map(x=><option key={x}>{x}</option>)}</select></label></div><button className="ma-button" disabled={disabled} onClick={plan}><Route size={16}/>Build checked plan</button><a className="mc-secondary" href="/agent">Or ask the agent to plan under a budget ↗</a></article>}
 {stage===2&&<article className="mc-card"><span className="ma-eyebrow">02 / EXPLICIT CONFIRMATION</span><h2>Know the total.<br/><em>Then confirm.</em></h2><label>Saved workflow<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a plan</option>{workflows.map(x=><option key={x.id} value={x.id}>{x.id.slice(0,8)} · {x.status} · {money(x.quote.totalUnits)} USDC</option>)}</select></label>{w?<><div className="mc-lines">{w.quote.lines.map(l=><div key={l.productId}><span><b>{l.name}</b><small>{l.country} · quantity {l.quantity} · unit price {money(l.unitPriceUnits)} USDC</small></span><strong>{money(l.amountUnits)} USDC</strong></div>)}</div><div className="mc-totals"><span>Total {money(w.quote.totalUnits)} USDC</span><span>Budget {money(w.quote.budgetUnits)} USDC</span><span>Available {money(w.currentAvailableUnits)} USDC</span></div><p>Quote expires {new Date(w.expiresAt).toLocaleString()}. No purchase gas is charged: this uses the prepaid account. Funding and contract gas are separate.</p>{BigInt(w.fundingShortfallUnits)>0n&&<p className="mc-error">Funding shortfall: {money(w.fundingShortfallUnits)} USDC. <a href="/app?section=funds">Top up account ↗</a></p>}{w.quote.steps.map(s=><div className="mc-trace" key={s.tool}><Check size={14}/><div><b>{s.tool} · {s.status}</b><p>{s.explanation}</p></div></div>)}<button className="ma-button" disabled={disabled||!w.canConfirm} onClick={confirm}><ShoppingBag size={16}/>Confirm simulated bundle · {money(w.quote.totalUnits)} USDC</button>{w.status==='EXECUTED'&&<button className="ma-button secondary" onClick={()=>setStage(3)}>Continue to sale record</button>}<button className="mc-secondary" disabled={disabled||w.status!=='PROPOSED'} onClick={()=>run(async()=>{await api('workflows/'+w.id+'/cancel',{confirmed:true});await refresh()})}>Cancel unexecuted plan</button></>:<p>Create or select a plan first.</p>}</article>}
 {stage===3&&<article className="mc-card"><span className="ma-eyebrow">03 / SALE RECORD</span><h2>A purchase is a cost.<br/><em>A resale is a separate event.</em></h2><p>The purchased order fixes COGS. Enter a sale scenario without inventing verified revenue. Each order can have one full-quantity sale record in this MVP.</p><label>Purchased test order<select value={saleForm.orderId} onChange={e=>setSaleForm(f=>({...f,orderId:e.target.value}))}><option value="">Select an owned order</option>{orders.filter(o=>!sales.some(s=>s.orderId===o.id)).map(o=><option key={o.id} value={o.id}>{o.name} · qty {o.quantity} · COGS {money(o.amount_units)}</option>)}</select></label><div className="mc-fields">{(['gross','fees','refundReserve'] as const).map(k=><label key={k}>{({gross:'Declared gross sales (USDC)',fees:'Variable fees (USDC)',refundReserve:'Refund reserve (USDC)'})[k]}<input value={saleForm[k]} inputMode="decimal" onChange={e=>setSaleForm(f=>({...f,[k]:e.target.value}))}/></label>)}</div><button className="ma-button" disabled={disabled||!saleForm.orderId} onClick={record}><Calculator size={16}/>Record scenario and calculate margin</button></article>}
 {stage===4&&<article className="mc-card"><span className="ma-eyebrow">04 / BUYER PAYMENT EVIDENCE</span><h2>A declaration is not cash.<br/><em>Check the transfer.</em></h2><label>Sale record<select value={saleId} onChange={e=>setSaleId(e.target.value)}><option value="">Select a sale</option>{sales.map(s=><option key={s.id} value={s.id}>{s.id.slice(0,8)} · {s.paymentStatus}</option>)}</select></label>{sale&&<><p>A different buyer wallet must send exactly <b>{money(sale.grossUnits)} test USDC</b> to your seller wallet on Arc after this record was created. This does not top up your Mercenta account.</p><code className="mc-address">{wallet}</code><label>Buyer public address<input value={buyer} onChange={e=>setBuyer(e.target.value)} placeholder="0x…"/></label><label>Payment transaction hash<input value={paymentHash} onChange={e=>setPaymentHash(e.target.value)} placeholder="0x…"/></label><button className="ma-button" disabled={disabled||!/^0x[a-fA-F0-9]{40}$/.test(buyer)||!/^0x[a-fA-F0-9]{64}$/.test(paymentHash)} onClick={verifyPayment}><ShieldCheck size={16}/>Verify exact payment</button>{sale.payment&&<a className="mc-secondary" target="_blank" rel="noreferrer" href={transaction(sale.payment.tx_hash)}>Inspect verified buyer payment ↗</a>}<p>Two confirmations, canonical block, exact sender/receiver/amount, and receipt replay protection are required. Goods are still simulated; this is not proof of a real commercial invoice.</p><button className="ma-button secondary" onClick={()=>setStage(5)}>Continue to allocation</button></>}</article>}
 {stage===5&&<article className="mc-card"><span className="ma-eyebrow">05 / SELLER-OWNED ALLOCATION</span><h2>Protect restock.<br/><em>Allocate the margin.</em></h2><label>Sale record<select value={saleId} onChange={e=>setSaleId(e.target.value)}><option value="">Select a sale</option>{sales.map(s=><option key={s.id} value={s.id}>{s.id.slice(0,8)} · {s.paymentStatus}</option>)}</select></label>{sale&&<><div className="mc-split">{[['Gross','grossUnits'],['Restock / COGS','cogsUnits'],['Variable fees','feesUnits'],['Refund reserve','refundReserveUnits'],['Allocatable margin','allocatableMarginUnits'],['Profit budget','profitUnits'],['Owner pay','ownersPayUnits'],['Tax budget','taxUnits'],['OPEX','opexUnits']].map(([label,key])=><div key={key}><span>{label}</span><b>{money(sale.quote[key!])} USDC</b></div>)}</div><p>Illustrative split: profit 10%, owner 25%, tax 25%, OPEX 40% of margin. Minimum margin floor: 5% of gross. Not tax advice or yield.</p>{sale.paymentStatus!=='TESTNET_PAYMENT_VERIFIED'&&<label className="mc-check"><input type="checkbox" checked={scenario} onChange={e=>setScenario(e.target.checked)}/><span>I understand this is a declared scenario, not proven revenue. The allocation uses my own wallet funds.</span></label>}<button className="ma-button secondary" disabled={disabled||(sale.paymentStatus!=='TESTNET_PAYMENT_VERIFIED'&&!scenario)} onClick={prepare}>Prepare immutable allocation proposal</button>{allocation&&<div className="mc-sign"><label>Allocation proposal — select the original to recover its receipt<select value={allocation.id} onChange={e=>setAllocationId(e.target.value)}>{sale.allocations.map(p=><option key={p.id} value={p.id}>{p.id.slice(0,8)} · {p.status}</option>)}</select></label><b>{allocation.status}</b><p>Sale ID is stable across renewed proposals, preventing a second contract settlement for this sale. Wallet needs {money(sale.grossUnits)} USDC plus gas. Prepaid account funds cannot finance this signature.</p>{allocation.status==='WALLET_SIGNATURE_REQUIRED'&&<><button className="ma-button" disabled={disabled||!!allocationHash||allocation.expiresAt<Date.now()} onClick={sign}><Wallet size={16}/>Review exact approval & allocation in wallet</button><label>Allocation hash — recover a previously submitted transaction<input value={allocationHash} onChange={e=>setAllocationHash(e.target.value)} placeholder="0x…"/></label><button className="ma-button secondary" disabled={disabled||!/^0x[a-fA-F0-9]{64}$/.test(allocationHash)} onClick={verifyAllocation}>Verify allocation receipt</button></>}{allocation.result?.txHash!=null&&<a target="_blank" rel="noreferrer" href={transaction(String(allocation.result.txHash))}>Inspect verified allocation ↗</a>}</div>}</>}</article>}
 {stage===6&&<article className="mc-card"><span className="ma-eyebrow">06 / EVIDENCE, NOT CLAIMS</span><h2>Every result.<br/><em>A source you can inspect.</em></h2><div className="mc-controls"><button className="ma-button secondary" disabled={disabled||!w} onClick={()=>w&&inspect('workflows',w.id)}>Inspect selected workflow</button><button className="ma-button secondary" disabled={disabled||!sale} onClick={()=>sale&&inspect('sales',sale.id)}>Inspect selected sale</button></div><p>Exports contain your own IDs, wallet addresses, sealed journals and receipt metadata. They are private account evidence, not an independent audit.</p>{evidence&&<><button className="ma-button" onClick={download}><Download size={16}/>Download evidence JSON</button><pre className="mc-evidence">{JSON.stringify(evidence,null,2)}</pre></>}</article>}
 </div><aside className="mc-aside"><article className="mc-card"><span className="ma-eyebrow">TRUST BOUNDARIES</span><h3>Model proposes.<br/>Policy checks.<br/>You confirm.</h3><ul><li><ShieldCheck size={15}/>Prepaid purchases: authoritative ledger and atomic debit.</li><li><Wallet size={15}/>Vault allocations: your wallet signatures, exact allowance.</li><li><FileCheck2 size={15}/>Buyer payment: verified transfer, never invented revenue.</li><li><LockKeyhole size={15}/>Quarterly profit lock: no live Earn or APY.</li></ul><a target="_blank" rel="noreferrer" href="https://testnet.arcscan.app/address/0xf6802aef42935d78b56830c8b5d40616bf716995">Inspect deployed vault ↗</a><p>Testnet contract, no independent audit. Do not send mainnet funds or keys.</p></article><article className="mc-card"><span className="ma-eyebrow">YOUR SALE METRICS / ALL TIME</span>{[['Verified testnet gross',metrics?.verifiedTestnetGrossUnits],['Verified testnet margin',metrics?.verifiedTestnetMarginUnits],['Sale-linked allocated profit',metrics?.allocatedProfitUnits],['Declared scenario gross',metrics?.scenarioGrossUnits]].map(([label,value])=><div className="mc-number" key={label}><span>{label}</span><b>{value!==undefined?money(value):'—'} USDC</b></div>)}<p>Declared scenarios are not included in verified gross or verified margin. Profit allocation is a budget movement, not a return on investment.</p><button className="mc-secondary" disabled={disabled} onClick={()=>run(refresh)}><RefreshCw size={13}/>Refresh evidence and state</button></article><article className="mc-card"><span className="ma-eyebrow">REHEARSAL CHECKLIST</span><p>Two wallets for a buyer-payment proof. Test USDC for the prepaid purchase, seller allocation and gas. No real codes or unreviewed yield vaults. Use the recorded transaction if the browser closes after broadcasting.</p><a href="/app?section=funds">Funding and history ↗</a></article></aside></div></section>;
}
