'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Bot,ShieldCheck,Sun,Moon,BookOpen,Globe,Info} from 'lucide-react';
import {MainnetServiceStatus} from './MainnetServiceStatus';
import {refreshPublicCatalog} from '@/lib/public-catalog-client';
import {WorkspaceNavigator} from './WorkspaceNavigator';
import {MainnetIdentity} from './MainnetIdentity';
import './mainnet-identity.css';
import {useSurfaceMotion} from '@/lib/surface-motion';
import {Brand} from './ProductShell';import {NetworkSelector} from './NetworkSelector';import {CatalogFamilyCard} from './CatalogFamilyCard';import {CatalogFamilyDialog} from './CatalogFamilyDialog';import {CatalogCollection} from './CatalogCollection';import {OfficialContacts} from '@/components/OfficialContacts';
import type {BrowseCatalog} from '@/lib/catalog-browse';import {unpackBrowse} from '@/lib/catalog-browse';import {homeFeaturedFamilies} from '@/lib/home-featured';import type {ProductFamily} from '@/lib/catalog-families';import {groupCatalog,regionLabel} from '@/lib/catalog-families';import {useGuideLanguage,GuideLanguage} from './WorkspaceGuide';
import './account.css';import './workspace-ux.css';import './network-workspace.css';import './workspace-polish.css';import './mainnet-polish.css';
type View='home'|'catalogue'|'agent'|'launch';
function Hint({label,text}:{label:string;text:string}){return <details className="mn-hint"><summary aria-label={label}><Info size={15}/></summary><p>{text}</p></details>;}
export function MainnetWorkspace({catalog,initialSection='dashboard'}:{catalog:BrowseCatalog;initialSection?:string}){
 const [lang,setLang]=useGuideLanguage(),ru=lang==='ru';
 const surface=useRef<HTMLElement>(null);
 const [theme,setTheme]=useState<'dark'|'light'>('dark'),[tab,setTab]=useState<View>(initialSection==='agent-chat'?'agent':initialSection==='shop'?'catalogue':['orders','funds','budget','support','api-access','launch'].includes(initialSection)?'launch':'home');
 useSurfaceMotion(surface,tab);
 const [activeFamily,setActiveFamily]=useState<ProductFamily|null>(null),[goal,setGoal]=useState(''),[region,setRegion]=useState('all'),[query,setQuery]=useState('');
 const [feed,setFeed]=useState(catalog);
 const products=useMemo(()=>unpackBrowse(feed).products,[feed]),regions=useMemo(()=>[...new Set(groupCatalog(products).flatMap(f=>f.regions))].sort(),[products]);
 const [featured,setFeatured]=useState(()=>homeFeaturedFamilies(feed,false));
 useEffect(()=>{if(feed)setFeatured(homeFeaturedFamilies(feed,true));},[feed]);
 useEffect(()=>{let active=true;const refresh=()=>{if(document.visibilityState==='hidden')return;void refreshPublicCatalog().then(v=>{if(active)setFeed(v)}).catch(()=>{});};refresh();const timer=setInterval(refresh,75000);return()=>{active=false;clearInterval(timer)};},[]);
 const open=(v:View)=>{setTab(v);const section={home:'dashboard',catalogue:'shop',agent:'agent-chat',launch:'launch'}[v];window.history.replaceState(null,'',section==='dashboard'?'/app':'/app?section='+section);};
 const sections:readonly [View,string][]=[['home',ru?'Главная':'Overview'],['catalogue',ru?'Каталог':'Catalogue'],['agent',ru?'Агент':'Agent'],['launch',ru?'Статус сервиса':'Service status']];
 return <div className="mp ma ma-ux nw-mainnet mn-prelaunch" data-theme={theme}>
  <a className="ux-skip" href="#mainnet-content">{ru?'Перейти к содержимому':'Skip to content'}</a>
  <div className="ma-main"><header className="ma-header"><Brand small/><GuideLanguage lang={lang} onChange={setLang}/><WorkspaceNavigator ru={ru} network="mainnet" disabled={!!activeFamily} onNavigate={s=>open(s==="Shop"?"catalogue":s==="Agent Chat"?"agent":s==="Dashboard"?"home":"launch")}/><NetworkSelector mode="mainnet" ru={ru}/><button className="ma-icon" aria-label={ru?'Сменить тему':'Change theme'} onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><a className="ma-button secondary" href="/api-docs"><BookOpen size={16}/>{ru?'API документация':'API docs'}</a></header>
  <main ref={surface} id="mainnet-content" className="ma-content">
   <div className="mn-status-strip"><span><span className="mn-status-dot live"/>{ru?'ARC MAINNET · ШЛЮЗ АКТИВЕН (5042)':'ARC MAINNET · GATEWAY LIVE (5042)'}</span><a href="https://explorer.arc.io/address/0x06b67adf8d63c8c35a6beda42a3bb93d485af3ed#code" target="_blank" rel="noreferrer" style={{display:'inline-flex',alignItems:'center',gap:'6px',color:'#63b3ed',textDecoration:'none',fontSize:'12px'}}><ShieldCheck size={14}/>{ru?'Контракт верифицирован (0x06b6…3ed)':'Verified Router (0x06b6…3ed)'}<ArrowUpRight size={13}/></a></div>
   <div className="mn-gateway-banner" role="status"><div className="mn-gateway-info"><div className="mn-gateway-title"><ShieldCheck size={18}/><strong>{ru?'Шлюз покупок активен на Arc Mainnet':'MercentaCheckout Gateway Live on Arc Mainnet'}</strong></div><p>{ru?'Смарт-контракт MercentaCheckout верифицирован на Blockscout. Продажи открыты (Unpaused). Оплата производится в USDC сети Arc (Chain ID 5042) через Web3-кошелёк.':'Smart contract MercentaCheckout is verified on Blockscout (exact match). Sales are unpaused. Purchases execute in Arc USDC (Chain ID 5042) via on-chain Web3 settlement.'}</p></div><div className="mn-gateway-meta"><span><b>Router:</b> <a href="https://explorer.arc.io/address/0x06b67adf8d63c8c35a6beda42a3bb93d485af3ed#code" target="_blank" rel="noreferrer">0x06b6…3ed <ArrowUpRight size={11}/></a></span><span><b>Merchant:</b> <a href="https://explorer.arc.io/address/0x58863e4a739da0e62c2eba258b7783e95d5c48ce" target="_blank" rel="noreferrer">0x5886…48ce <ArrowUpRight size={11}/></a></span></div></div>
   <div className="mn-identity-bar"><div><strong>{ru?'Отдельная личность Mainnet':'Separate Mainnet identity'}</strong><p>{ru?'Подпись только для входа. Сессия — 15 минут; покупка требует отдельного разрешения.':'Sign-in signature only. A 15-minute session; purchases require separate permission.'}</p></div><MainnetIdentity ru={ru}/></div>
   <div className="nw-mobile-language"><GuideLanguage lang={lang} onChange={setLang}/></div>
   <nav className="nw-mainnet-tabs" role="tablist" aria-label={ru?'Разделы Mainnet':'Mainnet sections'}>{sections.map(([id,label],i)=><button key={id} id={'mn-tab-'+id} role="tab" aria-selected={tab===id} tabIndex={tab===id?0:-1} aria-controls={'mn-panel-'+id} onClick={()=>open(id)} onKeyDown={e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?sections.length-1:(i+(e.key==='ArrowRight'?1:sections.length-1))%sections.length;open(sections[n][0]);document.getElementById('mn-tab-'+sections[n][0])?.focus();}}>{label}</button>)}</nav>
   <section id={'mn-panel-'+tab} role="tabpanel" aria-labelledby={'mn-tab-'+tab} className="mn-panel">
   {tab==='home'&&<><div className="mn-hero-grid"><div className="nw-mainnet-hero"><span className="rf-context">MERCENTA / ARC MAINNET · 5042</span><h1>{ru?'Найдите нужное.\nВыбирайте осознанно.':'Find what you need.\nChoose with clarity.'}</h1><p>{ru?'Знакомые платформы. Подходящий регион. Понятные детали до любого решения об оплате.':'Familiar platforms. The right region. Clear details before any decision to pay.'}</p><div className="nw-mainnet-cta"><button className="ma-button" onClick={()=>open('catalogue')}>{ru?'Посмотреть товары':'Explore products'}<ArrowRight size={18}/></button><button className="ma-button secondary" onClick={()=>open('agent')}>{ru?'Подготовить запрос':'Prepare a brief'}<Bot size={18}/></button></div><p className="mn-caption">{ru?'Для просмотра кошелёк не нужен.':'No wallet needed to explore.'}</p></div>
    <aside className="mn-next-step" aria-label={ru?'Как будет работать покупка':'Purchase workflow'}><span className="rf-context">{ru?'ВАШ СЛЕДУЮЩИЙ ШАГ':'YOUR NEXT STEP'}</span><h2>{ru?'Сначала детали.\nПотом решение.':'Details first.\nDecision second.'}</h2><ol>{(ru?[['Товар и регион','Проверьте, где можно активировать товар.'],['Точная сумма','Перед оплатой нужен свежий расчёт в USDC.'],['Ваше подтверждение','Разрешение на оплату — отдельный шаг.']]:[['Product and region','Check where the product can be redeemed.'],['Exact total','A fresh USDC payment quote comes before payment.'],['Your confirmation','Permission to spend is a separate step.']]).map(([title,text],i)=><li key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><div className="mn-caption"><ShieldCheck size={14}/>{ru?'Прямая оплата на смарт-контракт MercentaCheckout.':'Direct payment to MercentaCheckout smart contract.'}</div></aside></div>
    <div className="mn-network-facts"><span><Globe size={16}/>Arc Mainnet <b>5042</b></span><span>USDC <Hint label={ru?'Точность USDC':'USDC precision'} text={ru?'USDC для gas — 18 знаков; ERC-20 USDC — 6. Это две формы одного баланса, их нельзя складывать.':'Native USDC for gas uses 18 decimals; ERC-20 USDC uses 6. They are two views of one balance and must not be added.'}/></span><a href="https://explorer.arc.io" target="_blank" rel="noreferrer">{ru?'Обозреватель сети':'Network explorer'}<ArrowUpRight size={14}/></a></div></>}
   {(tab==='home'||tab==='catalogue')&&<><div className="rf-section-heading"><div><span className="rf-context">{ru?'ЦИФРОВЫЕ ТОВАРЫ':'DIGITAL GOODS'}</span><h2>{tab==='home'?(ru?'Знакомые платформы. Один каталог.':'Familiar platforms. One catalogue.'):(ru?'Выберите товар и регион':'Choose a product and region')}</h2></div>{tab==='home'?<button className="mn-text-button" onClick={()=>open('catalogue')}>{ru?'Весь каталог':'Full catalogue'}<ArrowRight size={16}/></button>:<span>{ru?'Ориентировочные цены в USD':'Indicative USD prices'}</span>}</div>
    {tab==='catalogue'?<CatalogCollection key={query+'|'+region} products={products} lang={lang} isMainnet={true} initialQuery={query} initialRegion={region}/>:<div className="cf-grid">{featured.map(family=><CatalogFamilyCard key={family.key} family={family} ru={ru} priority onOpen={()=>setActiveFamily(family)}/>)}</div>}
    <p className="rf-context-note">{ru?'Сохранённый каталог — не котировка оплаты. Регион, цена и наличие проверяются заново перед заказом.':'A saved listing is not a payment quote. Region, price and availability must be rechecked before ordering.'}</p></>}
   {tab==='agent'&&<div className="mn-agent-grid"><div><span className="rf-context">MERCENTA / PURCHASE BRIEF</span><h1>{ru?'Понятная цель.\nЯсные границы.':'A clear goal.\nClear boundaries.'}</h1><p>{ru?'Подготовьте поиск сейчас. Mainnet-агент пока не запущен: эта форма не обращается к ИИ, не подписывает разрешений и не покупает товары.':'Prepare your search now. The Mainnet agent is not released: this form does not call an AI model, sign permissions or purchase products.'}</p><a href="https://testnet.mercenta.xyz/app?section=agent-chat" className="mn-text-button">{ru?'Попробовать работающего агента в Testnet':'Try the working agent on Testnet'}<ArrowUpRight size={16}/></a></div><form className="mn-brief" onSubmit={e=>{e.preventDefault();if(!goal.trim())return;setQuery(goal.trim());open('catalogue');}}><label htmlFor="mn-product">{ru?'Какой товар нужен?':'What product do you need?'}</label><input id="mn-product" maxLength={100} value={goal} onChange={e=>setGoal(e.target.value)} placeholder={ru?'Например, Steam или Spotify':'For example, Steam or Spotify'}/><div className="mn-suggestions">{['Steam','Roblox','Spotify'].map(s=><button type="button" key={s} onClick={()=>setGoal(s)}>{s}</button>)}</div><label htmlFor="mn-region">{ru?'Где будете активировать?':'Where will you redeem it?'}</label><select id="mn-region" value={region} onChange={e=>setRegion(e.target.value)}><option value="all">{ru?'Пока не выбрал регион':'Choose a region later'}</option>{regions.map(r=><option key={r} value={r}>{regionLabel(r,ru)}</option>)}</select><button className="ma-button" type="submit" disabled={!goal.trim()}>{ru?'Посмотреть подходящие варианты':'Review matching products'}<ArrowRight size={17}/></button><p className="mn-caption"><ShieldCheck size={14}/>{ru?'Только локальный поиск. Не разрешение тратить деньги.':'Local catalogue search only. Not permission to spend.'}</p></form></div>}
   {tab==='launch'&&<MainnetServiceStatus ru={ru}/>}
   </section>
   {activeFamily&&<CatalogFamilyDialog family={activeFamily} lang={lang} isMainnet={true} onClose={()=>setActiveFamily(null)}/>}
   <div className="nw-journey"><div><span className="rf-context">{ru?'ХОТИТЕ ПРОЙТИ ВЕСЬ ПУТЬ СЕЙЧАС?':'WANT TO TRY THE FULL JOURNEY NOW?'}</span><h2>{ru?'Отдельная среда. Без настоящих денег.':'A separate environment. Without real money.'}</h2><p>{ru?'В Testnet работают агент, лимиты и тестовые заказы. Балансы между сетями не переносятся.':'Testnet has the agent, limits and test orders. Balances do not carry between networks.'}</p></div><a className="ma-button secondary" href="https://testnet.mercenta.xyz/app">{ru?'Открыть Testnet':'Open Testnet'}<ArrowUpRight size={17}/></a></div>
   <footer className="ma-footer"><span>Mercenta · Arc Mainnet · {ru?'Шлюз активен':'Gateway Live'}</span><a href="/api-docs">OpenAPI / Swagger</a><OfficialContacts ru={ru}/></footer>
  </main></div>
 </div>;
}
