'use client';
import {useMemo,useState} from 'react';import {ArrowRight,ArrowUpRight,Bot,ShieldCheck,Sun,Moon,BookOpen} from 'lucide-react';
import {Brand} from './ProductShell';import {NetworkSelector} from './NetworkSelector';import {CatalogFamilyCard} from './CatalogFamilyCard';import {CatalogFamilyDialog} from './CatalogFamilyDialog';import {CatalogCollection} from './CatalogCollection';import {OfficialContacts} from '@/components/OfficialContacts';
import type {BrowseCatalog} from '@/lib/catalog-browse';import {unpackBrowse} from '@/lib/catalog-browse';import {homeFeaturedFamilies} from '@/lib/home-featured';import type {ProductFamily} from '@/lib/catalog-families';import {useGuideLanguage,GuideLanguage} from './WorkspaceGuide';import './account.css';import './workspace-ux.css';import './network-workspace.css';
import './workspace-polish.css';
export function MainnetWorkspace({catalog,initialSection='dashboard'}:{catalog:BrowseCatalog;initialSection?:string}){
 const [lang,setLang]=useGuideLanguage(),ru=lang==='ru',[theme,setTheme]=useState<'dark'|'light'>('dark'),[tab,setTab]=useState(initialSection==='agent-chat'?'agent':initialSection==='shop'?'catalogue':'home'),[activeFamily,setActiveFamily]=useState<ProductFamily|null>(null);
 const products=useMemo(()=>unpackBrowse(catalog).products,[catalog]),featured=useMemo(()=>homeFeaturedFamilies(catalog),[catalog]);
 return <div className="mp ma ma-ux nw-mainnet" data-theme={theme}><a className="ux-skip" href="#mainnet-content">{ru?'Перейти к содержимому':'Skip to content'}</a><div className="ma-main"><header className="ma-header"><Brand small/><GuideLanguage lang={lang} onChange={setLang}/><NetworkSelector mode="mainnet" ru={ru}/><button className="ma-icon" aria-label={ru?'Сменить тему':'Change theme'} onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><a className="ma-button secondary" href="/api-docs"><BookOpen size={16}/>API docs</a></header><main id="mainnet-content" className="ma-content"><div className="nw-preview-note" role="status"><ShieldCheck size={20}/><div><b>{ru?'Mainnet · предпросмотр, без оплаты':'Mainnet · preview, not checkout'}</b><p>{ru?'Настоящие покупки, пополнения и финансовые действия пока закрыты. Не отправляйте средства. Testnet-баланс здесь не отображается.':'Real purchases, deposits and financial actions are not enabled. Do not send funds. Your testnet balance is not shown here.'}</p></div></div><div className="nw-mobile-language"><GuideLanguage lang={lang} onChange={setLang}/></div><nav className="nw-mainnet-tabs" role="tablist" aria-label={ru?'Mainnet разделы':'Mainnet workspace'}>{[['home',ru?'Главная':'Overview'],['catalogue',ru?'Каталог':'Catalogue'],['agent',ru?'Агент':'Agent']].map(([id,label])=><button key={id} id={'mn-tab-'+id} role="tab" tabIndex={tab===id?0:-1} onKeyDown={e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const tabs=['home','catalogue','agent'],index=tabs.indexOf(id),next=e.key==='Home'?0:e.key==='End'?2:(index+(e.key==='ArrowRight'?1:2))%3;setTab(tabs[next]);document.getElementById('mn-tab-'+tabs[next])?.focus()}} aria-selected={tab===id} aria-controls={'mn-panel-'+id} onClick={()=>setTab(id)}>{label}</button>)}</nav><section id={'mn-panel-'+tab} role="tabpanel" aria-labelledby={'mn-tab-'+tab}>
 {tab==='home'&&<><div className="nw-mainnet-hero"><span className="rf-context">MERCENTA / ARC MAINNET · 5042</span><h1>{ru?'Настоящие товары.\nПродуманные покупки.':'Real products.\nConsidered purchases.'}</h1><p>{ru?'Посмотрите ассортимент и регионы. Познакомьтесь с тем, как агент будет подбирать товар в пределах вашего бюджета. Оплата откроется только после production-проверок.':'Explore products and regions. See how an agent can source a product within your budget. Checkout opens only after production verification.'}</p><div className="nw-mainnet-cta"><button className="ma-button" onClick={()=>setTab('catalogue')}>{ru?'Посмотреть товары':'Explore products'}<ArrowRight size={18}/></button><button className="ma-button secondary" onClick={()=>setTab('agent')}>{ru?'Как помогает агент':'Meet the agent'}<Bot size={18}/></button></div></div><div className="nw-journey"><div><span className="rf-context">{ru?'ХОТИТЕ ПОПРОБОВАТЬ СЕЙЧАС?':'WANT TO TRY IT NOW?'}</span><h2>{ru?'Весь путь — без настоящих денег.':'The whole journey, without real money.'}</h2><p>{ru?'В Testnet доступны бюджет, агент, тестовая покупка и журнал действий.':'Testnet includes budgeting, the agent, a test purchase and an action record.'}</p></div><a className="ma-button secondary" href="https://testnet.mercenta.xyz/app">{ru?'Открыть Testnet':'Open Testnet'}<ArrowUpRight size={17}/></a></div></>}
 {(tab==='home'||tab==='catalogue')&&<><div className="rf-section-heading"><h2>{ru?'Ассортимент Mercenta':'The Mercenta catalogue'}</h2><span>{ru?'Предпросмотр цен в USD':'Indicative USD prices'}</span></div>{tab==='catalogue'?<CatalogCollection products={products} lang={lang} readOnly previewOnly/>:<div className="cf-grid">{featured.map(family=><CatalogFamilyCard key={family.key} family={family} ru={ru} priority onOpen={()=>setActiveFamily(family)}/>)}</div>}<p className="rf-context-note">{ru?'Выбор региона не разрешает оплату. Цены из сохранённого каталога, не гарантия наличия.':'Region selection does not authorize payment. Saved catalogue prices do not guarantee availability.'}</p></>}
 {tab==='agent'&&<div className="nw-agent-preview"><Bot size={28}/><span className="rf-context">{ru?'ПРИМЕР ПУТИ · НИЧЕГО НЕ ВЫПОЛНЕНО':'WORKFLOW PREVIEW · NOT EXECUTED'}</span><h2>{ru?'Ваша цель. Понятные границы.':'Your goal. Clear boundaries.'}</h2><p>{ru?'Вы задаёте товар, регион и предел расходов. Агент ищет варианты и проверяет ограничения. Ниже — описание будущего mainnet-пути, не выполненные операции.':'You set the product, region and spending cap. The agent finds options and checks boundaries. This describes the production workflow, not completed actions.'}</p><ol>{(ru?['Найти товар и подходящий регион.','Проверить наличие, цену и лимиты.','Показать предложение или использовать отдельное ограниченное разрешение.','Проверить списание и выдачу по исходному заказу.']:['Find the product and eligible region.','Check stock, price and spending boundaries.','Show a proposal or use a separate bounded authorization.','Verify payment and delivery against the original order.']).map(s=><li key={s}>{s}</li>)}</ol><a className="ma-button" href="https://testnet.mercenta.xyz/app?section=agent-chat">{ru?'Попробовать агента в Testnet':'Try the agent in Testnet'}<ArrowUpRight size={17}/></a></div>}
 </section>{activeFamily&&<CatalogFamilyDialog family={activeFamily} lang={lang} readOnly previewOnly onClose={()=>setActiveFamily(null)}/>}<footer className="ma-footer"><span>Mercenta · Arc Mainnet preview</span><a href="/api-docs">OpenAPI / Swagger</a><OfficialContacts ru={ru}/></footer></main></div></div>
}
