'use client';
import {useEffect,useRef,useState} from 'react';import {ChevronDown,Check,ShieldCheck,ArrowUpRight,X} from 'lucide-react';
import {NETWORKS,networkDestination,type NetworkMode} from '@/lib/network-profile';import './network-workspace.css';
export function NetworkSelector({mode='testnet',ru=false,disabled=false}:{mode?:NetworkMode;ru?:boolean;disabled?:boolean}){
 const [target,setTarget]=useState<NetworkMode|null>(null),dialog=useRef<HTMLDialogElement>(null),menu=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{if(!target)return;const focused=document.activeElement as HTMLElement|null;const node=dialog.current;node?.showModal();return()=>{node?.close();if(focused?.isConnected)focused.focus()}},[target]);
 const choose=(next:NetworkMode)=>{menu.current?.removeAttribute('open');if(next!==mode)setTarget(next)};
 return <><details ref={menu} className="nw-selector"><summary aria-label={ru?'Выбрать сеть':'Choose network'} aria-disabled={disabled} onClick={e=>{if(disabled)e.preventDefault()}}><span className={'nw-dot '+mode}/>{mode==='mainnet'?'Mainnet':'Testnet'}<ChevronDown size={14}/></summary><div className="nw-network-menu"><p>{ru?'Сеть пространства':'Workspace network'}</p>{(['testnet','mainnet'] as const).map(n=><button key={n} disabled={disabled} aria-pressed={n===mode} onClick={()=>choose(n)}><span><b>{NETWORKS[n].name}</b><small>{n==='testnet'?(ru?'Тестовые средства · симулированная выдача':'Test assets · simulated delivery'):(ru?'Настоящий USDC · покупки пока закрыты':'Real USDC · checkout not enabled')}</small></span>{n===mode&&<Check size={16}/>}</button>)}<small>{ru?'Балансы и вход не переносятся между сетями.':'Balances and sign-in do not carry between networks.'}</small></div></details>{target&&<dialog ref={dialog} className="nw-switch-dialog" onCancel={e=>{e.preventDefault();setTarget(null)}} aria-labelledby="network-switch-title"><button className="nw-dialog-close" aria-label={ru?'Отмена':'Cancel'} onClick={()=>setTarget(null)}><X size={20}/></button><ShieldCheck size={28}/><h2 id="network-switch-title">{ru?'Перейти в':'Switch to'} {NETWORKS[target].name}?</h2><p>{target==='mainnet'?(ru?'Вы откроете отдельное mainnet-пространство. Реальные покупки и пополнения пока закрыты. Не отправляйте деньги.':'You will open a separate mainnet workspace. Real purchases and deposits are not enabled yet. Do not send funds.'):(ru?'Вы откроете безопасную репетицию. Только test USDC; коды не активируются.':'You will open a safe rehearsal. Test USDC only; delivery codes cannot be redeemed.')}</p><p>{ru?'Действие не переводит деньги и не запрашивает подпись кошелька. Несохранённые формы не переносятся.':'This does not transfer funds or request a wallet signature. Unsaved forms do not carry over.'}</p><a className="ma-button" href={networkDestination(target)}>{ru?'Открыть пространство':'Open workspace'}<ArrowUpRight size={17}/></a><button className="ma-button secondary" onClick={()=>setTarget(null)}>{ru?'Остаться здесь':'Stay here'}</button></dialog>}</>;
}
