'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,LockKeyhole,ShieldCheck,Wallet,Info} from 'lucide-react';
import {planCapital,type CapitalSnapshot} from '@/lib/capital-policy';
import {blindGrantSchema,blindReceiptSchema,scenarioUnits,type BlindGrant,type BlindReceipt} from '@/lib/operator-lab-client';
import {operatorRequest} from '@/lib/operator-client';import {accountMoney} from '@/lib/account-format';
import type {Language} from '@/lib/workspace-plan';import './operator-capital-lab.css';
const initial={cash:'500',floor:'100',orders:'25',refunds:'25',buffer:'25',obligations:'50',purchase:'0',yieldQuote:'500',incoming:'0',burn:'0'};
type Fields=typeof initial;
function snapshot(f:Fields,state:CapitalSnapshot['redemptionState'],eligibility:boolean):CapitalSnapshot{const now=Date.now();return {settledCashUnits:scenarioUnits(f.cash),reserveFloorUnits:scenarioUnits(f.floor),reservedOrderUnits:scenarioUnits(f.orders),refundLiabilityUnits:scenarioUnits(f.refunds),liquidityBufferUnits:scenarioUnits(f.buffer),burn30dUnits:scenarioUnits(f.burn),pendingPurchaseUnits:scenarioUnits(f.purchase),yieldRedeemableUnits:scenarioUnits(f.yieldQuote),pendingIncomingUnits:scenarioUnits(f.incoming),maxActionUnits:'250000000',observedAt:now,redemptionDelayMs:86400000,obligations:[{id:'scenario-obligation',dueAt:now+3600000,amountUnits:scenarioUnits(f.obligations)}],redemptionState:state,paused:false,eligibilityVerified:eligibility,quoteFresh:true};}
const decisionLabels:Record<string,[string,string]>={HOLD:['Hold cash','Сохранить ликвидность'],RECONCILE:['Reconcile first','Сначала сверить результат'],WAIT_FOR_SETTLEMENT:['Wait for settled funds','Дождаться подтверждённых средств'],MANUAL_REVIEW:['Owner review required','Нужна проверка владельца'],REQUEST_REDEMPTION:['Prepare a redemption request','Подготовить запрос погашения'],LIQUIDITY_SHORTFALL:['Insufficient verified liquidity','Недостаточно проверенной ликвидности'],PURCHASE_READY_FOR_REVIEW:['Purchase can be reviewed','Можно проверить покупку'],PROPOSE_ALLOCATION:['Allocation proposal only','Только предложение размещения']};
export function OperatorCapitalLab({wallet,readOnly,lang,onConnect}:{wallet:string|null;readOnly:boolean;lang:Language;onConnect?:()=>void}){
 const ru=lang==='ru',[tab,setTab]=useState<'capital'|'blind'>('capital'),[fields,setFields]=useState<Fields>(initial),[redemption,setRedemption]=useState<CapitalSnapshot['redemptionState']>('NONE'),[eligible,setEligible]=useState(false),[plan,setPlan]=useState(()=>planCapital(snapshot(initial,'NONE',false),Date.now())),[error,setError]=useState(''),[grant,setGrant]=useState<BlindGrant|null>(null),[receipt,setReceipt]=useState<BlindReceipt|null>(null),[busy,setBusy]=useState(false);
 const epoch=useRef(0),mounted=useRef(true),locked=useRef(false),grantRequest=useRef<string|null>(null),executionRequest=useRef<string|null>(null);
 useEffect(()=>{epoch.current++;setGrant(null);setReceipt(null);setError('');grantRequest.current=null;executionRequest.current=null;},[wallet]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;}},[]);
 const calculate=(f=fields,r=redemption,e=eligible)=>{try{setPlan(planCapital(snapshot(f,r,e),Date.now()));setError('');}catch{setError(ru?'Используйте неотрицательные суммы с точностью до 6 знаков.':'Use non-negative amounts with at most six decimal places.');}};
 const preset=(state:CapitalSnapshot['redemptionState'])=>{const f=state==='NONE'?initial:{...initial,cash:'75',purchase:'100',incoming:'250'};setFields(f);setRedemption(state);setEligible(false);calculate(f,state,false);};
 const act=async(fn:()=>Promise<void>)=>{if(locked.current||!wallet||readOnly)return;locked.current=true;setBusy(true);setError('');const version=epoch.current;try{await fn();}catch(e){if(mounted.current&&version===epoch.current){const code=(e as Error).message;setError(code==='WALLET_AUTH_REQUIRED'?(ru?'Войдите кошельком для серверной проверки.':'Sign in with your wallet for the server check.'):(ru?'Проверка не завершена. Повторите тот же запрос или проверьте историю.':'Check not completed. Retry the same request or inspect receipt history.'));}}finally{locked.current=false;if(mounted.current)setBusy(false);}};
 const issue=()=>act(async()=>{const version=epoch.current;grantRequest.current??=crypto.randomUUID();const g=await operatorRequest('lab/blind/grants',blindGrantSchema,{requestId:grantRequest.current,confirmSynthetic:true});if(version!==epoch.current||!mounted.current)return;grantRequest.current=null;executionRequest.current=null;setGrant(g);setReceipt(null);});
 const execute=()=>act(async()=>{if(!grant)return;const version=epoch.current;executionRequest.current??=crypto.randomUUID();const r=await operatorRequest('lab/blind/execute',blindReceiptSchema,{requestId:executionRequest.current,handle:grant.handle,operation:'demo.digest',input:{text:'Verify the secret-isolated demo operation without returning the credential'}});if(version!==epoch.current||!mounted.current)return;setReceipt(r);setGrant(g=>g?{...g,callsRemaining:0}:g);});
 const revoke=()=>act(async()=>{if(!grant)return;const version=epoch.current;const g=await operatorRequest('lab/blind/grants/'+grant.handle+'/revoke',blindGrantSchema,{});if(version===epoch.current&&mounted.current)setGrant(g);});
 const field=(key:keyof Fields,label:string)=><label key={key} htmlFor={'capital-'+key}>{label}<input id={'capital-'+key} inputMode="decimal" value={fields[key]} maxLength={17} onChange={e=>setFields(f=>({...f,[key]:e.target.value}))}/></label>;
 return <details className="op-lab"><summary><ShieldCheck size={19}/><span><strong>{ru?'Ликвидность и защита секретов':'Liquidity & secret isolation'}</strong><small>{ru?'Два инженерных сценария. Без настоящего yield и без TEE.':'Two engineering scenarios. No live yield. No TEE claim.'}</small></span><ArrowRight size={18}/></summary><div className="op-lab-body">
 <div className="op-lab-boundary"><Info size={16}/><p>{ru?'Сценарии не используют ваш реальный баланс и не перемещают средства. Серверный demo-ключ синтетический; купленные credentials пока не подключены.':'Scenarios do not use your actual balance or move funds. The server demo key is synthetic; purchased credentials are not connected yet.'}</p></div>
 <div className="op-lab-tabs" role="tablist" aria-label={ru?'Инженерные сценарии':'Engineering scenarios'}>{(['capital','blind'] as const).map(id=><button key={id} id={'lab-tab-'+id} role="tab" tabIndex={tab===id?0:-1} aria-selected={tab===id} aria-controls={'lab-panel-'+id} onClick={()=>{setTab(id);setError('');}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?'capital':e.key==='End'?'blind':id==='capital'?'blind':'capital';setTab(next);document.getElementById('lab-tab-'+next)?.focus();}}>{id==='capital'?(ru?'План ликвидности':'Capital planning'):'Blind execution'}</button>)}</div>
 <div role="tabpanel" id={'lab-panel-'+tab} aria-labelledby={'lab-tab-'+tab}>
 {tab==='capital'?<div className="op-lab-capital"><header><span className="ma-eyebrow">NEVER-IDLE CAPITAL / PLANNING ONLY</span><h3>{ru?'Сначала обязательства. Затем свободный остаток.':'Obligations first. Idle surplus second.'}</h3><p>{ru?'Проверьте, какую часть условного бюджета нужно оставить ликвидной. Погашение не считается мгновенным.':'See which part of a hypothetical budget must remain liquid. Redemption is never assumed to be instant.'}</p></header>
 <div className="op-lab-presets">{(['NONE','PENDING','UNKNOWN'] as const).map((s,i)=><button type="button" key={s} onClick={()=>preset(s)}>{(ru?['Бюджет 500','Погашение ожидается','Результат неизвестен']:['500 budget','Redemption pending','Unknown outcome'])[i]}</button>)}</div>
 <form onSubmit={e=>{e.preventDefault();calculate();}}><div className="op-lab-fields">{field('cash',ru?'Подтверждённые средства, USDC':'Settled cash, USDC')}{field('floor',ru?'Резервный пол, USDC':'Reserve floor, USDC')}{field('purchase',ru?'Предстоящая покупка, USDC':'Upcoming purchase, USDC')}</div><details className="op-lab-assumptions"><summary>{ru?'Обязательства и допущения сценария':'Obligations and scenario assumptions'}</summary><div className="op-lab-fields">{field('orders',ru?'Резерв заказов':'Reserved orders')}{field('refunds',ru?'Обязательства возврата':'Refund liabilities')}{field('buffer',ru?'Буфер ликвидности':'Liquidity buffer')}{field('obligations',ru?'Счета в горизонте погашения':'Bills inside redemption horizon')}{field('burn',ru?'Расходы за 30 дней':'Trailing 30-day burn')}{field('yieldQuote',ru?'Условная стоимость погашения':'Hypothetical redemption quote')}{field('incoming',ru?'Неподтверждённое поступление':'Unsettled incoming funds')}<label htmlFor="capital-redemption">{ru?'Состояние погашения':'Redemption state'}<select id="capital-redemption" value={redemption} onChange={e=>setRedemption(e.target.value as CapitalSnapshot['redemptionState'])}>{['NONE','PENDING','UNKNOWN','SETTLED','FAILED'].map(s=><option key={s}>{s}</option>)}</select></label></div><label className="op-lab-check"><input type="checkbox" checked={eligible} onChange={e=>setEligible(e.target.checked)}/>{ru?'Предположить подтверждённый доступ к yield только для расчёта. Это не реальный допуск.':'Assume verified yield access for this calculation only. This is not actual eligibility.'}</label><p>{ru?'Горизонт погашения: 24 часа. Лимит предложения: 250 USDC. Процент доходности не задан и не гарантируется.':'Redemption horizon: 24 hours. Proposal cap: 250 USDC. No yield rate is specified or guaranteed.'}</p></details><button className="ma-button secondary" type="submit">{ru?'Рассчитать сценарий':'Calculate scenario'}<ArrowRight size={16}/></button></form>
 <section className="op-lab-plan" aria-label={ru?'Результат расчёта':'Planning result'} aria-live="polite"><span className="ma-eyebrow">{ru?'РАСЧЁТ, НЕ ИСПОЛНЕНИЕ':'CALCULATION, NOT EXECUTION'}</span><h4>{decisionLabels[plan.decision]?.[ru?1:0]??plan.decision}</h4><dl>{[[ru?'Защищённый остаток':'Protected cash',plan.protectedUnits],[ru?'Кандидат на размещение':'Allocation candidate',plan.candidateSurplusUnits],[ru?'Дефицит ликвидности':'Liquidity shortfall',plan.shortfallUnits],[ru?'Неподтверждённые средства не учтены':'Unsettled funds excluded',plan.ignoredPendingIncomingUnits]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{accountMoney(value)} USDC</dd></div>)}</dl><p><LockKeyhole size={14}/>{ru?'USYC-операции закрыты. Начисленная доходность: не подтверждена.':'USYC execution is closed. Earned yield: not verified.'}</p><code>{plan.reason}</code></section></div>:
 <div className="op-lab-blind"><header><span className="ma-eyebrow">BLIND EXECUTION / SOFTWARE DEMO</span><h3>{ru?'Агент получает право использования. Не ключ.':'The agent gets permission to use. Not the key.'}</h3><p>{ru?'Сервер создаёт синтетический секрет, шифрует его и выполняет одну фиксированную digest-операцию. В ответе — handle и receipt, без plaintext.':'The server creates and encrypts a synthetic secret, then runs one fixed digest operation. The response contains a handle and receipt, never plaintext.'}</p></header><ol className="op-lab-flow">{(ru?['Шифрование на сервере','Opaque handle + одна операция','Receipt без секрета']:['Server-side encryption','Opaque handle + one operation','Secret-free receipt']).map((s,i)=><li key={s}><span>{i+1}</span>{s}</li>)}</ol>
 {!wallet?<div className="op-lab-signin"><Wallet size={18}/><p>{ru?'Для серверного сценария нужно подтвердить владение кошельком. Подпись покупки не требуется.':'Verify wallet ownership to run the server demo. No purchase signature is required.'}</p>{onConnect&&<button className="ma-button" onClick={onConnect}>{ru?'Войти кошельком':'Sign in with wallet'}</button>}</div>:<div className="op-lab-actions"><button className="ma-button secondary" disabled={busy||readOnly} onClick={()=>void issue()}>{ru?'Создать demo-разрешение':'Create demo permission'}<ArrowRight size={16}/></button><button className="ma-button" disabled={busy||readOnly||!grant||grant.status!=='ACTIVE'||(grant.callsRemaining===0&&receipt?.state!=='UNKNOWN')} onClick={()=>void execute()}>{ru?'Выполнить одну demo-операцию':'Run one demo operation'}</button>{grant&&<button className="ma-link" disabled={busy||readOnly||grant.status==='REVOKED'} onClick={()=>void revoke()}>{ru?'Отозвать разрешение':'Revoke permission'}</button>}</div>}
 {busy&&<p role="status">{ru?'Проверяем серверный результат…':'Checking the server result…'}</p>}
 {grant&&<dl className="op-lab-grant"><div><dt>Handle</dt><dd><code>{grant.handle}</code></dd></div><div><dt>{ru?'Состояние':'Status'}</dt><dd>{grant.status} · {grant.callsRemaining} {ru?'операций осталось':'calls remaining'}</dd></div><div><dt>{ru?'Разрешённый инструмент':'Permitted operation'}</dt><dd>demo.digest · 10 min</dd></div></dl>}
 {receipt&&<section className="op-lab-receipt" aria-live="polite"><h4>{receipt.state==='SUCCEEDED'?<Check size={17}/>:<Info size={17}/>} {receipt.state==='SUCCEEDED'?(ru?'Серверная demo-операция выполнена':'Server demo operation completed'):(ru?'Результат требует сверки':'Outcome needs reconciliation')}</h4><p>{ru?'Средства не списывались. Настоящий provider API не вызывался. Повтор использует тот же request ID.':'No funds were debited. No real provider API was called. Retry uses the same request ID.'}</p><details><summary>{ru?'Посмотреть безопасный receipt':'Inspect the secret-free receipt'}</summary><pre>{JSON.stringify(receipt,null,2)}</pre></details></section>}
 <p className="op-lab-disclaimer"><LockKeyhole size={15}/>{ru?'Это software isolation в обычном серверном процессе, не аппаратный TEE. Remote attestation, реальные credentials и внешние API остаются отдельным этапом.':'This is software isolation inside a regular server process, not hardware TEE. Remote attestation, real credentials and external APIs remain separate release work.'}</p></div>}
 </div>{error&&<p className="ma-error" role="alert">{error}</p>}
 <a className="ma-link" href="https://docs.mercenta.xyz/docs/guides/capital-and-blind-execution">{ru?'Границы безопасности и архитектура':'Security boundaries and architecture'}<ArrowRight size={14}/></a>
 </div></details>;
}
