/* eslint-disable @next/next/no-img-element -- Local brand and hero WebP assets are pre-optimized. */
"use client";
import Link from "next/link";
import { Activity,AlertTriangle,ArrowRight,ArrowUpRight,Bot,Check,CheckCircle2,ChevronDown,ChevronRight,Circle,Clock,Code2,Copy,Cpu,Download,ExternalLink,FileText,Gamepad2,Globe,Heart,Layers,LayoutGrid,List,Menu,Pause,Play,Plus,RefreshCw,Search,Settings2,ShieldCheck,SlidersHorizontal,Terminal,Wallet,X } from "lucide-react";
import React,{ useEffect,useRef,useState } from "react";
export { Activity,AlertTriangle,ArrowRight,ArrowUpRight,Bot,Check,CheckCircle2,ChevronDown,ChevronRight,Circle,Clock,Code2,Copy,Cpu,Download,ExternalLink,FileText,Gamepad2,Globe,Heart,Layers,LayoutGrid,List,Menu,Pause,Play,Plus,RefreshCw,Search,Settings2,ShieldCheck,SlidersHorizontal,Terminal,Wallet,X };
export function Brand({small=false}:{small?:boolean}){return <Link href="/" className={`mp-brand ${small?'mp-brand-small':''}`} aria-label="Mercenta home"><img src="/mercenta-mark.webp" alt="" width="384" height="359"/><span>mercenta.</span></Link>}
export function Eyebrow({children}:{children:React.ReactNode}){return <span className="mp-eyebrow">{children}</span>}
export function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:string}){return <span className={`mp-badge ${tone}`}><span className="mp-dot"/>{children}</span>}
export function ProductHeader({active}:{active:"catalog"|"status"}){const [open,setOpen]=useState(false);const links=<><Link href="/">Home</Link><a href="/catalog" aria-current={active==='catalog'?'page':undefined}>Catalog</a><a href="/app">Console & Liquidity</a><a href="/status" aria-current={active==='status'?'page':undefined}>Status</a></>;return <header className="mp-header"><div className="mp-wrap mp-header-inner"><Brand/><nav aria-label="Main navigation">{links}</nav><a className="mp-button outline header-cta" href="/app">Open console <ArrowUpRight size={17}/></a><button className="mp-icon-button mobile-only" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu/></button></div>{open&&<Modal title="Navigation" onClose={()=>setOpen(false)}><nav className="mp-mobile-nav">{links}</nav></Modal>}</header>}
export function ProductFooter(){return <footer className="mp-footer mp-wrap"><Brand small/><p>Intelligent commerce. Non-negotiable control.</p><nav aria-label="Footer"><a href="/catalog">Catalog</a><a href="/app">Console & Liquidity</a><a href="/status">Status</a></nav><Eyebrow>MERcenta / PRE-LAUNCH</Eyebrow></footer>}
export function Modal({title,onClose,children,wide=false,canClose=true}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean;canClose?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;const old=document.body.style.overflow;d?.showModal();document.body.style.overflow="hidden";return()=>{document.body.style.overflow=old;d?.close();}},[]);return <dialog aria-label={title} ref={ref} className={`mp-dialog ${wide?'wide':''}`} onCancel={e=>{e.preventDefault();if(canClose)onClose()}} onClick={e=>{if(canClose&&e.target===ref.current)onClose()}}><section className="mp-drawer"><header><div><Eyebrow>Mercenta / workspace</Eyebrow><h2>{title}</h2></div><button autoFocus disabled={!canClose} className="mp-icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></header><div className="mp-drawer-body">{children}</div></section></dialog>}
export function DownloadJson(data:unknown,name:string){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export async function CopyJson(data:unknown){await navigator.clipboard.writeText(JSON.stringify(data,null,2))}
export const categoryMeta={cloud:{name:"Cloud Compute & GPU Vouchers",subtitle:"Cloud & GPU capacity",Icon:Cpu},developer:{name:"Developer API & Token Bundles",subtitle:"Tokens & developer tools",Icon:Code2},gaming:{name:"Gaming Keys & Platform Vouchers",subtitle:"Keys & platform vouchers",Icon:Gamepad2},streaming:{name:"Streaming & Media Subscriptions",subtitle:"Media & subscriptions",Icon:Play},creator:{name:"Creator & Game Micro-Donations",subtitle:"Support & micro-donations",Icon:Heart}};
export function CategoryIcon({category,size=26}:{category:string;size?:number}){const Icon=categoryMeta[category as keyof typeof categoryMeta]?.Icon??Layers;return <Icon size={size} strokeWidth={1.3}/>}
