/* eslint-disable @next/next/no-img-element -- Local brand and hero WebP assets are pre-optimized. */
"use client";
import { EXAMPLE_INCIDENT } from '@/lib/status-snapshot';
import { useEffect,useRef,useState } from 'react';
import { Activity,AlertTriangle,ArrowRight,ArrowUpRight,Badge,CategoryIcon,Check,Clock,Download,DownloadJson,Eyebrow,FileText,Globe,Modal,ProductFooter,ProductHeader,RefreshCw,ShieldCheck,Terminal,Wallet } from './ProductShell';
type Probe={state:'unchecked'|'checking'|'ok'|'error';checkedAt?:string;elapsed?:number};
const modules=[{id:'gateway',name:'Policy gateway',description:'Spend, reserves, margin, supplier and approval checks.',Icon:ShieldCheck},{id:'escrow',name:'Liquidity & reserves',description:'Budget availability and reserved-funds boundary.',Icon:Wallet},{id:'settlement',name:'Settlement rails',description:'Planned USDC routing. A health probe does not verify settlement.',Icon:Globe},{id:'telemetry',name:'Agent telemetry',description:'Intent traces, events and order records.',Icon:Activity},{id:'enclave',name:'Hardware boundary',description:'Attestation and verification boundary.',Icon:Terminal},{id:'sdk',name:'Developer rails',description:'Supplier integrations and SDK connectivity.',Icon:FileText}];
export function ProductStatus(){const [probe,setProbe]=useState<Probe>({state:'unchecked'}),[detail,setDetail]=useState<string|null>(null),[sample,setSample]=useState(false);const abortRef=useRef<AbortController|null>(null);useEffect(()=>()=>abortRef.current?.abort(),[]);
 const check=async()=>{abortRef.current?.abort();const c=new AbortController();abortRef.current=c;setProbe({state:'checking'});const start=performance.now();const timer=setTimeout(()=>c.abort(),10000);try{const res=await fetch('/api/health',{cache:'no-store',signal:c.signal});const data=await res.json();if(!res.ok||data.ok!==true)throw new Error('unavailable');setProbe({state:'ok',checkedAt:new Date().toISOString(),elapsed:Math.round(performance.now()-start)});}catch{setProbe({state:'error',checkedAt:new Date().toISOString()});}finally{clearTimeout(timer)}};
 const label=probe.state==='ok'?'Endpoint reachable':probe.state==='error'?'Endpoint check failed':probe.state==='checking'?'Checking endpoint…':'Ready to check';
 const moduleInfo=modules.find(m=>m.id===detail);
 return <div className="mp"><ProductHeader active="status"/><main><section className="mp-wrap mp-status-hero"><div><div className="mp-kicker"><Eyebrow>01 / SYSTEM VISIBILITY</Eyebrow><Badge>PRE-LAUNCH</Badge></div><h1>Infrastructure.<br/><span>In the open.</span></h1><p className="mp-lead">Know what is connected.<br/>Know what still needs a signal.</p><p className="mp-status-description">A direct endpoint check, with an honest view of monitoring coverage. No invented uptime. No assumed settlement.</p></div><section className="mp-probe-card" aria-label="Endpoint health check"><div className="mp-probe-head"><Eyebrow>LIVE CHECK / THIS ORIGIN</Eyebrow><Badge tone={probe.state==='ok'?'ok':probe.state==='error'?'stop':'neutral'}>{probe.state==='ok'?'REACHABLE':probe.state==='error'?'FAILED':'ON DEMAND'}</Badge></div><div className={`mp-probe-symbol ${probe.state==='ok'?'ok':probe.state==='error'?'stop':''}`}><img src="/mercenta-mark.webp" alt=""/>{probe.state==='ok'&&<span><Check size={16}/></span>}</div><h2 aria-live="polite">{label}</h2><p>{probe.state==='ok'?'The health endpoint reports API liveness and database access.':probe.state==='error'?'The request did not return a healthy response. Try again or inspect the service.':'Run a read-only check of the API and database on this site.'}</p><button className="mp-button full" disabled={probe.state==='checking'} onClick={check}><RefreshCw size={17} className={probe.state==='checking'?'mp-spin':''}/>{probe.state==='checking'?'Checking…':probe.state==='unchecked'?'Run endpoint check':'Check again'}</button><div className="mp-probe-foot"><span>{probe.checkedAt?new Date(probe.checkedAt).toISOString().slice(11,19)+' UTC':'NOT CHECKED YET'}</span><span>{probe.elapsed!==undefined?probe.elapsed+' ms round trip':'GET /api/health'}</span></div></section></section>
 <section className="mp-status-coverage"><div className="mp-wrap"><div><AlertTriangle size={23}/><strong>Module telemetry is not connected.</strong></div><p>An endpoint response is not an uptime guarantee. External suppliers, chains and delivery require separate monitoring.</p><Badge tone="hold">COVERAGE INCOMPLETE</Badge></div></section>
 <section className="mp-wrap mp-status-modules"><div className="mp-section-heading"><div><Eyebrow>02 / THE CONTROL PLANE</Eyebrow><h2>Every layer.<br/><span>Accounted for.</span></h2></div><p>Six modules. Explicit monitoring coverage.<br/>Nothing inferred from a green dot.</p></div><div className="mp-module-grid">{modules.map(({id,name,description,Icon},i)=><button className="mp-module" key={id} onClick={()=>setDetail(id)}><div><span className="mp-module-icon">{id==='escrow'?<CategoryIcon category="cloud" size={24}/>:<Icon size={24}/>}</span><span className="mp-index">0{i+1}</span></div><h3>{name}</h3><p>{description}</p><div className="mp-module-state"><Badge>Telemetry not connected</Badge><ArrowUpRight size={17}/></div></button>)}</div></section>
 <section className="mp-wrap mp-status-lower"><div className="mp-panel mp-chain-panel"><div className="mp-panel-title"><div><Eyebrow>03 / PLANNED RAILS</Eyebrow><h2>Connected is not assumed.</h2></div><Globe size={23}/></div>{['Arc','Base','Solana'].map((n,i)=><div className="mp-chain-row" key={n}><span className="mp-chain-icon">{n.slice(0,1)}</span><div><strong>{n}</strong><span>Planned USDC rail</span></div><Badge>Not monitored</Badge><span className="mp-index">0{i+1}</span></div>)}<p className="mp-note">This page does not confirm RPC availability, funds, finality or settlement. No live chain probes are configured here.</p></div><div className="mp-panel mp-incident-panel"><div className="mp-panel-title"><div><Eyebrow>04 / INCIDENT HISTORY</Eyebrow><h2>A trail, not a guess.</h2></div><Clock size={23}/></div><div className="mp-history-empty"><FileText size={29}/><h3>No live incident feed connected.</h3><p>Incident history and uptime will appear when a monitoring source is configured.</p></div><button className="mp-text-link" onClick={()=>setSample(true)}>Preview an example incident <ArrowRight size={17}/></button></div></section>
 <section className="mp-wrap mp-status-export"><div><Eyebrow>KEEP THE CONTEXT</Eyebrow><h2>Inspect. Don’t assume.</h2><p>Export the endpoint result and monitoring coverage as JSON.</p></div><button className="mp-button outline" onClick={()=>DownloadJson({generatedAt:new Date().toISOString(),scope:'this origin only',endpoint:'/api/health',probe,modules:modules.map(m=>({id:m.id,name:m.name,telemetry:'not_connected'})),rails:['Arc','Base','Solana'].map(chain=>({chain,status:'not_monitored'}))},'mercenta-status.json')}>Download status snapshot <Download size={17}/></button></section></main><ProductFooter/>
 {moduleInfo&&<Modal title={moduleInfo.name} onClose={()=>setDetail(null)}><Badge tone="hold">Telemetry not connected</Badge><p className="mp-drawer-intro">{moduleInfo.description}</p><div className="mp-monitor-empty"><Activity size={30}/><h3>No independent signal yet.</h3><p>The API health check cannot establish this module’s health. Configure module-specific probes before publishing availability or uptime.</p></div><div className="mp-detail-total"><p><span>Monitoring coverage</span><strong>Not configured</strong></p><p><span>Uptime history</span><span>Unavailable</span></p><p><span>Live incident feed</span><span>Not connected</span></p></div><a className="mp-button outline full" href="/app">Inspect the console <ArrowUpRight size={17}/></a></Modal>}
 {sample&&<Modal title="Example incident." onClose={()=>setSample(false)}><Badge>DEMONSTRATION / NOT A LIVE INCIDENT</Badge><Eyebrow>{EXAMPLE_INCIDENT.id}</Eyebrow><h3 className="mp-incident-title">{EXAMPLE_INCIDENT.title}</h3><p className="mp-drawer-intro">An example of the incident layout. The content below comes from the original static demo fixture, not a monitoring service.</p><div className="mp-incident-timeline"><div><Clock size={17}/><div><strong>Example started</strong><p>{EXAMPLE_INCIDENT.started.replace('T',' ').replace('Z',' UTC')}</p></div></div><div><Activity size={17}/><div><strong>Example update / monitoring</strong><p>{EXAMPLE_INCIDENT.body}</p><small>{EXAMPLE_INCIDENT.updated.replace('T',' ').replace('Z',' UTC')}</small></div></div></div><p className="mp-note">This does not indicate a current outage, degradation or operational state.</p></Modal>}
 </div>
}
