/* eslint-disable @next/next/no-img-element -- Local brand and hero WebP assets are pre-optimized. */
"use client";
import WalletButton from '@/components/wallet-button';
import { CASES,POLICY,percent,tone,usdc,type SupplierState } from '@/lib/policy';
import { checkIntent,defaultWorkspacePolicy,type WorkspacePolicy } from '@/lib/product-policy';
import React,{ useEffect,useMemo,useState } from 'react';
import { Coins } from 'lucide-react';
import { LiquidityCockpit } from './LiquidityCockpit';
import { AIAssistantWidget } from './AIAssistantWidget';
import { Activity,ArrowRight,ArrowUpRight,Badge,Bot,Brand,CategoryIcon,Check,ChevronRight,Clock,Copy,CopyJson,DownloadJson,Eyebrow,FileText,LayoutGrid,Menu,Modal,Plus,Settings2,ShieldCheck,Terminal,Wallet,X } from './ProductShell';
type Section='Overview'|'Orders'|'Liquidity'|'Agents'|'Policy'|'Activity';
const sections=[{name:'Overview',Icon:LayoutGrid},{name:'Orders',Icon:FileText},{name:'Liquidity',Icon:Coins},{name:'Agents',Icon:Bot},{name:'Policy',Icon:ShieldCheck},{name:'Activity',Icon:Activity}] as const;
const intents=[{id:'MR-ORD-2481',name:'Cloud compute',category:'cloud',agent:'Procurement agent',...CASES.order},{id:'MR-ORD-2482',name:'Compute capacity',category:'cloud',agent:'Procurement agent',...CASES.thin},{id:'MR-ORD-2483',name:'API credit pool',category:'developer',agent:'Policy monitor',...CASES.uncertain},{id:'MR-ORD-2484',name:'Dedicated GPU cluster',category:'cloud',agent:'Procurement agent',...CASES.overLimit}];
type DemoIntent=typeof intents[number];
export function ProductConsole(){
 const [section,setSection]=useState<Section>('Overview'),[mobile,setMobile]=useState(false),[policy,setPolicy]=useState<WorkspacePolicy>({...defaultWorkspacePolicy}),[record,setRecord]=useState<DemoIntent|null>(null),[statusFilter,setStatusFilter]=useState('all'),[q,setQ]=useState(''),[simulation,setSimulation]=useState(false),[agentEdit,setAgentEdit]=useState<number|null>(null),[agents,setAgents]=useState([{name:'Procurement agent',role:'Resources & infrastructure',enabled:true},{name:'Policy monitor',role:'Exceptions & approval checks',enabled:true},{name:'Settlement observer',role:'Planned delivery & records',enabled:false}]),[message,setMessage]=useState('');
 useEffect(()=>{window.scrollTo(0,0)},[section]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(t)},[message]);
 const results=useMemo(()=>intents.map(o=>({...o,result:checkIntent(o.amount,o.cost,o.supplier,policy)})),[policy]);
 const filtered=results.filter(o=>(statusFilter==='all'||o.result.decision===statusFilter)&&`${o.name} ${o.id} ${o.agent}`.toLowerCase().includes(q.toLowerCase()));
 useEffect(()=>{const s=new URLSearchParams(location.search).get('section');if(s==='liquidity')setSection('Liquidity')},[]);
 const nav=<><div className="mp-workspace-switch"><div className="mp-workspace-avatar">M</div><div><strong>Mercenta workspace</strong><span>Illustrative environment</span></div></div><Eyebrow>WORKSPACE</Eyebrow><nav aria-label="Workspace navigation">{sections.map(({name,Icon})=><button key={name} aria-current={section===name?'page':undefined} onClick={()=>{setSection(name);setMobile(false);history.replaceState(null,'',name==='Liquidity'?'/app?section=liquidity':'/app')}}><Icon size={18}/>{name}{name==='Liquidity'&&<span className="mp-nav-count">LAB</span>}{name==='Orders'&&<span className="mp-nav-count">{intents.length}</span>}</button>)}</nav><div className="mp-side-bottom"><a href="/catalog"><CategoryIcon category="cloud" size={18}/>Resource catalog <ArrowUpRight size={15}/></a><a href="/status"><Activity size={18}/>System status <ArrowUpRight size={15}/></a><div className="mp-side-preview"><Badge>PRE-LAUNCH</Badge><p>Your agents can explore.<br/>No live funds move here.</p></div></div></>;
 const orderTable=(compact=false)=><div className="mp-order-table" role="group" aria-label="Illustrative orders"><div className="mp-order-row mp-order-head"><span>Resource / order</span><span>Agent</span><span>Amount</span><span>Policy decision</span><span/></div>{(compact?results.slice(0,3):filtered).map(o=><button className="mp-order-row" key={o.id} onClick={()=>setRecord(o)} aria-label={'Inspect '+o.id}><span className="mp-order-resource"><span className="mp-category-icon"><CategoryIcon category={o.category} size={21}/></span><span><strong>{o.name}</strong><small>{o.id}</small></span></span><span className="mp-order-agent">{o.agent}</span><span className="mp-order-amount">{usdc(o.amount)}</span><span><Badge tone={tone(o.result.decision)}>{o.result.decision==='Human approval required'?'Human review':o.result.decision==='Policy blocked'?'Blocked':'Cleared'}</Badge></span><ChevronRight size={17}/></button>)}{!compact&&!filtered.length&&<div className="mp-empty"><FileText size={28}/><h3>No matching intents.</h3><button className="mp-button outline" onClick={()=>{setQ('');setStatusFilter('all')}}>Reset filters</button></div>}</div>;
  return <div className="mp mp-console"><aside className="mp-sidebar"><Brand/>{nav}</aside><div className="mp-console-main"><header className="mp-console-header"><button className="mp-icon-button mobile-only" aria-label="Open workspace menu" onClick={()=>setMobile(true)}><Menu/></button><span className="mp-console-mobile-brand"><Brand small/></span><div className="mp-breadcrumb"><span className="mp-crumb-workspace">Workspace</span> <ChevronRight size={14}/> <strong>{section}</strong></div><div><a href="/catalog" className="mp-header-link">Catalog <ArrowUpRight size={15}/></a><WalletButton/></div></header><main className="mp-console-content"><div className="mp-console-heading"><div><Eyebrow>CONTROL PLANE / {section.toUpperCase()}</Eyebrow><h1>{section==='Overview'?<>Your agents.<br/><span>Your rules.</span></>:section==='Orders'?<>Every intent.<br/><span>Nothing hidden.</span></>:section==='Liquidity'?<>Treasury yield.<br/><span>Working capital.</span></>:section==='Agents'?<>Autonomy starts<br/><span>with boundaries.</span></>:section==='Policy'?<>Define the rules.<br/><span>Keep the keys.</span></>:<>A clear trail.<br/><span>At every step.</span></>}</h1><p>{section==='Overview'?'A single workspace for intent, authorization and evidence.':section==='Orders'?'Inspect the illustrative lifecycle. No orders are submitted.':section==='Liquidity'?'Explore Arc Earn yield vaults, borrow working capital against cirBTC, and configure fiat onramping.':section==='Agents'?'Explore local agent settings. These controls do not start live agents.':section==='Policy'?'Adjust local demo rules and see the decisions change.':'Four sample intents, with every decision explained.'}</p></div><button className="mp-button" onClick={()=>setSimulation(true)}>Test an intent <Plus size={17}/></button></div>
 <div className="mp-environment"><Badge>DEMO WORKSPACE</Badge><span>Sample amounts. Local controls. No live orders, payments or settlement.</span></div>
 {message&&<div className="mp-inline-message" role="status">{message}<button className="mp-icon-button" aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {section==='Overview'&&<><div className="mp-console-stats"><div><span><Wallet size={18}/>Sample spend balance</span><strong>{policy.availableToSpend.toLocaleString('en-US')}<small>USDC</small></strong><p>{policy.reserved.toLocaleString('en-US')} reserved in this scenario</p></div><div><span><FileText size={18}/>Illustrative intents</span><strong>{intents.length.toString().padStart(2,'0')}<small>EXAMPLES</small></strong><p>{results.filter(o=>o.result.decision==='Cleared').length} cleared / {results.filter(o=>o.result.decision==='Policy blocked').length} blocked / {results.filter(o=>o.result.decision==='Human approval required').length} review</p></div><div><span><ShieldCheck size={18}/>Your policy boundary</span><strong>{(policy.grossMarginFloor*100).toFixed(0)}<small>% FLOOR</small></strong><p>{policy.autoApprovalLimit.toLocaleString('en-US')} USDC auto-approval limit</p></div></div>
 <div className="mp-console-overview-grid"><section className="mp-boundary-card"><img className="mp-boundary-art" src="/policy-gate.webp" alt=""/><Eyebrow>THE CONTROL LAYER / V0.3</Eyebrow><h2>The model proposes.<br/><span>Your policy decides.</span></h2><p>Five checkpoints between an agent’s intent and your money.</p><div className="mp-flow-line">{['Intent','Policy','Decision','Record'].map((n,i)=><React.Fragment key={n}><span className={i===1?'highlight':''}>{i===1?<img src="/mercenta-mark.webp" alt=""/>:i===0?<Terminal size={19}/>:i===2?<Check size={19}/>:<FileText size={19}/>}<small>{n}</small></span>{i<3&&<i/>}</React.Fragment>)}</div><button className="mp-text-link" onClick={()=>setSection('Policy')}>Inspect your guardrails <ArrowRight size={18}/></button></section><section className="mp-panel mp-guardrails"><div className="mp-panel-title"><h2>Active guardrails</h2><Badge>DEMO</Badge></div>{['Spend balance','Free after reserves','Margin floor','Supplier verification','Approval threshold'].map((n,i)=><div className="mp-guardrail-row" key={n}><span className="mp-index">0{i+1}</span><strong>{n}</strong><ShieldCheck size={17}/></div>)}<button className="mp-text-link" onClick={()=>setSimulation(true)}>Run a sample intent <ArrowRight size={17}/></button></section></div>
 <section className="mp-panel"><div className="mp-panel-title"><div><Eyebrow>INTENT → EVIDENCE</Eyebrow><h2>Recent sample orders</h2></div><button className="mp-text-link" onClick={()=>setSection('Orders')}>View all <ArrowRight size={17}/></button></div>{orderTable(true)}</section></>}
 {section==='Orders'&&<section className="mp-panel"><div className="mp-panel-title"><h2>Illustrative order queue</h2><Badge>{intents.length} intents</Badge></div><div className="mp-table-controls"><label className="mp-search"><FileText size={18}/><input aria-label="Search orders" placeholder="Search resource, agent or order ID…" value={q} onChange={e=>setQ(e.target.value)}/></label><select aria-label="Filter decisions" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All decisions</option><option>Cleared</option><option>Policy blocked</option><option>Human approval required</option></select></div>{orderTable()}</section>}
 {section==='Liquidity'&&<LiquidityCockpit onNotify={msg=>setMessage(msg)}/>}
 {section==='Agents'&&<div className="mp-agent-grid">{agents.map((a,i)=><section className="mp-panel mp-agent-card" key={i}><div className="mp-agent-top"><div className="mp-category-icon"><Bot size={28}/></div><Badge tone={a.enabled?'neutral':'hold'}>{a.enabled?'Enabled locally':'Paused locally'}</Badge></div><Eyebrow>AGENT / 0{i+1}</Eyebrow><h2>{a.name}</h2><p>{a.role}</p><dl><div><dt>Environment</dt><dd>Simulation only</dd></div><div><dt>Policy</dt><dd>Shared workspace rules</dd></div></dl><button className="mp-button outline full" onClick={()=>setAgentEdit(i)}>Configure preview <Settings2 size={17}/></button></section>)}<div className="mp-agent-info"><ShieldCheck size={28}/><h2>No blank checks.</h2><p>Agent configuration stays local to this preview. Connecting a wallet signs you in; it does not fund these examples.</p></div></div>}
 {section==='Policy'&&<PolicyEditor value={policy} onSave={p=>{setPolicy(p);setMessage('Demo policy updated. Sample decisions recalculated.')}} onReset={()=>{setPolicy({...defaultWorkspacePolicy});setMessage('Demo policy restored to its defaults.')}}/>}
 {section==='Activity'&&<section className="mp-panel"><div className="mp-panel-title"><div><Eyebrow>ILLUSTRATIVE RECORDS / NOT LIVE LOGS</Eyebrow><h2>Decision trail</h2></div><button className="mp-button outline" onClick={()=>DownloadJson({demo:true,policy,records:results},'mercenta-demo-activity.json')}>Export <ArrowRight size={16}/></button></div><div className="mp-activity-list">{results.map((o,i)=><button key={o.id} onClick={()=>setRecord(o)}><span className={`mp-activity-symbol ${tone(o.result.decision)}`}>{o.result.decision==='Cleared'?<Check size={19}/>:o.result.decision==='Policy blocked'?<X size={19}/>:<Clock size={19}/>}</span><div><span className="mp-meta">EXAMPLE 0{i+1} / {o.id}</span><h3>{o.result.decision}</h3><p>{o.name} · {o.result.checks.filter(c=>c.state!=='pass').map(c=>c.label).join(', ')||'All five checkpoints passed'}</p></div><ChevronRight size={18}/></button>)}</div></section>}
 <footer className="mp-console-footnote"><Eyebrow>PRE-LAUNCH / ILLUSTRATIVE ONLY</Eyebrow><span>Local edits reset on reload.</span><a href="/status">Status & connectivity <ArrowUpRight size={15}/></a></footer>
 </main></div>
 {mobile&&<Modal title="Your workspace." onClose={()=>setMobile(false)}>{nav}</Modal>}
 {record&&<Modal title={record.id} onClose={()=>setRecord(null)}><RecordDetails order={record} policy={policy}/></Modal>}
 {simulation&&<Modal title="Test your guardrails." onClose={()=>setSimulation(false)}><IntentLab policy={policy}/></Modal>}
 {agentEdit!==null&&<Modal title="Configure demo agent." onClose={()=>setAgentEdit(null)}><AgentEditor agent={agents[agentEdit]} onSave={a=>{setAgents(prev=>prev.map((x,i)=>i===agentEdit?a:x));setAgentEdit(null);setMessage('Local agent preview updated. No live process changed.')}}/></Modal>}
 <AIAssistantWidget scope="treasury" onOpenEarn={()=>{location.href='/app?section=liquidity&tab=earn'}} onOpenBorrow={()=>{location.href='/app?section=liquidity&tab=borrow'}}/>
 </div>
}
function CheckRows({result}:{result:ReturnType<typeof checkIntent>}){return <div className="mp-check-rows">{result.checks.map((c,i)=><div key={c.id}><span className="mp-index">0{i+1}</span><div><strong>{c.label}</strong><small>{c.note}</small></div><span className={`mp-check-result ${c.state}`}>{c.state==='pass'?<Check size={15}/>:c.state==='hold'?<Clock size={15}/>:<X size={15}/>} {c.state==='pass'?'PASS':c.state==='hold'?'REVIEW':'BLOCK'}</span></div>)}</div>}
function Decision({result}:{result:ReturnType<typeof checkIntent>}){return <div className={`mp-decision ${tone(result.decision)}`}><div><Eyebrow>POLICY DECISION / DEMO</Eyebrow><strong>{result.decision}</strong></div><div><Eyebrow>GROSS MARGIN</Eyebrow><strong>{percent(result.margin)}</strong></div></div>}
function RecordDetails({order:o,policy}:{order:DemoIntent;policy:WorkspacePolicy}){const r=checkIntent(o.amount,o.cost,o.supplier,policy);const [copied,setCopied]=useState('');return <><Badge>Example record / no live settlement</Badge><div className="mp-receipt"><div className="mp-receipt-top"><img src="/mercenta-mark.webp" alt="Mercenta"/><Eyebrow>ILLUSTRATIVE ORDER RECORD</Eyebrow></div><Eyebrow>{o.id}</Eyebrow><h3>{o.name}</h3><strong className="mp-receipt-amount">{o.amount.toLocaleString('en-US')} <small>USDC</small></strong><dl><div><dt>Supplier cost</dt><dd>{usdc(o.cost)}</dd></div><div><dt>Illustrative fee (1.5%)</dt><dd>{usdc(o.amount*POLICY.platformFee)}</dd></div><div><dt>Gross margin before fee</dt><dd>{percent(r.margin)}</dd></div></dl><Badge tone={tone(r.decision)}>{r.decision}</Badge></div><CheckRows result={r}/><button className="mp-button full" onClick={async()=>{try{await CopyJson({demo:true,order:o,policy,result:r});setCopied('Example JSON copied.')}catch{DownloadJson({demo:true,order:o,policy,result:r},'mercenta-example-record.json');setCopied('Example JSON downloaded.')}}}><Copy size={17}/> Copy record as JSON</button><p className="mp-note" role="status">{copied||'This is not a signed receipt, a transaction or proof of settlement.'}</p></>}
function IntentLab({policy}:{policy:WorkspacePolicy}){const [amount,setAmount]=useState('2100'),[cost,setCost]=useState('1700'),[supplier,setSupplier]=useState<SupplierState>('verified');const valid=amount.trim()!==''&&cost.trim()!=='';const r=checkIntent(valid?Number(amount):NaN,valid?Number(cost):NaN,supplier,policy);return <><Badge>Simulation / no funds move</Badge><p className="mp-drawer-intro">Change the intent. Watch the rules decide. Uses your current local workspace policy.</p><div className="mp-lab-presets">{Object.values(CASES).map(c=><button className="mp-mini-tab" key={c.label} onClick={()=>{setAmount(String(c.amount));setCost(String(c.cost));setSupplier(c.supplier)}}>{c.label==='This page’s order'?'Valid order':c.label}</button>)}</div><div className="mp-two-fields"><label className="mp-field">Client amount / USDC<input aria-label="Client amount" type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="mp-field">Supplier cost / USDC<input aria-label="Supplier cost" type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></label></div><label className="mp-field">Supplier status<select aria-label="Supplier status" value={supplier} onChange={e=>setSupplier(e.target.value as SupplierState)}><option value="verified">Verified in simulation</option><option value="uncertain">Unknown in simulation</option></select></label><CheckRows result={r}/><Decision result={r}/><p className="mp-note">The margin is computed before the illustrative platform fee. No external supplier verification is performed.</p></>}
function PolicyEditor({value,onSave,onReset}:{value:WorkspacePolicy;onSave:(p:WorkspacePolicy)=>void;onReset:()=>void}){const [available,setAvailable]=useState(String(value.availableToSpend)),[reserved,setReserved]=useState(String(value.reserved)),[floor,setFloor]=useState(String(value.grossMarginFloor*100)),[limit,setLimit]=useState(String(value.autoApprovalLimit)),[error,setError]=useState('');const save=(e:React.FormEvent)=>{e.preventDefault();const v={availableToSpend:Number(available),reserved:Number(reserved),grossMarginFloor:Number(floor)/100,autoApprovalLimit:Number(limit)};if([available,reserved,floor,limit].some(s=>s.trim()==='')||Object.values(v).some(n=>!Number.isFinite(n)||n<0)||v.grossMarginFloor>1||v.reserved>v.availableToSpend){setError('Enter valid non-negative amounts. Reserves cannot exceed the balance; margin must be between 0 and 100%.');return}setError('');onSave(v)};return <div className="mp-policy-layout"><form className="mp-panel mp-policy-form" onSubmit={save}><div className="mp-panel-title"><h2>Workspace policy</h2><Badge>LOCAL DEMO</Badge></div><p>All four sample orders use these settings. No production policy is changed.</p><div className="mp-two-fields"><label className="mp-field">Sample spend balance / USDC<input type="number" min="0" step="0.01" value={available} onChange={e=>setAvailable(e.target.value)} required/></label><label className="mp-field">Reserved funds / USDC<input type="number" min="0" step="0.01" value={reserved} onChange={e=>setReserved(e.target.value)} required/></label><label className="mp-field">Gross margin floor / %<input type="number" min="0" max="100" step="0.1" value={floor} onChange={e=>setFloor(e.target.value)} required/></label><label className="mp-field">Auto-approval limit / USDC<input type="number" min="0" step="0.01" value={limit} onChange={e=>setLimit(e.target.value)} required/></label></div><div className="mp-policy-lock"><ShieldCheck size={20}/><div><strong>Unknown suppliers are blocked.</strong><span>Required in this preview. Not a model preference.</span></div></div>{error&&<p className="mp-error" role="alert">{error}</p>}<div className="mp-action-row"><button className="mp-button" type="submit">Apply demo rules <Check size={17}/></button><button type="button" className="mp-button outline" onClick={()=>{setAvailable(String(defaultWorkspacePolicy.availableToSpend));setReserved(String(defaultWorkspacePolicy.reserved));setFloor('15');setLimit('5000');setError('');onReset()}}>Restore defaults</button></div></form><aside className="mp-policy-envelope"><img src="/mercenta-mark.webp" alt=""/><Eyebrow>POLICY ENVELOPE / CURRENT</Eyebrow><h2>Your rules.<br/><span>Machine-enforced.</span></h2><dl><div><dt>Margin floor</dt><dd>{(value.grossMarginFloor*100).toFixed(1)}%</dd></div><div><dt>Approval threshold</dt><dd>{value.autoApprovalLimit.toLocaleString('en-US')}<small>USDC</small></dd></div></dl><p><Check size={17}/> Same input. Same decision.</p></aside></div>}
function AgentEditor({agent,onSave}:{agent:{name:string;role:string;enabled:boolean};onSave:(a:{name:string;role:string;enabled:boolean})=>void}){const [name,setName]=useState(agent.name),[enabled,setEnabled]=useState(agent.enabled);return <form onSubmit={e=>{e.preventDefault();if(name.trim())onSave({...agent,name:name.trim(),enabled})}}><Badge>Local preview only</Badge><label className="mp-field">Agent name<input maxLength={60} required value={name} onChange={e=>setName(e.target.value)}/></label><label className="mp-check mp-agent-enabled"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enabled in this demo workspace</label><p className="mp-note">This does not pause, start or configure a live agent.</p><button className="mp-button full" type="submit">Save local preview <Check size={17}/></button></form>}
