/* eslint-disable @next/next/no-img-element -- Local brand and hero WebP assets are pre-optimized. */
"use client";
import {parseMoney,formatMoney,displayUnits} from '@/lib/liquidity-math';
import type { CatalogDenomination,CatalogProduct,CategoryId } from '@/lib/supplier';
import { useEffect,useMemo,useRef,useState } from 'react';
import { ArrowRight,ArrowUpRight,Badge,CategoryIcon,categoryMeta,Copy,CopyJson,Download,DownloadJson,Eyebrow,LayoutGrid,List,Modal,Plus,ProductFooter,ProductHeader,Search,ShieldCheck,Terminal,X } from './ProductShell';
import { AIAssistantWidget } from './AIAssistantWidget';
type Line={product:CatalogProduct;denom:CatalogDenomination;quantity:number};
const money=(n:number|string|bigint,c:string)=>displayUnits((typeof n==='bigint'?n:parseMoney(String(n))).toString())+' '+c;
const lineUnits=(price:number,quantity:number)=>parseMoney(String(price))*BigInt(quantity);
const priceCompare=(a:number,b:number)=>{const x=parseMoney(String(a)),y=parseMoney(String(b));return x<y?-1:x>y?1:0};
const date=(s:string)=>new Date(s).toISOString().slice(0,16).replace('T',' ')+' UTC';
export function buildManifest(lines:Line[]){const totals:Record<string,bigint>={};for(const l of lines)totals[l.denom.currency]=(totals[l.denom.currency]??0n)+lineUnits(l.denom.price,l.quantity);return {sdk:'mercenta-agent-sdk',version:'1',mode:'agent-batch',draft:true,generatedAt:new Date().toISOString(),items:lines.map(l=>({productId:l.product.id,denominationId:l.denom.id,label:l.product.name+' — '+l.denom.name,quantity:l.quantity,unitPrice:formatMoney(parseMoney(String(l.denom.price))),currency:l.denom.currency})),totals:{lines:lines.length,units:lines.reduce((n,l)=>n+l.quantity,0),byCurrency:Object.fromEntries(Object.entries(totals).map(([c,n])=>[c,formatMoney(n)]))}}}
export function ProductCatalog({products,live,generatedAt}:{products:CatalogProduct[];live:boolean;generatedAt:string}){
 const [category,setCategory]=useState<CategoryId|'all'>('all'),[query,setQuery]=useState(''),[region,setRegion]=useState('all'),[kind,setKind]=useState('all'),[stock,setStock]=useState(false),[sort,setSort]=useState('featured'),[view,setView]=useState('grid'),[shown,setShown]=useState(24),[selected,setSelected]=useState<Line[]>([]),[active,setActive]=useState<CatalogProduct|null>(null),[batch,setBatch]=useState(false),[message,setMessage]=useState('');const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const params=new URLSearchParams(location.search);const search=params.get('search');if(search)setQuery(search);const c=params.get('category');if(c&&c in categoryMeta)setCategory(c as CategoryId);const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus()} };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(t)},[message]);
 const regions=useMemo(()=>[...new Set(products.map(p=>p.countryCode).filter(Boolean))].sort() as string[],[products]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();const list=products.filter(p=>(category==='all'||p.category===category)&&(region==='all'||p.countryCode===region)&&(kind==='all'||p.type===kind)&&(!stock||p.inStock>0)&&(!q||`${p.name} ${p.brand} ${p.id} ${p.denominations.map(d=>d.name).join(' ')}`.toLowerCase().includes(q)));if(sort!=='featured')list.sort((a,b)=>sort==='stock'?b.totalStock-a.totalStock:a.currency.localeCompare(b.currency)||(sort==='price-up'?priceCompare(a.minPrice,b.minPrice):priceCompare(b.minPrice,a.minPrice)));return list},[products,category,query,region,kind,stock,sort]);
 const reset=()=>{setQuery('');setCategory('all');setRegion('all');setKind('all');setStock(false);setSort('featured');setShown(24)};
 const changeCategory=(c:CategoryId|'all')=>{setCategory(c);setShown(24)};
 const toggle=(p:CatalogProduct)=>{setSelected(prev=>prev.some(l=>l.product.id===p.id)?prev.filter(l=>l.product.id!==p.id):[...prev,{product:p,denom:p.denominations.find(d=>d.available)??p.denominations[0],quantity:1}])};
 const copy=async()=>{try{await CopyJson(buildManifest(selected));setMessage('Batch JSON copied. No orders submitted.')}catch{setMessage('Clipboard unavailable. Use Download JSON instead.')}};
 const count=(c:string)=>products.filter(p=>p.category===c).length;
 return <div className="mp"><ProductHeader active="catalog"/><main>
 <section className="mp-wrap mp-catalog-hero"><div><div className="mp-kicker"><Eyebrow>01 / THE AGENT CATALOG</Eyebrow><Badge tone={live?'ok':'neutral'}>{live?'Supplier feed':'Curated snapshot'}</Badge></div><h1>Digital goods.<br/><span>Agent-ready.</span></h1><p className="mp-lead">The resources your agents need.<br/>One structured path to acquire them.</p><a href="#inventory" className="mp-text-link">Explore the catalog <ArrowRight size={19}/></a></div><a href="#inventory" className="mp-feature" onClick={()=>changeCategory('cloud')}><img className="mp-feature-art" src="/policy-gate.webp" alt=""/><div className="mp-feature-top"><Eyebrow>BUILT FOR THE NEXT WORKLOAD</Eyebrow><CategoryIcon category="cloud"/></div><div className="mp-feature-copy"><Eyebrow>COMPUTE / INFRASTRUCTURE</Eyebrow><h2>More power.<br/>Same control.</h2><span>Explore cloud & GPU capacity <ArrowUpRight size={19}/></span></div></a></section>
 <section className="mp-category-rail mp-wrap" aria-label="Product categories">{Object.entries(categoryMeta).map(([c,m],i)=><button key={c} onClick={()=>changeCategory(c as CategoryId)} className={category===c?'selected':''}><div><CategoryIcon category={c}/><span className="mp-index">0{i+1}</span></div><strong>{m.name}</strong><span>{m.subtitle}</span><small>{count(c)} listings <ArrowUpRight size={15}/></small></button>)}</section>
 <section className="mp-wrap mp-inventory" id="inventory"><div className="mp-section-heading"><div><Eyebrow>02 / EXPLORE INVENTORY</Eyebrow><h2>{category==='all'?'Find your next resource.':categoryMeta[category].name+'.'}</h2></div><span className="mp-meta">{live?'Feed fetched':'Snapshot loaded'} · {date(generatedAt)}</span></div>
 <div className="mp-filterbar"><label className="mp-search"><Search size={19}/><input ref={searchRef} aria-label="Search catalog" placeholder="Search products, brands or SKU…" value={query} onChange={e=>{setQuery(e.target.value);setShown(24)}}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}<kbd>⌘ K</kbd></label><label className="mp-select-label"><span>Region</span><select aria-label="Region" value={region} onChange={e=>{setRegion(e.target.value);setShown(24)}}><option value="all">All regions</option>{regions.map(r=><option key={r}>{r}</option>)}</select></label><label className="mp-select-label"><span>Format</span><select aria-label="Product format" value={kind} onChange={e=>{setKind(e.target.value);setShown(24)}}><option value="all">All formats</option><option value="voucher">Voucher</option><option value="direct_topup">Top-up</option><option value="esim">eSIM</option></select></label></div>
 <div className="mp-resultsbar"><div><button className={`mp-mini-tab ${category==='all'?'selected':''}`} onClick={()=>changeCategory('all')}>All goods <span>{products.length}</span></button><span className="mp-meta" aria-live="polite">{filtered.length} results</span><label className="mp-check"><input type="checkbox" checked={stock} onChange={e=>{setStock(e.target.checked);setShown(24)}}/> Available only</label></div><div><select aria-label="Sort products" value={sort} onChange={e=>{setSort(e.target.value);setShown(24)}}><option value="featured">Featured order</option><option value="price-up">Price / currency ↑</option><option value="price-down">Price / currency ↓</option><option value="stock">Stock level ↓</option></select><div className="mp-toggle"><button aria-label="Grid view" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={17}/></button><button aria-label="List view" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={19}/></button></div></div></div>
 {message&&<div className="mp-inline-message" role="status">{message}<button className="mp-icon-button" aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {filtered.length===0?<div className="mp-empty"><Search size={34}/><h3>No matching resources.</h3><p>Try another search or reset your filters.</p><button className="mp-button" onClick={reset}>Reset filters <ArrowRight size={17}/></button></div>:<div className={`mp-products ${view==='list'?'is-list':''}`}>{filtered.slice(0,shown).map(p=><article key={p.id} className={`mp-product ${selected.some(l=>l.product.id===p.id)?'is-selected':''}`}><div className="mp-product-top"><div className="mp-category-icon"><CategoryIcon category={p.category} size={28}/></div><Eyebrow>{categoryMeta[p.category]?.name??p.category}</Eyebrow><label className="mp-product-select"><input type="checkbox" aria-label={'Select '+p.name} checked={selected.some(l=>l.product.id===p.id)} disabled={!p.denominations.some(d=>d.available)} onChange={()=>toggle(p)}/></label></div><div className="mp-product-title"><span className="mp-meta">{p.brand} / {p.countryCode??'Global'}</span><h3>{p.name}</h3></div><div className="mp-product-options"><span>{p.denominations.length} options</span><Badge tone={p.inStock?'neutral':'stop'}>{p.inStock?(live?'Available in feed':'Snapshot available'):'Unavailable'}</Badge></div><div className="mp-product-bottom"><div><small>From</small><strong>{money(p.minPrice,p.currency)}</strong></div><button className="mp-icon-button" aria-label={'View '+p.name} onClick={()=>setActive(p)}><ArrowUpRight size={20}/></button></div></article>)}</div>}
 {shown<filtered.length&&<button className="mp-button outline mp-load-more" onClick={()=>setShown(n=>n+24)}>Load more resources <Plus size={17}/></button>}
 <p className="mp-disclaimer">{live?'Feed availability can change. Quotes must be verified before authorization.':'Prices and availability shown from a curated fallback snapshot, not live inventory.'} Catalog prices retain their source currency. No checkout or live settlement on this page.</p></section>
 <section className="mp-catalog-end mp-wrap"><Terminal size={30}/><div><Eyebrow>FROM RESOURCE TO INTENT</Eyebrow><h2>Less checkout.<br/>More orchestration.</h2></div><div><p>Select resources. Build a structured batch.<br/>Keep authorization in your policy layer.</p><a href="/app" className="mp-button outline">Explore the console <ArrowUpRight size={18}/></a></div></section>
 </main><ProductFooter/>
 {selected.length>0&&<aside className="mp-batch-dock"><div><Badge>{selected.length} selected</Badge><span>Agent batch / draft</span></div><button className="mp-button" onClick={()=>setBatch(true)}>Review batch <ArrowRight size={17}/></button><button className="mp-icon-button" aria-label="Clear batch" onClick={()=>setSelected([])}><X size={18}/></button></aside>}
 
 {active&&<ProductDetail key={active.id} product={active} live={live} onClose={()=>setActive(null)} onQueue={line=>{setSelected(prev=>[...prev.filter(l=>l.product.id!==line.product.id),line]);setActive(null);setMessage('Added to draft batch. No order submitted.')}}/>}
 {batch&&<Modal title="Your agent batch." onClose={()=>setBatch(false)}><Badge>Draft / no orders submitted</Badge><p className="mp-drawer-intro">Structured resources, ready for your integration. This export is a manifest, not an authorization or receipt.</p><div className="mp-batch-lines">{selected.map(l=><div key={l.product.id}><CategoryIcon category={l.product.category} size={22}/><div><strong>{l.product.name}</strong><small>{l.quantity} × {l.denom.name}</small></div><span>{money(lineUnits(l.denom.price,l.quantity),l.denom.currency)}</span><button className="mp-icon-button" aria-label={'Remove '+l.product.name} onClick={()=>setSelected(prev=>prev.filter(x=>x.product.id!==l.product.id))}><X size={16}/></button></div>)}</div><div className="mp-detail-total">{Object.entries(buildManifest(selected).totals.byCurrency).map(([c,n])=><p key={c}><span>Draft total / {c}</span><strong>{money(n,c)}</strong></p>)}</div><div className="mp-action-row"><button disabled={!selected.length} className="mp-button" onClick={copy}><Copy size={17}/> Copy JSON</button><button disabled={!selected.length} className="mp-button outline" onClick={()=>DownloadJson(buildManifest(selected),'mercenta-batch.json')}><Download size={17}/> Download JSON</button></div><p className="mp-note" role="status">{message}</p><p className="mp-note">No supplier cost, on-chain proof or margin approval is invented. Verify each quote in your integration.</p></Modal>}
  <AIAssistantWidget
    scope="catalog"
    onSelectProduct={(productId) => {
      const found = products.find((p) => p.id === productId);
      if (found) {
        setActive(found);
      }
    }}
  />
 </div>
}
function ProductDetail({product:p,live,onClose,onQueue}:{product:CatalogProduct;live:boolean;onClose:()=>void;onQueue:(l:Line)=>void}){const [id,setId]=useState(p.denominations.find(d=>d.available)?.id??p.denominations[0]?.id??''),[quantity,setQuantity]=useState(1),[copied,setCopied]=useState('');const d=p.denominations.find(x=>x.id===id);const max=d?.stock&&d.stock>0?Math.min(d.stock,99):99;const payload=d?buildManifest([{product:p,denom:d,quantity}]):null;return <Modal title="Resource details." onClose={onClose}><div className="mp-detail-heading"><div className="mp-category-icon"><CategoryIcon category={p.category} size={32}/></div><div><Eyebrow>{categoryMeta[p.category]?.name??p.category}</Eyebrow><h3>{p.name}</h3><p>{p.brand} · {p.countryCode??'Global'}</p></div></div><Badge>{live?'Feed quote / verify before purchase':'Snapshot / illustrative availability'}</Badge><div className="mp-field"><label htmlFor="resource-option">Choose an option</label><select id="resource-option" value={id} onChange={e=>{setId(e.target.value);setQuantity(1)}}>{p.denominations.map(x=><option key={x.id} value={x.id}>{x.name} · {money(x.price,x.currency)}{x.available?'':' · unavailable'}</option>)}</select></div><div className="mp-field"><label htmlFor="resource-qty">Quantity</label><input id="resource-qty" type="number" min="1" max={max} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(max,Math.floor(Number(e.target.value)||1))))}/></div><div className="mp-detail-total"><p><span>Resource total</span><strong>{d?money(lineUnits(d.price,quantity),d.currency):'No quote'}</strong></p><p><span>Supplier cost</span><span>Not provided</span></p><p><span>Policy authorization</span><span>Not evaluated</span></p></div><button disabled={!d?.available} className="mp-button full" onClick={()=>d&&onQueue({product:p,denom:d,quantity})}>{d?.available?'Add to agent batch':'Option unavailable'} <Plus size={18}/></button><div className="mp-code-head"><Eyebrow>STRUCTURED INTENT / DRAFT</Eyebrow><button className="mp-icon-button" aria-label="Copy resource JSON" onClick={async()=>{try{await CopyJson(payload);setCopied('JSON copied.')}catch{setCopied('Clipboard unavailable.')}}}><Copy size={17}/></button></div><pre className="mp-code">{JSON.stringify(payload?.items[0]??{},null,2)}</pre><span role="status" className="mp-note">{copied}</span><p className="mp-note"><ShieldCheck size={17}/> A quote is not permission. Authorization belongs in the policy layer.</p></Modal>}
