/* eslint-disable @next/next/no-img-element -- Local brand and hero WebP assets are pre-optimized. */
"use client";
import {ProductImage} from './ProductImage';
import {CatalogItemDialog} from './CatalogItemDialog';
import {parseMoney,formatMoney,displayUnits} from '@/lib/liquidity-math';
import type { CatalogDenomination,CatalogProduct,CategoryId } from '@/lib/supplier';
import { useEffect,useMemo,useRef,useState } from 'react';
import { ArrowRight,ArrowUpRight,Badge,CategoryIcon,categoryMeta,Copy,CopyJson,Download,DownloadJson,Eyebrow,LayoutGrid,List,Modal,Plus,ProductFooter,ProductHeader,Search,ShieldCheck,Terminal,X } from './ProductShell';
type Line={product:CatalogProduct;denom:CatalogDenomination;quantity:number};
const money=(n:number|string|bigint,c:string)=>displayUnits((typeof n==='bigint'?n:parseMoney(String(n))).toString())+' '+c;
const lineUnits=(price:number,quantity:number)=>parseMoney(String(price))*BigInt(quantity);
const priceCompare=(a:number,b:number)=>{const x=parseMoney(String(a)),y=parseMoney(String(b));return x<y?-1:x>y?1:0};
const date=(s:string)=>new Date(s).toISOString().slice(0,16).replace('T',' ')+' UTC';
export function buildManifest(lines:Line[]){const totals:Record<string,bigint>={};for(const l of lines)totals[l.denom.currency]=(totals[l.denom.currency]??0n)+lineUnits(l.denom.price,l.quantity);return {sdk:'mercenta-agent-sdk',version:'1',mode:'agent-batch',draft:true,generatedAt:new Date().toISOString(),items:lines.map(l=>({productId:l.product.id,denominationId:l.denom.id,label:l.product.name+' — '+l.denom.name,quantity:l.quantity,unitPrice:formatMoney(parseMoney(String(l.denom.price))),currency:l.denom.currency})),totals:{lines:lines.length,units:lines.reduce((n,l)=>n+l.quantity,0),byCurrency:Object.fromEntries(Object.entries(totals).map(([c,n])=>[c,formatMoney(n)]))}}}
export function ProductCatalog({products,live,generatedAt,sourceStatus}:{products:CatalogProduct[];live:boolean;generatedAt:string;sourceStatus?:string}){
 const [category,setCategory]=useState<CategoryId|'all'>('all'),[query,setQuery]=useState(''),[region,setRegion]=useState('all'),[kind,setKind]=useState('all'),[stock,setStock]=useState(false),[sort,setSort]=useState('featured'),[view,setView]=useState('grid'),[shown,setShown]=useState(24),[selected,setSelected]=useState<Line[]>([]),[active,setActive]=useState<CatalogProduct|null>(null),[batch,setBatch]=useState(false),[message,setMessage]=useState(''),[developer,setDeveloper]=useState(false);const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const params=new URLSearchParams(location.search);const search=params.get('search');if(search)setQuery(search);const c=params.get('category');if(c&&c in categoryMeta)setCategory(c as CategoryId);const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus()} };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(t)},[message]);
 const regions=useMemo(()=>[...new Set(products.map(p=>p.countryCode).filter(Boolean))].sort() as string[],[products]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();const list=products.filter(p=>(category==='all'||p.category===category)&&(region==='all'||p.countryCode===region)&&(kind==='all'||p.type===kind)&&(!stock||p.inStock>0)&&(!q||`${p.name} ${p.brand} ${p.id} ${p.denominations.map(d=>d.name).join(' ')}`.toLowerCase().includes(q)));if(sort!=='featured')list.sort((a,b)=>sort==='stock'?b.totalStock-a.totalStock:a.currency.localeCompare(b.currency)||(sort==='price-up'?priceCompare(a.minPrice,b.minPrice):priceCompare(b.minPrice,a.minPrice)));return list},[products,category,query,region,kind,stock,sort]);
 const reset=()=>{setQuery('');setCategory('all');setRegion('all');setKind('all');setStock(false);setSort('featured');setShown(24)};
 const changeCategory=(c:CategoryId|'all')=>{setCategory(c);setShown(24)};
 const toggle=(p:CatalogProduct)=>{setSelected(prev=>prev.some(l=>l.product.id===p.id)?prev.filter(l=>l.product.id!==p.id):[...prev,{product:p,denom:p.denominations.find(d=>d.available)??p.denominations[0],quantity:1}])};
 const copy=async()=>{try{await CopyJson(buildManifest(selected));setMessage('Batch JSON copied. No orders submitted.')}catch{setMessage('Clipboard unavailable. Use Download JSON instead.')}};
 const count=(c:string)=>products.filter(p=>p.category===c).length;
 return <div className="mp"><ProductHeader active="catalog"/><main>
 <section className="mp-wrap cp-catalog-intro"><div><Eyebrow>MERCENTA / DIGITAL GOODS</Eyebrow><h1>Choose the product.<br/><span>Know what you get.</span></h1><p>Choose a product, region and option. See the availability and indicative price before proceeding.</p></div><div className="cp-source-status"><Badge tone={live?'ok':'neutral'}>{live?'Mercenta catalogue':'Illustrative examples'}</Badge><p>{live?'Browse the connected catalogue. Real-product checkout and delivery are not enabled yet.':sourceStatus==='access-denied'?'The catalogue source is unavailable. These are examples, not products available to buy.':'The Mercenta catalogue is unavailable. These examples are not live inventory.'}</p></div></section>
 <div className="mp-wrap cp-category-tabs" aria-label="Product categories"><button aria-pressed={category==='all'} onClick={()=>changeCategory('all')}>All products</button>{Object.entries(categoryMeta).map(([c,m])=><button key={c} aria-pressed={category===c} onClick={()=>changeCategory(c as CategoryId)}>{m.name}<span>{count(c)}</span></button>)}</div>
 <section className="mp-wrap mp-inventory" id="inventory"><div className="mp-section-heading"><div><Eyebrow>02 / EXPLORE INVENTORY</Eyebrow><h2>{category==='all'?'Find your next resource.':categoryMeta[category].name+'.'}</h2></div><span className="mp-meta">{live?'Feed fetched':'Examples loaded'} · {date(generatedAt)}</span></div>
 <div className="mp-filterbar"><label className="mp-search"><Search size={19}/><input ref={searchRef} aria-label="Search catalog" placeholder="Search products, brands or SKU…" value={query} onChange={e=>{setQuery(e.target.value);setShown(24)}}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}<kbd>⌘ K</kbd></label><label className="mp-select-label"><span>Region</span><select aria-label="Region" value={region} onChange={e=>{setRegion(e.target.value);setShown(24)}}><option value="all">All regions</option>{regions.map(r=><option key={r}>{r}</option>)}</select></label><label className="mp-select-label"><span>Format</span><select aria-label="Product format" value={kind} onChange={e=>{setKind(e.target.value);setShown(24)}}><option value="all">All formats</option><option value="voucher">Voucher</option><option value="direct_topup">Top-up</option><option value="esim">eSIM</option></select></label></div>
 <div className="mp-resultsbar"><div><button className={`mp-mini-tab ${category==='all'?'selected':''}`} onClick={()=>changeCategory('all')}>All goods <span>{products.length}</span></button><span className="mp-meta" aria-live="polite">{filtered.length} results</span><label className="mp-check"><input type="checkbox" checked={stock} disabled={!live} onChange={e=>{setStock(e.target.checked);setShown(24)}}/> Available only</label></div><div><select aria-label="Sort products" value={sort} onChange={e=>{setSort(e.target.value);setShown(24)}}><option value="featured">Featured order</option><option value="price-up">Price / currency ↑</option><option value="price-down">Price / currency ↓</option><option value="stock">Stock level ↓</option></select><div className="mp-toggle"><button aria-label="Grid view" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={17}/></button><button aria-label="List view" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={19}/></button></div></div></div>
 {message&&<div className="mp-inline-message" role="status">{message}<button className="mp-icon-button" aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {filtered.length===0?<div className="mp-empty"><Search size={34}/><h3>No matching resources.</h3><p>Try another search or reset your filters.</p><button className="mp-button" onClick={reset}>Reset filters <ArrowRight size={17}/></button></div>:<div className={`mp-products ${view==='list'?'is-list':''}`}>{filtered.slice(0,shown).map(p=><article key={p.id} className={`mp-product ${selected.some(l=>l.product.id===p.id)?'is-selected':''}`}><ProductImage name={p.name} category={p.category} imageUrl={p.imageSource==='supplier'?p.imageUrl:undefined}/><div className="mp-product-top"><div className="mp-category-icon"><CategoryIcon category={p.category} size={28}/></div><Eyebrow>{categoryMeta[p.category]?.name??p.category}</Eyebrow>{developer&&<label className="mp-product-select"><input type="checkbox" aria-label={'Select '+p.name} checked={selected.some(l=>l.product.id===p.id)} disabled={!live||!p.denominations.some(d=>d.available)} onChange={()=>toggle(p)}/></label>}</div><div className="mp-product-title"><span className="mp-meta">{p.brand} / {p.countryCode??'Global'}</span><h3>{p.name}</h3></div><div className="mp-product-options"><span>{p.denominations.length} options</span><Badge tone={p.inStock?'neutral':'stop'}>{!live?'Example only':p.inStock?'Available in feed':'Availability unconfirmed'}</Badge></div><div className="mp-product-bottom"><div><small>From</small><strong>{p.denominations.length?money(p.minPrice,p.currency):"No price supplied"}</strong></div><button className="mp-icon-button" aria-label={'View '+p.name} onClick={()=>setActive(p)}><ArrowUpRight size={20}/></button></div></article>)}</div>}
 {shown<filtered.length&&<button className="mp-button outline mp-load-more" onClick={()=>setShown(n=>n+24)}>Load more resources <Plus size={17}/></button>}
 <details className="customer-developer-tools"><summary>Developer tools</summary><p>Optional integration drafts, not customer checkout.</p><label className="mp-check"><input type="checkbox" checked={developer} onChange={e=>setDeveloper(e.target.checked)}/> Show draft-selection controls</label></details><p className="mp-disclaimer">{live?'Feed availability can change. Quotes must be verified before authorization.':'Illustrative products and example prices, not live inventory. No stock quantities are asserted.'} Catalog prices retain their source currency. No checkout or live settlement on this page.</p></section>

 </main><ProductFooter/>
 {selected.length>0&&<aside className="mp-batch-dock"><div><Badge>{selected.length} selected</Badge><span>Agent batch / draft</span></div><button className="mp-button" onClick={()=>setBatch(true)}>Review batch <ArrowRight size={17}/></button><button className="mp-icon-button" aria-label="Clear batch" onClick={()=>setSelected([])}><X size={18}/></button></aside>}

 {active&&<CatalogItemDialog key={active.id} product={active} onClose={()=>setActive(null)} onDraft={developer&&live?line=>{setSelected(prev=>[...prev.filter(l=>l.product.id!==line.product.id),line]);setActive(null);setMessage('Added to draft. No order submitted.')}:undefined}/>}
 {batch&&<Modal title="Your agent batch." onClose={()=>setBatch(false)}><Badge>Draft / no orders submitted</Badge><p className="mp-drawer-intro">Structured resources, ready for your integration. This export is a manifest, not an authorization or receipt.</p><div className="mp-batch-lines">{selected.map(l=><div key={l.product.id}><CategoryIcon category={l.product.category} size={22}/><div><strong>{l.product.name}</strong><small>{l.quantity} × {l.denom.name}</small></div><span>{money(lineUnits(l.denom.price,l.quantity),l.denom.currency)}</span><button className="mp-icon-button" aria-label={'Remove '+l.product.name} onClick={()=>setSelected(prev=>prev.filter(x=>x.product.id!==l.product.id))}><X size={16}/></button></div>)}</div><div className="mp-detail-total">{Object.entries(buildManifest(selected).totals.byCurrency).map(([c,n])=><p key={c}><span>Draft total / {c}</span><strong>{money(n,c)}</strong></p>)}</div><div className="mp-action-row"><button disabled={!selected.length} className="mp-button" onClick={copy}><Copy size={17}/> Copy JSON</button><button disabled={!selected.length} className="mp-button outline" onClick={()=>DownloadJson(buildManifest(selected),'mercenta-batch.json')}><Download size={17}/> Download JSON</button></div><p className="mp-note" role="status">{message}</p><p className="mp-note">No supplier cost, on-chain proof or margin approval is invented. Verify each quote in your integration.</p></Modal>}

 </div>
}
