 'use client';
import {useEffect,useMemo,useState} from 'react';
import type {Catalog} from '@/lib/supplier';
import type {Language} from '@/lib/workspace-plan';
import {ProductImage} from './ProductImage';
const PAGE_SIZE=24;
export function SupplierCatalogBrowser({lang}:{lang:Language}){
 const ru=lang==='ru';
 const [feed,setFeed]=useState<Catalog|null>(null),[error,setError]=useState(false),[query,setQuery]=useState(''),[region,setRegion]=useState('all'),[kind,setKind]=useState('all'),[shown,setShown]=useState(PAGE_SIZE);
 useEffect(()=>{let live=true;fetch('/api/catalog',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(v=>{if(live)setFeed(v)}).catch(()=>{if(live)setError(true)});return()=>{live=false}},[]);
 const regions=useMemo(()=>[...new Set((feed?.products??[]).map(p=>p.countryCode).filter(Boolean))].sort() as string[],[feed]);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();return (feed?.products??[]).filter(p=>(region==='all'||p.countryCode===region)&&(kind==='all'||p.type===kind)&&(!q||(p.name+' '+p.brand+' '+p.countryCode+' '+p.denominations.map(d=>d.name).join(' ')).toLowerCase().includes(q)))},[feed,query,region,kind]);
 if(!feed&&!error)return <div className="supplier-state" role="status">{ru?'Проверяем доступ к каталогу…':'Checking supplier catalogue…'}</div>;
 if(error||!feed?.live)return <div className="supplier-state"><h2>{ru?'Каталог AppRoute пока недоступен':'AppRoute catalogue is not available yet'}</h2><p>{feed?.sourceStatus==='access-denied'?(ru?'Поставщик отклонил доступ. Мы не выдаём примеры за реальный ассортимент.':'The supplier denied access. Examples are not presented as live inventory.'):(ru?'Не удалось подтвердить источник товаров. Покупки у поставщика не включены.':'The supplier feed could not be verified. Supplier purchasing is not enabled.')}</p><a href="/catalog">{ru?'Посмотреть каталог и статус источника':'View catalogue and source status'} ↗</a></div>;
 return <section className="supplier-browser"><p className="supplier-note">{ru?'Каталог получен от AppRoute. Цены поставщика в USD — не цена оплаты в USDC. Закупка и выдача ещё не включены.':'Catalogue received from AppRoute. Supplier prices in USD are not USDC checkout quotes. Procurement and delivery are not enabled.'}</p><div className="supplier-controls"><input className="supplier-search" aria-label={ru?'Поиск по AppRoute':'Search AppRoute catalogue'} placeholder={ru?'Товар, номинал или регион':'Product, option or region'} value={query} onChange={e=>{setQuery(e.target.value);setShown(PAGE_SIZE)}}/><label>{ru?'Регион':'Region'}<select aria-label={ru?'Регион AppRoute':'AppRoute region'} value={region} onChange={e=>{setRegion(e.target.value);setShown(PAGE_SIZE)}}><option value="all">{ru?'Все регионы':'All regions'}</option>{regions.map(r=><option key={r}>{r}</option>)}</select></label><label>{ru?'Тип товара':'Product format'}<select aria-label={ru?'Тип товара AppRoute':'AppRoute format'} value={kind} onChange={e=>{setKind(e.target.value);setShown(PAGE_SIZE)}}><option value="all">{ru?'Все типы':'All formats'}</option><option value="voucher">{ru?'Коды и карты':'Vouchers & cards'}</option><option value="direct_topup">{ru?'Пополнения':'Top-ups'}</option><option value="esim">eSIM</option></select></label></div><p className="supplier-count" role="status">{rows.length} / {feed.products.length} {ru?'товаров в полученном каталоге':'products in the received catalogue'} · {ru?'Показано':'Showing'} {Math.min(shown,rows.length)}</p>{!rows.length?<div className="supplier-state"><h2>{ru?'Ничего не найдено':'No matching products'}</h2><button className="ma-button secondary" onClick={()=>{setQuery('');setRegion('all');setKind('all');setShown(PAGE_SIZE)}}>{ru?'Сбросить фильтры':'Reset filters'}</button></div>:<div className="supplier-grid">{rows.slice(0,shown).map(p=><article className="supplier-card" key={p.id}><ProductImage name={p.name} category={p.category} imageUrl={p.imageSource==='supplier'?p.imageUrl:undefined}/><div><span>{p.countryCode??(ru?'Регион не указан':'Region unspecified')}</span><h2>{p.name}</h2><p>{p.denominations.length} {ru?'вариантов':'options'} · {p.type}</p><strong>{p.denominations.length?(ru?'От ':'From ')+p.minPrice+' '+p.currency:(ru?'Цена не предоставлена':'No price supplied')}</strong><a href={'/catalog?search='+encodeURIComponent(p.name)}>{ru?'Варианты и детали':'Options and details'} ↗</a></div></article>)}</div>}{shown<rows.length&&<button className="ma-button secondary supplier-more" onClick={()=>setShown(n=>n+PAGE_SIZE)}>{ru?'Показать ещё 24':'Show 24 more'}</button>}<p className="supplier-note">{ru?'Наличие меняется. Обложки иллюстративные: в текущем ответе нет фотографий товаров. Полнота каталога пока не подтверждена.':'Availability can change. Covers are illustrative: the current response does not include product photos. Catalogue completeness is not yet verified.'}</p></section>;
}
