'use client';
import '../../../public/vendor/swagger/swagger-ui.css';
import Script from 'next/script';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ShieldCheck,Sun,Moon} from 'lucide-react';
import {Brand} from './ProductShell';
import {NetworkSelector} from './NetworkSelector';
import type {NetworkMode} from '@/lib/network-profile';
import './account.css';import './workspace-ux.css';import './network-workspace.css';import './swagger-reference.css';
type SwaggerFactory=(options:Record<string,unknown>)=>{getSystem?:()=>unknown};
declare global {interface Window {SwaggerUIBundle?:SwaggerFactory&{presets:{apis:unknown}}}}
export function SwaggerReference({hostMode}:{hostMode:NetworkMode}){
 const [profile,setProfile]=useState<NetworkMode>(hostMode),[loaded,setLoaded]=useState(false),[failed,setFailed]=useState(false),[theme,setTheme]=useState<'dark'|'light'>('dark');const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!loaded||!root.current||!window.SwaggerUIBundle)return;const node=root.current;node.replaceChildren();window.SwaggerUIBundle({url:'/api/openapi?network='+profile,domNode:node,presets:[window.SwaggerUIBundle.presets.apis],layout:'BaseLayout',deepLinking:true,filter:true,docExpansion:'none',displayRequestDuration:true,persistAuthorization:false,validatorUrl:null,supportedSubmitMethods:profile==='testnet'&&hostMode==='testnet'?['get']:[],defaultModelsExpandDepth:0});return()=>node.replaceChildren()},[loaded,profile,hostMode]);
 return <div className="mp ma ma-ux sw-page" data-theme={theme}><header className="sw-header"><Brand small/><span>API reference</span><div><NetworkSelector mode={hostMode}/><button className="ma-icon" aria-label="Change theme" onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><a className="ma-button secondary" href="/app">Open workspace<ArrowUpRight size={16}/></a></div></header><main className="sw-content"><span className="rf-context">MERCENTA · DEVELOPERS</span><h1>Build with a clear contract.</h1><p>Authentication, budgets, agent tasks, quotes, orders and delivery. Choose the API profile before integrating.</p><div className="sw-profiles" aria-label="API profile"><button aria-pressed={profile==='testnet'} onClick={()=>setProfile('testnet')}>Testnet · rehearsal</button><button aria-pressed={profile==='mainnet'} onClick={()=>setProfile('mainnet')}>Mainnet · release gates</button><a href={'/api/openapi?network='+profile} download={'mercenta-'+profile+'.json'}>Download OpenAPI 3.1<ArrowUpRight size={15}/></a></div><aside className="nw-preview-note"><ShieldCheck size={20}/><div><b>{profile==='mainnet'?'Real-buy API is not enabled.':'Test assets. Simulated digital delivery.'}</b><p>{profile==='mainnet'?'Financial paths return 503. No production debit, deposit, wallet session or testnet fallback. This is the release contract, not a claim that real checkout is live.':'Use a verified wallet session for account tools, or scoped Bearer keys for /api/v1. Mutating Try it out is disabled. Never paste wallet keys or supplier credentials.'}</p></div></aside><p className="sw-contract-note">Inputs are generated from server validation schemas. Business rules still apply. Generic response objects are explicitly untyped; this reference is not yet a fully typed SDK.</p>{failed&&<p role="alert">Swagger could not load. <a href={'/api/openapi?network='+profile}>Open the JSON contract</a>.</p>}{!loaded&&!failed&&<div className="sw-skeleton" aria-label="Preparing API reference"><i/><i/><i/></div>}<div ref={root} className="sw-renderer"/><Script src="/vendor/swagger/swagger-ui-bundle.js" strategy="afterInteractive" onReady={()=>setLoaded(true)} onError={()=>setFailed(true)}/></main><footer className="sw-footer">Mercenta · support@mercenta.xyz · Swagger UI, Apache-2.0</footer></div>;
}
