'use client';
import {useRef,useState} from 'react';
import './product-refinement.css';
import {useRevealMotion} from '@/lib/surface-motion';
import {StartJourney} from './StartJourney';
import {ArrowRight,ArrowUpRight,Wallet,ShieldCheck,Bot,SlidersHorizontal,ShoppingBag,Search,FileCheck2,Check} from 'lucide-react';
import {accountMoney} from '@/lib/account-format';
import {compactUsdc,type PreviewProduct} from '@/lib/workspace-discovery';
import type {Language} from '@/lib/workspace-plan';
import type {BrowseCatalog} from '@/lib/catalog-browse';
import {homeFeaturedFamilies,saveHomeGoal,saveFamilyIntent} from '@/lib/home-featured';
import type {Destination} from './WorkspaceGuide';
import {CatalogFamilyCard} from './CatalogFamilyCard';
type Row=Record<string,string|number|null>;
type Props={catalog?:BrowseCatalog;lang:Language;wallet:string|null;available:string|null;reserved:string|null;orders:number|null;spent:string|null;recent:Row[];products:PreviewProduct[];onReview:(p:PreviewProduct)=>void;onNavigate:(s:Destination)=>void;onSetup:()=>void;onFund:()=>void;canFund:boolean;loading:boolean;readOnly:boolean;network?:'testnet'|'mainnet'};
export function WorkspaceHome(p:Props){
 const ru=p.lang==='ru',signedIn=!!p.wallet,amount=p.available===null?null:compactUsdc(p.available),needsFunds=amount&&BigInt(p.available!)===0n&&p.canFund,isMainnet=p.network==='mainnet';
 const reveal=useRef<HTMLDivElement>(null);useRevealMotion(reveal);
 const [goal,setGoal]=useState(''),featured=homeFeaturedFamilies(p.catalog);
 return <div ref={reveal} className="rf-home hf-home">
 {isMainnet&&<div className="mn-gateway-banner" role="status" style={{marginBottom:'24px'}}><div className="mn-gateway-info"><div className="mn-gateway-title"><ShieldCheck size={18}/><strong>{ru?'Шлюз покупок активен на Arc Mainnet (5042)':'MercentaCheckout Gateway Live on Arc Mainnet (5042)'}</strong></div><p>{ru?'Смарт-контракт MercentaCheckout верифицирован на Blockscout. Продажи открыты. Оплата производится в USDC сети Arc (Chain ID 5042).':'Smart contract MercentaCheckout is verified on Blockscout. Sales are unpaused. Purchases execute in Arc USDC (Chain ID 5042).'}</p></div><div className="mn-gateway-meta"><span><b>Router:</b> <a href="https://explorer.arc.io/address/0x06b67adf8d63c8c35a6beda42a3bb93d485af3ed#code" target="_blank" rel="noreferrer">0x06b6…3ed <ArrowUpRight size={11}/></a></span><span><b>Merchant:</b> <a href="https://explorer.arc.io/address/0x58863e4a739da0e62c2eba258b7783e95d5c48ce" target="_blank" rel="noreferrer">0x5886…48ce <ArrowUpRight size={11}/></a></span></div></div>}
 <section className="hf-hero"><div className="hf-intro"><span className="hf-eyebrow">{ru?'ВАШЕ ПРОСТРАНСТВО MERCENTA':'YOUR MERCENTA WORKSPACE'}</span><h1>{ru?'Найдите нужное.':'Find your next thing.'}<br/><span>{ru?'Остальное — под контролем.':'Keep the rest in control.'}</span></h1><p>{ru?'Цифровые товары, агент и ваш бюджет. Начните с того, что вам нужно — без лишних шагов.':'Digital products, an agent and your budget. Start with what you need. Leave the unnecessary steps behind.'}</p><div className="hf-hero-actions"><button className="ma-button" onClick={needsFunds?p.onFund:()=>p.onNavigate('Shop')}>{needsFunds?(ru?'Пополнить test USDC':'Add test USDC'):(ru?'Посмотреть товары':'Explore products')}<ArrowRight size={18}/></button><StartJourney compact ru={ru} onNavigate={p.onNavigate} onBudget={p.onSetup}/></div><span className="hf-hint">{ru?'Для просмотра товаров кошелёк не нужен.':'No wallet needed to explore.'}</span></div>
 <form className="hf-agent" onSubmit={e=>{e.preventDefault();if(saveHomeGoal(goal))p.onNavigate('Agent Chat')}}><div className="hf-agent-label"><Bot size={21}/><span>{ru?'НАЧНИТЕ С ЗАПРОСА':'START WITH A GOAL'}</span></div><h2>{ru?'Пусть агент найдёт.':'Let your agent find it.'}</h2><p>{ru?'Скажите, что ищете. На следующем шаге зададите регион и предел расходов.':'Tell it what you need. Set your region and spending limit on the next step.'}</p><label htmlFor="home-agent-goal">{ru?'Какой товар ищем?':'What are you looking for?'}</label><input id="home-agent-goal" value={goal} onChange={e=>setGoal(e.target.value)} maxLength={140} placeholder={ru?'Например, Steam для моего региона':'For example, Steam for my region'}/><div className="hf-suggestions">{['Steam','Roblox','Spotify'].map(s=><button type="button" key={s} onClick={()=>setGoal(ru?`Найди ${s} для моего региона`:`Find ${s} for my region`)}>{s}</button>)}</div><button className="ma-button secondary" disabled={!goal.trim()} type="submit">{ru?'Подготовить задачу':'Prepare my task'}<ArrowRight size={17}/></button><small><ShieldCheck size={14}/>{ru?'Только черновик. Это не разрешение на покупку.':'A draft, not permission to spend.'}</small></form></section>
<section className="hf-route" aria-label={ru?'Как работает Mercenta':'How Mercenta works'}>{(ru?[['Скажите, что нужно','Товар, регион и предел расходов.'],['Проверьте предложение','Агент ищет. Вы видите вариант и точную котировку.'],['Контролируйте решение','Отдельное подтверждение или явное ограниченное разрешение.']]:[['Start with a need','A product, a region and a spending cap.'],['Review the proposal','The agent searches. You see the option and exact quote.'],['Keep the decision yours','Separate confirmation or explicit bounded permission.']]).map(([title,text],i)=><div key={title}><span className="hf-route-number" aria-hidden="true">{i===0?<Search size={16}/>:i===1?<FileCheck2 size={16}/>:<Check size={16}/>}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}</section>
{signedIn&&<section className="rf-account" aria-label={ru?'Ваш счёт':'Your account'}><div><span><Wallet size={18}/>{p.readOnly?(ru?'Последний загруженный баланс':'Last loaded account balance'):(ru?'Доступно на счёте Mercenta':'Available in your Mercenta account')}</span><strong title={amount?.exact+' USDC'}>{amount?.text??'—'}<small> USDC</small></strong><p>{p.readOnly?(ru?'Сервис недоступен: актуальный баланс не подтверждён.':'Service unavailable: the current balance is not confirmed.'):(ru?'Это предоплаченный счёт, не баланс внешнего кошелька.':'Your prepaid account, not the balance of your external wallet.')}</p></div><div className="rf-account-actions"><button className="ma-link" onClick={()=>p.onNavigate('Funds')}>{ru?'Открыть счёт':'View account'}<ArrowUpRight size={17}/></button>{p.spent!==null&&<p>{ru?'Расходы за 30 дней':'Spent in 30 days'} <b title={accountMoney(p.spent)+' USDC'}>{compactUsdc(p.spent).text} USDC</b></p>}{p.orders!==null&&<p>{ru?'Заказов за 30 дней':'Orders in 30 days'} <b>{p.orders}</b></p>}{p.reserved!==null&&BigInt(p.reserved)>0n&&<p>{ru?'Зарезервировано':'Reserved'} <b>{compactUsdc(p.reserved).text} USDC</b></p>}</div></section>}
 {featured.length>0&&<section data-surface-reveal className="hf-featured"><div className="hf-section-title"><div><span className="hf-eyebrow">{ru?'ЦИФРОВЫЕ ВОЗМОЖНОСТИ':'DIGITAL POSSIBILITIES'}</span><h2>{ru?'Знакомые платформы. Ваш регион.':'Familiar platforms. Your region.'}</h2></div><button className="ma-link" onClick={()=>p.onNavigate('Shop')}>{ru?'Весь каталог':'Full catalogue'}<ArrowUpRight size={17}/></button></div><div className="hf-products">{featured.map(family=><CatalogFamilyCard key={family.key} family={family} ru={ru} priority onOpen={()=>{saveFamilyIntent(family);p.onNavigate('Shop')}}/>)}</div><p className="hf-catalog-note">{ru?'Выберите свой регион в каталоге. Цены в USD — не котировки для оплаты; реальная выдача пока закрыта.':'Choose your region in the catalogue. USD prices are not checkout quotes; real delivery is not enabled.'}</p></section>}
{signedIn&&p.recent.length>0&&<section className="rf-recent"><div className="rf-section-heading"><h2>{ru?'Последние покупки':'Recent purchases'}</h2><button className="ma-link" onClick={()=>p.onNavigate('Orders')}>{ru?'Все покупки':'View purchases'}<ArrowUpRight size={16}/></button></div>{p.recent.slice(0,3).map(r=><button className="ux-recent-row" key={String(r.id)} onClick={()=>p.onNavigate('Orders')}><span><b>{String(r.name??'Order')}</b><small>{String(r.status??'').replaceAll('_',' ').toLowerCase()}</small></span><strong title={accountMoney(String(r.amount_units??'0'))+' USDC'}>{compactUsdc(String(r.amount_units??'0')).text}<small> USDC</small></strong></button>)}</section>}
 <section data-surface-reveal className="hf-utilities" aria-label={ru?'Другие возможности':'More ways to start'}><button onClick={p.onSetup}><SlidersHorizontal size={22}/><span><strong>{ru?'Ваш бюджет. Ваши правила.':'Your budget. Your boundaries.'}</strong><small>{ru?'Распределите расходы, оставьте резерв. Без перевода денег.':'Plan your spending and leave a reserve. No funds are moved.'}</small></span><ArrowRight size={18}/></button><button onClick={()=>p.onNavigate(signedIn?'Orders':'Shop')}><ShoppingBag size={22}/><span><strong>{signedIn?(ru?'Покупки и результаты':'Purchases and results'):(ru?'Изучите до покупки':'Explore before you buy')}</strong><small>{signedIn?(ru?'Статусы, выдача и история заказов.':'Order status, delivery and history.'):(ru?'Сравните регионы, номиналы и варианты товаров.':'Compare regions, denominations and product options.')}</small></span><ArrowRight size={18}/></button></section>
 <p className="rf-safety hf-safety"><ShieldCheck size={16}/>{isMainnet?(ru?'Arc Mainnet (5042) · Верифицированный контракт MercentaCheckout · Прямые ончейн расчеты.':'Arc Mainnet (5042) · Verified MercentaCheckout Router · On-chain USDC settlement.'):(ru?'Arc Testnet · только test USDC · тестовые коды не активируются.':'Arc Testnet · test USDC only · test codes are not redeemable.')}</p></div>;
}
