import {readFileSync,writeFileSync,renameSync,existsSync,openSync,fsyncSync,closeSync,lstatSync} from 'node:fs';import {join,dirname} from 'node:path';
import {createPublicClient,http,encodeFunctionData,parseAbi,formatUnits,keccak256,parseTransaction,decodeEventLog,type Hex,type Address} from 'viem';
import {CHAIN,loadAgentConfig} from '../src/services/circle-policy.js';import {localAccount} from '../src/services/circle-signers.js';import {gatewayAvailableUnits} from '../src/services/circle-gateway-balance.js';import {DEPOSIT_UNITS,GAS_BUDGET_WEI,assertFundingBudget,paddedGas} from '../src/services/circle-funding-policy.js';
const WALLET='0x83758c71386c873d5c518251613bf340f5bd558d',OWNER='0x58863e4a739da0e62c2eba258b7783e95d5c48ce';
const TOKEN='0x3600000000000000000000000000000000000000',GATEWAY='0x0077777d7eba4688bdef3e311b846f25870a19b9';
const TOKEN_HASH='0xc9987bd3af6b26a030951faa7eacc017b68343aeedf3ce5fe68f821c4b93939d',GATEWAY_HASH='0x874a21508289bf01ee9802032607ae53ba0a4f47f28143a8493921b8db102187';
const erc=parseAbi(['function approve(address,uint256) returns(bool)','function allowance(address,address) view returns(uint256)','function balanceOf(address) view returns(uint256)','event Transfer(address indexed from,address indexed to,uint256 value)']);
const abi=parseAbi(['function deposit(address,uint256)','function availableBalance(address,address) view returns(uint256)','function totalBalance(address,address) view returns(uint256)']);
type Tx={step:'approval'|'deposit';hash:Hex;raw:Hex;to:Address;data:Hex;gas:string;maxFee:string;nonce:number;status:'SIGNED'|'SENT'|'CONFIRMED';gasPaid?:string};
type Journal={id:string;wallet:string;owner:string;amountUnits:string;gasCapWei:string;baseline:string;txs:Tx[];completed:boolean};
async function main(){
 const configPath=process.env.CIRCLE_AGENT_CONFIG_FILE??join(process.env.LOCALAPPDATA!,'Mercenta','circle','arc-agent-config.json');
 function checkedConfig(){const c=loadAgentConfig(configPath);if(!c||c.provider!=='local-eoa'||c.walletAddress!==WALLET||c.ownerWallet!==OWNER||c.enabled||c.services.length)throw Error('FUNDING_CONFIGURATION_CHANGED');return c;}
 const c=checkedConfig(),account=localAccount(c);if(CHAIN.chain.id!==5042002||CHAIN.domain!==26||CHAIN.usdc.toLowerCase()!==TOKEN||CHAIN.gatewayWallet.toLowerCase()!==GATEWAY)throw Error('UNTRUSTED_SDK_CONFIGURATION');
 const client=createPublicClient({chain:CHAIN.chain,transport:http(process.env.ARC_RPC_URL??'https://rpc.testnet.arc.network',{timeout:10000,retryCount:0})});
 async function verifyNetwork(){checkedConfig();if(await client.getChainId()!==5042002)throw Error('WRONG_CHAIN');const [tokenCode,gatewayCode]=await Promise.all([client.getCode({address:CHAIN.usdc}),client.getCode({address:CHAIN.gatewayWallet})]);if(!tokenCode||!gatewayCode||keccak256(tokenCode)!==TOKEN_HASH||keccak256(gatewayCode)!==GATEWAY_HASH)throw Error('CONTRACT_RUNTIME_CHANGED');}
 await verifyNetwork();const file=join(dirname(configPath),'gateway-approved-010-20261002.json');
 let journal:Journal|undefined;if(existsSync(file)){const s=lstatSync(file);if(!s.isFile()||s.isSymbolicLink()||s.size>64000||process.platform!=='win32'&&(s.mode&0o077)!==0)throw Error('UNSAFE_JOURNAL');journal=JSON.parse(readFileSync(file,'utf8'));if(!journal||journal.id!=='gateway-010-20261002'||journal.wallet!==WALLET||journal.owner!==OWNER||journal.amountUnits!==DEPOSIT_UNITS.toString()||journal.gasCapWei!==GAS_BUDGET_WEI.toString()||journal.txs.length>2)throw Error('JOURNAL_MISMATCH');}
 function save(){const temp=file+'.tmp';writeFileSync(temp,JSON.stringify(journal,null,2)+'\n',{mode:0o600});const fd=openSync(temp,'r+');fsyncSync(fd);closeSync(fd);renameSync(temp,file);}
 const walletBefore=await client.getBalance({address:account.address}),gatewayOnchain=await client.readContract({address:CHAIN.gatewayWallet,abi,functionName:'availableBalance',args:[CHAIN.usdc,account.address]});
 const fees=await client.estimateFeesPerGas();const allowance=await client.readContract({address:CHAIN.usdc,abi:erc,functionName:'allowance',args:[account.address,CHAIN.gatewayWallet]});
 const approveData=encodeFunctionData({abi:erc,functionName:'approve',args:[CHAIN.gatewayWallet,DEPOSIT_UNITS]}),depositData=encodeFunctionData({abi,functionName:'deposit',args:[CHAIN.usdc,DEPOSIT_UNITS]});
 const approvalEstimate=allowance>=DEPOSIT_UNITS?0n:paddedGas(await client.estimateGas({account,to:CHAIN.usdc,data:approveData,value:0n}));
 if(!journal){if(gatewayOnchain!==0n||allowance!==0n)throw Error('UNEXPECTED_EXISTING_FUNDING');assertFundingBudget(0n,approvalEstimate||1n,fees.maxFeePerGas,120000n*fees.maxFeePerGas);if(walletBefore<100_000_000_000_000_000n+GAS_BUDGET_WEI)throw Error('INSUFFICIENT_WALLET_USDC');}
 const execute=process.argv.includes('--execute');if(!execute){console.log(JSON.stringify({mode:'PLAN_ONLY',wallet:account.address,depositUsdc:'0.10',gasBudgetUsdc:'0.02',walletUsdc:formatUnits(walletBefore,18),approvalGasLimit:approvalEstimate.toString(),depositGasReserved:'120000',maxFeePerGas:fees.maxFeePerGas.toString(),maximumEstimatedGasUsdc:formatUnits((approvalEstimate+120000n)*fees.maxFeePerGas,18),existingJournal:!!journal,noTransactionSigned:true}));return;}
 if(!journal){journal={id:'gateway-010-20261002',wallet:WALLET,owner:OWNER,amountUnits:DEPOSIT_UNITS.toString(),gasCapWei:GAS_BUDGET_WEI.toString(),baseline:gatewayOnchain.toString(),txs:[],completed:false};save();}
 const paid=()=>journal!.txs.reduce((sum,t)=>sum+BigInt(t.gasPaid??'0'),0n);
 async function send(step:'approval'|'deposit',to:Address,data:Hex,reserveNext:boolean){
  let tx=journal!.txs.find(t=>t.step===step);
  if(!tx){await verifyNetwork();const currentFees=await client.estimateFeesPerGas(),estimated=paddedGas(await client.estimateGas({account,to,data,value:0n}));assertFundingBudget(paid(),estimated,currentFees.maxFeePerGas,reserveNext?120000n*currentFees.maxFeePerGas:0n);const pending=await client.getTransactionCount({address:account.address,blockTag:'pending'}),latest=await client.getTransactionCount({address:account.address,blockTag:'latest'});if(pending!==latest)throw Error('OTHER_PENDING_TRANSACTION');const raw=await account.signTransaction({chainId:5042002,type:'eip1559',to,data,value:0n,nonce:pending,gas:estimated,maxFeePerGas:currentFees.maxFeePerGas,maxPriorityFeePerGas:currentFees.maxPriorityFeePerGas});tx={step,to,data,raw,hash:keccak256(raw),gas:estimated.toString(),maxFee:currentFees.maxFeePerGas.toString(),nonce:pending,status:'SIGNED'};journal!.txs.push(tx);save();}
  const parsed=parseTransaction(tx.raw);if(keccak256(tx.raw)!==tx.hash||parsed.chainId!==5042002||parsed.to?.toLowerCase()!==to.toLowerCase()||parsed.data!==data||(parsed.value??0n)!==0n||parsed.gas!==BigInt(tx.gas)||parsed.maxFeePerGas!==BigInt(tx.maxFee)||parsed.nonce!==tx.nonce)throw Error('SIGNED_TRANSACTION_MISMATCH');
  if(tx.status!=='CONFIRMED'){await verifyNetwork();assertFundingBudget(paid(),BigInt(tx.gas),BigInt(tx.maxFee));let seen=await client.getTransaction({hash:tx.hash}).catch(()=>null);if(!seen){const hash=await client.sendRawTransaction({serializedTransaction:tx.raw});if(hash!==tx.hash)throw Error('BROADCAST_HASH_MISMATCH');}tx.status='SENT';save();const receipt=await client.waitForTransactionReceipt({hash:tx.hash,confirmations:2,timeout:180000});if(receipt.status!=='success')throw Error('FUNDING_TRANSACTION_REVERTED');const block=await client.getBlock({blockNumber:receipt.blockNumber});if(block.hash!==receipt.blockHash)throw Error('NON_CANONICAL_RECEIPT');const transaction=await client.getTransaction({hash:tx.hash});if(transaction.from.toLowerCase()!==WALLET||transaction.to?.toLowerCase()!==to.toLowerCase()||transaction.input!==data||transaction.value!==0n)throw Error('TRANSACTION_ATTRIBUTION_MISMATCH');const actual=receipt.gasUsed*receipt.effectiveGasPrice;if(paid()+actual>GAS_BUDGET_WEI)throw Error('ACTUAL_GAS_BUDGET_EXCEEDED');if(step==='deposit'){let verified=false;for(const log of receipt.logs){if(log.address.toLowerCase()!==TOKEN)continue;try{const event=decodeEventLog({abi:erc,data:log.data,topics:log.topics});if(event.eventName==='Transfer'&&event.args.from.toLowerCase()===WALLET&&event.args.to.toLowerCase()===GATEWAY&&event.args.value===DEPOSIT_UNITS)verified=true}catch{}}if(!verified)throw Error('DEPOSIT_TRANSFER_EVIDENCE_MISSING');}tx.gasPaid=actual.toString();tx.status='CONFIRMED';save();}
  console.log(JSON.stringify({step,txHash:tx.hash,status:tx.status,gasUsdc:formatUnits(BigInt(tx.gasPaid??'0'),18)}));
 }
 if(!journal.completed){await send('approval',CHAIN.usdc,approveData,true);const exactAllowance=await client.readContract({address:CHAIN.usdc,abi:erc,functionName:'allowance',args:[account.address,CHAIN.gatewayWallet]});if(!journal.txs.some(t=>t.step==='deposit')&&exactAllowance!==DEPOSIT_UNITS)throw Error('EXACT_APPROVAL_REQUIRED');await send('deposit',CHAIN.gatewayWallet,depositData,false);const amount=await client.readContract({address:CHAIN.gatewayWallet,abi,functionName:'availableBalance',args:[CHAIN.usdc,account.address]});if(amount-BigInt(journal.baseline)!==DEPOSIT_UNITS)throw Error('ONCHAIN_DEPOSIT_BALANCE_MISMATCH');journal.completed=true;save();}
 let available:bigint|null=null;for(let i=0;i<10;i++){available=await gatewayAvailableUnits(c).catch(()=>null);if(available!==null&&available>=DEPOSIT_UNITS)break;await new Promise(r=>setTimeout(r,3000));}
 console.log(JSON.stringify({completed:journal.completed,depositUsdc:'0.10',gasTotalUsdc:formatUnits(paid(),18),gasWithinApprovedBudget:paid()<=GAS_BUDGET_WEI,walletUsdc:formatUnits(await client.getBalance({address:account.address}),18),gatewayAvailableUsdc:available===null?null:formatUnits(available,6),gatewayApiReady:available!==null&&available>=DEPOSIT_UNITS,purchasesExecuted:false,executionEnabled:false,hashes:journal.txs.map(t=>({step:t.step,txHash:t.hash}))}));
}
main().catch((error)=>{const code=typeof error?.code==="string"&&/^[A-Z_0-9]{1,80}$/.test(error.code)?error.code:typeof error?.message==="string"&&/^[A-Z_0-9]{1,80}$/.test(error.message)?error.message:"SAFE_ERROR_DETAILS_SUPPRESSED";console.error(code);console.error('GATEWAY_APPROVED_DEPOSIT_STOPPED: inspect the restricted journal and reconcile its existing hashes; do not create a replacement deposit. No private data printed.');process.exitCode=1});
