"use client";
import Link from 'next/link';import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,RefreshCw,ShieldCheck,Wallet,Globe2,TriangleAlert,ExternalLink,LockKeyhole} from 'lucide-react';
import BrandMark from '@/components/landing/BrandMark';
import {EARN_MARKET,canOpenExternalEarn,unavailableEarn,type EarnSnapshot} from '@/lib/earn-market';
import styles from './earn.module.css';
import {MorphoPanel} from './MorphoPanel';
export function EarnHub(){
 const [provider,setProvider]=useState('aave');
 const [ru,setRu]=useState(false),[snapshot,setSnapshot]=useState<EarnSnapshot|null>(null),[loading,setLoading]=useState(true),[accepted,setAccepted]=useState(false),[now,setNow]=useState(0);
 const controller=useRef<AbortController|null>(null);const t=(en:string,russian:string)=>ru?russian:en;
 const refresh=useCallback(async()=>{controller.current?.abort();const ctl=new AbortController();controller.current=ctl;setLoading(true);setSnapshot(null);
 try{const r=await fetch('/api/earn/market',{cache:'no-store',signal:ctl.signal});if(!r.ok)throw Error('UNAVAILABLE');const s=await r.json() as EarnSnapshot;
 if(!['available','blocked','unavailable'].includes(s.status)||s.chainId!==1||s.externalExecutionOnly!==true||s.mercentaCustody!==false||!Number.isSafeInteger(s.expiresAt)||!Number.isSafeInteger(s.observedAt)||s.expiresAt>s.observedAt+30000||s.principalGuaranteed!==false||s.interestGuaranteed!==false||s.arcNativeYield!==false||(s.annualRatePercent!==null&&!/^\d{1,8}\.\d{2}$/.test(s.annualRatePercent)))throw Error('INVALID_SNAPSHOT');
 if(!ctl.signal.aborted)setSnapshot(s);
 }catch{if(!ctl.signal.aborted)setSnapshot(unavailableEarn());}finally{if(!ctl.signal.aborted){setNow(Date.now());setLoading(false);}}},[]);
 useEffect(()=>{if(provider!=='aave')return;void refresh();const timer=setInterval(()=>{void refresh()},30000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{controller.current?.abort();clearInterval(timer);clearInterval(clock)}},[refresh,provider]);
 const fresh=!!snapshot&&snapshot.expiresAt>now&&snapshot.observedAt<=now;
 const open=canOpenExternalEarn(snapshot,accepted,now)&&!loading;
 const rate=fresh&&snapshot?.annualRatePercent!==null?snapshot?.annualRatePercent:null;
 return <div className={styles.root} lang={ru?'ru':'en'}><a className={styles.skip} href="#earn-content">{t('Skip to content','Перейти к содержимому')}</a>
 <header className={styles.header}><Link className={styles.brand} href="/" aria-label="Mercenta home"><BrandMark/>mercenta.</Link><nav aria-label={t('Earn navigation','Навигация Earn')}><Link href="/catalog">{t('Catalogue','Каталог')}</Link><Link href="/support">{t('Help','Помощь')}</Link><div className={styles.language} role="group" aria-label={t('Language','Язык')}><button aria-pressed={!ru} onClick={()=>setRu(false)}>EN</button><button aria-pressed={ru} onClick={()=>setRu(true)}>RU</button></div></nav></header>
 <main id="earn-content" className={styles.main}><div className={styles.overline}><span/>MERCENTA / EXTERNAL EARN</div><section className={styles.hero}><div><h1>{t('Your capital.','Ваш капитал.')}<br/><em>{t('A separate decision.','Отдельное решение.')}</em></h1><p>{t('Explore variable USDC interest from an external lending market. Your position stays with your wallet—not on a Mercenta prepaid balance.','Переменная доходность USDC во внешнем кредитном рынке. Позиция принадлежит вашему кошельку — это не пополнение счёта Mercenta.')}</p></div><aside className={styles.boundary}><Globe2 size={23}/><strong>{provider==='aave'?'Ethereum Mainnet · 1':'Arc Mainnet · 5042'}</strong><p>{provider==='morpho'?t('Arc-native USDC research preview. No automatic allocation. Keep your purchase budget separate; Testnet funds cannot be used.','Обзор USDC в Arc. Авторазмещения нет. Бюджет покупок отдельно; Testnet-средства использовать нельзя.'):t('Not Arc. No automatic bridge. You need USDC and ETH for gas on Ethereum. Testnet balances cannot be used.','Не Arc. Автоматического моста нет. Нужны USDC и ETH для газа в Ethereum. Testnet-баланс использовать нельзя.')}</p></aside></section>
 <div className={styles.providerPicker} role="group" aria-label={t('Earn provider and network','Провайдер и сеть Earn')}><button aria-pressed={provider==='aave'} onClick={()=>{setProvider('aave');setAccepted(false)}}>Aave <span>Ethereum · APR</span></button><button aria-pressed={provider==='morpho'} onClick={()=>{setProvider('morpho');setAccepted(false)}}>Morpho <span>Arc · APY</span></button></div><p className={styles.caption}>{t('Two networks. Separate positions. No automatic bridge or rate ranking.','Две сети. Отдельные позиции. Нет автоматического моста или рейтинга ставок.')}</p>
 {provider==='morpho'?<MorphoPanel ru={ru}/>:<> <div className={styles.grid}><section className={styles.market} aria-labelledby="market-title"><div className={styles.marketTop}><div><span className={styles.overline}>EXTERNAL PROVIDER</span><h2 id="market-title">Aave V3 / USDC</h2></div><button className={styles.refresh} onClick={()=>void refresh()} disabled={loading} aria-label={t('Refresh market verification','Обновить проверку рынка')}><RefreshCw size={17} className={loading?styles.spinning:''}/></button></div>
 <div className={styles.rate} aria-live="polite"><strong>{loading?'—':rate?rate+'%':'—'}</strong><span>{t('Current variable supply APR','Текущая переменная годовая ставка')}</span><p>{t('An observed annualized rate, not a fixed return or forecast. Interest comes from protocol lending activity.','Наблюдаемая годовая ставка, не фиксированный доход и не прогноз. Источник процентов — кредитная деятельность протокола.')}</p></div>
 <div className={styles.status} role="status"><span data-ready={!loading&&fresh&&snapshot?.status==='available'}/>{loading?t('Checking two RPC witnesses…','Проверяем два RPC…'):fresh&&snapshot?.status==='available'?t('Market observations agree','Данные рынка согласованы'):t('Verification unavailable or supply blocked','Проверка недоступна или размещение заблокировано')}</div>
 <dl className={styles.details}><div><dt>{t('Network','Сеть')}</dt><dd>Ethereum · 1</dd></div><div><dt>{t('Position owner','Владелец позиции')}</dt><dd>{t('Your wallet','Ваш кошелёк')}</dd></div><div><dt>{t('Mercenta custody','Хранение в Mercenta')}</dt><dd>{t('None','Нет')}</dd></div><div><dt>{t('Execution','Исполнение')}</dt><dd>{t('Official Aave interface','Официальный интерфейс Aave')}</dd></div></dl>
 {snapshot?.blockNumber&&<a className={styles.proof} href={'https://etherscan.io/block/'+snapshot.blockNumber} target="_blank" rel="noopener noreferrer">{t('Observed block','Проверенный блок')} {snapshot.blockNumber} <ExternalLink size={14}/></a>}
 <label className={styles.consent}><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>{t('I understand this is Ethereum, capital and returns are not guaranteed, and deposits/withdrawals happen in Aave—not Mercenta.','Я понимаю: это Ethereum, капитал и доход не гарантированы; размещение и вывод выполняются в Aave, а не в Mercenta.')}</span></label>
 {open?<a className={styles.primary} href={EARN_MARKET.appUrl} target="_blank" rel="noopener noreferrer">{t('Continue in official Aave','Продолжить в официальном Aave')} <ArrowUpRight size={18}/></a>:<button className={styles.primary} disabled>{t('Continue in official Aave','Продолжить в официальном Aave')} <ArrowUpRight size={18}/></button>}
 <p className={styles.caption}>{t('Opening Aave does not sign, approve or move money. Select Ethereum and USDC there, check terms, then confirm each transaction in your wallet.','Переход не подписывает, не разрешает списание и не переводит деньги. В Aave выберите Ethereum и USDC, проверьте условия и подтвердите каждую операцию своим кошельком.')}</p></section>
 <aside className={styles.sidebar}><article><ShieldCheck size={24}/><h2>{t('No hidden IOU.','Без скрытого долга.')}</h2><p>{t('Mercenta does not promise to pay your interest, guarantee principal or reimburse protocol losses. No owner funding is used to manufacture a yield.','Mercenta не обещает оплачивать проценты, гарантировать вклад или компенсировать потери протокола. Доходность не создаётся за счёт денег владельца.')}</p></article><article className={styles.risk}><TriangleAlert size={23}/><h2>{t('Know the risks.','Понимайте риски.')}</h2><ul><li>{t('Smart-contract, governance and oracle failures.','Сбои контрактов, управления и оракулов.')}</li><li>{t('USDC depeg, issuer freezes and network fees.','Отклонение USDC от курса, блокировки эмитента и комиссии сети.')}</li><li>{t('Variable rates; withdrawal may be unavailable or delayed.','Ставка меняется; вывод может быть недоступен или задержан.')}</li><li>{t('Eligibility and access depend on provider terms and your jurisdiction.','Допуск зависит от условий провайдера и вашей юрисдикции.')}</li></ul></article></aside></div>
 <section className={styles.flow} aria-label={t('Earn workflow','Как работает Earn')}>{[[Wallet,t('Prepare Ethereum funds','Подготовьте средства в Ethereum'),t('USDC plus ETH for gas. Keep your purchase budget separate.','USDC и ETH для газа. Бюджет покупок держите отдельно.')],[ArrowUpRight,t('Supply in Aave','Разместите в Aave'),t('Review the official market and wallet transaction. Receive the protocol position in your wallet.','Проверьте рынок и транзакцию. Позиция протокола поступает в ваш кошелёк.')],[LockKeyhole,t('Monitor and withdraw there','Следите и выводите там'),t('Aave shows your position and accrued interest. Redemption is subject to protocol liquidity and rules.','В Aave видны позиция и начисления. Вывод зависит от ликвидности и правил протокола.')]].map(([Icon,title,text],i)=>{const I=Icon as typeof Wallet;return <article key={i}><I size={22}/><span>0{i+1}</span><h3>{String(title)}</h3><p>{String(text)}</p></article>})}</section>
 <details className={styles.contracts}><summary>{t('Contracts and integration boundaries','Контракты и границы интеграции')}</summary><dl>{[['USDC',EARN_MARKET.usdc],['Aave Pool',EARN_MARKET.pool],['aUSDC',EARN_MARKET.aToken]].map(([label,address])=><div key={label}><dt>{label}</dt><dd><a href={'https://etherscan.io/address/'+address} target="_blank" rel="noopener noreferrer">{address} <ArrowUpRight size={13}/></a></dd></div>)}</dl><p>{t('Code presence and agreeing RPCs are not a security audit or a guarantee. Mercenta does not enable borrowing, auto-allocation, bridging or a managed customer vault in this version.','Наличие кода и согласие RPC — не аудит и не гарантия. В этой версии Mercenta не включает borrow, авторазмещение, мост или управляемый клиентский vault.')}</p><a href={EARN_MARKET.docsUrl} target="_blank" rel="noopener noreferrer">{t('Read official protocol documentation','Официальная документация протокола')} <ArrowRight size={16}/></a></details>
 </>}
 </main><footer className={styles.footer}><span>Mercenta · External Earn</span><Link href="/privacy">{t('Privacy','Конфиденциальность')}</Link><Link href="/support">{t('Support','Поддержка')}</Link><Link href="/">{t('Back to Mercenta','Вернуться в Mercenta')} <ArrowRight size={15}/></Link></footer></div>;
}
