"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,RefreshCw,ShieldCheck,TriangleAlert,ExternalLink} from 'lucide-react';
import {MORPHO_ARC,MORPHO_VAULTS,morphoSnapshotSchema,unavailableMorpho,canExploreMorpho,formatMorphoUsdc,type MorphoSnapshot} from '@/lib/morpho-market';
import styles from './earn.module.css';
export function MorphoPanel({ru}:{ru:boolean}){
 const t=(en:string,russian:string)=>ru?russian:en;
 const [snapshot,setSnapshot]=useState<MorphoSnapshot|null>(null),[selected,setSelected]=useState('galaxy'),[accepted,setAccepted]=useState(false),[loading,setLoading]=useState(true),[now,setNow]=useState(0);
 const ctl=useRef<AbortController|null>(null);
 const refresh=useCallback(async()=>{
  ctl.current?.abort();const controller=new AbortController();ctl.current=controller;setLoading(true);setSnapshot(null);
  try{const r=await fetch('/api/earn/morpho',{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('UNAVAILABLE');const s=morphoSnapshotSchema.parse(await r.json());if(!controller.signal.aborted)setSnapshot(s);}
  catch{if(!controller.signal.aborted)setSnapshot(unavailableMorpho());}
  finally{if(!controller.signal.aborted){setLoading(false);setNow(Date.now());}}
 },[]);
 useEffect(()=>{void refresh();const poll=setInterval(()=>void refresh(),30000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{ctl.current?.abort();clearInterval(poll);clearInterval(clock)}},[refresh]);
 const vault=snapshot?.vaults.find(v=>v.id===selected),spec=MORPHO_VAULTS.find(v=>v.id===selected)!,fresh=!!snapshot&&snapshot.expiresAt>now&&snapshot.observedAt<=now;
 const show=fresh&&!loading&&vault?.status==='observed',open=!loading&&canExploreMorpho(snapshot,selected,accepted,now);
 return <section aria-label={t('Morpho Arc exploration','Обзор Morpho Arc')}>
 <div className={styles.vaultPicker} role="group" aria-label={t('Choose a vault to inspect','Выберите vault для проверки')}>{MORPHO_VAULTS.map(v=><button key={v.id} aria-pressed={selected===v.id} onClick={()=>{setSelected(v.id);setAccepted(false)}}>{v.name}<small>Arc · USDC</small></button>)}</div>
 <div className={styles.grid}><article className={styles.market}><div className={styles.marketTop}><div><span className={styles.overline}>MORPHO / ARC · 5042</span><h2>{spec.name}</h2></div><button className={styles.refresh} onClick={()=>void refresh()} disabled={loading} aria-label={t('Refresh Morpho observations','Обновить данные Morpho')}><RefreshCw size={17} className={loading?styles.spinning:''}/></button></div>
 <div className={styles.rate} aria-live="polite"><strong>{show&&vault?.netApyPercent?vault.netApyPercent+'%':'—'}</strong><span>{t('API-reported variable net APY','Переменная net APY по данным API')}</span><p>{t('Reported by the Morpho indexer, not independently calculated on-chain. Indexer freshness is not verified. Not a guaranteed return; not directly comparable to Aave APR.','Данные индексатора Morpho, не независимый on-chain расчёт. Свежесть индексатора не подтверждена. Это не гарантия дохода; напрямую с APR Aave не сравнивается.')}</p></div>
 <div className={styles.status} role="status"><span/>{loading?t('Checking API and two Arc RPCs…','Проверяем API и два Arc RPC…'):show?t('Contract observations agree · allocation review pending','Данные контрактов согласованы · аллокации ещё проверяются'):t('Observations unavailable or vault restricted','Данные недоступны или vault ограничен')}</div>
 <dl className={styles.details}>{[[t('Network','Сеть'),'Arc Mainnet · 5042'],[t('Assets in vault · on-chain','Активы vault · on-chain'),fresh?formatMorphoUsdc(vault?.totalAssetsMicro??null,ru?'ru-RU':'en-US'):'—'],[t('Withdrawal liquidity · API reported','Ликвидность вывода · по API'),fresh?formatMorphoUsdc(vault?.reportedLiquidityMicro??null,ru?'ru-RU':'en-US'):'—'],[t('Performance fee · share of yield','Performance fee · доля дохода'),fresh&&vault?.performanceFeePercent!==null&&vault?.performanceFeePercent!==undefined?vault.performanceFeePercent+'%':'—'],[t('Management fee · annual','Management fee · в год'),fresh&&vault?.managementFeePercent!==null&&vault?.managementFeePercent!==undefined?vault.managementFeePercent+'%':'—'],[t('Execution / custody','Исполнение / хранение'),t('External protocol / no Mercenta custody','Внешний протокол / не в Mercenta')]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
 {fresh&&snapshot?.blockNumber&&<a className={styles.proof} href={'https://arc.etherscan.io/block/'+snapshot.blockNumber} target="_blank" rel="noopener noreferrer">{t('Observed block','Проверенный блок')} {snapshot.blockNumber} <ExternalLink size={14}/></a>}
 <p className={styles.notice}>{t('Research preview, not an approved investment. Detailed allocation, collateral and oracle review is incomplete. No deposit or withdrawal has been tested by Mercenta.','Обзор для исследования, не одобренная инвестиция. Проверка аллокаций, обеспечения и оракулов не завершена. Mercenta не тестировала депозит или вывод.')}</p>
 <label className={styles.consent}><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>{t('I understand this Earn notice and the Morpho disclaimer: capital and returns are not guaranteed; transactions happen in Morpho, with my wallet, not Mercenta.','Я понимаю это уведомление Earn и disclaimer Morpho: капитал и доход не гарантированы; операции выполняются в Morpho с моим кошельком, а не в Mercenta.')} <a href={MORPHO_ARC.termsUrl} target="_blank" rel="noopener noreferrer">{t('Read Morpho disclaimer','Прочитать disclaimer Morpho')}</a></span></label>
 {open?<a className={styles.primary} href={MORPHO_ARC.appUrl} target="_blank" rel="noopener noreferrer">{t('Inspect in official Morpho','Проверить в официальном Morpho')} <ArrowUpRight size={18}/></a>:<button className={styles.primary} disabled>{t('Inspect in official Morpho','Проверить в официальном Morpho')} <ArrowUpRight size={18}/></button>}
 <p className={styles.caption}>{t('This opens the official app, not a pre-filled deposit. Select Arc and verify the exact vault address below. Opening the link never signs, approves, bridges or moves funds.','Откроется официальный сайт, не готовый депозит. Выберите Arc и сверьте точный адрес vault ниже. Переход не подписывает, не разрешает списание, не создаёт мост и не переводит средства.')}</p>
 </article><aside className={styles.sidebar}><article><ShieldCheck size={24}/><h2>{t('Your position. Separate from purchases.','Ваша позиция. Отдельно от покупок.')}</h2><p>{t('Your wallet controls the protocol position. Supplied USDC enters Morpho; it is not held as a Mercenta prepaid balance. No owner-funded interest, fixed rate or loss reimbursement.','Кошелёк контролирует позицию протокола. Размещённые USDC поступают в Morpho, не на предоплаченный счёт Mercenta. Нет процентов за счёт владельца, фиксированной ставки или возмещения потерь.')}</p></article><article className={styles.risk}><TriangleAlert size={23}/><h2>{t('More than an APY.','Не только APY.')}</h2><ul><li>{t('Borrower bad debt, collateral and oracle risk.','Плохой долг заёмщиков, риски обеспечения и оракулов.')}</li><li>{t('Curator, allocator and gate changes can affect access, fees and allocations.','Куратор, allocator и gates влияют на доступ, комиссии и аллокации.')}</li><li>{t('Withdrawal liquidity can disappear. Shared markets must not be counted twice.','Ликвидность вывода может исчезнуть. Общие рынки нельзя учитывать дважды.')}</li><li>{t('Contract bugs, USDC issuer freezes, depeg and network costs.','Ошибки контрактов, блокировки USDC, отклонение курса и комиссии сети.')}</li></ul></article></aside></div>
 <details className={styles.contracts}><summary>{t('Exact vault and verification boundaries','Точный vault и границы проверки')}</summary><dl><dt>{spec.name}</dt><dd><a href={'https://arc.etherscan.io/address/'+spec.address} target="_blank" rel="noopener noreferrer">{spec.address}</a></dd><dt>USDC · Arc</dt><dd>{MORPHO_ARC.usdc}</dd></dl><p>{t('Pinned addresses and runtime hashes; agreeing RPC observations of asset, assets, gates and fees. Rates and liquidity are API-reported and may lag. Presence of code, listing and zero gates are not an audit or proof of successful withdrawal. Testnet funds cannot be used.','Фиксированные адреса и хеши кода; два RPC сверяют токен, активы, gates и комиссии. Ставки и ликвидность сообщаются API и могут отставать. Наличие кода, listing и нулевые gates — не аудит и не доказательство успешного вывода. Testnet-средства использовать нельзя.')}</p><a href={MORPHO_ARC.docsUrl} target="_blank" rel="noopener noreferrer">{t('Official Morpho risks','Официальное описание рисков Morpho')} <ArrowUpRight size={16}/></a><p className={styles.caption}>Protocol: Morpho · {t('Read-only Mercenta interface','Read-only интерфейс Mercenta')}</p></details>
 </section>;
}
