'use client';
import {useState} from 'react';
import {Check,X,Braces,ShieldCheck,RotateCcw,Terminal} from 'lucide-react';
import {CopyButton} from './Primitives';
const contrasts=[['Disconnected product lists','One catalogue, with regions inside each product.'],['Budgets checked after the fact','Explicit spend caps checked before execution.'],['Unclear permission to purchase','A separate confirmation or bounded delegation.'],['Retry anxiety and duplicate actions','Request IDs protect supported writes from replay.'],['Missing context when something fails','Saved task events and manual Mercenta Support.']];
export function WorkflowContrast(){return <section className="mx-wrap me-section" aria-labelledby="me-contrast-title"><header className="text-center"><span className="me-eyebrow">THE WORKFLOW, RECONSIDERED</span><h2 id="me-contrast-title">Less chasing.<br/><span>More control.</span></h2><p>From disconnected steps to a proposal you can understand and a decision you own.</p></header><div className="grid gap-4 md:grid-cols-2 mt-10"><article className="me-contrast-muted rounded-2xl border border-dashed bg-neutral-50 p-6 md:p-8"><span className="me-pill">Without Mercenta</span><ul>{contrasts.map(([pain])=><li key={pain}><span className="me-tile"><X size={15}/></span><span>{pain}</span></li>)}</ul><footer>Manual hand-offs. Less context.</footer></article><article className="me-contrast-hero rounded-2xl border border-neutral-700 bg-neutral-900 p-6 md:p-8"><span className="me-pill">With Mercenta</span><ul>{contrasts.map(([,outcome])=><li key={outcome}><span className="me-tile"><Check size={15}/></span><span>{outcome}</span></li>)}</ul><footer>5 policy checkpoints in the illustrative control flow.<br/><small>Testnet execution only. Mainnet checkout is closed.</small></footer></article></div></section>}
export const API_SNIPPETS={cURL:'curl --fail "https://mercenta.xyz/api/catalog?view=browse"',TypeScript:`type Browse = { live: boolean; generatedAt: string; rows: unknown[][] };\n\nconst response = await fetch(\n  "https://mercenta.xyz/api/catalog?view=browse"\n);\nif (!response.ok) throw new Error("Catalogue unavailable");\nconst catalog: Browse = await response.json();\nconsole.log(catalog.live, catalog.rows.length);`,Python:`import json\nfrom urllib.request import urlopen\n\nwith urlopen(\n    "https://mercenta.xyz/api/catalog?view=browse",\n    timeout=15,\n) as response:\n    catalog = json.load(response)\n\nprint(catalog["live"], len(catalog["rows"]))`};
export function DeveloperBlock(){const [language,setLanguage]=useState<keyof typeof API_SNIPPETS>('cURL');return <section id="build" className="mx-wrap me-section grid gap-8 md:grid-cols-2 items-center"><div><span className="me-eyebrow">API FIRST / START READ-ONLY</span><h2>Your interface.<br/><span>Mercenta underneath.</span></h2><p>Explore the public catalogue today. Add authenticated Testnet account tools when you are ready. A request is never permission to spend.</p><ul className="me-feature-list">{[[Braces,'Typed entry point','A small read-only client and OpenAPI reference.'],[ShieldCheck,'Idempotent writes','Supported account actions require stable request IDs.'],[RotateCcw,'Inspect before retrying','Saved run events today. Webhook delivery is not connected yet.']].map(([Icon,title,text])=>{const Glyph=Icon as typeof Braces;return <li key={String(title)}><span className="me-icon"><Glyph size={19}/></span><div><strong>{String(title)}</strong><small>{String(text)}</small></div></li>})}</ul><div className="me-actions"><a className="me-button me-primary" href="/api-docs">Read the reference ↗</a><a href="/releases">Release notes →</a></div></div><div className="me-code"><header><div role="group" aria-label="Code language">{(Object.keys(API_SNIPPETS) as (keyof typeof API_SNIPPETS)[]).map(l=><button className="me-tab" aria-pressed={l===language} key={l} onClick={()=>setLanguage(l)}>{l}</button>)}</div><CopyButton text={API_SNIPPETS[language]}/></header><pre><code>{API_SNIPPETS[language]}</code></pre><footer><i className="me-dot"/> GET catalogue · Read-only · No credentials required</footer></div></section>}
const url='https://mercenta.xyz/sdk/mercenta-client-0.1.1.tgz';
export const INSTALL_COMMANDS={npm:`npm install ${url}`,pnpm:`pnpm add ${url}`,bun:`bun add ${url}`,deno:'import { MercentaClient } from "https://mercenta.xyz/sdk/mercenta-client.mjs";'};
export function SDKHero(){const [pm,setPm]=useState<keyof typeof INSTALL_COMMANDS>('npm');return <section className="mx-wrap me-section me-sdk text-center"><span className="me-pill">Read-only client · v0.1.1 · Direct download</span><h2>Build your storefront.<br/><span>Keep the controls.</span></h2><p>A tiny, dependency-free client for public catalogue reads. No embedded credentials, wallet access, or purchasing methods. This is a downloadable package, not a registry release.</p><div className="me-code text-left mx-auto max-w-3xl"><header><span className="me-window-dots" aria-hidden="true">● ● ●</span><div role="group" aria-label="Package manager">{(Object.keys(INSTALL_COMMANDS) as (keyof typeof INSTALL_COMMANDS)[]).map(p=><button key={p} data-pm={p} className="me-tab" aria-pressed={pm===p} onClick={()=>setPm(p)}>{p}</button>)}</div><Terminal size={16}/></header><div className="me-install"><code><span aria-hidden="true">{pm==='deno'?'':'$ '}</span>{INSTALL_COMMANDS[pm]}</code><CopyButton text={INSTALL_COMMANDS[pm]}/></div></div><div className="me-actions justify-center"><a className="me-button me-primary" href={url}>Download client ↗</a><a href="/api-docs">Read the docs →</a></div><small>MIT licensed · Zero runtime dependencies · Read-only by design</small></section>}
